/*$File_version=MS4.3.0.02$*/
/*$file name : acapamasmspasnouihdr.sql*/
/*$version   : 4.0.0.1*/
/*==================================================
   stored procedure : acapamasmspasnouihdr
   method           : acapamasmmtasnouihdr
   author           : Balamurali S
   created on       : 26 may 2001 13:34:40:140
   created at       : s4141
   generated by     : fpuser

    Modified By		: Sangeetha Sitaraman
    Date		: 13-01-2006
    Purpose		: For FA revamp(for earlier version of the SP pls.refer VSS) 


grant exec on acapamasmspasnouihdr to public
declare @P1 int
set @P1=NULL
exec acapamasmspasnouihdr '~#~', '~#~', '~#~', '~#~', '1', '~#~', -9.150000000000000e+002, 
'01/01/1900', '~#~', '~#~', '01/01/1900', '~#~', 1, '2', 'acapamasmsrasno', 'finuser',
 '~#~', '@@@@@', '~#~', '~#~', '01/01/1900', 'HalfYearly', '~#~', '~#~', '0', '~#~', -9.150000000000000e+002, -915, -9.150000000000000e+002, '~#~', -915, '~#~', @P1 output
select @P1
/*  Harithra		 17-08-2018         EPE-8428                             */
/*Abilash Sriram N		19/07/2023						EPE-65400				*/
====================================================*/
CREATE procedure acapamasmspasnouihdr
	@assetclass                fin_assetclass,
	@assetdescription          fin_desc40,
	@assetgrpnum               fin_group,
	@assetlocation             fin_assetlocation,
	@assetnumber               fin_assetnumber,
	--@barcode             fin_DocumentNumber,
	@barcode                   fin_barcode,--EPE-65400
	@businessuse               fin_depprecent,
	@capitalizationdate        fin_date,
	@capitalizationnumber	   fin_documentnumber ,	
	@costcenter                fin_costcentercode,
	@createddate               fin_date,
	@creationby                fin_ctxt_user,
	@ctxt_language             fin_ctxt_language,
	@ctxt_ouinstance           fin_ctxt_ouinstance,
	@ctxt_service              fin_ctxt_service,
	@ctxt_user                 fin_ctxt_user,
	@custodian                 fin_employeename,
	@depcategory               fin_depcategory,
	@fb                        fin_financebookid,
	@guid					   fin_guid ,
	@inservicedate             fin_date,
	@invcyclemlenn             fin_desc40,
	@manufacturer              fin_name,
	@model                     fin_desc40,
	@newtag                    fin_flag,
	@proposalnumber			   fin_documentnumber ,
	@salvagevalue              fin_amount,
	@serialnumber              fin_serialno,
	@tagcost                   fin_amount,
	@tagdescription            fin_desc40,
	@tagnumber                 fin_assettagno,
	@warrentynumber            fin_documentnumber,
	/*code modified for EPE-8428 - Harithra*/
	@accountcode          	   fin_accountcode, --Input 
	@accountdescription   	   fin_accountdesc, --Input 
	@lscostcentre         	   fin_costcentercode, --Input 
	@analysiscode         	   fin_analysiscode, --Input 
	@subanalysiscode      	   fin_subanalysiscode, --Input 
	@m_errorid                 fin_int output
as
begin

	
	-- nocount should be switched on to prevent phantom rows 
	set nocount on
	/*code modified for EPE-8428 - Harithra*/
	Set @accountcode           = ltrim(rtrim(@accountcode))
	Set @accountdescription    = ltrim(rtrim(@accountdescription))
	Set @lscostcentre          = ltrim(rtrim(@lscostcentre))
	Set @analysiscode          = ltrim(rtrim(@analysiscode))
	Set @subanalysiscode       = ltrim(rtrim(@subanalysiscode))

	-- @m_errorid should be 0 to indicate success
	select @m_errorid =0
	
	
	select @assetclass = ltrim(rtrim(@assetclass))
	if @assetclass = '~#~' 
		select @assetclass = null

	select @assetdescription = ltrim(rtrim(@assetdescription))
	if @assetdescription = '~#~' 
		select @assetdescription = null

	select @assetgrpnum = ltrim(rtrim(@assetgrpnum))
	if @assetgrpnum = '~#~' 
		select @assetgrpnum = null

	select @assetlocation = ltrim(rtrim(@assetlocation))
	if @assetlocation = '~#~' 
		select @assetlocation = null

	select @assetnumber = ltrim(rtrim(@assetnumber))
	if @assetnumber = '~#~' 
		select @assetnumber = null

	select @barcode = ltrim(rtrim(@barcode))
	if @barcode = '~#~' 
		select @barcode = null

	if @businessuse = -915 
		select @businessuse = null

	select @capitalizationdate = ltrim(rtrim(@capitalizationdate))
	if @capitalizationdate = '1900-01-01' 
		select @capitalizationdate = null

	select @costcenter = ltrim(rtrim(@costcenter))
	if @costcenter = '~#~' 
		select @costcenter = null

	select @createddate = ltrim(rtrim(@createddate))
	if @createddate = '1900-01-01' 
		select @createddate = null

	select @creationby = ltrim(rtrim(@creationby))
	if @creationby = '~#~' 
		select @creationby = null

	if @ctxt_language = -915 
		select @ctxt_language = null

	if @ctxt_ouinstance = -915 
		select @ctxt_ouinstance = null

	select @ctxt_service = ltrim(rtrim(@ctxt_service))
	if @ctxt_service = '~#~' 
		select @ctxt_service = null

	select @ctxt_user = ltrim(rtrim(@ctxt_user))
	if @ctxt_user = '~#~' 
	select @ctxt_user = null

		select @custodian = ltrim(rtrim(@custodian))
	if @custodian = '~#~' 
	select @custodian = null

		select @depcategory = ltrim(rtrim(@depcategory))
	if @depcategory = '~#~' 
		select @depcategory = null

	select @fb = ltrim(rtrim(@fb))
	if @fb = '~#~' 
		select @fb = null

	select @inservicedate = ltrim(rtrim(@inservicedate))
	if @inservicedate = '1900-01-01' 
		select @inservicedate = null

	select @manufacturer = ltrim(rtrim(@manufacturer))
	if @manufacturer = '~#~' 
		select @manufacturer = null

	select @model = ltrim(rtrim(@model))
	if @model = '~#~' 
		select @model = null

	select @newtag = ltrim(rtrim(@newtag))
	if @newtag = '~#~' 
		select @newtag = null

	if @salvagevalue = -915 
		select @salvagevalue = null

	select @serialnumber = ltrim(rtrim(@serialnumber))
	if @serialnumber = '-915 ' or @serialnumber ='~#~'
		select @serialnumber = null

	if @tagcost = -915 
		select @tagcost = null

	select @tagdescription = ltrim(rtrim(@tagdescription))
	if @tagdescription = '~#~' 
		select @tagdescription = null

	if @tagnumber = -915 
		select @tagnumber = null

	select @warrentynumber = ltrim(rtrim(@warrentynumber))
	if @warrentynumber = '~#~' 
		select @warrentynumber = null
	/*code modified for EPE-8428 - Harithra*/
	IF @accountcode = '~#~' 
		Select @accountcode = null  

	IF @accountdescription = '~#~' 
		Select @accountdescription = null  

	IF @lscostcentre = '~#~' 
		Select @lscostcentre = null  

	IF @analysiscode = '~#~' 
		Select @analysiscode = null  

	IF @subanalysiscode = '~#~' 
		Select @subanalysiscode = null  

	
	select 0 'fprowno'


	set nocount off
end






