/*$File_version=ms4.3.0.18$*/
/*$file name : acapamasmspasnohref.sql*/
/*$version   : 4.0.0.015*/
/*==================================================
   stored procedure : acapamasmspasnohref
   method           :acapamasmmtasnohref
   author           : balamurali s
   created on       : 26 may 2001 13:34:40:030
   created at       : s4141
   generated by     : fpuser
   modified by	    : Prasad
   modified date    : 27/06/2003

   modified by		:  Uma Maheswari 
   modified date	:  7th aug 2004
   Modification purpose :  ACAPDMS41SYTST_000125 , ACAPBP_SUPPORT_000053 & vantive id 4395 	

   Modified By :	saurabh mathur
   Date        :	08/10/2004
   Description :	ACAPFIN41CT_000133/34


   modified by      : Sangeetha Sitaraman
   modifieddate     : 13-01-2006
   Purpose	    : Code revamped for FA changes (Refer VSS for the previous version)

   
   modified by      : Swetha
   modifieddate     : 08/02/2006
   Purpose	    : ACAPDMS412AT_000338

      
   modified by      : Swetha
   modifieddate     : 09/02/2006
   Purpose	    : ACAPDMS412AT_000341

Modified BY			Date			Purpose
 Kavitha R	     27/02/2006		ACAPDMS412AT_000355	
 Swetha		     28/02/2006		ACAPDMS412AT_000268
 Swetha              03/04/2006     ACAPDMS412AT_000423
 Swetha              5/4/2006       ACAPDMS412AT_000437
 Swetha              22/08/2006     ACAPDMS412AT_000494  
 Swetha              24/08/2006     ACAPDMS412AT_000520
 Swetha              11/9/2006      ACAPDMS412AT_000548
 Swetha              05/01/2007     SDINDMS412AT_000538            
 Esther 	     18/05/2007	    ACAPDMS412AT_000710

 proc  acapamasmspasnohref
acapamasmsp,P
declare @P1 int
set @P1=NULL
exec acapamasmspasnohref 1, '2', 'acapamasmsrasno', 'finuser', '~#~', 
'~#~', '~#~', '~#~', '1', '~#~', -9.150000000000000e+002, '01/01/1900', 
'~#~', '~#~', '01/01/1900', '~#~', '~#~', '@@@@@', '~#~', '~#~', 
'01/01/1900', 'HalfYearly', '~#~', '~#~', '0', '~#~', -9.150000000000000e+002, 
-915, -9.150000000000000e+002, '~#~', -915, '~#~', @P1 output
select @P1
grant exec on acapamasmspasnohref to public
C.Ramesh Kumar				16.07.2014					14H109_ACAP_00004
Damodharan. R				05/12/2014					14H109_ADEPP_00004  
Thyagaraj B M				05/08/2015				    14H109_ADEPP_00048 
Krishna Kumar N				31/07/2018					EPE-7866    
Harithra					17-08-2018					EPE-8428   
Uma Maheshwari M			18-09-2018					EPE-9198        
Amrutha R.S					07/01/2019					epe-11283:EPE-11483
Abimathi.M					18-12-2019					EPE-16037	                              
/* gokul M					03/11/2020					EPE-23559 */
Abimathi.M					29-01-2021					EPE-29928
Ashok V						23/12/2020					PTP-1377
Nithya S					04/04/2022					EPE-43676
Mabel Rita L                09/08/2022                  SSIU-13
/*Abilash Sriram N		19/07/2023						EPE-65400				*/
/*Srinivasan M           19/06/2024                     EPE-82887*/
====================================================*/
CREATE procedure acapamasmspasnohref
	@ctxt_language             fin_ctxt_language,
	@ctxt_ouinstance           fin_ctxt_ouinstance,
	@ctxt_service              fin_ctxt_service,
	@ctxt_user                 fin_ctxt_user,
	@assetclass                fin_assetclass,
	@assetdescription          fin_desc40,
	@assetgrpnum               fin_group,
	@assetlocation             fin_assetlocation,
	@assetnumber               fin_assetnumber,
	--@barcode             fin_DocumentNumber,
	@barcode                   fin_barcode,--EPE-65400
	@businessuse               fin_depprecent,
	@capitalizationdate        fin_date,
	@capitalizationnumber	   fin_documentnumber ,	
	@costcenter                fin_costcentercode,
	@createddate               fin_date,
	@creationby                fin_ctxt_user,
	@custodian                 fin_employeename,
	@depcategory               fin_depcategory,
	@fb                        fin_financebookid,
	@guid			   fin_guid ,
	@inservicedate             fin_date,
	@invcyclemlenn fin_desc40,
	@manufacturer              fin_name,
	@model            fin_desc40,
	@newtag                    fin_flag,
	@proposalnumber		   fin_documentnumber ,
	@salvagevalue              fin_amount,
	@serialnumber         fin_serialno,
	@tagcost                   fin_amount,
	@tagdescription            fin_desc40,
	@tagnumber            fin_assettagno,
	@warrentynumber            fin_documentnumber,
	/*Code added by Damodharan. R for Defect ID 14H109_ADEPP_00004 starts here*/
	@residualvalue      		fin_depprecent,
	@usefullifeinmonths   		fin_lineno,
	/*Code added by Damodharan. R for Defect ID 14H109_ADEPP_00004 ends here*/
/*code modified for EPE-8428 - Harithra*/
	@accountcode          		fin_accountcode, --Input/Output
	@accountdescription   		fin_accountdesc, --Input/Output
	@lscostcentre         		fin_costcentercode, --Input/Output
	@analysiscode         		fin_analysiscode, --Input/Output
	@subanalysiscode      		fin_subanalysiscode, --Input/Output
	@assetclassification  	fin_desc255, --Input/Output
	@assetcategory        	fin_desc255, --Input/Output
	@assetcluster         	fin_desc255, --Input/Output
	@salvageper           	fin_depprecent,--EPE-43676
	@m_errorid                  fin_int output
as
begin
	-- nocount should be switched on to prevent phantom rows 
	set nocount on

	-- @m_errorid should be 0 to indicate success
	select @m_errorid =0
	/*code modified for EPE-8428 - Harithra*/
	Set @accountcode           = ltrim(rtrim(@accountcode))
	Set @accountdescription    = ltrim(rtrim(@accountdescription))
	Set @lscostcentre          = ltrim(rtrim(@lscostcentre))
	Set @analysiscode          = ltrim(rtrim(@analysiscode))
	Set @subanalysiscode       = ltrim(rtrim(@subanalysiscode))
	
	declare @status_tmp		fin_status,
		@statustext_tmp		fin_param_text,
		@maxtagno_tmp		fin_int ,
		@assetclassdoc_tmp	fin_assetclass ,
		@assetclass_tmp		fin_assetclass ,
		@tagcost_tmp		fin_amount,
		@propno			fin_documentnumber,
		@proposal_number	fin_documentnumber
         declare @doc_number   fin_documentnumber
    	 declare @doc_type     fin_doctype
		 declare @count1_tmp   fin_int
		declare @count2_tmp   fin_int
		declare @asset_number fin_assetnumber
		declare @doc_amount   fin_amount
		,@ainfou 		fin_ctxt_ouinstance --SSIU-13
	/*Code added by Damodharan. R for Defect ID 14H109_ADEPP_00004 starts here*/
    declare @resval_tmp					fin_paramcode,
			@usefulllife_tmp			fin_desc40,
    		@allmodresval_tmp			fin_desc40,
			@sysdate					fin_date,
			@company_code				fin_companycode,
			@adepou						fin_ctxt_ouinstance,
			@yearly_percent				fin_flag,
			@usefullifeinmonths_tmp		fin_lineno,
			@hdnrt_stcontrol			udd_ctxt_state_name,
			/*-------EPE-9198-------*/
			@hdn_residualvalue			 fin_desc255, 
			@hdn_usefullife				fin_desc255, 
			@hdn_workflowsec			fin_desc255
			/*-------EPE-9198-------*/
	/*Code added by Damodharan. R for Defect ID 14H109_ADEPP_00004 ends here*/	 
			,@shift_applicable		fin_paramcode  	--EPE-23559 
			,@stNatureOfShift		fin_rowno  	--EPE-23559 

	if @ctxt_language = -915 
		select @ctxt_language = null
	if @ctxt_ouinstance = -915 
		select @ctxt_ouinstance = null
	select @ctxt_service = ltrim(rtrim(@ctxt_service))
	if @ctxt_service = '~#~' 
		select @ctxt_service = null
	select @ctxt_user = ltrim(rtrim(@ctxt_user))
	if @ctxt_user = '~#~' 
		select @ctxt_user = null
	select @assetclass = ltrim(rtrim(@assetclass))
	if @assetclass = '~#~' 
		select @assetclass = null
	select @assetdescription = ltrim(rtrim(@assetdescription))
	if @assetdescription = '~#~' 
		select @assetdescription = null
	select @assetgrpnum = ltrim(rtrim(@assetgrpnum))
	if @assetgrpnum = '~#~' 
		select @assetgrpnum = null
	select @assetlocation = ltrim(rtrim(@assetlocation))
	if @assetlocation = '~#~' 
		select @assetlocation = null
	select @assetnumber = ltrim(rtrim(upper(@assetnumber)))
	if @assetnumber = '~#~' 
		select @assetnumber = null
	select @barcode = ltrim(rtrim(@barcode))
	if @barcode = '~#~' 
		select @barcode = null
	if @businessuse = -915 
		select @businessuse = null
	select @capitalizationdate = ltrim(rtrim(@capitalizationdate))
	if @capitalizationdate = '1900-01-01' 
		select @capitalizationdate = null
	select @costcenter = ltrim(rtrim(@costcenter))
	if @costcenter = '~#~' 
		select @costcenter = null
	select @createddate = ltrim(rtrim(@createddate))
	if @createddate = '1900-01-01' 
		select @createddate = null
	select @creationby = ltrim(rtrim(@creationby))
	if @creationby = '~#~' 
		select @creationby = null
	select @custodian = ltrim(rtrim(@custodian))
	if @custodian = '~#~' 
		select @custodian = null
	select @depcategory = ltrim(rtrim(@depcategory))
	if @depcategory = '~#~' 
		select @depcategory = null
	select @fb = ltrim(rtrim(@fb))
	if @fb = '~#~' 
		select @fb = null
	select @inservicedate = ltrim(rtrim(@inservicedate))
	if @inservicedate = '1900-01-01' 
		select @inservicedate = null
	select @manufacturer = ltrim(rtrim(@manufacturer))
	if @manufacturer = '~#~' 
		select @manufacturer = null
	select @model = ltrim(rtrim(@model))
	if @model = '~#~' 
		select @model = null
	select @newtag = ltrim(rtrim(@newtag))
	if @newtag = '~#~' 
		select @newtag = null
	if @salvagevalue = -915 
		select @salvagevalue = null
	select @serialnumber = ltrim(rtrim(@serialnumber))
	if @serialnumber = '-915' or @serialnumber = '~#~'
		select @serialnumber = null
	if @tagcost = -915 
		select @tagcost = null
	select @tagdescription = ltrim(rtrim(@tagdescription))
	if @tagdescription = '~#~' 
		select @tagdescription = null
	if @tagnumber = -915 
		select @tagnumber = null
	select @warrentynumber = ltrim(rtrim(@warrentynumber))
	if @warrentynumber = '~#~' 
		select @warrentynumber = null

	select @proposalnumber = ltrim(rtrim(@proposalnumber))
	if @proposalnumber = '~#~' 
		select @proposalnumber = null

	/*Code added by Damodharan. R for Defect ID 14H109_ADEPP_00004 starts here*/
	if @residualvalue = -915
		Select @residualvalue = null  

	if  @usefullifeinmonths = -915
		Select @usefullifeinmonths = null 
	/*Code added by Damodharan. R for Defect ID 14H109_ADEPP_00004 ends here*/
	/*code modified for EPE-8428 - Harithra*/
	IF @accountcode = '~#~' 
		Select @accountcode = null  

	IF @accountdescription = '~#~' 
		Select @accountdescription = null  

	IF @lscostcentre = '~#~' 
		Select @lscostcentre = null  

	IF @analysiscode = '~#~' 
		Select @analysiscode = null  

	IF @subanalysiscode = '~#~' 
		Select @subanalysiscode = null  
	--EPE-11335	
	Set @assetclassification   = ltrim(rtrim(@assetclassification))
	IF @assetclassification = '~#~' 
		Select @assetclassification = null  

	Set @assetcategory         = ltrim(rtrim(@assetcategory))
	Set @assetcluster          = ltrim(rtrim(@assetcluster))


	IF @assetcategory = '~#~' 
		Select @assetcategory = null  

	IF @assetcluster = '~#~' 
		Select @assetcluster = null  


	--EPE-11335

	IF @salvageper = -915
		Select @salvageper = null --EPE-43676

 	if @assetnumber is null
	begin
		exec fin_sp_raise_error '', '', '', '', 'ACAP',1,@m_errorid output
		return
	end
	
	if not exists (select 'x' from acap_asset_doc_tmp(nolock)
			where guid = @guid)
	begin
		select 	@fb 			= fb_id
		from 	acap_asset_tag_dtl (nolock)
		where 	ou_id 			= @ctxt_ouinstance
		and 	upper(asset_number)	= upper(@assetnumber)
	end

		
	if not exists (select 	'x' from acap_asset_hdr(nolock)
			where 	ou_id			= @ctxt_ouinstance
			and   	upper(asset_number)	= upper(@assetnumber))
	begin
		exec fin_sp_raise_error '', '', '', '', 'ACAP',2,@m_errorid output
		return
	end

	declare @workflow_app		fin_metadata_code

	select @workflow_app		= dbo.workflowapp_fet_fn(@ctxt_user,@ctxt_ouinstance,'ACAP','ACAPASSET','CRAUAS')

	select @workflow_app		= isnull(@workflow_app,'N')
	/*-------EPE-9198-------*/
	if (@workflow_app = 'Y')
	  select  @hdn_workflowsec  = 1

	   else 
	      select @hdn_workflowsec  = 0
/*-------EPE-9198-------*/
	--for getting the asset status
	select 	@status_tmp		= asset_status
	from 	acap_asset_hdr(nolock)
	where 	ou_id			= @ctxt_ouinstance
	and   	upper(asset_number)	= upper(@assetnumber)

	--getting the status text for place holder
	select 	@statustext_tmp		= parameter_text
	from 	fin_quick_code_met (nolock)
	where 	component_id 		= 'ACAP'
	and 	parameter_category  	= 'AS_STA'
	and 	language_id		= @ctxt_language
	and 	parameter_code		= @status_tmp


	if not exists (select 'x' from acap_asset_hdr(nolock)
			where ou_id		= @ctxt_ouinstance
			and   upper(asset_number)	= upper(@assetnumber)
			and   asset_status	= 'AC')
	begin
		exec fin_sp_raise_error '', '', '', '', 'ACAP',3,@m_errorid output
		return
	end

        /* code modified by Swetha for ACAPDMS412AT_000437 on 5/4/2006 */
       /* code modified by Swetha for ACAPDMS412AT_000520 on 24/08/2006 */
        if exists (select 'x' from acap_asset_doc_tmp(nolock)
			where   guid             = @guid 
                        /* Code modified by Swetha for SDINDMS412AT_000538 on 05/01/2007 */
                        and     doc_type        <> 'PM_PV' )
                        /* Code modified by Swetha for SDINDMS412AT_000538 on 05/01/2007 */
        /* code modified by Swetha for ACAPDMS412AT_000520 on 24/08/2006 */
        begin 

        	select 	@assetclassdoc_tmp 	= asset_class,
        		@propno			= proposal_number
        	from 	acap_asset_doc_tmp (nolock)
        	where 	guid 			= @guid
        
        	select 	@assetclass_tmp 	= asset_class 
        	from 	acap_asset_hdr(nolock)
        	where 	ou_id			= @ctxt_ouinstance
        	and   	upper(asset_number)	= upper(@assetnumber)
        
        	if @capitalizationdate is null
        	begin
        		select 	@assetclass_tmp 	= asset_class ,
        			@capitalizationdate	= cap_date
        		from 	acap_asset_hdr(nolock)
        		where 	ou_id			= @ctxt_ouinstance
        		and   	upper(asset_number)	= upper(@assetnumber)
        	end
        
        	if @assetclassdoc_tmp <> @assetclass_tmp
        	begin
        		exec fin_sp_raise_error '','','','','ACAP',4,@m_errorid output
        		return
        	end
        end
         /* code modified by Swetha for ACAPDMS412AT_000437 on 5/4/2006 */

	if exists (select 'x' from acap_asset_doc_tmp (nolock)
		   where guid = @guid )
	begin	
		
		select 	@tagcost_tmp 	= sum(cap_amount)
		from 	acap_asset_doc_tmp (nolock)
		where 	guid 		= @guid
	end


	if exists(select 'x' from acap_asset_doc_line_Dtl(nolock)
			where 	ou_id			= @ctxt_ouinstance
			and   	upper(asset_number)	= upper(@assetnumber))
	begin
		if not exists (select 'x' from acap_asset_doc_tmp(nolock)
				where guid	= @guid)
		begin
			--raiserror('Selected Asset is created with document reference. Select a document in the entry page to amend the asset',16,1)
			select @m_errorid = 10
			return
		end
	end

	if not exists(select 'x' from acap_asset_doc_line_dtl(nolock)
			where 	ou_id			= @ctxt_ouinstance
			and   	upper(asset_number)	= upper(@assetnumber))
	begin
		if exists (select 'x' from acap_asset_doc_tmp(nolock)
				where guid	= @guid)
		begin
			--raiserror('Selected Asset is created without document reference.Select an asset with document reference for amedment ',16,1)
			select @m_errorid = 11
			return
		end
	end
        
        /* code added by Swetha for ACAPDMS412AT_000423 on 04/04/2006 */
        declare spy_cur cursor for 
	select distinct doc_number ,asset_number,doc_amount
	from   acap_asset_doc_tmp(nolock)
	where guid      = @guid 
        /* Code modified by Swetha for SDINDMS412AT_000538 on 05/01/2007 */        
	and   doc_type  = 'PM_PV'
        /* Code modified by Swetha for SDINDMS412AT_000538 on 05/01/2007 */

	open spy_cur

	fetch next from spy_cur into @doc_number,@asset_number,@doc_amount

	while (@@fetch_status = 0 )
	begin 

		select @count1_tmp = count('X')
		from   si_line_dtl T1(NOLOCK),
		       acap_asset_doc_tmp T2(nolock)
		where  T1.tran_no    =   @doc_number
		and    T1.ref_doc_no =   T2.doc_number
		and    T1.tran_ou    = @ctxt_ouinstance	
		and    T1.tran_ou    =   T2.ou_id
		and    T2.guid 	    =   @guid 



		select @count2_tmp   = count('x')
		from   si_line_dtl 	  T1(NOLOCK),
		       acap_asset_doc_dtl T2(NOLOCK)
		where  T1.tran_no      =   @doc_number
		and    T1.ref_doc_no   =   T2.doc_number
		and    T1.tran_ou      =   @ctxt_ouinstance	
		and    T1.tran_ou      =   T2.ou_id
        /* Code modified by Swetha for ACAPDMS412AT_000494 on 22/08/2006 */
		and    T2.asset_number =   isnull(@asset_number,@assetnumber)
        /* Code modified by Swetha for ACAPDMS412AT_000494 on 22/08/2006 */

		if @count1_tmp < 1 and @count2_tmp < 1
		begin 
			--Choose the reference document for which the Supplier Payment Voucher has been raised.
			select @m_errorid =900014587
			return
		end
	
		fetch next from spy_cur into @doc_number,@asset_number,@doc_amount
	end

	close spy_cur
	deallocate spy_cur      

       /* code added by Swetha for ACAPDMS412AT_000423 on 04/04/2006 */  

/* Code added by Esther J on 18/05/2007 for defect ACAPDMS412AT_000710 starts */
	select @depcategory = '' 
	from acap_asset_hdr A(nolock),	ainf_asset_class_vw D (nolock)
	where 	 A.ou_id		= @ctxt_ouinstance
	and   A.asset_number		= @assetnumber
	and   A.fb_id			= @fb
	and 	D.ou_id 		= A.ou_id
	and 	D.asset_class_code      = A.asset_class
	and 	D.dest_component 	= 'ACAP'  
	and 	D.depreciable	 	= 'N'
/* Code added by Esther J on 18/05/2007 for defect ACAPDMS412AT_000710 ends */

	/*Code added by Damodharan. R for Defect ID 14H109_ADEPP_00004 starts here*/
	if @ctxt_service = 'ACAPAMASMSRTGNO'
	begin 
		select @sysdate			=	dbo.res_getdate(@ctxt_ouinstance)
		
		select 	@adepou	 					=	destinationouinstid  
		from  	fw_admin_view_comp_intxn_model (nolock)
		where  	sourcecomponentname			=	'ACAP'
		and    	sourceouinstid				=	@ctxt_ouinstance
		and    	destinationcomponentname	=	'ADEP'

		select	@company_code	=	company_code
		from	emod_ou_vw (nolock)
		where	ou_id			=	@ctxt_ouinstance
		and		@sysdate between effective_from and isnull(effective_to,@sysdate)

		select	@resval_tmp		    =  parameter_code,
				@residualvalue= parameter_value--14H109_ADEPP_00048
		from	cps_processparam_sys (nolock)
		where	company_code	    = @company_code
		AND 	parameter_type	    = 'FASYS' 
		AND		parameter_category  = 'RESVALAPP'
		and		language_id         = @ctxt_language	--14H109_ADEPP_00048
		
			--code for EPE-11483 begins here
		if exists (select 'X'
				   from   ainf_asset_class_mst (nolock)
				   where  asset_class_code	 =  @assetclass		
				   and    ou_id				 =	@ctxt_ouinstance
				   and    asset_Class_status = 'A'
				   and    residual_val        is not null
				   )
		begin	
			select @residualvalue		=  residual_val
			from   ainf_asset_class_mst (nolock)
			where  asset_class_code		=  @assetclass
			and    ou_id				=  @ctxt_ouinstance
			and    asset_Class_status   = 'A'

		end	
		--code for EPE-11483 ends here
	
		if @resval_tmp is null
		begin
			select @resval_tmp = 'N',
				@residualvalue =  NULL--14H109_ADEPP_00048
		end
		/*-------EPE-9198-------*/
		if(@resval_tmp='N')
			select @hdn_residualvalue =0
		else 
			select @hdn_residualvalue =1
/*-------EPE-9198-------*/

		select	@allmodresval_tmp	= parameter_code
		from	fin_processparam_sys i(nolock)
		where	company_code 		= @company_code
		and		component_id 		= 'ADEP'
		and     parameter_type		= 'PROPAR'
		and		parameter_category	= 'ALLMODRESVAL'	

		if @allmodresval_tmp is null
		begin
			select @allmodresval_tmp = 'N'
		end

		select	@usefulllife_tmp    =  parameter_code
		from	fin_processparam_sys (nolock)
		where	company_code	    = @company_code
		and		component_id 		= 'ADEP'	
		AND 	parameter_type	    = 'PROPAR' 
		AND		parameter_category  = 'ALLMODUSEFULLIFE'

		if @usefulllife_tmp is null
			begin
				select @usefulllife_tmp = 'N'
			end
			/*-------EPE-9198-------*/
		if (@usefulllife_tmp = 'N')
			select @hdn_usefullife  = 0
		else 
			select @hdn_usefullife  = 1

			/*-------EPE-9198-------*/

		if @usefulllife_tmp = 'Y'
		begin		
			if isnull(@depcategory,'')	=	''
			begin
				select @usefullifeinmonths	=	NULL
			end
			else
			begin	
				select	@usefullifeinmonths_tmp	=	b.useful_asset_life,
						@yearly_percent		=	yearly_percent
				from	adep_assign_rules_mst a (nolock)
				join	adep_depr_rule_hdr b (nolock)
				on		a.ou_id				=	b.ou_id
				and		a.depr_rule_number	=	b.depr_rule_number	
				and		a.asset_class		=	b.asset_class
				and		a.ou_id				=	@adepou
				and		a.depr_book			=	'CORP'
				and		a.depr_category		=	@depcategory
				and		a.asset_class		=	@assetclass
				and		a.status			=	'A'				
				and		@sysdate between a.eff_date and isnull(a.exp_date,@sysdate)
				
				if @yearly_percent	=	'Y'
				begin
					select	@usefullifeinmonths	=	NULL
				end
				else
				begin
					if @usefullifeinmonths_tmp is not null
					begin
						select	@usefullifeinmonths	=	@usefullifeinmonths_tmp * 12
					end
					else
					begin
						select	@usefullifeinmonths	=	NULL
					end
				end
			end
		end
		else
		begin
			select @usefullifeinmonths	=	NULL
		end
		
		if @resval_tmp = 'Y' and @allmodresval_tmp = 'Y'
		begin
	/*Code commented & added by thyagaraj for defect id :14H109_adepP_00048 starts here*/
		--select	@residualvalue	=	residual_percentage
		--from	adep_residual_meta (nolock)
		--where	company_code 	=	@company_code
		select @residualvalue				 = @residualvalue --14H109_ADEPP_00048
  /*Code commented & added by thyagaraj for defect id :14H109_adepP_00048 ends here*/ 
		end
		else
		begin
			select	@residualvalue	=	NULL
		end 
					
	/*	select @hdnrt_stcontrol =	case	when @resval_tmp = 'N' and @allmodresval_tmp = 'N' and @usefulllife_tmp = 'N' and @newtag = '1' then 'ResOffUseLifeOff'
											when @resval_tmp = 'Y' and @allmodresval_tmp = 'N' and @usefulllife_tmp = 'N' and @newtag = '1' then 'ResOffUseLifeOff'
											when @resval_tmp = 'N' and @allmodresval_tmp = 'Y' and @usefulllife_tmp = 'N' and @newtag = '1' then 'ResOffUseLifeOff'
											when @resval_tmp = 'N' and @allmodresval_tmp = 'N' and @usefulllife_tmp = 'Y' and @newtag = '1' then 'ResOffUseLifeOn'
											when @resval_tmp = 'Y' and @allmodresval_tmp = 'N' and @usefulllife_tmp = 'Y' and @newtag = '1' then 'ResOffUseLifeOn'
											when @resval_tmp = 'N' and @allmodresval_tmp = 'Y' and @usefulllife_tmp = 'Y' and @newtag = '1' then 'ResOffUseLifeOn'
											when @resval_tmp = 'Y' and @allmodresval_tmp = 'Y' and @usefulllife_tmp = 'N' and @newtag = '1' then 'ResOnUseLifeOff'
											when @resval_tmp = 'Y' and @allmodresval_tmp = 'Y' and @usefulllife_tmp = 'Y' and @newtag = '1' then 'ResOnUseLifeOn'
											when @newtag = '0' then 'ResOffUseLifeOff'
											else '' 
									end    */
	end
	else
	begin
		select	@hdnrt_stcontrol	=	'ResOffUseLifeOff',
				@residualvalue		=	NULL,
				@usefullifeinmonths	=	NULL
	end
	/*Code added by Damodharan. R for Defect ID 14H109_ADEPP_00004 ends here*/

	--EPE-1135
	DECLARE @asset_classification FIN_dESC255

	SELECT /*@asset_classification */ @AssetClassification = asset_classification--code modified for PTP-1377
			,@assetclass = asset_class--code added for PTP-1377
	FROM	ainq_asset_hdr(NOLOCK)
	where 	ou_id		= @ctxt_ouinstance
	and   	asset_number	= @assetnumber

	select  distinct @assetcategory = Asset_Category,
					@assetcluster = Asset_Cluster
	from  adep_entity_depcat_map (nolock)
	where asset_class = @assetclass
	and Asset_Classification = @AssetClassification
	and   ou_id		  =	@ctxt_ouinstance
	--EPE-1135

	--EPE-29928
	if @ctxt_service='acapamasmsrasno'
	begin
		select 	@assetclass 	= asset_class 
		from 	ainq_asset_hdr(nolock)
		where 	ou_id			= @ctxt_ouinstance
		and   	asset_number	= @assetnumber
	end
	--EPE-29928
	--SSIU-13
	select 	@ainfou 			        =  destinationouinstid
	from 	fw_admin_view_comp_intxn_model  (nolock)
	where 	sourceouinstid 			    =  @ctxt_ouinstance 
	and 	sourcecomponentname 		= 'ACAP'
	and 	destinationcomponentname 	= 'AINF'
	--SSIU-13
	--EPE-23559  starts
		select @shift_applicable  = shift_applicable
		from   ainf_asset_class_mst(NOLOCK)
		where  ou_id               = isnull(@ainfou,@ctxt_ouinstance) ---isnull added for SSIU-13
		and    asset_class_code    = @assetclass

		if @shift_applicable = 'Y'
		begin 
			select @stnatureofshift = 1
		end
		else
		begin
			select @stnatureofshift = 0
		end		
		--EPE-23559  ends

	/*code Added for EPE-43676 begins here */
	if exists (select 'X'
	           from   ainf_asset_class_mst (nolock)
			   where  asset_class_code	 =  @assetclass			
			   and    ou_id				 =	@ctxt_ouinstance
			   and    asset_Class_status = 'A'
			   and    salvage_per        is not null
			   )
	begin	
		select @salvageper			=	salvage_per
		from   ainf_asset_class_mst (nolock)
		where  asset_class_code		=  @assetclass
		and    ou_id				=  @ctxt_ouinstance
		and    asset_Class_status   = 'A'
	end
	else
	begin
		select @salvageper			=	null
	end
	/*code added for EPE-43676 ends here */

	if @ctxt_service='acapamasmsrasno'
	
	begin
	
		--for displaying the output
		select 	ltrim(rtrim(0))				'fprowno',
			ltrim(rtrim(asset_class ))		'assetclass',
			ltrim(rtrim(asset_desc ))		'assetdescription',
			ltrim(rtrim(asset_group ))		'assetgrpnum',
			ltrim(rtrim(asset_number ))		'assetnumber',
			ltrim(rtrim(@barcode ))			'barcode',
			@businessuse				'businessuse',
			ltrim(rtrim(convert(nvarchar(10),@capitalizationdate,120)))	'capitalizationdate',
			ltrim(rtrim(cost_center ))		'costcenter',
			ltrim(rtrim(convert(nvarchar(10),@createddate,120)))		'createddate',
			ltrim(rtrim(@creationby ))		'creationby',
			ltrim(rtrim(@custodian ))		'custodian',
			ltrim(rtrim(isnull(depr_category,@depcategory)))		'depcategory',--code modified for PTP-1377
			ltrim(rtrim(@fb ))			'fb',
			@guid					'guid' ,
			ltrim(rtrim(@manufacturer ))		'manufacturer',
			ltrim(rtrim(@model ))			'model',
			ltrim(rtrim(@newtag ))			'newtag',
			@salvagevalue				'salvagevalue',
			ltrim(rtrim(@serialnumber ))		'serialnumber',
			ltrim(rtrim(@tagdescription ))		'tagdescription',
			ltrim(rtrim(@tagnumber)) 		'tagnumber',
			ltrim(rtrim(@warrentynumber)) 		'warrentynumber',
			@proposalnumber				'Proposalnumber',
			/* code modified by Swetha for ACAPDMS412AT_000341 on 09/02/2006 */
			isnull(@tagcost_tmp,0)			'tagcost'
			/* code modified by Swetha for ACAPDMS412AT_000341 on 09/02/2006 */
			/*Code added by Damodharan. R for Defect ID 14H109_ADEPP_00004 starts here*/
			,@ResidualValue						'RESIDUALVALUE',
			@UsefulLifeinMonths					'USEFULLIFEINMONTHS',
			@hdnrt_stcontrol					'HDNRT_STCONTROL',
/*code modified for EPE-8428 - Harithra*/
			@accountcode 'accountcode', 
			@accountdescription 'accountdescription', 
			@lscostcentre 'lscostcentre', 
			@analysiscode 'analysiscode', 
			@subanalysiscode 'subanalysiscode'
			/*Code added by Damodharan. R for Defect ID 14H109_ADEPP_00004 ends here*/
			,@assetclassification 'assetclassification' --EPE-11335
			,@assetcategory 'assetcategory', 
			@assetcluster 'assetcluster',
			--EPE-29928 starts
			(select	parameter_text
				from	fin_quick_code_met (nolock)
				where component_id 		= 'ACAP'
				and 	parameter_type 	= 'CBO'
				and 	parameter_category= 'NAT_SFT'
				and 	parameter_code 	= 'S'
				and	language_id 		= @ctxt_language)		'natureofshift'
			,@stnatureofshift	'stnatureofshift'
			--EPE-29928 ends
			,@salvageper			'salvageper'--EPE-43676
		from 	ainq_asset_tag_vw(nolock) 
		where 	ou_id		= @ctxt_ouinstance
		and   	asset_number	= @assetnumber
		return
	end

	--if the service is for on enter of tag number
	if @ctxt_service='acapamasmsrtgno'
	begin

		--if tag number is null then raise error
		if @tagnumber is null
		begin
			exec fin_sp_raise_error '', '', '', '', 'ACAP',5 , @m_errorid output
			return
		end
	
		
		if @newtag = 0
		begin
		
			--if tag number does not exists then raise error
			if not exists (select 'x' from acap_asset_tag_dtl(nolock)
					where ou_id		= @ctxt_ouinstance
					and   asset_number	= @assetnumber
					and   fb_id		= @fb
					and   tag_number	= @tagnumber
					)
			begin
				exec fin_sp_raise_error '', '', '', '', 'ACAP',6 , @m_errorid output
				return
			end
	
			--if tag number does not exists then raise error
			if not exists (select 'x' from acap_asset_tag_dtl(nolock)
					where ou_id		= @ctxt_ouinstance
					and   asset_number	= @assetnumber
					and   fb_id		= @fb
					and   tag_number	= @tagnumber
					and   tag_status	= 'AC'
					/* Code added by Swetha for ACAPDMS412AT_000268 on 28/02/2006 */
					and   isnull(inv_status,'OK') = 'OK'
					/* Code added by Swetha for ACAPDMS412AT_000268 on 28/02/2006 */
					)
			begin
				exec fin_sp_raise_error '', '', '', '', 'ACAP',7 , @m_errorid output
				return
			end
	--code commented for 14H109_ACAP_00004 starts
		/*	if exists(select 'x' from ainq_asset_tag_balance_vw(nolock)
					where  	ou_id 		= @ctxt_ouinstance
					and     asset_number 	= @assetnumber
					and 	fb_id		= @fb
					and	tag_number	= @tagnumber
					and     isnull(cum_depr_charge,0)> 0)
			begin
				--raiserror('Further Processing for the asset and tag combination has happened .Hence cannot  be amended',16,1)
				select @m_errorid = 13
				return
			end
			if not exists(select 'x' from ainq_asset_tag_dtl(nolock)
					where  	ou_id 		= @ctxt_ouinstance
					and     asset_number 	= @assetnumber
					and 	fb_id		= @fb
					and	tag_number	= @tagnumber
					and     isnull(revalued_cost,0) = 0)
			begin
				--raiserror('Further Processing for the asset has happened .Hence cannot  be amended',16,1)
				select @m_errorid = 13
				return
			end*/
		--code commented for 14H109_ACAP_00004 ends
			
			if @propno is not null
			begin				
				select 	@proposal_number = proposal_number
				from  	acap_asset_tag_dtl(nolock)
				where 	ou_id		= @ctxt_ouinstance
				and   	asset_number	= @assetnumber
				and	tag_number	= @tagnumber
		
				/*if @propno <> @proposal_number
				begin
					--raiserror('Proposal number for the asset and the selected document is not the same',16,1)
					select @m_errorid = 12
					return
				end*/
			end
		
		end
	 /* code added for EPE-82887 starts*/
			if  @assetdescription is null 
		      begin 
				select  @assetdescription = asset_desc 
				FROM	ainq_asset_hdr(NOLOCK)
				where 	ou_id		= @ctxt_ouinstance
			    and   	asset_number= @assetnumber
		     end
	/* code added for EPE-82887 ends*/
		
		
		if @newtag = 1
		begin
			/* Code modified by Swetha for ACAPDMS412AT_000338 on 08/02/2006 */
                        /* Code modified by Swetha for ACAPDMS412AT_000548 on 11/9/2006 */
                        
			if exists (select 'x'
				   from acap_asset_info_tmp (nolock)
				   where guid			= @guid
                                    and  new_tag                = 1
                                    and  @tagnumber             > tag_number)
			begin
				select 	@maxtagno_tmp		= max(tag_number)
				from 	acap_asset_info_tmp (nolock)
				where 	guid			= @guid
				and 	ou_id			= @ctxt_ouinstance
				and  	upper(asset_number)	= upper(@assetnumber)
                                 and     new_tag                = 1
			end
			else
			begin 
				select 	@maxtagno_tmp		= max(tag_number)
				from 	acap_asset_tag_dtl (nolock)
				where 	ou_id			= @ctxt_ouinstance
				and  	upper(asset_number)	= upper(@assetnumber)
			end
		
			if @tagnumber <> @maxtagno_tmp + 1
			begin
				exec fin_sp_raise_error '', '', '', '', 'ACAP',8, @m_errorid output
				return
			end
                        /* Code modified by Swetha for ACAPDMS412AT_000548 on 11/9/2006 */
			/* Code modified by Swetha for ACAPDMS412AT_000338 on 08/02/2006 */

			--for displaying the output
			select 	ltrim(rtrim(0)) 					'fprowno',
				ltrim(rtrim(@assetclass)) 				'assetclass',
				ltrim(rtrim(@assetdescription)) 			'assetdescription',
				ltrim(rtrim(@assetgrpnum ))				'assetgrpnum',
				null							'assetlocation',
				ltrim(rtrim(@assetnumber)) 				'assetnumber',
				null							'barcode',
				null							'businessuse',
				ltrim(rtrim(convert(nvarchar(10),@capitalizationdate,120)))'capitalizationdate',
				null							'costcenter',
				ltrim(rtrim(convert(nvarchar(10),@createddate,120))) 	'createddate',
				@creationby						'creationby',
				null							'custodian',
				@depcategory						'depcategory',
				@fb								'fb',
				@guid							'guid' ,
				null							'inservicedate',
				null							'manufacturer',
				null							'model',
				@newtag 						'newtag',
				null							'salvagevalue',
				null							'serialnumber',
				@tagcost_tmp						'tagcost',
				null							'tagdescription',
				@tagnumber						'tagnumber',
				null							'warrentynumber',
				@proposalnumber						'proposalnumber'
				/*Code added by Damodharan. R for Defect ID 14H109_ADEPP_00004 starts here*/
				,@ResidualValue						'RESIDUALVALUE',
				@UsefulLifeinMonths					'USEFULLIFEINMONTHS',
				@hdnrt_stcontrol					'HDNRT_STCONTROL',
/*code modified for EPE-8428 - Harithra*/
				@accountcode 'accountcode', 
				@accountdescription 'accountdescription', 
				@lscostcentre 'lscostcentre', 
				@analysiscode 'analysiscode', 
				@subanalysiscode 'subanalysiscode'
				/*Code added by Damodharan. R for Defect ID 14H109_ADEPP_00004 ends here*/
				,@assetclassification 'assetclassification' --EPE-11335		
				,@assetcategory 'assetcategory', 
				@assetcluster 'assetcluster'	
				--EPE-23559 starts
				,(select	parameter_text
				from	fin_quick_code_met (nolock)
				where component_id 		= 'ACAP'
				and 	parameter_type 	= 'CBO'
				and 	parameter_category= 'NAT_SFT'
				and 	parameter_code 	= 'S'
				and	language_id 		= @ctxt_language)		'natureofshift'
				,@stnatureofshift	'stnatureofshift'
				 --EPE-23559 ends
				 ,@salvageper			'salvageper'--EPE-43676
				return
		end
/*Code modified by Kavitha R on 27/02/2006 for defect id ACAPDMS412AT_000355 begins*/
		--for displaying the output
		select 	@tagcost_tmp		= isnull(@tagcost_tmp,0) + sum(isnull(tag_cost,0))
		from 	acap_asset_tag_dtl a(nolock)
		where 	a.ou_id			= @ctxt_ouinstance
		and   	a.asset_number		= @assetnumber
		and   	a.tag_number		= @tagnumber
		and   	a.fb_id			= @fb
		and	a.tag_status		= 'AC'

		--for displaying the output
		select 	top 1 ltrim(rtrim(@assetclass)) 			'assetclass',
			ltrim(rtrim(@assetdescription)) 			'assetdescription',
			ltrim(rtrim(@assetgrpnum ))				'assetgrpnum',
			ltrim(rtrim(asset_location)) 				'assetlocation',
			ltrim(rtrim(@assetnumber)) 				'assetnumber',
			ltrim(rtrim(bar_code)) 					'barcode',
			business_use		 				'businessuse',
			ltrim(rtrim(convert(nvarchar(10),@capitalizationdate,120)))'capitalizationdate',
			''							'capitalizationnumber',
			ltrim(rtrim(cost_center)) 				'costcenter',
			ltrim(rtrim(convert(nvarchar(10),@createddate,120))) 	'createddate',
			ltrim(rtrim(@creationby)) 				'creationby',
			ltrim(rtrim(custodian ))				'custodian',
			ltrim(rtrim(isnull(depr_category,@depcategory))) 	'depcategory',  --ACAPDMS412AT_000710
			ltrim(rtrim(@fb)) 					'fb',
			@guid							'guid' ,		
			ltrim(rtrim(convert(nvarchar(10),inservice_date,120)))	'inservicedate',
			(select b.parameter_text	
			from 	fin_quick_code_met b(nolock)
			where	b.component_id		= 'ACAP'
			and	b.parameter_type	= 'CBO'
			and	b.parameter_category	= 'INVCYC'
			and	b.parameter_code	= a.inv_cycle
			and	b.language_id		= @ctxt_language)	'invcyclemlenn',
			ltrim(rtrim(manufacturer)) 				'manufacturer',
			ltrim(rtrim(model)) 					'model',
			ltrim(rtrim(@newtag ))					'newtag',
			isnull(@proposalnumber,ltrim(rtrim(proposal_number)))				'proposalnumber',
			salvage_value		 				'salvagevalue',
			ltrim(rtrim(serial_no)) 				'serialnumber',
			isnull(@tagcost_tmp,0)					'tagcost',
			ltrim(rtrim(tag_desc)) 					'tagdescription',
			ltrim(rtrim(@tagnumber)) 				'tagnumber',
			ltrim(rtrim(warranty_no)) 				'warrentynumber',
			0							'fprowno'
			/*Code added by Damodharan. R for Defect ID 14H109_ADEPP_00004 starts here*/
			,@ResidualValue						'RESIDUALVALUE',
			@UsefulLifeinMonths					'USEFULLIFEINMONTHS',
			@hdnrt_stcontrol					'HDNRT_STCONTROL',
			/*code modified for EPE-8428 - Harithra*/
			a.LAccount_code 'accountcode', 
			a.LAccount_desc 'accountdescription', 
			a.Lcost_center 'lscostcentre', 
			a.LAnalysis_code 'analysiscode', 
			a.LSubAnalysis_code 'subanalysiscode',
			@hdn_residualvalue	'hdn_residuallife',--EPE-9198 
			@hdn_usefullife		 'hdn_userfullife',--EPE-9198 
			@hdn_workflowsec	'hdn_workflowsec' --EPE-9198
			/*Code added by Damodharan. R for Defect ID 14H109_ADEPP_00004 ends here*/			
			,@assetclassification 'assetclassification' --EPE-11335
			,@assetcategory			'assetcategory', 
			@assetcluster			'assetcluster',
			a.asset_capacity_uom	'measurunit', --EPE-16037
			a.asset_capacity		'totalcapact' --EPE-16037
			--EPE-23559 starts
			,(select	parameter_text
			from	fin_quick_code_met (nolock)
			where component_id 		= 'ACAP'
			and 	parameter_type 	= 'CBO'
			and 	parameter_category= 'NAT_SFT'
			and 	parameter_code 	= a.natureofshift
			and	language_id 		= @ctxt_language)		'natureofshift'
			,@stnatureofshift	'stnatureofshift'
			 --EPE-23559 ends
			 ,salvage_valper			'salvageper'--EPE-43676
		from 	acap_asset_tag_dtl a(nolock)
		where 	a.ou_id			= @ctxt_ouinstance
		and   	a.asset_number		= @assetnumber
		and   	a.tag_number		= @tagnumber
		and   	a.fb_id			= @fb
		and	a.tag_status		= 'AC'
		order by createddate desc	
/*Code modified by Kavitha R on 27/02/2006 for defect id ACAPDMS412AT_000355 ends*/
	end

	set nocount off
end
































