/*$File_version=ms4.3.0.38$*/
/*$file name : acapaccountingpost.sql*/
/*$version   : 4.0.0.041*/
/*==================================================
   stored procedure : acapaccountingpost
   method           :acapaccountingpost
   created on       : 26 may 2001 13:35:11:437
   created at       : s4177
   generated by     : swanand


   Modified By      : Swetha
   Modified Date    : 9/1/2006
   Modified Purpose : ACAP Code Revamp(Pls Refer Source Safe For Earlier Version)

   Modified By      : Swetha
   Modified Date    : 06/03/2006
   Modified Purpose : ACAP Code Revamp(Pls Refer Source Safe For Earlier Version)

   Modified By      : Swetha
   Modified Date    : 20/03/2006
   Modified Purpose : ACAPDMS412AT_000322

   
   Modified By      : Swetha
   Modified Date    : 28/03/2006
   Modified Purpose : ACAPDMS412AT_000147

   Modified By      : Swetha
   Modified Date    : 28/03/2006
   Modified Purpose : ACAPDMS412AT_000147

   Modified By      : Swetha
   Modified Date    : 29/03/2006
   Modified Purpose : ACAPDMS412AT_000147

   
   Modified By      : Swetha
   Modified Date    : 18/5/2006
   Modified Purpose : ACAPDMS412AT_000444

   Modified By      : Swetha
   Modified Date    : 6/6/2006
   Modified Purpose : ACAPDMS412AT_000462
 
   Modified By      : Swetha
   Modified Date    : 26/6/2006
   Modified Purpose : ACAPDMS412AT_000440
   
   Modified By      : Swetha
   Modified Date    : 16/10/2006
   Modified Purpose : ACAPDMS412AT_000559

Modification History
Modified By		Date			Remarks
Uma Maheswari		23rd Jan 2007		ACAPDMS412AT_000614
Uma Maheswari		23rd Jan 2007		ACAPDMS412AT_000613
Uma Maheswari		06th Feb 2007		ACAPDMS412AT_000620
Uma Maheswari		13th Jun 2007		AINQDMS412AT_000030
Uma Maheswari		20th June 2008		DMS412AT_ACAP_00022
Uma Maheswari		25th Nov 2008		ES_ACAP_00041
Angelin.R		25th Nov 2008		8H123-2_MR_00003
Uma Maheswari		19th Aug 2009		ES_ACAP_00074
Vairamani C		18 Nov 2009		ES_ACAP_00095
Esther J		01/02/2010		9H123-1_ACAP_00023
Esther J		05/09/2012		12H124_ACAP_00001[ES_General_00632]
Esther J		05/09/2012		12H124_ACAP_00001:12H124_ACAP_00066[ES_General_00632]
Esther J		05/09/2012		12H124_ACAP_00001:12H124_ACAP_00053[ES_General_00632]
ESther J		27/09/2012		12H124_ACAP_00001:12H124_ACAP_00096 
Aditya Sitaraman 26/07/2013		ES_ACAP_00475
Aditya Sitaraman 08/10/2013		ES_ACAP_00521
Santhakumar R	 16/12/2013		ES_ACAP_00534
Aditya Sitaraman 28/11/2014		ES_ACAP_00693
Aditya Sitaraman 05/02/2015		ES_ACAP_00725
Aditya Sitaraman 06/05/2015		ES_ACAP_00770
Indira G		 26/08/2015		ES_ACAP_00829
Aditya Sitaraman 07/10/2015		ES_ACAP_00852			
Aditya Sitaraman 04/12/2015		ES_ACAP_00906	
Aditya Sitaraman 19/01/2016		ES_ACAP_00939
Kavitha R		 01/11/2016		14H109_General_00167
Ashok V			 2/15/2017		ES_ACAP_01153
Aditya S		 05/07/2017		TDH-127	
Aditya S		 25/10/2017		NSAPL-2409
Uma Maheswari B	 09-03-2018		EBS-1074/EBS-1117	
Ashok V			 13/03/2018		EP-96	
Aditya S		 27/03/2018		EP-93
Sweety Ninave	 18/04/2018		EDS-57	
Aditya S		 24/04/2018		EDS-58 
/*  Harithra		 17-08-2018         EPE-8428                             */
/*  Harithra		 17-08-2018         EPE-8702                            */
/*Ramesh Kumar C	 26/04/2019			EPE-13183							*/
/*Aditya S			 20/08/2019			PTP-106								*/
/*Aditya S			 30/08/2019			EBS-3394							*/
/*Ashok V			 16/03/2020			EA-630								*/
/*Aditya S			 19/03/2020			PTP-631								*/
/*Aditya S			 20/07/2020			LOEINT-450							*/
/*Balaji C			 22/07/2020			PE-527								*/
/*Aditya S			 07/12/2020			ADECCOPROD-1782						*/
/*Srinivasan M       23/08/2023         RGSE-213*/

grant all on acapaccountingpost to public
*/
--procedure to takre care of all the accounting related information which should 
--be posted to FBP

Create procedure acapaccountingpost
	@ctxt_language   		fin_ctxt_language  ,
	@ctxt_ouinstance   		fin_ctxt_ouinstance  ,
	@ctxt_service   		fin_ctxt_service  ,
	@ctxt_user  			fin_ctxt_user  ,
	@assetclass				fin_assetclass ,
	@fb   					fin_financebookid  ,			
	@transaction_number 	fin_documentnumber ,
	@capital_date			fin_date,
	@transaction_date		fin_date,
	@transaction_type		fin_trantype,
	@assetnumber			fin_assetnumber ,
	@tagnumber				fin_assettagno ,
	@assetcost				fin_amount ,
	@costcenter 			fin_costcentercode,
	@acap_type				fin_desc20,
	@m_errorout				fin_int output

as	
begin

	declare @companycode_tmp		fin_desc40 ,
		@capdate_tmp			fin_date ,
		@capnumber_tmp			fin_desc40,
		@basecurrency_tmp		fin_currencycode ,
		@dracctcode_tmp			fin_accountcode ,
		@guid_tmp			fin_guid ,
		@pbasecurrency_tmp		fin_currencycode ,
		@exchangeratetype_tmp		fin_type ,
		@exchangerate_tmp		fin_exchangerate ,
		@maximumlimit_tmp		fin_amount ,
		@minimumlimit_tmp		fin_amount ,
		@exchangeratecategory_tmp	fin_param_text ,
		@currencyunits_tmp		fin_units ,
		@pbaseamt_tmp			fin_amount ,
		@bu_tmp				fin_buid ,
		@year_tmp			fin_financeyear ,
		@proposalnum_tmp		fin_documentnumber ,
		@budgetnum_tmp			fin_documentnumber,
		@costcenter_tmp			fin_costcentercode ,
		@macflag_tmp			fin_flag ,
		@craccount_tmp			fin_accountcode,
		@docnumber_tmp			fin_documentnumber,
		@line_tmp			fin_lineno,
		@pubouinstid_tmp		fin_ctxt_ouinstance ,
		@today				fin_date 	,
		@errorcode_tmp 			fin_int ,
		@errortmp1			fin_int,
		@m_errorid 			fin_int ,
		@tagnumber_tmp			fin_assettagno,
		@lineno_tmp			fin_lineno ,
		@capamount_tmp 			fin_amount,
		@crdr1 				fin_flag,
		@crdr2 				fin_flag,
		@usg_type			fin_usageid,
		@errormsg			fin_placeholder,
		@ctrldracc_tmp			fin_controlaccounttype,
		@ctrlcracc_tmp			fin_controlaccounttype,
		@sidocno_tmp			fin_documentnumber,
		@paytd_matchingtype_tmp 	fin_param_code,
		@ponumber_tmp 			fin_documentnumber,
		@ref_doc_no_tmp 		fin_documentnumber,
		@acccount 			fin_int,
		@jourcount			fin_int,
		@wipcount			fin_int,
		@crdepr				fin_amount,
		@drdepr				fin_amount,
		@crrevdepr			fin_amount,
		@drrevdepr			fin_amount,
		@netdepr			fin_amount,
		@netrevdepr			fin_amount,
		@orig_tag_cost			fin_amount,
		@new_tag_cost			fin_amount,
		@appor_ratio			fin_amount,
		@cap_flag			fin_flag,
		@cap_wo_number			fin_documentnumber,
		@lineno1_tmp			fin_lineno,
		@account_code			fin_accountcode,
		@trfaccount_tmp			fin_accountcode,--code added for the dts id 12H124_ACAP_00001[ES_General_00632] 
                @po_no                          fin_documentnumber,
                @gr_no                          fin_documentnumber,
                @paytd_matchingtype	        udd_metadata_code,
                @voucher_type                   fin_documenttype,
                @reversal_period                fin_financeperiodrange,
                @posting_date                   fin_date,
                @errormsgout                    fin_text255,
                @notypeno                       fin_notypeno,
                @retval_tmp                     fin_int,
                @tranno                         fin_documentnumber,
                --14H109_arev_00034
				@imp_loss_pr					fin_amount,	
				@imp_loss_af					fin_amount,
				@acc_imp_loss					fin_accountcode,
				@imp_loss						fin_accountcode
				,@cost_Center_tmp				fin_costcentercode, --EP-93	
				@ccexists						fin_flag ,			--EBS-3394
				--14H109_arev_00034
				/*code modified for EPE-8428 - Harithra*/
				@cps_param_tmp					fin_flag,
				@laccount_crcode_tmp			fin_accountcode, 
				@lcost_center_tmp				fin_costcentercode,
				@lanalysis_tmp					fin_analysiscode,--EPE-8702
				@lsubanalysis_tmp				fin_subanalysiscode--EPE-8702
	set ansi_nulls on 
	set @errorcode_tmp = 0

	/* Code added by Uma for the bug id : ACAPDMS412AT_000620 starts here*/
	--BEGIN of Standard code for getting precision type
	declare @pqty_tmp                  fin_int ,
		@pamt_tmp                  fin_int ,
		@prate_tmp                 fin_int ,
		@perate_tmp            fin_int ,
		@phigh_tmp                 fin_int ,
		@pmed_tmp                  fin_int ,
		@plow_tmp                fin_int
	
	exec fin_sp_precisiontype_rtr @pqty_tmp output, @pamt_tmp output,
	     @prate_tmp output, @perate_tmp output, @phigh_tmp output,
	     @pmed_tmp output, @plow_tmp output

	/* Code added by Uma for the bug id : ACAPDMS412AT_000620 ends here*/
	
	select @costcenter_tmp = @costcenter --Code added by Uma for the bug id : ACAPDMS412AT_000614

	select @costcenter = null
	
	if @fb  is null
	begin
		return 84
	end		 				

	-- get only datepart from date time 
	select @today = dbo.RES_Getdate(@ctxt_ouinstance)
	select @today = convert(datetime,convert(nchar(12),@today))

	--getting company code
	select 	@companycode_tmp= company_code 
	from 	emod_ou_vw(nolock)
	where 	ou_id 		= @ctxt_ouinstance
	and 	@today 	between effective_from 
		and isnull(effective_to,@today)
/*code modified for EPE-8428 - Harithra*/
	select @cps_param_tmp = parameter_code 
	from cps_processparam_sys
	where company_code  = @companycode_tmp
	and	language_id   = @ctxt_language
	and	parameter_type = 'FASYS'
	and parameter_category = 'MANENTWOREFDOC'

	if upper(@acap_type) in ('AST','AMD') 
		select @usg_type = 'CAPASS'

	else if upper(@acap_type) = 'WIP' 		
		select @usg_type = 'CWIP'	

	if @acap_type not in ('CJV','WIP')  
	begin	
		----- To get the debit account
		exec @errorcode_tmp = ardisspgetassetacc @ctxt_language ,@ctxt_ouinstance,
			@ctxt_service ,@ctxt_user ,@assetclass ,@fb,
			@usg_type ,@transaction_date ,@dracctcode_tmp output , 
			@errormsg output 
	
		select 	@ctrldracc_tmp 	= ctrl_acctype 
		from 	as_opaccountfb_vw (nolock)
		where 	company_code 	= @companycode_tmp
		and 	account_code  	= @dracctcode_tmp          
		and 	fb_id   	= @fb
		
		/*
		0- Success
		1 - No Account Code exists  for the Asset Class Code and Usage.
		2 - Provide Login OU
		3 - Provide Asset Class Code
		4 - Provide Financebook
		5 - Provide UsageID
		6 - Provide Transactiondate
		7 - OU not mapped to any company
		*/

		select  @m_errorout = 	case isnull(@errorcode_tmp,0)
						when 1 then 186
						when 2 then 109
						when 3 then 245
						when 4 then 110
						when 5 then 246
						when 6 then 152
						when 7 then 247
						when 0 then 0
					end
	
		if isnull(@m_errorout,0) <> 0
		begin
			return @m_errorout			
		end
		
		--code added for ES_ACAP_00725 starts 
		if upper(@acap_type) in ( 'AST' ,'AMD')
		and @ctxt_service not in ('acapspastgsrspastg')--ES_ACAP_00770  
		begin
				if not exists
				(
					select 	'x' 
					from 	acap_tag_doc_dtl(nolock)
					where 	ou_id 		= @ctxt_ouinstance
					and 	asset_number	= @assetnumber
					and 	cap_number 	= @transaction_number
				)
				--PTP-631	
				and exists
				(
					select 	'x'
					from 	acap_asset_tag_dtl (nolock)
					where 	ou_id 			= @ctxt_ouinstance
					and 	asset_number	= @assetnumber
					and 	cap_number 		= @transaction_number
					and		LAccount_code	is null
				)
				--PTP-631	
				begin
		--code added for ES_ACAP_00725 end
					------ To get credit Account
					exec @errorcode_tmp = ardisspgetassetacc @ctxt_language ,@ctxt_ouinstance,
						@ctxt_service ,@ctxt_user ,@assetclass ,@fb,
						'CWIP' ,@transaction_date ,@craccount_tmp output , @errormsg output 
				
					/*	0- Success
					1 - No Account Code exists  for the Asset Class Code and Usage.
					2 - Provide Login OU
					3 - Provide Asset Class Code
					4 - Provide Financebook
					5 - Provide UsageID
					6 - Provide Transactiondate
					7 - OU not mapped to any company
					*/
					
					select @m_errorout = 0 
					
					select  @m_errorout = 	case isnull(@errorcode_tmp,0)
									when 1 then 186
									when 2 then 109
									when 3 then 245
									when 4 then 110
									when 5 then 246
									when 6 then 152
									when 7 then 247
									when 0 then 0
								end
					
					if isnull(@m_errorout,0) <> 0
					begin
						return @m_errorout			
					end
				end		--ES_ACAP_00725
			end			--ES_ACAP_00725
	end	
	
	--getting bu
	select 	@bu_tmp 	= bu_id
	from 	emod_lo_bu_ou_vw(nolock)
	where 	ou_id 		= @ctxt_ouinstance
	and	company_code 	= @companycode_tmp
	
	--getting currency code
	select 	@basecurrency_tmp	= currency_code 
	from 	emod_basecurr_vw A(nolock),
		emod_ou_vw B(nolock)
	where 	B.ou_id			= @ctxt_ouinstance
	and 	A.company_code		= B.company_code
	and 	A.flag			= 'B'

	if   upper(@ctxt_service)  in ('ACAPRVASMSRRVAS')
	begin
		select 	@transaction_number 	= H.document_number
		from 	acap_reverse_asset_dtl D (nolock) ,
			acap_reverse_asset_hdr H (nolock)
		where 	H.asset_number 		= @assetnumber
		and 	d.document_number 	= H.document_number
		
		select  @exchangerate_tmp 	= pbc_erate		
		from 	acap_accounting_info_dtl (nolock)
		where 	tran_number  		= @transaction_number
		and	tran_type    		= @transaction_type
		and	asset_number 		= @assetnumber
	end
	else
	begin
		exec @errorcode_tmp = emod_sysact_spparcurrval 	
			@ctxt_ouinstance,
			@transaction_date,
			@pbasecurrency_tmp output

		/*		
		1	--	Enter Organisation Unit.
		2	--	Enter Date
		3	--	Ou is not valid
		4	--	Given Ou is not mapped to any BU
		5	--	Company is not in active status
		6	--	Paralell Currency was  deleted  for the company
		7	--	Paralell Currency was  not defined  for the company
		8	--	Curencies is not  in mapped status
		9	--	Curencies is not  in active status
		0	--	Success.
		*/

		select @m_errorout = 0 

		select  @m_errorout = 	case isnull(@errorcode_tmp,0)
						when 1 then 149
						when 2 then 152
						when 3 then 167
						when 4 then 180
						when 5 then 182
						when 6 then 243
						when 7 then 244
						when 8 then 183
						when 9 then 184	
						when 0 then 0
					end

		if isnull(@m_errorout,0) <> 0
		begin
			return @m_errorout			
		end

		--here use company parameter setup to get exchange rate type
		select 	@exchangeratetype_tmp 	= parameter_value
		from 	cps_processparam_vw (nolock)
		where 	company_code		= @companycode_tmp
		and 	parameter_code		= 'FAMERTYPE'

		if @pbasecurrency_tmp is not null
		begin
			--getting parallel exchange rate
			exec @errorcode_tmp = erate_sysact_spgetexcgrate 
				@ctxt_ouinstance, @ctxt_user,@ctxt_language,@basecurrency_tmp,
				@pbasecurrency_tmp,@today,@exchangeratetype_tmp,
				@exchangerate_tmp output, @maximumlimit_tmp output,
				@minimumlimit_tmp output, @exchangeratecategory_tmp output,
				@currencyunits_tmp output,'ACAP'

			--	1	-	process parameter for base currency sequence not set define the process parameter
			--	2	-	process parameter for cross currency sequence not set define the process parameter
			--	3	-	from currency code <fromcurrencycode> provided is not mapped to the company  provide valid from currency code
			--	4	-	to currency code <tocurrencycode> provided is not mapped to the company  provide valid to currency code
			--	5	-	enter the date for which exchange rate is required
			--	6	-	date is not as per the date format  specify date as per the date format
			--	7	-	exchange rate type  <exchratetypecombo> specified does not exist  enter valid exchange rate type
			--	8	-	exchange rate does not exist for the currency combination <fromcurrencycode> and <tocurrencycode> and exchange rate type <exchratetypecombo>


			select @m_errorout = 0 

			select @m_errorout = 	case isnull(@errorcode_tmp,0)
							when 1 then 188
							when 2 then 189
							when 3 then 190
							when 4 then 191	
							when 5 then 192
							when 6 then 193
							when 7 then 194
							when 8 then 195
							when 0 then 0
						end
			if isnull(@m_errorout,0) <> 0
			begin
				return @m_errorout
			end	
		end
	end

	if upper(@acap_type) in ( 'AST' ,'AMD')
	begin
		-- to get credit account code when no doc is selceted
		if not exists
		(
			select 	'x' 
			from 	acap_tag_doc_dtl(nolock)
			where 	ou_id 		= @ctxt_ouinstance
			and 	asset_number	= @assetnumber
			and 	cap_number 	= @transaction_number
		)
		begin
			if upper(@ctxt_service) not in('ACAPRVASMSRRVAS')
			begin
				delete 	acap_accounting_info_dtl
				from 	acap_accounting_info_dtl A,
					acap_asset_tag_dtl B 
				where 	A.asset_number 	<> B.asset_number
				and 	A.tag_number 	<> B.tag_number
				and 	A.tran_number 	=  @transaction_number
			end

			select 	@ctrlcracc_tmp 	= ctrl_acctype 
			from 	as_opaccountfb_vw (nolock)
			where 	company_code 	= @companycode_tmp
			and 	account_code  	= @craccount_tmp                    
			and 	fb_id   	= @fb
			/*code modified for EPE-8428 - Harithra*/
			if LOWER(@ctxt_service)  in ('acaprvasmsrrvas') 
			begin
				declare tagdtlcur cursor for
				select 	tag_number , sum(isnull(tag_cost ,0)),null,null,null,null-- Code modified by Uma for the bug id: DMS412AT_ACAP_00022
				from 	acap_asset_tag_dtl (nolock)
				where 	ou_id 		= @ctxt_ouinstance
				and 	asset_number	= @assetnumber
				and 	tag_status	= 'RE'
				group by tag_number-- Code added by Uma for the bug id: DMS412AT_ACAP_00022
			end
			else if lower(@ctxt_service) = 'acapspastgsrspastg'
			begin
				declare tagdtlcur cursor for
				select 	tag_number , tag_cost ,null,null,null,null
				from 	acap_split_asset_dtl (nolock)
				where 	ou_id 		= @ctxt_ouinstance
				and 	document_number	= @transaction_number
				order by tag_number asc
			end
			else
			begin
				declare tagdtlcur cursor for
				select 	tag_number , tag_cost ,LAccount_code,Lcost_center,LAnalysis_code,LSubAnalysis_code
				from 	acap_asset_tag_dtl (nolock)
				where 	ou_id 		= @ctxt_ouinstance
				and 	asset_number	= @assetnumber
				and 	cap_number 	= @transaction_number
			end
			open tagdtlcur

			fetch  next from tagdtlcur into @tagnumber_tmp ,@capamount_tmp	,@laccount_crcode_tmp, @lcost_center_tmp,@lanalysis_tmp,@lsubanalysis_tmp--EPE-8702
			while @@fetch_status =0 
			begin
				--to get the parallel base amount
				select @pbaseamt_tmp = @exchangerate_tmp * @capamount_tmp
                        
                                /* code modified by Swetha for ACAPDMS412AT_000444 on 18/5/2006 */
  /* Code modified by Swetha for ACAPDMS412AT_000559 on 16/10/2006 */
				if upper(@ctxt_service) in ('ACAPCRSMASSRSMAT','ACAPCRCMASSRCPXAST','ACAPAMASMSRAMAS','ACAPEDASSSREDTAST','ACAPAUASMSRAUAS','ACAPAUASESRAUAS','ACAPSPASTGSRSPASTG','ACAPAPADDBSRBLKAST','ACAPCRBLTGSRBLKTG')	
                                /* Code modified by Swetha for ACAPDMS412AT_000559 on 16/10/2006 */
                                /* code modified by Swetha for ACAPDMS412AT_000444 on 18/5/2006 */
				begin
					select @crdr1 = 'CR'
					select @crdr2 = 'DR'
				end

				if upper(@ctxt_service) = 'ACAPRVASMSRRVAS'			
				begin
					select @crdr1 = 'DR'
					select @crdr2 = 'CR'

					select 	@transaction_number 	= H.document_number
					from 	acap_reverse_asset_dtl D (nolock) ,
						acap_reverse_asset_hdr H (nolock)
					where 	H.asset_number 		= @assetnumber
					and 	d.document_number 	= H.document_number
					and 	d.tag_number 		= @tagnumber_tmp
				end

				if upper(@ctxt_service) = 'ACAPSPASTGSRSPASTG'
				begin
					select @craccount_tmp = @dracctcode_tmp
					select @ctrlcracc_tmp =	@ctrldracc_tmp
				end
				
	            if upper(@ctxt_service) not in  ('ACAPRVASMSRRVAS')
				begin  
				/*code modified for EPE-8428 - Harithra*/
				if @cps_param_tmp = 'Y'
				begin --Cr lg for manual starts
        		if not exists 
					(
						select 	'x' 
						from 	acap_accounting_info_dtl (nolock)
						where 	tran_number 	= @transaction_number
						and	tran_type 	= @transaction_type
						and	asset_number 	= @assetnumber
						and	tag_number 	= @tagnumber_tmp
						and	account_code 	= @laccount_crcode_tmp 
						and	drcr_flag 	= @crdr1
					)			
					begin
						insert into acap_accounting_info_dtl
						(
							tran_number,tran_type,asset_number,tag_number,
							account_code,drcr_flag,timestamp,ou_id,
							tran_date,posting_date,currency,
							tran_amount,
							fb_id,cost_center,analysis_code,company_code,bu_id,
							sub_analysis_code,
							bc_erate,
							base_amount,
							pbc_erate,
							pbase_amount,
							cap_date,
							createdby,createddate,modifiedby,modifieddate,
							account_type
						)
						values 
						(
							@transaction_number,@transaction_type,@assetnumber,@tagnumber_tmp,
							@laccount_crcode_tmp,@crdr1,1,@ctxt_ouinstance,
							@transaction_date,@capital_date,@basecurrency_tmp,
							@capamount_tmp,
							@fb,@lcost_center_tmp,@lanalysis_tmp,@companycode_tmp,@bu_tmp,--EPE-8702
							@lsubanalysis_tmp,
							1,
							@capamount_tmp,
							@exchangerate_tmp,
							@pbaseamt_tmp,
							@capital_date,@ctxt_user,dbo.RES_Getdate(@ctxt_ouinstance),null,null,
							null
						)
					end
					else
					begin
						update 	acap_accounting_info_dtl 
						set 	tran_date 	= @transaction_date,
							posting_date 	= @capital_date, 
							currency 	= @basecurrency_tmp,
							tran_amount 	= @capamount_tmp,
							fb_id 		= @fb,
							cost_center 	= @lcost_center_tmp,
							bc_erate 	= 1,
							company_code 	= @companycode_tmp,
							bu_id 		= @bu_tmp,
							base_amount 	= @capamount_tmp,
							pbc_erate 	= @exchangerate_tmp,
							pbase_amount 	= @pbaseamt_tmp,
							cap_date 	= @capital_date,
							account_code= @laccount_crcode_tmp,
							analysis_code = @lanalysis_tmp,--EPE-8702
							sub_analysis_code = @lsubanalysis_tmp--EPE-8702
							

						where 	tran_number 	= @transaction_number
						and	tran_type 	= @transaction_type
						and	asset_number 	= @assetnumber
						and	tag_number 	= @tagnumber_tmp
						--and	account_code 	= @craccount_tmp
						and	drcr_flag 	= @crdr1						
					end	 -- Cr lg for manual ends
					end
					else --Cr lg for regular starts
					begin
        			if not exists 
					(
						select 	'x' 
						from 	acap_accounting_info_dtl (nolock)
						where 	tran_number 	= @transaction_number
						and	tran_type 	= @transaction_type
						and	asset_number 	= @assetnumber
						and	tag_number 	= @tagnumber_tmp
						and	account_code 	= @craccount_tmp 
						and	drcr_flag 	= @crdr1
					)			
					begin
						insert into acap_accounting_info_dtl
						(
							tran_number,tran_type,asset_number,tag_number,
							account_code,drcr_flag,timestamp,ou_id,
							tran_date,posting_date,currency,
							tran_amount,
							fb_id,cost_center,analysis_code,company_code,bu_id,
							sub_analysis_code,
							bc_erate,
							base_amount,
							pbc_erate,
							pbase_amount,
							cap_date,
							createdby,createddate,modifiedby,modifieddate,
							account_type
						)
						values 
						(
							@transaction_number,@transaction_type,@assetnumber,@tagnumber_tmp,
							@craccount_tmp,@crdr1,1,@ctxt_ouinstance,
							@transaction_date,@capital_date,@basecurrency_tmp,
							@capamount_tmp,
							@fb,@costcenter,'',@companycode_tmp,@bu_tmp,
							'',
							1,
							@capamount_tmp,
							@exchangerate_tmp,
							@pbaseamt_tmp,
							@capital_date,@ctxt_user,dbo.RES_Getdate(@ctxt_ouinstance),null,null,
							@ctrlcracc_tmp
						)
					end
					else
					begin
						update 	acap_accounting_info_dtl 
						set 	tran_date 	= @transaction_date,
							posting_date 	= @capital_date, 
							currency 	= @basecurrency_tmp,
							tran_amount 	= @capamount_tmp,
							fb_id 		= @fb,
							cost_center 	= @costcenter,
							bc_erate 	= 1,
							company_code 	= @companycode_tmp,
							bu_id 		= @bu_tmp,
							base_amount 	= @capamount_tmp,
							pbc_erate 	= @exchangerate_tmp,
							pbase_amount 	= @pbaseamt_tmp,
							cap_date 	= @capital_date
						where 	tran_number 	= @transaction_number
						and	tran_type 	= @transaction_type
						and	asset_number 	= @assetnumber
						and	tag_number 	= @tagnumber_tmp
						and	account_code 	= @craccount_tmp
						and	drcr_flag 	= @crdr1						
					end	 

					end --Cr lg for regular ends
					--DR INSERT
					if not exists 
					(
						select 	'x' 
						from 	acap_accounting_info_dtl (nolock)
						where 	tran_number 	= @transaction_number
						and	tran_type 	= @transaction_type
						and	asset_number 	= @assetnumber
						and	tag_number 	= @tagnumber_tmp
						and	account_code 	= @dracctcode_tmp
						and	drcr_flag 	= @crdr2
					)	
                			begin 
						insert into acap_accounting_info_dtl
						(
							tran_number,tran_type,asset_number,tag_number,
							account_code,drcr_flag,timestamp,ou_id,
							tran_date,posting_date,
							currency,
							tran_amount,
							fb_id,cost_center,analysis_code,company_code,bu_id,
							sub_analysis_code,
							bc_erate,
							base_amount,
							pbc_erate,
							pbase_amount,
							cap_date,createdby,createddate,modifiedby,modifieddate,
							account_type
						)
						values 
						(
							@transaction_number,@transaction_type,@assetnumber,@tagnumber_tmp,
							@dracctcode_tmp,@crdr2,1,@ctxt_ouinstance,
							@transaction_date,@capital_date, --@today,
							@basecurrency_tmp,
							@capamount_tmp,
							@fb,@costcenter,'',@companycode_tmp,@bu_tmp,
							'',
							1,
							@capamount_tmp,
							@exchangerate_tmp,
							@pbaseamt_tmp,
							@capital_date,@ctxt_user,dbo.RES_Getdate(@ctxt_ouinstance),null,null,
							@ctrldracc_tmp
						)
                			end
			                else
			                begin 
						update 	acap_accounting_info_dtl 
						set 	tran_date 	= @transaction_date,
							posting_date 	= @capital_date,
							currency 	= @basecurrency_tmp,
							tran_amount 	= @capamount_tmp,
							fb_id 		= @fb,
							cost_center 	= @costcenter,
							company_code 	= @companycode_tmp,
							bu_id 		= @bu_tmp,
							bc_erate 	= 1,
							base_amount 	= @capamount_tmp,
							pbc_erate 	= @exchangerate_tmp,
							pbase_amount 	= @pbaseamt_tmp,
							cap_date 	= @capital_date
						where 	tran_number 	= @transaction_number
						and	tran_type 	= @transaction_type
						and	asset_number 	= @assetnumber
						and	tag_number	= @tagnumber_tmp
						and	account_code 	= @dracctcode_tmp
						and	drcr_flag 	= @crdr2
                    			end
            			end

				if @ctxt_service = 'acaprvasmsrrvas'
				begin
					insert into acap_accounting_info_dtl
					(
						tran_number,tran_type,asset_number,tag_number,
						account_code,doc_number,drcr_flag,
						timestamp,ou_id,tran_date,posting_date,
						currency,
						tran_amount,
						fb_id,cost_center,analysis_code,
						sub_analysis_code,
						bc_erate,
						base_amount,
						pbc_erate,
						pbase_amount,
						cap_date,company_code,bu_id,
						createdby,createddate,modifiedby,modifieddate,
						account_type
					)
					select 	@transaction_number,@transaction_type,@assetnumber,@tagnumber_tmp,
						account_code,@docnumber_tmp,@crdr1,
						timestamp,ou_id,@transaction_date,@capital_date, --@today,
						currency,
						tran_amount,
						fb_id,cost_center,analysis_code,
						sub_analysis_code,
						bc_erate,
						base_amount,
						pbc_erate,
						pbase_amount,
						cap_date,company_code,bu_id,
						@ctxt_user,dbo.RES_Getdate(@ctxt_ouinstance),modifiedby,modifieddate,
						account_type		
					from 	acap_accounting_info_dtl (nolock)
					where 	ou_id 		= @ctxt_ouinstance
					and 	asset_number 	= @assetnumber
					and 	tag_number	= @tagnumber_tmp
					and	 drcr_flag 	= 'CR'

					insert into acap_accounting_info_dtl
					(
						tran_number,tran_type,asset_number,tag_number,
						account_code,doc_number,drcr_flag,
						timestamp,ou_id,tran_date,posting_date,
						currency,
						tran_amount,
						fb_id,cost_center,analysis_code,
						sub_analysis_code,
						bc_erate,
						base_amount,
						pbc_erate,
						pbase_amount,
						cap_date,company_code,bu_id,
						createdby,createddate,modifiedby,modifieddate,
						account_type
					)
					select 	@transaction_number,@transaction_type,@assetnumber,@tagnumber_tmp,
						account_code,@docnumber_tmp,@crdr2,
						timestamp,ou_id,@transaction_date,@capital_date, --@today,
						currency,
						tran_amount,
						fb_id,cost_center,analysis_code,
						sub_analysis_code,
						bc_erate,
						base_amount,
						pbc_erate,
						pbase_amount,
						cap_date,company_code,bu_id,
						@ctxt_user,dbo.RES_Getdate(@ctxt_ouinstance),modifiedby,modifieddate,
						account_type		
					from 	acap_accounting_info_dtl (nolock)
					where 	ou_id 		= @ctxt_ouinstance
					and 	asset_number 	= @assetnumber
					and 	tag_number	= @tagnumber_tmp
					and 	drcr_flag 	= 'DR'
					and 	tran_type 	<> @transaction_type	
				end

				if @ctxt_service = 'ACAPSPASTGSRSPASTG'
				begin
					select	@orig_tag_cost		= A.tag_cost,
							@imp_loss_pr		= isnull(cum_imp_loss,0)	--14H109_arev_00034
					from	ainq_asset_tag_vw A(nolock),
						acap_split_asset_dtl B(nolock)
					where	A.ou_id			= @ctxt_ouinstance
					and	A.asset_number		= @assetnumber
					and	A.tag_number		= B.tag_number
					and	A.depr_book			= B.depr_book	--NSAPL-2409		
					and	B.ou_id 		= @ctxt_ouinstance
					and 	B.document_number	= @transaction_number

					select	@new_tag_cost	= tag_cost	
					from	acap_asset_tag_dtl(nolock)
					where	ou_id		= @ctxt_ouinstance
					and	asset_number	= @assetnumber
					and	tag_number	= @tagnumber
					select	@appor_ratio	= @new_tag_cost/@orig_tag_cost

					select	@crrevdepr	=	isnull(sum(isnull(reval_depr_charge,0)),0),
						@crdepr		=	isnull(sum(isnull(depr_charge,0)),0)	
					from	ainq_asset_tag_balance_vw(nolock)
					where	ou_id		=	@ctxt_ouinstance	
					and	asset_number	=	@assetnumber
					and	tag_number	=	@tagnumber
					and	drcr_flag	=	'CR'
				
					select	@drrevdepr	=	isnull(sum(isnull(reval_depr_charge,0)),0),
						@drdepr		=	isnull(sum(isnull(depr_charge,0)),0)
					from	ainq_asset_tag_balance_vw(nolock)
					where	ou_id		=	@ctxt_ouinstance	
					and	asset_number	=	@assetnumber
					and	tag_number	=	@tagnumber
					and	drcr_flag	=	'DR'

				
					select	@netdepr	=	abs(@crdepr - @drdepr)* @appor_ratio
					select	@netrevdepr	=	abs(@crrevdepr - @drrevdepr) * @appor_ratio
					select	@imp_loss_af =  @imp_loss_pr * @appor_ratio --14H109_arev_00034
					
					if isnull(@imp_loss_af,0) <> 0
					begin
						select	@acc_imp_loss	= account_code
						from	ainq_accounting_info_dtl(nolock)
						where	ou_id			= @ctxt_ouinstance	
						and		asset_number	= @assetnumber
						and		tag_number		= @tagnumber
						and		account_type	= 'ACCIMPLOSS'
						
						insert into acap_accounting_info_dtl
						(
							tran_number,tran_type,asset_number,tag_number,
							account_code,drcr_flag,
							timestamp,ou_id,tran_date,posting_date,
							currency,
							tran_amount,
							fb_id,cost_center,analysis_code,
							company_code,bu_id,sub_analysis_code,
							bc_erate,
							base_amount,
							pbc_erate,
							pbase_amount,
							cap_date,createdby,createddate,modifiedby,modifieddate,
							account_type
						)
						values  
						(
							@transaction_number,@transaction_type,@assetnumber,@tagnumber_tmp,
							@acc_imp_loss,'CR',
							1,@ctxt_ouinstance,@transaction_date,@capital_date, 
							@basecurrency_tmp,
							@imp_loss_af,
							@fb,@costcenter,'',
							@companycode_tmp,@bu_tmp,'',
							1,
							@imp_loss_af,
							@exchangerate_tmp,
							@imp_loss_af*@exchangerate_tmp,
							@capital_date,@ctxt_user,dbo.RES_Getdate(@ctxt_ouinstance),null,null,'ACCIMPLOSS'
						)	
						
					end

					if isnull(@netdepr,0) <> 0
					begin
						insert into acap_accounting_info_dtl
						(
							tran_number,tran_type,asset_number,tag_number,
							account_code,drcr_flag,
							timestamp,ou_id,tran_date,posting_date,
							currency,
							tran_amount,
							fb_id,cost_center,analysis_code,
							company_code,bu_id,sub_analysis_code,
							bc_erate,
							base_amount,
							pbc_erate,
							pbase_amount,
							cap_date,createdby,createddate,modifiedby,modifieddate,
							account_type
						)
						values 
						(
							@transaction_number,@transaction_type,@assetnumber,@tagnumber_tmp,
							@craccount_tmp,@crdr1,
							1,@ctxt_ouinstance,@transaction_date,@capital_date, 
							@basecurrency_tmp,
							@netdepr,
							@fb,@costcenter,'',
							@companycode_tmp,@bu_tmp,'',
							1,
							@netdepr,
							@exchangerate_tmp,
							@netdepr*@exchangerate_tmp,
							@capital_date,@ctxt_user,dbo.RES_Getdate(@ctxt_ouinstance),null,null,@ctrlcracc_tmp
						)

						insert into acap_accounting_info_dtl
						(
							tran_number,tran_type,asset_number,tag_number,
							account_code,drcr_flag,
							timestamp,ou_id,tran_date,posting_date,
							currency,
							tran_amount,
							fb_id,cost_center,analysis_code,
							company_code,bu_id,sub_analysis_code,
							bc_erate,
							base_amount,
							pbc_erate,
							pbase_amount,
							cap_date,createdby,createddate,modifiedby,modifieddate,
							account_type
						)
						values 
						(
							@transaction_number,@transaction_type,@assetnumber,@tagnumber_tmp,
							@craccount_tmp,@crdr2,
							1,@ctxt_ouinstance,@transaction_date,@capital_date, 
							@basecurrency_tmp,
							@netdepr,
							@fb,@costcenter,'',
							@companycode_tmp,@bu_tmp,'',
							1,
							@netdepr,
							@exchangerate_tmp,
							@netdepr*@exchangerate_tmp,
							@capital_date,@ctxt_user,dbo.RES_Getdate(@ctxt_ouinstance),null,null,
							@ctrldracc_tmp
						)
					end

					if isnull(@netrevdepr,0) <> 0
					begin			
						insert into acap_accounting_info_dtl
						(
							tran_number,tran_type,asset_number,tag_number,
							account_code,drcr_flag,
							timestamp,ou_id,tran_date,posting_date,
							currency,
							tran_amount,
							fb_id,cost_center,analysis_code,
							company_code,bu_id,sub_analysis_code,
							bc_erate,
							base_amount,
							pbc_erate,
							pbase_amount,
							cap_date,createdby,createddate,modifiedby,modifieddate,
							account_type
						)
						values 
						(
							@transaction_number,@transaction_type,@assetnumber,@tagnumber_tmp,
							@craccount_tmp,@crdr1,
							1,@ctxt_ouinstance,@transaction_date,@capital_date, 
							@basecurrency_tmp,
							@netrevdepr,
							@fb,@costcenter,'',
							@companycode_tmp,@bu_tmp,'',
							1,
							@netrevdepr,
							@exchangerate_tmp,
							@netrevdepr*@exchangerate_tmp,
							@capital_date,@ctxt_user,dbo.RES_Getdate(@ctxt_ouinstance),null,null,
							@ctrlcracc_tmp
						)

						insert into acap_accounting_info_dtl
						(
							tran_number,tran_type,asset_number,tag_number,
							account_code,drcr_flag,
							timestamp,ou_id,tran_date,posting_date,
							currency,
							tran_amount,
							fb_id,cost_center,analysis_code,
							company_code,bu_id,sub_analysis_code,
							bc_erate,
							base_amount,
							pbc_erate,
							pbase_amount,
							cap_date,createdby,createddate,modifiedby,modifieddate,
							account_type
						)
						values 
						(
							@transaction_number,@transaction_type,@assetnumber,@tagnumber_tmp,
							@craccount_tmp,@crdr2,
							1,@ctxt_ouinstance,@transaction_date,@capital_date, 
							@basecurrency_tmp,
							@netrevdepr,
							@fb,@costcenter,'',
							@companycode_tmp,@bu_tmp,'',
							1,
							@netrevdepr,
							@exchangerate_tmp,
							@netrevdepr*@exchangerate_tmp,
							@capital_date,@ctxt_user,dbo.RES_Getdate(@ctxt_ouinstance),null,null,
							@ctrldracc_tmp
						)
					end
				end
				fetch  next from tagdtlcur into  @tagnumber_tmp ,@capamount_tmp	,@laccount_crcode_tmp, @lcost_center_tmp,@lanalysis_tmp,@lsubanalysis_tmp--EPE-8702
			end
			close tagdtlcur 
			deallocate tagdtlcur 
		end
		else --when doc selected
		begin
			if @ctxt_service not in('acaprvasmsrrvas')
			begin
				delete 	acap_accounting_info_dtl
				from 	acap_accounting_info_dtl A,
					acap_tag_doc_dtl B 			
				where 	A.asset_number 	<> B.asset_number
				and 	A.tag_number 	<> B.tag_number
				and 	A.tran_number 	= @transaction_number
			end

				

			declare tagdtlcur cursor for 
			select 	tag_number ,doc_number, sum(isnull(cap_amount,0)),account_code ,line_no --EP-93	
			from 	acap_tag_doc_dtl (nolock)
			where 	ou_id 		= @ctxt_ouinstance
			and 	asset_number	= @assetnumber
			and 	cap_number 	= @transaction_number	
			group by asset_number,tag_number ,doc_number,account_code,line_no--EP-93					

			open tagdtlcur 

			fetch  next from tagdtlcur 
				into @tagnumber_tmp , @docnumber_tmp ,@capamount_tmp ,@craccount_tmp,@lineno_tmp --EDS-57	
	
			while @@fetch_status =0 
			begin
				select 	@ctrlcracc_tmp 	= ctrl_acctype 
				from 	as_opaccountfb_vw (nolock)
				where 	company_code 	= @companycode_tmp
				and 	account_code  	= @craccount_tmp                    
				and 	fb_id  		= @fb

				--to get the parallel base amount
				select @pbaseamt_tmp = @exchangerate_tmp * @capamount_tmp
								
				/* Code modified by Swetha for FA Code Revamp */
                                /* Code modified by Swetha for ACAPDMS412AT_000559 on 16/10/2006 */
				if @ctxt_service in ('acapcrsmassrsmat','acapcrcmassrcpxast','acapamasmsramas','acapedasssredtast','ACAPAUASMSRAUAS','ACAPAUASESRAUAS','acapapaddbsrblkast','ACAPSPASTGSRSPASTG','ACAPCRBLTGSRBLKTG')	
                                /* Code modified by Swetha for ACAPDMS412AT_000559 on 16/10/2006 */
				/* Code modified by Swetha for FA Code Revamp */	
				begin
				/* Code added by Swetha for ACAPDMS412AT_000322 on 20/03/2006 */
					if (@capamount_tmp < 0)
					begin 
						select @crdr1 = 'DR'
						select @crdr2 = 'CR'
						select @capamount_tmp = @capamount_tmp * -1
					end
					else
					begin 
						select @crdr1 = 'CR'
						select @crdr2 = 'DR'
					end
				/* Code added by Swetha for ACAPDMS412AT_000322 on 20/03/2006 */
				end		
	
				if @ctxt_service = 'acaprvasmsrrvas'			
				begin
					select @crdr1 = 'DR'
					select @crdr2 = 'CR'
				end

				if @ctxt_service in ('acaprvasmsrrvas')		 	
				begin
					--EP-93	
					if not exists
					(
						select 'x'
						from 	acap_accounting_info_dtl (nolock)
						where 	ou_id 			=	@ctxt_ouinstance
						and 	asset_number	=	@assetnumber
						and 	tag_number		=	@tagnumber_tmp
						and		tran_number		=	@transaction_number
						and		tran_type		=	@transaction_type
					)
					begin
					--EP-93	
					insert into acap_accounting_info_dtl
					(
						tran_number,tran_type,asset_number,tag_number,
						account_code,doc_number,drcr_flag,
						timestamp,ou_id,tran_date,posting_date,
						currency,
						tran_amount,
						fb_id,cost_center,analysis_code,sub_analysis_code,
						bc_erate,
						base_amount,
						pbc_erate,
						pbase_amount,
						cap_date,company_code,bu_id,
						createdby,createddate,modifiedby,modifieddate,
						account_type
					)
					select 	@transaction_number,@transaction_type,@assetnumber,@tagnumber_tmp,
						account_code,@docnumber_tmp,@crdr1,
						timestamp,ou_id,@transaction_date,@capital_date, --@today,
						currency,
						tran_amount,
						fb_id,cost_center,analysis_code,sub_analysis_code,
						bc_erate,
						base_amount,
						pbc_erate,
						pbase_amount,
						cap_date,company_code,bu_id,
						@ctxt_user,dbo.RES_Getdate(@ctxt_ouinstance),modifiedby,modifieddate,
						account_type		
					from 	acap_accounting_info_dtl (nolock)
					where 	ou_id 		= @ctxt_ouinstance
					and 	asset_number	= @assetnumber
					and 	tag_number	= @tagnumber_tmp
					and 	drcr_flag 	= 'CR'
					
					insert into acap_accounting_info_dtl
					(
						tran_number,tran_type,asset_number,tag_number,
						account_code,doc_number,drcr_flag,
						timestamp,ou_id,tran_date,posting_date,
						currency,
						tran_amount,
						fb_id,cost_center,analysis_code,sub_analysis_code,
						bc_erate,
						base_amount,
						pbc_erate,
						pbase_amount,
						cap_date,company_code,bu_id,
						createdby,createddate,modifiedby,modifieddate,
						account_type
					)
					select 	@transaction_number,@transaction_type,@assetnumber,@tagnumber_tmp,
						account_code,@docnumber_tmp,@crdr2,
						timestamp,ou_id,@transaction_date,@capital_date,
						currency,
						tran_amount,
						fb_id,cost_center,analysis_code,sub_analysis_code,
						bc_erate,
						base_amount,
						pbc_erate,
						pbase_amount,
						cap_date,company_code,bu_id,
						@ctxt_user,dbo.RES_Getdate(@ctxt_ouinstance),modifiedby,modifieddate,
						account_type		
					from 	acap_accounting_info_dtl (nolock)
					where 	ou_id 		= @ctxt_ouinstance
					and 	asset_number 	= @assetnumber
					and 	tag_number	= @tagnumber_tmp
					and 	drcr_flag 	= 'DR'
					and 	tran_type 	<> @transaction_type	
					end --EP-93	
				end
				else
				begin
					/* Code Added by Uma for the defect id:ES_ACAP_00074 Starts here*/
					if @craccount_tmp is null or @craccount_tmp = ''
					begin
						exec fin_german_raiserror_sp 'ACAP',@ctxt_language,57
						return
					end
					/* Code Added by Uma for the defect id:ES_ACAP_00074 Ends here*/

					--EP-93	
					select  @cost_Center_tmp	=	cost_Center
					from 	acap_tag_doc_dtl (nolock)
					where 	ou_id 			= @ctxt_ouinstance
					and 	asset_number	= @assetnumber
					and		tag_number		= @tagnumber_tmp	
					and 	cap_number 		= @transaction_number	
					and		doc_number		= @docnumber_tmp
					and		line_no			= @lineno_tmp

					select @cost_Center_tmp = isnull(@cost_Center_tmp,'##') 
					--EP-93	
	
					insert into acap_accounting_info_dtl
					(
						tran_number,tran_type,asset_number,tag_number,
						account_code,doc_number,drcr_flag,
						timestamp,ou_id,tran_date,posting_date,
						currency,
						tran_amount,
						fb_id,cost_center,analysis_code,sub_analysis_code,
						bc_erate,
						base_amount,
						pbc_erate,
						pbase_amount,
						cap_date,company_code,bu_id,
						createdby,createddate,modifiedby,modifieddate,
						account_type
					)
					values 
					(
						@transaction_number,@transaction_type,@assetnumber,@tagnumber_tmp,
						@craccount_tmp,@docnumber_tmp,@crdr1,
						1,@ctxt_ouinstance,@transaction_date,@capital_date,
						@basecurrency_tmp,
						@capamount_tmp,
						@fb,@cost_Center_tmp,'','',		--EP-93	
						1,
						@capamount_tmp,
						@exchangerate_tmp,
						@pbaseamt_tmp,
						@capital_date,@companycode_tmp,@bu_tmp,
						@ctxt_user,dbo.RES_Getdate(@ctxt_ouinstance),null,null,
						@ctrlcracc_tmp
					)
								
					insert into acap_accounting_info_dtl
					(
						tran_number,tran_type,asset_number,tag_number,
						account_code,doc_number,drcr_flag,
						timestamp,ou_id,tran_date,posting_date,
						currency,
						tran_amount,
						fb_id,cost_center,analysis_code,sub_analysis_code,
						bc_erate,
						base_amount,
						pbc_erate,
						pbase_amount,
						cap_date,company_code,bu_id,
						createdby,createddate,modifiedby,modifieddate,
						account_type
					)
					values 
					(
						@transaction_number,@transaction_type,@assetnumber,@tagnumber_tmp,
						@dracctcode_tmp,@docnumber_tmp,@crdr2,
						1,@ctxt_ouinstance,@transaction_date,@capital_date,
						@basecurrency_tmp,
						@capamount_tmp,
						@fb,@costcenter,'','',
						1,
						@capamount_tmp,
						@exchangerate_tmp,
						@pbaseamt_tmp,
						@capital_date,@companycode_tmp,@bu_tmp,
						@ctxt_user,dbo.RES_Getdate(@ctxt_ouinstance),null,null,
						@ctrldracc_tmp
					)
				end
				fetch  next from tagdtlcur into @tagnumber_tmp ,@docnumber_tmp ,@capamount_tmp ,@craccount_tmp,@lineno_tmp --EP-93	
			end		
			close tagdtlcur 
			deallocate tagdtlcur 
		end

		update 	T1
		set 	--T1.cost_center     	= T2.cost_center, --EP-93	
			/* Code Modifed by Vairamani C for ES_ACAP_00095 Starts here */
			T1.analysis_code	= T2.analysis_code,
			T1.sub_analysis_code	= T2.subanalysis_code
			/* Code Modifed by Vairamani C for ES_ACAP_00095 Ends here */
		from 	acap_accounting_info_dtl T1(NOLOCK),
		     	si_acct_info_dtl T2(NOLOCK)
		where 	T1.ou_id       		= @ctxt_ouinstance		--PE-527
		and		T1.tran_number  	= @transaction_number	--PE-527
		and   	T2.tran_no       	= T1.doc_number
		and   	T2.account_code  	= T1.account_code
		and   	T2.tran_ou       	= T1.ou_id
		/*code added for ES_ACAP_01153 starts*/
		update t1
		set T1.cost_center     	= isnull(T2.iid_cost_center,'##'),--isnull handled by RGSE-213
			T1.analysis_code	= isnull(T2.iid_analysis_code,'##'),--isnull handled by RGSE-213
			T1.sub_analysis_code	= isnull(T2.iid_subanalysis_code,'##')--isnull handled by RGSE-213
		from 	acap_accounting_info_dtl T1(NOLOCK),
				issue_inv_detail T2(NOLOCK)
		where 	T2.iid_issue_no  		= T1.doc_number
		and		T1.ou_id       			= @ctxt_ouinstance
		and		T1.tran_number  		= @transaction_number
		and   	T2.iid_dr_account_code 	= T1.account_code
		/*code added for ES_ACAP_01153 ends*/
		/*code added for EA-630 starts*/
		UPDATE dtl
		set		dtl.analysis_code	= map.analysis_code,
				dtl.sub_analysis_code = map.sub_analysis_code
		from	acap_accounting_info_dtl dtl(nolock),
				abb_account_analysis_map map(nolock)
		where	map.company_code			= @companycode_tmp
		and		map.map_status				= 'A'
		and		map.default_analysis_code	= 'Y'
		and		dtl.ou_id       	= @ctxt_ouinstance
		and		dtl.tran_number  	= @transaction_number 
		and		dtl.account_code	= map.account_code
		and		exists  (  select 'x' 
							from	ard_addn_account_mst mst(nolock)
							where	mst.company_code	= @companycode_tmp
							and		mst.usage_id		= 'CAPRECNCDOCS'
							and		dtl.ou_id       	= @ctxt_ouinstance
							and		dtl.tran_number  	= @transaction_number
							and		dtl.fb_id			= mst.fb_id
							and		dtl.account_code	= mst.account_code)

		if exists ( select 'x' 
					from	mac_cc_acc_mapped_vw vw(nolock),
							acap_accounting_info_dtl dtl(nolock)
					where	dtl.ou_id       	= @ctxt_ouinstance
					and		dtl.tran_number  	= @transaction_number 
					and		dtl.account_code	= vw.account_no
					and		vw.bu_id			= @bu_tmp 
					and		vw.ou_id			= dtl.ou_id		
					and		dtl.posting_date	between effective_date and isnull(expiry_date,dtl.posting_date)
					and		exists  (  select 'x' 
										from	ard_addn_account_mst mst(nolock)
										where	mst.company_code	= @companycode_tmp
										and		mst.usage_id		= 'CAPRECNCDOCS'
										and		dtl.ou_id       	= @ctxt_ouinstance
										and		dtl.tran_number  	= @transaction_number
										and		dtl.fb_id			= mst.fb_id
										and		dtl.account_code	= mst.account_code)
				 )
		begin
			update dtl
			set 	dtl.cost_center	= def.costcenter 
			from	acap_accounting_info_dtl dtl(nolock),
					crd_accountcc_map_default def(nolock)
			where 	dtl.ou_id       	= @ctxt_ouinstance
			and		dtl.tran_number  	= @transaction_number 
			and		dtl.account_code	= def.account_code
			and     def.bu_id			= @bu_tmp
			and		def.company_code	= @companycode_tmp
			and		exists  (  select 'x' 
										from	ard_addn_account_mst mst(nolock)
										where	mst.company_code	= @companycode_tmp
										and		mst.usage_id		= 'CAPRECNCDOCS'
										and		dtl.ou_id       	= @ctxt_ouinstance
										and		dtl.tran_number  	= @transaction_number
										and		dtl.fb_id			= mst.fb_id
										and		dtl.account_code	= mst.account_code)
		end
		/*code added for EA-630 ends*/


                /* Code added by Swetha for ACAPDMS412AT_000147 on 28/03/2006 */

                if exists 
		(
			select 	'x'
	                /* Code modified by Swetha for ACAPDMS412AT_000147 on 29/03/2006 */
	   from  	acap_asset_doc_dtl(nolock)
	                /* Code modified by Swetha for ACAPDMS412AT_000147 on 29/03/2006 */
	        where 	asset_number 	= @assetnumber
	                and   	ou_id       	= @ctxt_ouinstance
	                and   	tran_type in ('PM_PI','PM_MI')
		)
                begin 
                        declare cc_cur cursor for
                        select 	distinct  po_no,ref_doc_no
                        from   	sin_item_dtl       T1(NOLOCK),
                        	acap_accounting_info_dtl T2(NOLOCK)
                        where  	T1.tran_no        = T2.doc_number
                        and    	T1.tran_ou        = T2.ou_id
                        /* Code modfied by Swetha for ACAPDMS412AT_000147 on 28/03/2006 */
                        and    	T2.asset_number   = @assetnumber
                        and    	T2.ou_id          = @ctxt_ouinstance
                        
                        open cc_cur
                        
                        fetch next from cc_cur into @po_no,@gr_no
                        
                        while @@fetch_status = 0
                        begin 
                                select @paytd_matchingtype 	= paytd_matchingtype
                                from   po_itemdetail_vw(NOLOCK)
                                where  poitm_pono 		= @po_no 
                                and    poitm_poou 		= @ctxt_ouinstance
                                
                                if @paytd_matchingtype in ('3P','4P','3G','4G')
                                begin 
					/* Code modfied by Swetha for ACAPDMS412AT_000147 on 28/03/2006 */
                                        update 	T2
                                        set   	T2.cost_center 	= T1.cost_center    
                                        from  	fbp_posted_trn_dtl T1(nOLOCK),
                                        	acap_accounting_info_dtl T2(nOLOCK)
                                        where 	T1.document_no  = @gr_no
                                        and   	T1.account_code = T2.account_code
                                  	and   	T1.tran_ou      = T2.ou_id
                                        and   	T2.asset_number = @assetnumber
                         end
						 
							--ADECCOPROD-1782
							if @paytd_matchingtype in ('2P') and @gr_no is not null
                                begin 
					                    update 	T2
                                        set   	T2.cost_center 	= T1.cost_center  ,
												T2.analysis_code = T1.analysis_code,
												T2.sub_analysis_code = T1.subanalysis_code
                                        from  	fbp_posted_trn_dtl T1(nOLOCK),
                                        		acap_accounting_info_dtl T2(nOLOCK)
                                        where 	T1.document_no  = @gr_no
                                        and   	T1.account_code = T2.account_code
                                  		and   	T1.tran_ou      = T2.ou_id
                                        and   	T2.asset_number = @assetnumber
										and		T2.tran_number  = @transaction_number
							end
							--ADECCOPROD-1782

   fetch next from cc_cur into @po_no,@gr_no
                        end
			close cc_cur
			deallocate cc_cur
		end 
               /* Code added by Swetha for ACAPDMS412AT_000147 on 28/03/2006 */
	end
        /*Code modified by swetha for ACAPDMS412AT_000440 on 26/6/2006 */
	else if upper(@acap_type) = 'CJV' 
	begin
		delete 	from acap_journal_accounting_dtl
		where 	tran_number 	= @transaction_number
		and 	ou_id 		= @ctxt_ouinstance

                select 	@voucher_type   = voucher_type  
                from   	acap_journal_hdr(nolock)
                where  	voucher_number 	= @transaction_number
                and    	ou_id 		= @ctxt_ouinstance

               select 	@reversal_period= reversal_period ,
        	@notypeno   = num_type
   from   	acap_journal_hdr(nolock)
  where  	voucher_number 	= @transaction_number
             and 	ou_id 		= @ctxt_ouinstance  

                select 	@posting_date 		= fin_period_stdt
                from 	fcc_sysact_allperiod_vw (nolock)
                where 	close_status 		= 'O'
                and 	company_code   		= @companycode_tmp
                and 	financeperiodrange 	= @reversal_period

                if (@voucher_type = 'NO')
              begin 
        		insert into acap_journal_accounting_dtl 
        		(
				timestamp,tran_number,tran_type,
				account_code,drcr_flag,
				ou_id,tran_date,
				posting_date,
				currency,
				tran_amount,
				fb_id,cost_center,
				analysis_code,sub_analysis_code,
				bc_erate,
				base_amount,
				pbc_erate,
				pbase_amount,
				cap_date,bu_id,company_code,
				createdby,createddate,modifiedby,modifieddate,
				asset_number,tag_number,account_type
				,remarks--code 'reamrks' added for EP-96
			)
    		select  1,A.voucher_number,@transaction_type,
				B.account_code ,B.drcr_flag,
				@ctxt_ouinstance,A.transaction_date,
				/* Code modified by Swetha for ACAPDMS412AT_000462 on 6/6/2006 */
				isnull(@posting_date,A.transaction_date),
				@basecurrency_tmp,
				--B.tran_amount,
				round(B.tran_amount,@pamt_tmp), --EBS-1074
				A.fb_id,cost_center,
				/* Code modified by Swetha for ACAPDMS412AT_000462 on 6/6/2006 */
				B.analysis_code,B.subanalysis_code,
				1,
				--B.tran_amount,
				round(B.tran_amount,@pamt_tmp), --EBS-1074
				@exchangerate_tmp,
				--isnull(B.tran_amount * isnull(@exchangerate_tmp,0),0),
				round(isnull(B.tran_amount * isnull(@exchangerate_tmp,0),0),@pamt_tmp), --EBS-1074
				A.transaction_date,@bu_tmp, @companycode_tmp,
				@ctxt_user,dbo.RES_Getdate(@ctxt_ouinstance),null,null,
				B.asset_number,B.tag_number,''
				,B.remarks--code 'reamrks' added for EP-96
        		from 	acap_journal_hdr A (nolock), 
        			acap_journal_dtl B(nolock)
        		where 	A.ou_id 	 = @ctxt_ouinstance
        		and	A.voucher_number = @transaction_number
        		and 	A.ou_id 	 = B.ou_id
        		and	A.voucher_number = B.voucher_number
                end

                if (@voucher_type = 'RE')
                begin 
                        insert into acap_journal_accounting_dtl 
        		(
				timestamp,tran_number,
				tran_type,
				account_code,drcr_flag,
				ou_id,tran_date,posting_date,
				currency,
				tran_amount,
				fb_id,cost_center,analysis_code,sub_analysis_code,
				bc_erate,
				base_amount,
				pbc_erate,
				pbase_amount,
				cap_date,bu_id,company_code,
				createdby,createddate,modifiedby,modifieddate,
				asset_number,tag_number,account_type
				,B.remarks--code 'reamrks' added for EP-96
			)
        		select  1,A.voucher_number,
				Case @voucher_type 
					when 'RE' then 'FA_RACAPJV'
					else @transaction_type
				end,
				B.account_code ,B.drcr_flag,
				@ctxt_ouinstance,A.transaction_date,A.transaction_date,
				@basecurrency_tmp,
				--B.tran_amount,
				round(B.tran_amount,@pamt_tmp), --EBS-1074
				A.fb_id,cost_center,B.analysis_code,B.subanalysis_code,
				1,
				--B.tran_amount,
				round(B.tran_amount,@pamt_tmp), --EBS-1074
				@exchangerate_tmp,
				--isnull(B.tran_amount * isnull(@exchangerate_tmp,0),0),
				round(isnull(B.tran_amount * isnull(@exchangerate_tmp,0),0),@pamt_tmp), --EBS-1074
				A.transaction_date,@bu_tmp, @companycode_tmp,
				@ctxt_user,dbo.RES_Getdate(@ctxt_ouinstance),null,null,
				B.asset_number,B.tag_number,''
				,B.remarks--code 'reamrks' added for EP-96
        		from 	acap_journal_hdr A (nolock), 
        			acap_journal_dtl B(nolock)
			where 	A.ou_id 	 = @ctxt_ouinstance
			and	A.voucher_number = @transaction_number
			and 	A.ou_id 	 = B.ou_id
			and	A.voucher_number = B.voucher_number
     end
		
		update  T1
		set     T1.account_type  = ctrl_acctype
		from    acap_journal_accounting_dtl T1(NOLOCK),
			as_opaccountfb_vw T2(nolock)
		where   T2.company_code  = @companycode_tmp
		and 	T2.fb_id  	 = @fb
		and 	T2.account_code  = T1.account_code

	end	
        /*Code modified by swetha for ACAPDMS412AT_000440 on 26/6/2006 */			
	--for wip
	else if upper(@acap_type) = 'WIP' 
	begin
		--LOEINT-450
		/*
		delete 	acap_wip_accounting_dtl
		from 	acap_wip_accounting_dtl A,
			acap_wip_line_dtl B 
		where 	A.doc_number <> B.doc_number 
		and 	A.tran_number = @transaction_number
		*/
		
		delete from acap_wip_accounting_dtl
		where tran_number = @transaction_number
		and	  fb_id		  = @fb
		--LOEINT-450
	
		declare tagdtlcur cursor for
		select 	distinct asset_class ,HDR.doc_number, sum(LDT.wip_cost) , 
			LDT.doc_number ,account_code, line_no --EP-93	
		from 	acap_wip_line_dtl LDT(nolock),
			acap_wip_hdr HDR (nolock)
		where 	HDR.ou_id 		= @ctxt_ouinstance 
		and	LDT.ou_id 		= @ctxt_ouinstance 
		and	HDR.cap_wo_number 	= LDT.cap_wo_number 
		and     HDR.doc_number		= @transaction_number 
		group by asset_class ,HDR.doc_number, LDT.doc_number,account_code, line_no --EP-93		
			
		open tagdtlcur
	
		fetch next from tagdtlcur 
			into @assetclass ,@docnumber_tmp ,@capamount_tmp, @sidocno_tmp,@account_code,@lineno_tmp --EP-93	

		while @@fetch_status = 0 
		begin
		--	select 	@lineno_tmp 		= line_no ,			 --EP-93	
			select	@cap_wo_number 		= LDT.cap_wo_number, --EP-93	
					--@cost_Center_tmp	= case when cap_flag = 'NC' then '##' else cost_Center end	--EPE-13183	 --EP-93	-- Uma--PTP-106
					@cost_Center_tmp	= cost_Center	--PTP-106
			from 	acap_wip_line_dtl LDT(nolock),
				acap_wip_hdr HDR (nolock)
			where 	HDR.ou_id 		= @ctxt_ouinstance 
			and	LDT.ou_id 		= @ctxt_ouinstance 
			and	HDR.cap_wo_number 	= LDT.cap_wo_number 
			and 	HDR.doc_number	 	= @transaction_number
			--EP-93	
			and		ldt.doc_number		= @sidocno_tmp
			and		ldt.line_no			= @lineno_tmp
			--EP-93	

			select @cost_Center_tmp = isnull(@cost_Center_tmp,'##') --EP-93	

			select @lineno_tmp	= isnull(@lineno_tmp,0)-- without document wip can be created
		
			-- debit account code
			exec @errorcode_tmp = ardisspgetassetacc 
					@ctxt_language ,@ctxt_ouinstance,
					@ctxt_service ,@ctxt_user ,@assetclass ,@fb,
					@usg_type ,@transaction_date ,@dracctcode_tmp output , @errormsg output 
	
			/*	0- Success
				1 - No Account Code exists  for the Asset Class Code and Usage.
				2 - Provide Login OU
				3 - Provide Asset Class Code
				4 - Provide Financebook
				5 - Provide UsageID
				6 - Provide Transactiondate
				7 - OU not mapped to any company
			*/

			select @m_errorout = 0 
			select  @m_errorout = 	case isnull(@errorcode_tmp,0)
						    	when 1 then 186
						        when 2 then 109
							when 3 then 245
							when 4 then 110
							when 5 then 246
							when 6 then 152
							when 7 then 247
							when 0 then 0
						end

			if isnull(@m_errorout,0) <> 0
			begin
				return @m_errorout			
			end

			if @lineno_tmp = 0
			begin
				select @craccount_tmp = @dracctcode_tmp
			end
			else
			begin 
			        select @craccount_tmp = @account_code
			end
						
			select 	@ctrlcracc_tmp 	= ctrl_acctype 
			from 	as_opaccountfb_vw (nolock)
			where 	company_code 	= @companycode_tmp
			and 	account_code  	= @craccount_tmp                    
			and 	fb_id   	= @fb

			--to get the parallel base amount
			select @pbaseamt_tmp = @exchangerate_tmp * @capamount_tmp
		
			if @ctxt_service in 
			(
				'acapwaddmsrcreate','acapwmodmsredit','acapwmodmsrdel',
				'acapwmodmsrdelet','acapwmodmsrfet','acapwauesrauth'
				,'ACA_TIAC_Sr_Aut_Tgt','ACA_TIAC_Sr_Aut_Src' --code added for the dts id 12H124_ACAP_00001[ES_General_00632]
				--orginal service : ACA_TIAC_Sr_Aut , but interpreted as "ACA_TIAC_Sr_Aut_Tgt" for target cwip doc and as "ACA_TIAC_Sr_Aut_src" for source reversal cwip doc 
			)
			begin
				/* Code added by Swetha for ACAPDMS412AT_000322 on 20/03/2006 */
				if (@capamount_tmp < 0)
				begin 
					select @crdr1 = 'DR'
					select @crdr2 = 'CR'
					select @capamount_tmp = @capamount_tmp * -1
				end
				else 
				begin 
					select @crdr1 = 'CR'
					select @crdr2 = 'DR'
				end
				/* Code added by Swetha for ACAPDMS412AT_000322 on 20/03/2006 */
			end

			if @ctxt_service = 'acapwrvmsrrev'			
			begin
				select @crdr1 = 'DR'
				select @crdr2 = 'CR'
			end
			
			--code added for the dts id 12H124_ACAP_00001[ES_General_00632] starts
			
			/* for the target dor fetch the INTACCWIPTRF usage account code as cr whereas for the reverse doc no , fetch the same account code foe dr.
			CWIPTRF_063	Fetch Debit Account for Generating Reversal Work Order Document	Invoke Service from ARD to fetch Dr account code. Input 1. Login OU 2. usage id : INTACCWIPTRF, 3. FB. 4. Transfer Date. Get output Account code mapped for the usage		
			*/
			select @trfaccount_tmp  = NULL 
		
									
			if @ctxt_service = 'ACA_TIAC_Sr_Aut_Tgt' 
			begin
				select @crdr1 = 'CR'
				select @crdr2 = 'DR'	
				
				select @trfaccount_tmp = account_code
				from ard_addn_account_mst (nolock)
				where company_code 	= @companycode_tmp 
				and usage_id		= 'INTACCWIPTRF'	
				and fb_id			= @fb	
				and drcr_flag		= @crdr1		 --12H124_ACAP_00053
				and isnull(effective_to,'01-01-9999') <> effective_from 
				and @transaction_date between effective_from and isnull(effective_to,'01-01-9999')	
				
				select @craccount_tmp  = @trfaccount_tmp
				select @dracctcode_tmp = @dracctcode_tmp
				
			end
			
			if @ctxt_service = 'ACA_TIAC_Sr_Aut_Src' 
			begin
					
				select @crdr1 = 'CR'
				select @crdr2 = 'DR'	
			
			
				select @trfaccount_tmp = account_code
				from ard_addn_account_mst (nolock)
				where company_code 	= @companycode_tmp 
				and usage_id		= 'INTACCWIPTRF'	
				and fb_id			= @fb	
				and drcr_flag		=  @crdr2	  --12H124_ACAP_00053	
				and isnull(effective_to,'01-01-9999') <> effective_from 
				and @transaction_date between effective_from and isnull(effective_to,'01-01-9999')	
				
				select @craccount_tmp  = @account_code --@dracctcode_tmp --code changed for the dts id 12H124_ACAP_00001:12H124_ACAP_00096 
				--code added by R.Santhakumar for the case: ES_ACAP_00534 starts here 							
				if @account_code is null
				select @craccount_tmp  = @dracctcode_tmp
				--code added by R.Santhakumar for the case: ES_ACAP_00534 ends here 	
				select @dracctcode_tmp = @trfaccount_tmp
				
			end
			--code added for the dts id 12H124_ACAP_00001[ES_General_00632] ends			
			
			if not exists 
			(
				select 	'x' 
				from 	acap_wip_accounting_dtl (nolock)
				where 	tran_number 	= @transaction_number
				and	tran_type 	= @transaction_type
				and	doc_number 	= @sidocno_tmp
				and	account_code 	= @craccount_tmp
				and	drcr_flag 	= @crdr1
				and	isnull(cost_Center,'##') = isnull(@cost_Center_tmp,'##') --EP-93	
			)
			begin
				insert into acap_wip_accounting_dtl
				(
					tran_number,tran_type,doc_number,
					account_code,drcr_flag,
					timestamp,ou_id,tran_date,posting_date,
					currency,
					tran_amount,
					fb_id,cost_center,analysis_code,sub_analysis_code,
					bc_erate,
					base_amount,
					pbc_erate,
					pbase_amount,
					cap_date,createdby,createddate,modifiedby,modifieddate,
					bu_id,company_code
				)
				values 
				(
					@transaction_number,@transaction_type,@sidocno_tmp,
					/* Code modified by Swetha for ACAPDMS412AT_000462 on 6/6/2006 */
					@craccount_tmp,@crdr1,
					1,@ctxt_ouinstance,@transaction_date,@transaction_date,
					/* Code modified by Swetha for ACAPDMS412AT_000462 on 6/6/2006 */
					@basecurrency_tmp,
					@capamount_tmp,
					@fb,@cost_Center_tmp,'','', --EP-93	
					1,
					@capamount_tmp,
					@exchangerate_tmp,
					@pbaseamt_tmp,
					@capital_date,@ctxt_user,dbo.RES_Getdate(@ctxt_ouinstance),null,null,
					@bu_tmp,@companycode_tmp
				)

				
			end		
			else
			begin
				update 	acap_wip_accounting_dtl 
				set 	tran_date 	= @transaction_date,
                                /* Code modified by Swetha for ACAPDMS412AT_000462 on 6/6/2006 */
					posting_date 	= @transaction_date,
            /* Code modified by Swetha for ACAPDMS412AT_000462 on 6/6/2006 */
					currency 	= @basecurrency_tmp,
					tran_amount 	= isnull(tran_amount,0) + @capamount_tmp,--ES_ACAP_00693
					fb_id 		= @fb,
					cost_center 	= @cost_Center_tmp, --EP-93	
					bc_erate 	= 1,
					base_amount 	= isnull(base_amount,0) + @capamount_tmp,--ES_ACAP_00693
					pbc_erate 	= @exchangerate_tmp,
					pbase_amount 	= isnull(pbase_amount,0) + @pbaseamt_tmp,--ES_ACAP_00693
					cap_date 	= @capital_date
				where 	tran_number 	= @transaction_number
				and	tran_type 	= @transaction_type
				and	doc_number 	= @sidocno_tmp
				and	account_code 	= @craccount_tmp
				and	drcr_flag 	= @crdr1
				and	isnull(cost_Center,'##') = isnull(@cost_Center_tmp,'##') --EP-93	
			end
			
			--EBS-3394
			if exists
			(
				select  'x'
				from	mac_cc_acc_mapped_vw VW(nolock)
				where	bu_id		= @bu_tmp
				and		account_no	= @dracctcode_tmp
				and		center_no 	= @cost_Center_tmp			 
				and		effective_date	<=	@transaction_date
				and		isnull(expiry_date,@transaction_date)	>=	@transaction_date
			)
			begin
					select @ccexists = 'Y'
			end
			--EBS-3394

			if not exists 
			(
				select 	'x' 
				from 	acap_wip_accounting_dtl (nolock)
				where 	tran_number 	= @transaction_number
				and	tran_type 	= @transaction_type
				and	doc_number 	= @sidocno_tmp
				and	account_code 	= @dracctcode_tmp
				and	drcr_flag 	= @crdr2
				--and	isnull(cost_Center,'##') = isnull(@cost_Center_tmp,'##') --EP-93	 --EBS-3394
				and	isnull(cost_Center,'##') = case when @ccexists = 'Y' then @cost_Center_tmp else '##' end --EBS-3394
			)
			begin
				insert into acap_wip_accounting_dtl
				(
					tran_number,tran_type,doc_number,
					account_code,drcr_flag,
					timestamp,ou_id,tran_date,posting_date,
					currency,
					tran_amount,
					fb_id,cost_center,analysis_code,sub_analysis_code,
					bc_erate,
					base_amount,
					pbc_erate,
					pbase_amount,
					cap_date,createdby,createddate,modifiedby,modifieddate,
					bu_id,company_code
				)
				values 
				(
					@transaction_number,@transaction_type,@sidocno_tmp,
					/* Code modified by Swetha for ACAPDMS412AT_000462 on 6/6/2006 */
					@dracctcode_tmp,@crdr2,
					1,@ctxt_ouinstance,@transaction_date,@transaction_date,
					/* Code modified by Swetha for ACAPDMS412AT_000462 on 6/6/2006 */
					@basecurrency_tmp,
					@capamount_tmp,
					@fb,/*@cost_Center_tmp*/case when @ccexists = 'Y' then @cost_Center_tmp else '##' end,'','', --EP-93	 --EBS-3394
					1,
					@capamount_tmp,
					@exchangerate_tmp,
					@pbaseamt_tmp,
					@capital_date,@ctxt_user,dbo.RES_Getdate(@ctxt_ouinstance),null,null,
					@bu_tmp,@companycode_tmp
				)



			end
			else
			begin
				update 	acap_wip_accounting_dtl 
				set 	tran_date 	= @transaction_date,
                                      	/* Code modified by Swetha for ACAPDMS412AT_000462 on 6/6/2006 */
					posting_date 	= @transaction_date,
                                     	/* Code modified by Swetha for ACAPDMS412AT_000462 on 6/6/2006 */
					currency 	= @basecurrency_tmp,
					tran_amount 	= isnull(tran_amount,0) + @capamount_tmp,--ES_ACAP_00693
					fb_id 		= @fb,
					--cost_center 	= @cost_Center_tmp,--EP-93											--EBS-3394
					cost_center 	= case when @ccexists = 'Y' then @cost_Center_tmp else '##' end,	--EBS-3394
					bc_erate 	= 1,
					base_amount 	= isnull(base_amount,0) + @capamount_tmp,--ES_ACAP_00693
					pbc_erate 	= @exchangerate_tmp,
					pbase_amount 	= isnull(pbase_amount,0) + @pbaseamt_tmp,--ES_ACAP_00693
					cap_date 	= @capital_date
				where 	tran_number 	= @transaction_number
				and	tran_type 	= @transaction_type
				and	doc_number 	= @sidocno_tmp
				and	account_code 	= @dracctcode_tmp
				and	drcr_flag 	= @crdr2		
				--and	isnull(cost_Center,'##') = isnull(@cost_Center_tmp,'##') --EP-93						--EBS-3394
				and	isnull(cost_Center,'##') = case when @ccexists = 'Y' then @cost_Center_tmp else '##' end	--EBS-3394			 
			end

			fetch next from tagdtlcur 
				into @assetclass ,@docnumber_tmp ,@capamount_tmp, @sidocno_tmp,@account_code,@lineno_tmp --EP-93	
		end

		close tagdtlcur 
		deallocate tagdtlcur 
		
	
	--code added for the dts id 12H124_ACAP_00001[ES_General_00632] starts
	if @ctxt_service <> 'ACA_TIAC_Sr_Aut_Tgt' 
	begin
	--code added for the dts id 12H124_ACAP_00001[ES_General_00632] ends
	
		--ES_ACAP_00852
		;with cte as 
		(
				select  A.doc_number , A.doc_type , A.line_no , A.account_code , B.doc_number 'tran_no'
				from acap_wip_line_dtl A (nolock) , 
					 acap_wip_hdr B (nolock)
				where B.cap_wo_number = A.cap_wo_number
				and	  B.ou_id = A.ou_id
				and   B.doc_number = @transaction_number 
				and   B.ou_id      =  @ctxt_ouinstance
		)
		--ES_ACAP_00852
		
		update 	T1
		set 	--T1.cost_center     	= T2.cost_center,	--EP-93	
			/* Code Modifed by Vairamani C for ES_ACAP_00095 Starts here */
			T1.analysis_code	= T2.analysis_code,
			T1.sub_analysis_code	= T2.subanalysis_code
			/* Code Modifed by Vairamani C for ES_ACAP_00095 Ends here */
		from  	acap_wip_accounting_dtl T1(NOLOCK),
			si_acct_info_dtl T2(NOLOCK)
			,CTE						--ES_ACAP_00852
		where 	T2.tran_no       	= T1.doc_number
		and   	T2.account_code  	= T1.account_code
		--and  	T2.tran_ou       	= T1.ou_id  --Code Commented By Indira G For Defect ID:ES_ACAP_00829
		--code added for the dts id 12H124_ACAP_00001:12H124_ACAP_00066[ES_General_00632] starts
			and t1.tran_number 	= @transaction_number
			and	t1.ou_id		= @ctxt_ouinstance
		--code added for the dts id 12H124_ACAP_00001:12H124_ACAP_00066[ES_General_00632] ends
		--ES_ACAP_00852
		and 	T2.tran_no       	= cte.doc_number
		and   	T2.account_code  	= cte.account_code
		and     T2.line_no          = cte.line_no
		and		T2.tran_type        = cte.doc_type
		and     T1.tran_number		= cte.tran_no		
		--ES_ACAP_00852
                

                /* Code added by Swetha for ACAPDMS412AT_000147 on 28/03/2006 */

		/* Code modified by Swetha for ACAPDMS412AT_000147 on 29/03/2006 */
		select 	@cap_wo_number 	= cap_wo_number
		FRom   	acap_wip_hdr(nOLOCK)
		where  	doc_number 	= @transaction_number
		and    	ou_id      	= @ctxt_ouinstance

                if exists 
		(
			select 	'x'
			from  	acap_wip_dtl(nolock)
			where 	cap_wo_number = @cap_wo_number
			and   	ou_id         = @ctxt_ouinstance
			and   	doc_type in ('PM_PI','PM_MI')
		)
                begin 
                        declare cc_cur cursor for
                        select 	distinct  po_no,ref_doc_no
                        from   	sin_item_dtl      T1(NOLOCK),
                        	acap_wip_accounting_dtl T2(NOLOCK)
                        where  	T1.tran_no    = T2.doc_number
					   and    	T1.tran_ou        = T2.ou_id
      /* Code modfied by Swetha for ACAPDMS412AT_000147 on 28/03/2006 */
                  and    	T2.tran_number    = @transaction_number
                        and    	T2.ou_id          = @ctxt_ouinstance
                        
                        open cc_cur
                        
                        fetch next from cc_cur into @po_no,@gr_no
                        
                       while @@fetch_status = 0
                        begin 
                                select 	@paytd_matchingtype 	= paytd_matchingtype
                                from   	po_itemdetail_vw (NOLOCK)
                                where  	poitm_pono 		= @po_no 
                           and    	poitm_poou 		= @ctxt_ouinstance
                                
								 if @paytd_matchingtype in ('3P','4P','3G','4G')
								begin 
								/* Code modfied by Swetha for ACAPDMS412AT_000147 on 28/03/2006 */

											update 	T2
											set   	T2.cost_center 		= T1.cost_center,
													/* Code Modifed by Vairamani C for ES_ACAP_00095 Starts here */
													T2.analysis_code	= T1.analysis_code,
													T2.sub_analysis_code	= T1.subanalysis_code
													/* Code Modifed by Vairamani C for ES_ACAP_00095 Ends here */
											from  	fbp_posted_trn_dtl T1(nOLOCK),
                                        		acap_wip_accounting_dtl T2(nOLOCK)
											where 	T1.document_no  	= @gr_no
											and   	T1.account_code 	= T2.account_code
											--and   	T1.tran_ou      	= T2.ou_id --Code Commented By Indira G For Defect ID:ES_ACAP_00829
											and   	T2.tran_number  	= @transaction_number
											and    	T2.ou_id       		= @ctxt_ouinstance
									end
	            
									fetch next from cc_cur into @po_no,@gr_no
							end
							close cc_cur
							deallocate cc_cur
					end
					/* Code modified by Swetha for ACAPDMS412AT_000147 on 29/03/2006 */
					/* Code added by Swetha for ACAPDMS412AT_000147 on 28/03/2006 */
			end --if @ctxt_service <> 'ACA_TIAC_Sr_Aut_Tgt' ----code added for the dts id 12H124_ACAP_00001[ES_General_00632] starts
		end
		
		/*Code added by Uma for the bug id : ACAPDMS412AT_000614 starts here*/
		--Cost center updation for WIP A/c.. If cost center is mapped to wip account then 
		--update the cost center otherwise update with null 
		--CAPWIPACC (account type)
		if exists 
		(	
			select 	'X' 
			from	mac_cc_acc_mapped_vw vw(nolock),
				acap_accounting_info_dtl dtl(nolock)	
			where	tran_number	= @transaction_number
			and	asset_number	= @assetnumber
			and	VW.bu_id	= @bu_tmp
			and	account_no	= account_code
			and	center_no 	= @costcenter_tmp--ES_ACAP_00939
			and	account_type	= 'CAPWIPACC'
			and	VW.bu_id	= DTL.bu_id		
			--and	doc_number	is null -- Code commented by Uma for the defect id : ES_ACAP_00041
			--ES_ACAP_00939
			and	effective_date	<=	DTL.posting_date
			and	isnull(expiry_date,DTL.posting_date)	>=	DTL.posting_date 
			--ES_ACAP_00939
		)
		begin
			update 	acap_accounting_info_dtl
			set 	cost_center 	= @costcenter_tmp
			where	tran_number	= @transaction_number
			and	asset_number	= @assetnumber
			and	ou_id		= @ctxt_ouinstance
			and	account_type	= 'CAPWIPACC'
			--and	cost_center	is null -- Code added by Uma for the defect id : ES_ACAP_00041--ES_ACAP_00939
			and	isnull(cost_center,'##') = '##' --ES_ACAP_00939
		end
		/*Code added by Uma for the bug id : ACAPDMS412AT_000614 ends here*/
		
		/*Code Added by Angelin.R for the Feature : 8H123-2_MR_00003 Starts here*/
		/* -- commented as this part of code is handled above against the id ES_ACAP_00041 
		if exists (	select 	'X' 
				from	mac_cc_acc_mapped_vw vw(nolock),
					acap_accounting_info_dtl dtl(nolock)	
				where	tran_number	= @transaction_number
				and	asset_number	= @assetnumber
				and	VW.bu_id	= @bu_tmp
				and	account_no	= account_code
				and	cost_center 	is null
				and	account_type	= 'CAPWIPACC'
				and	VW.bu_id	= DTL.bu_id		
				and	doc_number	is not null)
		begin
			update 	acap_accounting_info_dtl
			set 	cost_center 	= @costcenter_tmp
			where	tran_number	= @transaction_number
			and	asset_number	= @assetnumber
			and	ou_id		= @ctxt_ouinstance
			and	account_type	= 'CAPWIPACC'
			and 	cost_center 	is null
			and	doc_number	is not null
		end
		*/
		
		
		--code commented and added for ES_ACAP_00906 starts
		/*
		/* Code added by Esther J for the dts id 9H123-1_ACAP_00023 starts */
		update 	T2  
		set   	T2.cost_center 		= T1.cost_center,
			T2.analysis_code	= T1.analysis_code,
			T2.sub_analysis_code	= T1.subanalysis_code
		from  	fbp_posted_trn_dtl T1(nOLOCK),
	    		acap_wip_accounting_dtl T2(nOLOCK)
		where 	T1.document_no  	= T2.doc_number
		and   	T1.account_code 	= T2.account_code
		--and   	T1.tran_ou      	= T2.ou_id	--Code Commented By Indira G For Defect ID:ES_ACAP_00829
		and     t1.tran_type 		= 'INV_IMIS'
		and   	T2.tran_number  	= @transaction_number
		and    	T2.ou_id       		= @ctxt_ouinstance
		/* Code added by Esther J for the dts id 9H123-1_ACAP_00023 ends*/
		*/
		;with cte as 
		(
				select  A.doc_number , A.doc_type , A.line_no , A.account_code , B.doc_number 'tran_no'
				from acap_wip_line_dtl A (nolock) , 
					 acap_wip_hdr B (nolock)
				where B.cap_wo_number = A.cap_wo_number
				and	  B.ou_id = A.ou_id
				and   B.doc_number = @transaction_number 
				and   B.ou_id      =  @ctxt_ouinstance
				and   A.doc_type   = 'INV_IMIS'
		)		

		update 	T2  
		set   	T2.cost_center 		 = isnull(T1.iid_cost_center,'##') , --EDS-58
			    T2.analysis_code	 = T1.iid_analysis_code,
			    T2.sub_analysis_code = T1.iid_subanalysis_code
		from  	issue_inv_detail T1(nolock)	,
	    		acap_wip_accounting_dtl T2(nOLOCK),
				cte
		where 	T1.iid_issue_no  		= T2.doc_number
		and   	T1.iid_dr_account_code 	= T2.account_code
		and   	T2.tran_number  		= @transaction_number
		and    	T2.ou_id       			= @ctxt_ouinstance
		and 	T1.iid_issue_no       	= cte.doc_number
		and   	T1.iid_dr_account_code  = cte.account_code
		and     T1.iid_line_no          = cte.line_no
		and     T2.tran_number			= cte.tran_no	
		--code commented and added for ES_ACAP_00906 ends

		if exists 
		(	
			select 	'X' 
			from	mac_acc_ce_cc_mapping VW(nolock),
				acap_wip_accounting_dtl DTL(nolock)	
			where	tran_number	= @transaction_number
			and 	VW.company_code = @companycode_tmp
			and	account_no	= account_code	
			--and 	cost_center 	is null	 -- Code added by Esther J for the dts id 9H123-1_ACAP_00023--EP-93	
			and	isnull(cost_center,'##') = '##' --EP-93	
		)
		begin
			update  acap_wip_accounting_dtl 
			set 	cost_center 	= center_no 	  	
			from	mac_acc_ce_cc_mapping M(nolock),
				acap_wip_accounting_dtl A(nolock)
			where	A.tran_number	= @transaction_number
			and 	M.company_code 	= @companycode_tmp
			and	M.account_no	= A.account_code
			--and 	cost_center 	is null	 -- Code added by Esther J for the dts id 9H123-1_ACAP_00023--EP-93	
			and	isnull(cost_center,'##') = '##' --EP-93	
 		end

		if exists 
		(	
			select 	'X' 
			from	mac_cc_acc_mapped_vw VW(nolock),
				acap_accounting_info_dtl DTL(nolock)	
			where	tran_number	= @transaction_number
			and	asset_number	= @assetnumber
			and	VW.bu_id	= @bu_tmp
			and	account_no	= account_code
			and	cost_center is null
			and	VW.bu_id	= DTL.bu_id		
		)
		begin
			update 	acap_accounting_info_dtl
			set 	cost_center 	= @costcenter_tmp
			where	tran_number	= @transaction_number
			and	asset_number	= @assetnumber
			and	account_type is null  
			and	ou_id		= @ctxt_ouinstance
			and 	cost_center is null
		end
		
		--code added for defect ES_ACAP_00521 starts
		if exists 
		(	
			select 	'X' 
			from	mac_cc_acc_mapped_vw VW(nolock),
				acap_accounting_info_dtl DTL(nolock)	
			where	tran_number	= @transaction_number
			and	asset_number	= @assetnumber
			and	VW.bu_id	= @bu_tmp
			and	account_no	= account_code
			and	DTL.cost_center is null
			and	VW.bu_id	= DTL.bu_id		
			and DTL.account_type = 'ASSETACCOUNT'
			and VW.center_no = @costcenter_tmp
		)
		begin
			update 	acap_accounting_info_dtl
			set 	cost_center 	= @costcenter_tmp
			where	tran_number	= @transaction_number
			and	asset_number	= @assetnumber
			and	account_type = 'ASSETACCOUNT'  
			and	ou_id		= @ctxt_ouinstance
			and cost_center is null
		end
		--code added for defect ES_ACAP_00521 ends
		
		/*Code Added by Angelin.R for the Feature : 8H123-2_MR_00003 Ends here*/

		/* Code added by Uma for the bug id: ACAPDMS412AT_000613 starts here*/
		update 	acap_accounting_info_dtl
		set	analysis_code	  	= 	case 
								when analysis_code ='' then '##'
						 		else analysis_code 
							end 	,
			sub_analysis_code 	= 	case 
								when sub_analysis_code ='' then '##'
						 		else sub_analysis_code 
							end
		where	tran_number		= 	@transaction_number
		and	asset_number		= 	@assetnumber
		and	ou_id			= 	@ctxt_ouinstance 
	/* Code added by Uma for the bug id: ACAPDMS412AT_000613 ends here*/
	
	
	/* Code added by Uma for the bug id : ACAPDMS412AT_000620 starts here*/

	-- acap_accounting_info_dtl --ROFF
	--Rounding off postings
	if exists 
	(	
		select 'x' 
		from 	acap_accounting_info_dtl (nolock)
		where 	tran_number 	= @transaction_number
		and	tran_type 	= @transaction_type	
		and	ou_id		= @ctxt_ouinstance
	)
	begin
		update	acap_accounting_info_dtl
		set	tran_amount	= round(tran_amount,@pamt_tmp),
			base_amount	= round(base_amount,@pamt_tmp),
			pbase_amount	= round(pbase_amount,@pamt_tmp)
		where 	tran_number 	= @transaction_number
		and	tran_type 	= @transaction_type	
		and	ou_id		= @ctxt_ouinstance
	
		declare	@sum_cr_baseamt		fin_amount ,
			@sum_cr_parbaseamt	fin_amount ,
			@sum_dr_baseamt		fin_amount ,
			@sum_dr_parbaseamt	fin_amount ,
			@base_amt_diff		fin_amount ,
			@par_base_amt_diff	fin_amount ,
			@roff_curr_code		fin_currencycode ,
			@roff_acct_code		fin_accountcode ,
			@fb_id_tmp		fin_financebookid ,
			@tran_date		fin_date ,
			@cur_tmp		fin_currencycode
	
		select 	@sum_cr_baseamt 	= sum(isnull(base_amount,0)),
			@sum_cr_parbaseamt	= sum(isnull(pbase_amount,0))
		from	acap_accounting_info_dtl (nolock)
		where 	tran_number 		= @transaction_number
		and	tran_type 		= @transaction_type	
		and	ou_id			= @ctxt_ouinstance
		and	drcr_flag		= 'CR'
	
		select 	@sum_dr_baseamt 	= sum(isnull(base_amount,0)) ,
			@sum_dr_parbaseamt	= sum(isnull(pbase_amount,0)) 
		from	acap_accounting_info_dtl (nolock)
		where 	tran_number 		= @transaction_number
		and	tran_type 		= @transaction_type	
		and	ou_id			= @ctxt_ouinstance
		and	drcr_flag		= 'DR'
	
		--Get finance book and currency code
		select 	@fb_id_tmp	 	= fb_id ,
			@cur_tmp		= currency ,
			@tran_date		= tran_date
		from	acap_accounting_info_dtl (nolock)
		where 	tran_number 		= @transaction_number
		and	tran_type 		= @transaction_type	
		and	ou_id			= @ctxt_ouinstance
	
		select 	@base_amt_diff		= @sum_cr_baseamt - @sum_dr_baseamt ,
			@par_base_amt_diff	= @sum_cr_parbaseamt - @sum_dr_parbaseamt
	
		select	@companycode_tmp 	= company_code
		from 	emod_ou_vw (nolock)
		where	ou_id			= @ctxt_ouinstance		
	
		--Get rounding off currency
		select 	@roff_curr_code = account_currency
		from 	ard_usage_met (nolock)
		where 	usage_id 	= 'ROFF'
	
		if @roff_curr_code = 'BASE'
		begin
			select 	@roff_curr_code = currency_code
			from 	emod_basecurr_vw (nolock)	
			where	company_code	= @companycode_tmp
			and	flag 		= 'B'
		end
		else
		begin
			select @roff_curr_code = @cur_tmp
		end
	
		--Base amount Rounding off
		if @base_amt_diff > 0  --Then 'DR'
		begin 
			--Get rounding off account code
			-- Get Expense Account for the expense code / Usage
			select 	@roff_acct_code	= account_code
			from   	ard_addn_account_vw (nolock)
			where	company_code 	= @companycode_tmp
			and	fb_id		= @fb_id_tmp
			and	usage_id	= 'ROFF'
			and	@tran_date between effective_from 
				and isnull(effective_to, '9999-12-31')
			and	currency_code	= @roff_curr_code
			and	drcr_flag	= 'DR'  
			
			/*if @roff_acct_code is null
			begin
				raiserror('ROFF a/c not defined',16,1)
				return
			end*/
	
			insert into acap_accounting_info_dtl
			(
				tran_number,tran_type,asset_number,tag_number,
				account_code,drcr_flag,
				timestamp,ou_id,tran_date,posting_date,
				currency,
				tran_amount,
				fb_id,company_code,bu_id,
				bc_erate,
				base_amount,
				pbc_erate,
				pbase_amount,
				cap_date,createdby,createddate,modifiedby,modifieddate,
				account_type
			)
			--select 	distinct	--TDH-127	
			select 	top 1			--TDH-127	
				tran_number,tran_type,asset_number,1,
				--account_code,'DR',                      --code commented for ES_ACAP_00475 
				@roff_acct_code , 'DR',					  --code added for ES_ACAP_00475 
				timestamp,ou_id,tran_date,posting_date,
				@roff_curr_code,
				0,
				@fb_id_tmp,company_code,bu_id,
				bc_erate,
				@base_amt_diff,
				pbc_erate,
				0,
				cap_date,createdby,createddate,modifiedby,modifieddate,
				account_type
			from	acap_accounting_info_dtl (nolock)
			where 	tran_number 	= @transaction_number
			and	tran_type 	= @transaction_type	
			and	ou_id		= @ctxt_ouinstance
			and	drcr_flag	= 'DR'
		end
	
		if @base_amt_diff < 0  --Then 'CR'
		begin 
			--Get rounding off account code
			-- Get Expense Account for the expense code / Usage
			select 	@roff_acct_code	= account_code
			from   	ard_addn_account_vw (nolock)
			where	company_code 	= @companycode_tmp
			and	fb_id		= @fb_id_tmp
			and	usage_id	= 'ROFF'
			and	@tran_date between effective_from 
				and isnull(effective_to, '9999-12-31')
			and	currency_code	= @roff_curr_code
			and	drcr_flag	= 'CR'  
			
			/*if @roff_acct_code is null
			begin
				raiserror('ROFF a/c not defined',16,1)
				return
			end*/
	
			insert into acap_accounting_info_dtl
			(
				tran_number,tran_type,asset_number,tag_number,
				account_code,drcr_flag,
				timestamp,ou_id,tran_date,posting_date,
				currency,
				tran_amount,
				fb_id,company_code,bu_id,
				bc_erate,
				base_amount,
				pbc_erate,
				pbase_amount,
				cap_date,createdby,createddate,modifiedby,modifieddate,
				account_type
			)
			--select 	distinct	--TDH-127	
			select 	top 1			--TDH-127	
				tran_number,tran_type,asset_number,1,
				--account_code,'CR',								 --code commented for ES_ACAP_00475 
				@roff_acct_code,'CR',								 --code added for ES_ACAP_00475 
				timestamp,ou_id,tran_date,posting_date,
				@roff_curr_code,
				0,
				@fb_id_tmp,company_code,bu_id,
				bc_erate,
				@base_amt_diff,
				pbc_erate,
				0,
				cap_date,createdby,createddate,modifiedby,modifieddate,
				account_type
			from	acap_accounting_info_dtl (nolock)
			where 	tran_number 	= @transaction_number
			and	tran_type 	= @transaction_type	
			and	ou_id		= @ctxt_ouinstance
			and	drcr_flag	= 'CR'
		end
	
		--Par base amount Rounding off

		if @par_base_amt_diff > 0  --Then 'DR'
		begin 
			--Get rounding off account code
			-- Get Expense Account for the expense code / Usage
			select 	@roff_acct_code	= account_code
			from   	ard_addn_account_vw (nolock)
			where	company_code 	= @companycode_tmp
			and	fb_id		= @fb_id_tmp
			and	usage_id	= 'ROFF'
			and	@tran_date between effective_from 
				and isnull(effective_to, '9999-12-31')
			and	currency_code	= @roff_curr_code
			and	drcr_flag	= 'DR'  
			
			/*if @roff_acct_code is null
			begin
				raiserror('ROFF a/c not defined',16,1)
				return
			end*/

			insert into acap_accounting_info_dtl
			(
				tran_number,tran_type,asset_number,tag_number,
				account_code,drcr_flag,
				timestamp,ou_id,tran_date,posting_date,
				currency,
				tran_amount,
				fb_id,company_code,bu_id,
				bc_erate,
				base_amount,
				pbc_erate,
				pbase_amount,
				cap_date,createdby,createddate,modifiedby,modifieddate,
				account_type
			)
			--select 	distinct	--TDH-127	
			select 	top 1			--TDH-127	
				tran_number,tran_type,asset_number,1,
				--account_code,'DR',								--code commented for ES_ACAP_00475 
				@roff_acct_code,'DR',								--code added for ES_ACAP_00475 
				timestamp,ou_id,tran_date,posting_date,
				@roff_curr_code,
				0,
				@fb_id_tmp,company_code,bu_id,
				bc_erate,
				0,
				pbc_erate,
				@par_base_amt_diff,
				cap_date,createdby,createddate,modifiedby,modifieddate,
				account_type
			from	acap_accounting_info_dtl (nolock)
			where 	tran_number 	= @transaction_number
			and	tran_type 	= @transaction_type	
			and	ou_id		= @ctxt_ouinstance
			and	drcr_flag	= 'DR'
		end
	
		if @par_base_amt_diff < 0  --Then 'CR'
		begin 
			--Get rounding off account code
			-- Get Expense Account for the expense code / Usage
			select 	@roff_acct_code	= account_code
			from   	ard_addn_account_vw (nolock)
			where	company_code 	= @companycode_tmp
			and	fb_id		= @fb_id_tmp
			and	usage_id	= 'ROFF'
			and	@tran_date between effective_from 
				and isnull(effective_to, '9999-12-31')
			and	currency_code	= @roff_curr_code
			and	drcr_flag	= 'CR'  
			
			/*if @roff_acct_code is null
			begin
				raiserror('ROFF a/c not defined',16,1)
				return
			end*/
	
			insert into acap_accounting_info_dtl
			(
				tran_number,tran_type,asset_number,tag_number,
				account_code,drcr_flag,
				timestamp,ou_id,tran_date,posting_date,
				currency,
				tran_amount,
				fb_id,company_code,bu_id,
				bc_erate,
				base_amount,
				pbc_erate,
				pbase_amount,
				cap_date,createdby,createddate,modifiedby,modifieddate,
				account_type
			)
			--select 	distinct	--TDH-127	
			select 	top 1			--TDH-127	
				tran_number,tran_type,asset_number,1,
				--account_code,'CR',							--code commented for ES_ACAP_00475 
				@roff_acct_code,'CR',							--code added for ES_ACAP_00475 
				timestamp,ou_id,tran_date,posting_date,
				@roff_curr_code,
				0,
				@fb_id_tmp,company_code,bu_id,
				bc_erate,
				0,
				pbc_erate,
				@par_base_amt_diff,
				cap_date,createdby,createddate,modifiedby,modifieddate,
				account_type
			from	acap_accounting_info_dtl (nolock)
			where 	tran_number 	= @transaction_number
			and	tran_type 	= @transaction_type	
			and	ou_id		= @ctxt_ouinstance
			and	drcr_flag	= 'CR'
		end
	end	

	/* Code added by Uma for the bug id : AINQDMS412AT_000030 starts here*/
	-- acap_journal_accounting_dtl --ROFF
	if exists 
	(	
		select 'x' 
		from 	acap_journal_accounting_dtl (nolock)
		where 	tran_number 	= @transaction_number
		and	tran_type 	= @transaction_type	
		and	ou_id		= @ctxt_ouinstance
	)
	begin
		update	acap_journal_accounting_dtl
		set	tran_amount	= round(tran_amount,@pamt_tmp),
			base_amount	= round(base_amount,@pamt_tmp),
			pbase_amount	= round(pbase_amount,@pamt_tmp)
		where 	tran_number 	= @transaction_number
		and	tran_type 	= @transaction_type	
		and	ou_id		= @ctxt_ouinstance

		--ACAP JV rounding off starts here
		select 	@sum_cr_baseamt 	= sum(isnull(base_amount,0)),
			@sum_cr_parbaseamt	= sum(isnull(pbase_amount,0))
		from	acap_journal_accounting_dtl (nolock)
		where 	tran_number 		= @transaction_number
		and	tran_type 		= @transaction_type	
		and	ou_id			= @ctxt_ouinstance
		and	drcr_flag		= 'CR'
	
		select 	@sum_dr_baseamt 	= sum(isnull(base_amount,0)) ,
			@sum_dr_parbaseamt	= sum(isnull(pbase_amount,0)) 
		from	acap_journal_accounting_dtl (nolock)
		where 	tran_number 		= @transaction_number
		and	tran_type 		= @transaction_type	
		and	ou_id			= @ctxt_ouinstance
		and	drcr_flag		= 'DR'
	
		--Get finance book and currency code
		select 	@fb_id_tmp	 	= fb_id ,
			@cur_tmp		= currency ,
			@tran_date		= tran_date
		from	acap_journal_accounting_dtl (nolock)
		where 	tran_number 		= @transaction_number
		and	tran_type 		= @transaction_type	
		and	ou_id			= @ctxt_ouinstance
	
		select 	@base_amt_diff		= @sum_cr_baseamt - @sum_dr_baseamt ,
			@par_base_amt_diff	= @sum_cr_parbaseamt - @sum_dr_parbaseamt
	
		select	@companycode_tmp 	= company_code
		from 	emod_ou_vw (nolock)
		where	ou_id			= @ctxt_ouinstance		
	
		--Get rounding off currency
		select 	@roff_curr_code = account_currency
		from 	ard_usage_met (nolock)
		where 	usage_id 	= 'ROFF'
	
		if @roff_curr_code = 'BASE'
		begin
			select 	@roff_curr_code = currency_code
			from 	emod_basecurr_vw (nolock)	
			where	company_code	= @companycode_tmp
			and	flag 		= 'B'
		end
		else
		begin
			select @roff_curr_code = @cur_tmp
		end
	
		--Base amount Rounding off
		if @base_amt_diff > 0  --Then 'DR'
		begin 
			--Get rounding off account code
			-- Get Expense Account for the expense code / Usage
			select 	@roff_acct_code	= account_code
			from   	ard_addn_account_vw (nolock)
			where	company_code 	= @companycode_tmp
			and	fb_id		= @fb_id_tmp
			and	usage_id	= 'ROFF'
			and	@tran_date between effective_from 
				and isnull(effective_to, '9999-12-31')
			and	currency_code	= @roff_curr_code
			and	drcr_flag	= 'DR'  
			
			/*if @roff_acct_code is null
			begin
				raiserror('ROFF a/c not defined',16,1)
				return
			end*/
	
			insert into acap_journal_accounting_dtl
			(
				tran_number,tran_type,asset_number,tag_number,
				account_code,drcr_flag,
				timestamp,ou_id,tran_date,posting_date,
				currency,
				tran_amount,
				fb_id,company_code,bu_id,
				bc_erate,
				base_amount,
				pbc_erate,
				pbase_amount,
				cap_date,createdby,createddate,modifiedby,modifieddate,
				account_type
			)
			--select 	distinct	--TDH-127	
			select 	top 1			--TDH-127	
				tran_number,tran_type,asset_number,1,
				--account_code,'DR',						--code commented for ES_ACAP_00475 
				@roff_acct_code,'DR',						--code added for ES_ACAP_00475 
				timestamp,ou_id,tran_date,posting_date,
				@roff_curr_code,
				0,
				@fb_id_tmp,company_code,bu_id,
				bc_erate,
				@base_amt_diff,
				pbc_erate,
				0,
				cap_date,createdby,createddate,modifiedby,modifieddate,
				account_type
			from	acap_journal_accounting_dtl (nolock)
			where 	tran_number 	= @transaction_number
			and	tran_type 	= @transaction_type	
			and	ou_id		= @ctxt_ouinstance
			and	drcr_flag	= 'DR'
		end
	
		if @base_amt_diff < 0  --Then 'CR'
		begin 
			
			--Get rounding off account code
			-- Get Expense Account for the expense code / Usage
			select 	@roff_acct_code	= account_code
			from   	ard_addn_account_vw (nolock)
			where	company_code 	= @companycode_tmp
			and	fb_id		= @fb_id_tmp
			and	usage_id	= 'ROFF'
			and	@tran_date between effective_from 
				and isnull(effective_to, '9999-12-31')
			and	currency_code	= @roff_curr_code
			and	drcr_flag	= 'CR'  
			
			/*if @roff_acct_code is null
			begin
				raiserror('ROFF a/c not defined',16,1)
				return
			end*/
	
			insert into acap_journal_accounting_dtl
			(
				tran_number,tran_type,asset_number,tag_number,
				account_code,drcr_flag,
				timestamp,ou_id,tran_date,posting_date,
				currency,
				tran_amount,
				fb_id,company_code,bu_id,
				bc_erate,
				base_amount,
				pbc_erate,
				pbase_amount,
				cap_date,createdby,createddate,modifiedby,modifieddate
				,account_type
			)
			--select 	distinct	--TDH-127	
			select 	top 1			--TDH-127	 
				tran_number,tran_type,asset_number,1,
				--account_code,'CR',								--code commented for ES_ACAP_00475 
				@roff_acct_code,'CR',								--code added for ES_ACAP_00475 
				timestamp,ou_id,tran_date,posting_date,
				@roff_curr_code,
				0,
				@fb_id_tmp,company_code,bu_id,
				bc_erate,
				@base_amt_diff,
				pbc_erate,
				0,
				cap_date,createdby,createddate,modifiedby,modifieddate,
				account_type
			from	acap_journal_accounting_dtl (nolock)
			where 	tran_number 	= @transaction_number
			and	tran_type 	= @transaction_type	
			and	ou_id		= @ctxt_ouinstance
			and	drcr_flag	= 'CR'
		end
	
		--Par base amount Rounding off

		if @par_base_amt_diff > 0  --Then 'DR'
		begin 
			--Get rounding off account code
			-- Get Expense Account for the expense code / Usage
			select 	@roff_acct_code	= account_code
			from   	ard_addn_account_vw (nolock)
			where	company_code 	= @companycode_tmp
			and	fb_id		= @fb_id_tmp
			and	usage_id	= 'ROFF'
			and	@tran_date between effective_from 
				and isnull(effective_to, '9999-12-31')
			and	currency_code	= @roff_curr_code
			and	drcr_flag	= 'DR'  
			
			/*if @roff_acct_code is null
			begin
				raiserror('ROFF a/c not defined',16,1)
				return
			end*/

			insert into acap_journal_accounting_dtl
			(
				tran_number,tran_type,asset_number,tag_number,
				account_code,drcr_flag,
				timestamp,ou_id,tran_date,posting_date,
				currency,
				tran_amount,
				fb_id,company_code,bu_id,
				bc_erate,
				base_amount,
				pbc_erate,
				pbase_amount,
				cap_date,createdby,createddate,modifiedby,modifieddate,
				account_type
			)
			--select 	distinct	--TDH-127	
			select 	top 1			--TDH-127	
				tran_number,tran_type,asset_number,1,
				--account_code,'DR',										--code commented for ES_ACAP_00475 	
				@roff_acct_code,'DR',										--code added for ES_ACAP_00475 
				timestamp,ou_id,tran_date,posting_date,
				@roff_curr_code,
				0,
				@fb_id_tmp,company_code,bu_id,
				bc_erate,
				0,
				pbc_erate,
				@par_base_amt_diff,
				cap_date,createdby,createddate,modifiedby,modifieddate,
				account_type
			from	acap_journal_accounting_dtl (nolock)
			where 	tran_number 	= @transaction_number
			and	tran_type 	= @transaction_type	
			and	ou_id		= @ctxt_ouinstance
			and	drcr_flag	= 'DR'
		end

		if @par_base_amt_diff < 0  --Then 'CR'
		begin 
			--Get rounding off account code
			-- Get Expense Account for the expense code / Usage
			select 	@roff_acct_code	= account_code
			from   	ard_addn_account_vw (nolock)
			where	company_code 	= @companycode_tmp
			and	fb_id		= @fb_id_tmp
			and	usage_id	= 'ROFF'
			and	@tran_date between effective_from 
				and isnull(effective_to, '9999-12-31')
			and	currency_code	= @roff_curr_code
			and	drcr_flag	= 'CR'  
			
			/*if @roff_acct_code is null
			begin
				raiserror('ROFF a/c not defined',16,1)
				return
			end*/
	
			insert into acap_journal_accounting_dtl
			(
				tran_number,tran_type,asset_number,tag_number,
				account_code,drcr_flag,
				timestamp,ou_id,tran_date,posting_date,
				currency,
				tran_amount,
				fb_id,company_code,bu_id,
				bc_erate,
				base_amount,
				pbc_erate,
				pbase_amount,
				cap_date,createdby,createddate,modifiedby,modifieddate,
				account_type
			)
			--select 	distinct	--TDH-127	
			select 	top 1			--TDH-127	 
				tran_number,tran_type,asset_number,1,
				--account_code,'CR',						--code commented for ES_ACAP_00475 	
				@roff_acct_code,'CR',						--code added for ES_ACAP_00475 	
				timestamp,ou_id,tran_date,posting_date,
				@roff_curr_code,
				0,
				@fb_id_tmp,company_code,bu_id,
				bc_erate,
				0,
				pbc_erate,
				abs(@par_base_amt_diff),
				cap_date,createdby,createddate,modifiedby,modifieddate,
				account_type
			from	acap_journal_accounting_dtl (nolock)
			where 	tran_number 	= @transaction_number
			and	tran_type 	= @transaction_type	
			and	ou_id		= @ctxt_ouinstance
			and	drcr_flag	= 'CR'
		end
		--rounding off completed for acap jv
	end
	/* Code added by Uma for the bug id : AINQDMS412AT_000030 ends here*/

	-- acap_wip_accounting_dtl --ROFF
	if exists 
	(	
		select 'x' 
		from 	acap_wip_accounting_dtl (nolock)
		where 	tran_number 	= @transaction_number
		and	tran_type 	= @transaction_type	
		and	ou_id		= @ctxt_ouinstance
	)
	begin
		update	acap_wip_accounting_dtl
		set	tran_amount	= round(tran_amount,@pamt_tmp),
			base_amount	= round(base_amount,@pamt_tmp),
			pbase_amount	= round(pbase_amount,@pamt_tmp)
		where 	tran_number 	= @transaction_number
		and	tran_type 	= @transaction_type	
		and	ou_id		= @ctxt_ouinstance
	end
	/* Code added by Uma for the bug id : ACAPDMS412AT_000620 ends here*/

	select @acccount  = 0,
	       @jourcount = 0,	
	       @wipcount  = 0

	select 	@acccount 	= count(*)  
	from 	acap_accounting_info_dtl (nolock)
	where 	tran_number 	= @transaction_number

	select 	@jourcount 	= count(*)  
	from 	acap_journal_accounting_dtl (nolock)
	where 	tran_number 	= @transaction_number

	select 	@wipcount 	= count(*)  
	from 	acap_wip_accounting_dtl (nolock)
	where 	tran_number 	= @transaction_number

	if @acccount = 0 and @jourcount = 0 and @wipcount = 0
	begin
		exec fin_raise_error 'Data Does not exist for posting'
		return
	end

	return 0

	set nocount off
end





