/*$File_version=ms4.3.0.12$*/
/*$file name : acapamasmspamashref.sql*/
/*$version   : 4.0.0.8*/
/*==================================================
   stored procedure : acapamasmspamashref
   method           :acapamasmmtamashref
   author           : Balamurali s
   created on       : 26 may 2001 13:34:39:920
   created at       : s4141
   generated by     : fpuser

   Modified By		: Saurabh  Mathur
   Modified Date	: 11-Aug-2004
   Purpose		: ACAPDMS41SYTST_000128

        Modified By      : Saurabh  Mathur
	Modified Date    : 20-Nov-2004
	Modified Purpose : SNP411UISTD_000008

        Modified By      : Saurabh  Mathur
	Modified Date    : 01-Dec-2004
	Modified Purpose : SNP411UISTD_000008

	Modified By		: Sangeetha Sitaraman
	Date		: 13-01-2006
	Purpose		: For FA revamp(for earlier version of the SP pls.refer VSS) 
	
	Modified By		: Swetha
	Date		: 28/02/2006
	Purpose		: ACAPDMS412AT_000360
	
	Modified By		: Swetha
	Date		: 10/03/2006
	Purpose		: ACAPDMS412AT_000374

	Modified by        : Ravikrishnan.N                                           
	Modified Date      : 07/Aug/2006                                              
	Purpose            : ACAPDMS412AT_000490          

	   Modified  by	    : Esther J
	   Date		    : 18/05/2007
	   Purpose	    : ACAPDMS412AT_000710
Modified by			date			purpose
Vijayan.j			19/08/2008		ES_ACAP_00015
                                  
 proc  acapamasmspamashref
grant exec on acapamasmspamashref to public
/* Damodharan. R	09/12/2014			14H109_ADEPP_00004						*/
/* Nithya s			14/08/2015		                14H109_ACAP_00059   	   */ 
/*  Harithra		 17-08-2018         EPE-8428                             */
/* Abinaya V		 07-09-2018         EBS-1924      */
/*Uma Maheshwari M   18-09-2018			EPE-9198		*/
/*Amani.P			10.01.2019			EPE-11335*/
/*gokul M				03/11/2020		EPE-23559  */
/*Nithya S				20/05/2022		EPE-47098  */
/*Abilash Sriram N		19/07/2023		EPE-65400	*/
/*Harithra				17/08/2023		EPE-66921*/
===================================================*/
CREATE procedure acapamasmspamashref
	@ctxt_language             fin_ctxt_language,
	@ctxt_ouinstance           fin_ctxt_ouinstance,
	@ctxt_service              fin_ctxt_service,
	@ctxt_user                 fin_ctxt_user,
	@assetclass                fin_assetclass,
	@assetdescription          fin_desc40,
	@assetgrpnum               fin_group,
	@assetlocation             fin_assetlocation,
	@assetnumber               fin_assetnumber,
	--@barcode             fin_DocumentNumber,
	@barcode                   fin_barcode,--EPE-65400
	@businessuse               fin_depprecent,
	@capitalizationdate        fin_date,
	@capitalizationnumber	   fin_documentnumber ,
	@costcenter                fin_costcentercode,
	@createddate               fin_date,
	@creationby                fin_ctxt_user,
	@custodian                 fin_employeename,
	@depcategory               fin_depcategory,
	@fb                        fin_financebookid,
	@guid                      fin_guid,
	@inservicedate             fin_date,
	@invcyclemlenn             fin_desc40,
	@manufacturer              fin_name,
	@model                     fin_desc40,
	@newtag                    fin_flag,
	@notypeno                  fin_notypeno,
	@proposalnumber		   fin_documentnumber ,	
	@salvagevalue              fin_amount,
	@serialnumber              fin_serialno,
	@status			   fin_status ,	
	@tagcost                   fin_amount,
	@tagdescription            fin_desc40,
	@tagnumber                 fin_assettagno,
	@timestamp                 fin_timestamp,
	@warrentynumber            fin_documentnumber,
	@residualvalue        	   fin_depprecent,		--Code added by Damodharan. R for Defect ID 14H109_ADEPP_00004 
	@usefullifeinmonths   	   fin_lineno,			--Code added by Damodharan. R for Defect ID 14H109_ADEPP_00004
	/*Code added for the defect id : 14H109_ACAP_00059 starts here */
	@workflowstatus  	fin_desc40, 
	@hdnrt_stcontrol 	udd_ctxt_state_name,
	/*Code added for the defect id : 14H109_ACAP_00059 ends here */
	/*code modified for EPE-8428 - Harithra*/
	@accountcode   			fin_accountcode, --Input/Output
	@accountdescription   	fin_accountdesc, --Input/Output
	@lscostcentre         	fin_costcentercode, --Input/Output
	@analysiscode    	fin_analysiscode, --Input/Output
	@subanalysiscode      	fin_subanalysiscode, --Input/Output
	@transaction_type       transactiontype,  --Input/Output --EBS-1924
	@assetclassification  	desc255, --Input/Output
	@assetcategory        	desc255, --Input/Output
	@assetcluster         	desc255, --Input/Output
	@natureofshift			fin_flag, --Input	--epe-23559
	@salvageper           	fin_depprecent,--EPE-43676
	@m_errorid              fin_int output
as
begin	-- nocount should be switched on to prevent phantom rows 
	set nocount on
	


	declare @docnum		fin_documentnumber
	declare @cap_number	fin_documentnumber
	declare @resval_tmp			fin_paramcode,
			@usefulllife_tmp	fin_desc40,
    		@allmodresval_tmp	fin_desc40,
    		@res_state			fin_paramcode,
    		@sysdate			fin_date,
			@company_code		fin_companycode,
			/*-------EPE-9198-------*/	
			@hdn_residualvalue  fin_desc255, 
			@hdn_usefullife		fin_desc255, 
			@hdn_workflowsec	fin_desc255
			/*-------EPE-9198-------*/
	-- @m_errorid should be 0 to indicate success
	select @m_errorid = 0	
	/*code modified for EPE-8428 - Harithra*/
	Set @accountcode           = ltrim(rtrim(@accountcode))
	Set @accountdescription    = ltrim(rtrim(@accountdescription))
	Set @lscostcentre          = ltrim(rtrim(@lscostcentre))
	Set @analysiscode          = ltrim(rtrim(@analysiscode))
	Set @subanalysiscode       = ltrim(rtrim(@subanalysiscode))
	set @transaction_type      = ltrim(rtrim(@transaction_type)) --EBS-1924
	Set @assetclassification   = ltrim(rtrim(@assetclassification))
	Set @assetcategory         = ltrim(rtrim(@assetcategory))
	Set @assetcluster          = ltrim(rtrim(@assetcluster))
	--EPE-23559 starts	
	 select  @natureofshift         = ltrim(rtrim(@natureofshift))  
	 IF @natureofshift = '~#~'  
			Select @natureofshift = null  
	 --EPE-23559 	  
	
	if @ctxt_language = -915 
		select @ctxt_language = null
	if @ctxt_ouinstance = -915 
		select @ctxt_ouinstance = null
	select @ctxt_service = ltrim(rtrim(@ctxt_service))
	if @ctxt_service = '~#~' 
		select @ctxt_service = null
	select @ctxt_user = ltrim(rtrim(@ctxt_user))
	if @ctxt_user = '~#~' 
		select @ctxt_user = null
	select @assetclass = ltrim(rtrim(@assetclass))
	if @assetclass = '~#~' 
		select @assetclass = null
	select @assetdescription = ltrim(rtrim(@assetdescription))
	if @assetdescription = '~#~' 
		select @assetdescription = null
	select @assetgrpnum = ltrim(rtrim(@assetgrpnum))
	if @assetgrpnum = '~#~' 
		select @assetgrpnum = null
	select @assetlocation = ltrim(rtrim(@assetlocation))
	if @assetlocation = '~#~' 
		select @assetlocation = null
	select @assetnumber = ltrim(rtrim(@assetnumber))
	if @assetnumber = '~#~' 
		select @assetnumber = null
	select @barcode = ltrim(rtrim(@barcode))
	if @barcode = '~#~' 
		select @barcode = null
	if @businessuse = -915 
		select @businessuse = null
	select @capitalizationdate = ltrim(rtrim(@capitalizationdate))
	if @capitalizationdate = '1900-01-01' 
		select @capitalizationdate = null
	select @costcenter = ltrim(rtrim(@costcenter))
	if @costcenter = '~#~' 
		select @costcenter = null
	select @createddate = ltrim(rtrim(@createddate))
	if @createddate = '1900-01-01' 
		select @createddate = null
	select @creationby = ltrim(rtrim(@creationby))
	if @creationby = '~#~' 
		select @creationby = null
	select @custodian = ltrim(rtrim(@custodian))
	if @custodian = '~#~' 
		select @custodian = null
	select @depcategory = ltrim(rtrim(@depcategory))
	if @depcategory = '~#~' 
		select @depcategory = null
	select @capitalizationnumber = ltrim(rtrim(@capitalizationnumber))
	if @capitalizationnumber = '~#~' 
		select @capitalizationnumber = null
	select @fb = ltrim(rtrim(@fb))
	if @fb = '~#~' 
		select @fb = null
	select @guid = ltrim(rtrim(@guid))
	if @guid = '~#~' 
		select @guid = null
	select @inservicedate = ltrim(rtrim(@inservicedate))
	if @inservicedate = '1900-01-01' 
		select @inservicedate = null
	select @manufacturer = ltrim(rtrim(@manufacturer))
	if @manufacturer = '~#~' 
		select @manufacturer = null
	select @model = ltrim(rtrim(@model))
	if @model = '~#~' 
		select @model = null
	select @newtag = ltrim(rtrim(@newtag))
	if @newtag = '~#~' 
		select @newtag = null
	select @notypeno = ltrim(rtrim(@notypeno))
	if @notypeno = '~#~' 
		select @notypeno = null
	if @salvagevalue = -915 
		select @salvagevalue = null
	if @serialnumber = '-915' or @serialnumber = '~#~' 
		select @serialnumber = null
	if @tagcost = -915 
		select @tagcost = null
	select @tagdescription = ltrim(rtrim(@tagdescription))
	if @tagdescription = '~#~' 
		select @tagdescription = null
	if @tagnumber = -915 
		select @tagnumber = null
	if @timestamp = -915 
		select @timestamp = null
	select @warrentynumber = ltrim(rtrim(@warrentynumber))
	if @warrentynumber = '~#~' 
		select @warrentynumber = null
	select @proposalnumber = ltrim(rtrim(@proposalnumber))
	if @proposalnumber = '~#~'
		select @proposalnumber = null
	
	/*Code added by Damodharan. R for Defect ID 14H109_ADEPP_00004 starts here*/
	if @residualvalue = -915
		Select @residualvalue = null  

	if  @usefullifeinmonths = -915
		Select @usefullifeinmonths = null 
	/*Code added by Damodharan. R for Defect ID 14H109_ADEPP_00004 ends here */
	
 	/*Code added for the defect id : 14H109_ACAP_00059 starts here */     
	 select @workflowstatus   = ltrim(rtrim(@workflowstatus))
	 if @workflowstatus = '~#~' 
		Select @workflowstatus = null  
	 select @hdnrt_stcontrol  = ltrim(rtrim(@hdnrt_stcontrol))
	 if @hdnrt_stcontrol = '~#~' 
		Select @hdnrt_stcontrol = null
	/*code modified for EPE-8428 - Harithra*/
 	IF @accountcode = '~#~' 
		Select @accountcode = null  

	IF @accountdescription = '~#~' 
		Select @accountdescription = null  

	IF @lscostcentre = '~#~' 
		Select @lscostcentre = null  

	IF @analysiscode = '~#~' 
		Select @analysiscode = null  

	IF @subanalysiscode = '~#~' 
		Select @subanalysiscode = null
		
	IF @transaction_type = '~#~'
		Select @transaction_type = null  --EBS-1924

	IF @assetclassification = '~#~' 
		Select @assetclassification = null  

	IF @assetcategory = '~#~' 
		Select @assetcategory = null  

	IF @assetcluster = '~#~' 
		Select @assetcluster = null  
	
	IF @salvageper = -915
		Select @salvageper = null --EPE-43676

	declare @workflow_app		fin_metadata_code

	select @workflow_app		= dbo.workflowapp_fet_fn(@ctxt_user,@ctxt_ouinstance,'ACAP','ACAPASSET','CRAUAS')

	select @workflow_app		= isnull(@workflow_app,'N')
	/*-------EPE-9198-------*/
	if (@workflow_app = 'Y')
	   select  @hdn_workflowsec  = 1

	   else 
	      select  @hdn_workflowsec  = 0
/*-------EPE-9198-------*/

	select  @sysdate			=	dbo.res_getdate(@ctxt_ouinstance)
	
	select	@company_code	=	company_code
	from	emod_ou_vw (nolock)
	where	ou_id			=	@ctxt_ouinstance
	and		@sysdate between effective_from and isnull(effective_to,@sysdate)
	
	select	@resval_tmp		    =  parameter_code
	from	cps_processparam_sys (nolock)
	where	company_code	    = @company_code
	AND 	parameter_type	    = 'FASYS' 
	AND		parameter_category  = 'RESVALAPP'
	
	if @resval_tmp is null
	begin
		select @resval_tmp = 'N'
		
	end
	/*-------EPE-9198-------*/
	if(@resval_tmp = 'N')
	select @hdn_residualvalue =0
	else 
	select @hdn_residualvalue =1
	/*-------EPE-9198-------*/
	select	@allmodresval_tmp	= parameter_code
	from	fin_processparam_sys i(nolock)
	where	company_code 		= @company_code
	and		component_id 		= 'ADEP'
	and     parameter_type		= 'PROPAR'
	and		parameter_category	= 'ALLMODRESVAL'	

	if @allmodresval_tmp is null
	begin
		select @allmodresval_tmp = 'N'
	end

	select	@usefulllife_tmp    =  parameter_code
	from	fin_processparam_sys (nolock)
	where	company_code	    = @company_code
	and		component_id 		= 'ADEP'	
	AND 	parameter_type	    = 'PROPAR' 
	AND		parameter_category  = 'ALLMODUSEFULLIFE'

	if @usefulllife_tmp is null
	begin
	    select @usefulllife_tmp = 'N'
	    
	end
	/*-------EPE-9198-------*/
	if( @usefulllife_tmp = 'N')
	select @hdn_usefullife  = 0
	else 
		select @hdn_usefullife  = 1

	/*-------EPE-9198-------*/
	if @resval_tmp = 'Y' and @allmodresval_tmp = 'Y'
	begin
		select @res_state	=	'Y'
		select @hdn_residualvalue =1-------EPE-9198
	end
	else
	begin
		select @res_state	=	'N'
		select @hdn_residualvalue =0-------EPE-9198
	end
	
/*
	select @hdnrt_stcontrol =	case	when @res_state = 'N' and @usefulllife_tmp = 'N'  AND	@workflow_app = 'N' then 'ResOffUseLifeOff'
										when @res_state = 'N' and @usefulllife_tmp = 'Y'  AND	@workflow_app = 'Y' then 'ResOffUseLifeOn'
										when @res_state = 'Y' and @usefulllife_tmp = 'N'  AND	@workflow_app = 'N' then 'ResOnUseLifeOff'
										when @res_state = 'Y' and @usefulllife_tmp = 'Y'  AND	@workflow_app = 'Y' then 'ResOnUseLifeOn'
										when @res_state = 'N' and @usefulllife_tmp = 'N'  AND   @workflow_app = 'Y'	then 'ResOffUseLifeOffWFOn'
										when @res_state = 'N' and @usefulllife_tmp = 'Y'  AND   @workflow_app = 'N' then 'ResOffUseLifeOnWFOff'
										when @res_state = 'Y' and @usefulllife_tmp = 'N'  AND	@workflow_app = 'Y'	then 'ResOnUseLifeOffWFOn'
										when @res_state = 'Y' and @usefulllife_tmp = 'Y'  AND   @workflow_app = 'N' then 'ResOnUseLifeOnWFOff'
									else ''
								end */
	/* code added by Nithya S for the dts id 14H109_ACAP_00059 ends*/
	
	if @newtag	=	1
	begin
		select 	@tagnumber	= max(tag_number)
		from 	acap_asset_tag_dtl(nolock)
		where 	ou_id		= @ctxt_ouinstance
		and   	asset_number	= @assetnumber	
	end

	select 	@status 		= parameter_text
	from 	fin_quick_code_met (nolock)
	where 	component_id 		= 'ACAP'
	and 	parameter_category 	= 'AS_STA'
	and 	parameter_code 		= 'AM'
	and	language_id		= @ctxt_language

	/* code commented & added by Swetha for ACAPDMS412AT_000360 on 28/02/2006 */

	/*select 	@docnum	= cap_number
	from 	acap_asset_doc_tmp (nolock)
	where 	guid	= @guid*/

	--Code  Commented & Added by Ravikrishnan on 07/Aug/2006 for Base Bug id:- ACAPDMS412AT_000490
	/*select @cap_number   = cap_number
	from	acap_asset_tag_dtl(nolock)
	where 	ou_id		= @ctxt_ouinstance
	and   	asset_number	= @assetnumber	
	and	tag_status	= 'AM'*/

	select  @cap_number	= rtrim(notes_desc)
	from	acap_notes_tmp(nolock)
	where	guid		= @guid


	--Code  Commented & Added by Ravikrishnan on 07/Aug/2006 for Base Bug id:- ACAPDMS412AT_000490		

/* Code added by Esther J on 18/05/2007 for defect ACAPDMS412AT_000710 starts */
	select @depcategory = '' 
	from acap_asset_hdr A(nolock),	ainf_asset_class_vw D (nolock)
	where 	A.ou_id			= @ctxt_ouinstance
	and   A.asset_number		= @assetnumber
	and   A.fb_id			= @fb
	and 	D.ou_id 		= A.ou_id
	and 	D.asset_class_code      = A.asset_class
	and 	D.dest_component 	= 'ACAP'  
	and 	D.depreciable	 	= 'N'
/* Code added by Esther J on 18/05/2007 for defect ACAPDMS412AT_000710 ends */

	/* code commented & added by Swetha for ACAPDMS412AT_000360 on 28/02/2006 */
	
	--EBS-1924
	   if exists (  select 'x'
					from   dim_maintain_dtls (nolock)
					where  company_code in (@company_code , '##')			
				  )

		begin 
			exec	acap_dim_populate_sp
			@ctxt_language,
			@ctxt_ouinstance,
			@ctxt_service,
			@ctxt_user,
			@cap_number,
			@ctxt_ouinstance,
			'FA_ACAP'	
		end 
  --EBS-1924

  
	select 	ltrim(rtrim(h.asset_class ))				'assetclass',
		ltrim(rtrim(h.asset_desc ))						'assetdescription',
		ltrim(rtrim(h.asset_group ))					'assetgrpnum',
		ltrim(rtrim(d.asset_location ))					'assetlocation',
		ltrim(rtrim(@assetnumber ))						'assetnumber',
		--ltrim(rtrim(@barcode ))							'barcode', --EPE-66921
		ltrim(rtrim(bar_code ))							'barcode', --EPE-66921
		@businessuse									'businessuse',
		ltrim(rtrim(convert(nvarchar(10),@capitalizationdate,120)))			'capitalizationdate',
		ltrim(rtrim(d.cost_center ))					'costcenter',
		ltrim(rtrim(convert(nvarchar(10),d.createddate,120)))	'createddate',
		ltrim(rtrim(d.createdby ))						'creationby',
		ltrim(rtrim(@custodian ))						'custodian',
		ltrim(rtrim(isnull(d.depr_category,@depcategory)))	'depcategory',  --ACAPDMS412AT_000710
		/* code modified by Swetha for ACAPDMS412AT_000360 on 28/02/2006 */
		ltrim(rtrim(@cap_number))						'capitalizationnumber',
		/* code modified by Swetha for ACAPDMS412AT_000360 on 28/02/2006 */
		ltrim(rtrim(h.fb_id ))							'fb',
		ltrim(rtrim(@guid ))							'guid',
		/* code modified by Swetha for ACAPDMS412AT_000374 on 28/02/2006 */
		ltrim(rtrim(convert(nvarchar(10),isnull(@inservicedate,inservice_date),120)))	'inservicedate',
		/* code modified by Swetha for ACAPDMS412AT_000374 on 28/02/2006 */
		ltrim(rtrim(@manufacturer ))					'manufacturer',
		ltrim(rtrim(@model ))							'model',
		ltrim(rtrim(@newtag ))							'newtag',
		ltrim(rtrim(@notypeno ))						'notypeno',
		--@salvagevalue									'salvagevalue',EPE-47098
		salvage_value									'salvagevalue',
		ltrim(rtrim(@serialnumber)) 					'serialnumber',
		@proposalnumber									'proposalnumber' ,
		@status											'status' ,
		@tagcost 										'tagcost',
		ltrim(rtrim(tag_desc)) 							'tagdescription',
		ltrim(rtrim(@tagnumber)) 						'tagnumber',
		ltrim(rtrim(@timestamp)) 						'timestamp',
		ltrim(rtrim(@warrentynumber)) 					'warrentynumber',
		@invcyclemlenn						'invcyclemlenn',	--code added by vijayan.j for the bugid:ES_ACAP_00015
		d.residualvalue                      'RESIDUALVALUE',		--Code added by Damodharan. R for Defect ID 14H109_ADEPP_00004 
		d.usefullifeinmonths                 'USEFULLIFEINMONTHS'	--Code added by Damodharan. R for Defect ID 14H109_ADEPP_00004
		/*Code added for the defect id : 14H109_ACAP_00059 starts here */ 		
		,dbo.wf_metadesc_fet_fn('ACAPAMASS',h.workflow_status)		'workflowstatus', --14H109_ACAP_00059
		@hdnrt_stcontrol				'hdnrt_stcontrol' ,
		/*Code added for the defect id : 14H109_ACAP_00059 ends here */	
		/*code modified for EPE-8428 - Harithra*/
		d.LAccount_code 'accountcode', 
		d.LAccount_desc 'accountdescription', 
		d.Lcost_center 'lscostcentre', 
		d.LAnalysis_code 'analysiscode', 
		d.LSubAnalysis_code 'subanalysiscode',
		@transaction_type    'transaction_type', --EBS-1924
		@hdn_residualvalue	'hdn_residuallife',--EPE-9198 
		@hdn_usefullife	 'hdn_userfullife', --EPE-9198
		@hdn_workflowsec	'hdn_workflowsec' --EPE-9198
		---EPE-11335
		,asset_classification 'assetclassification', 
		ltrim(rtrim(isnull(d.asset_category,@assetcategory)))	 'assetcategory', 
		ltrim(rtrim(isnull(d.asset_category,@assetcluster)))	 'assetcluster'
		---EPE-11335
		--epe-23559
		,(Select	parameter_text
		from    fin_quick_code_met(nolock)
		where   component_id		 =      'ACAP'     
		and		parameter_type		 =      'CBO' 
		and	    parameter_category	 =		'NAT_SFT'
		and		parameter_code = d.natureofshift
		and	    language_id			 =		 @ctxt_language)			'natureofshift'
		--epe-23559
		,salvage_valper						'salvageper'--EPE-43676
	from 	acap_asset_hdr h(nolock),
		acap_asset_tag_dtl d(nolock)
	where 	h.ou_id		= @ctxt_ouinstance
	and   	h.asset_number	= @assetnumber
	and   	d.ou_id		= @ctxt_ouinstance
	and   	d.asset_number	= @assetnumber
	and   	d.tag_number	= @tagnumber
	/* code modified by Swetha for ACAPDMS412AT_000360 on 28/02/2006 */
	and	h.cap_number	= d.cap_number
	/* code modified by Swetha for ACAPDMS412AT_000360 on 28/02/2006 */

         select  @m_errorid = 3459493
     
    delete from acap_asset_tmp 	where guid = @guid     
	delete from acap_asset_doc_tmp 	where guid = @guid
	delete from acap_asset_line_tmp where guid = @guid	
	delete from acap_doc_dtl_tmp 	where guid = @guid	
	delete from acap_asset_info_tmp where guid = @guid	

	--Code  Added by Ravikrishnan on 07/Aug/2006 for Base Bug id:- ACAPDMS412AT_000490
	delete from acap_notes_tmp	where guid = @guid
	--Code  Added by Ravikrishnan on 07/Aug/2006 for Base Bug id:- ACAPDMS412AT_000490
	set nocount off
end

