/*$File_version=MS4.3.0.13$*/
/*$file name : acapamasmspfethdrfetch.sql*/
/*$version   : 4.0.0.03*/
/*==================================================
   stored procedure : acapamasmspfethdrfetch
   method           : acapamasmmtfethdrfetch
   author           : Balamurali S
   created on       : 26 may 2001 13:34:40:250
   created at       : s4141
   generated by     : fpuser


   Modified By	    : Kavitha R
   Date		    :04/10/2004
   Purpose	    : ACAPFIN41CT_000132 

   Modified By	    : Kavitha R
   Date		    :04/10/2004
   Purpose	    : ACAPFIN41CT_000132 

   modified by  :    Saurabh mathur                                                           
   date         :    13th Oct 2004                                                           
   description  :    ACAPFIN41CT_000136  

    Modified By		: Sangeetha Sitaraman
    Date		: 13-01-2006
    Purpose		: For FA revamp(for earlier version of the SP pls.refer VSS) 

      		
	Esther		14/2/2014				13H120_General_00032 ;13H120_ACAP_00002 	
 proc  acapamasmspfethdrfetch
declare @P1 int
set @P1=0
exec acapamasmspfethdrfetch 1, '2', 'acapamasmsrfet', 'fin2user', '~#~', '~#~', '~#~', '~#~', '~#~', -915, @P1 output
select @P1
grant exec on acapamasmspfethdrfetch to public*/
/*  Damodharan. R	04/12/2014     14H109_ADEPP_00004                  */ 
/*	Nithya s			 14/08/2015		 14H109_ACAP_00059					 */
/*  Aditya S		22/05/2017			ZHE-562							*/		
/*  Harithra		 17-08-2018         EPE-8428                             */
/*  Abinaya V		 07-09-2018         EBS-1924         */
/*  Harithra		 03-09-2018         EPE-8428                             */
/*	Uma Maheshwari M				18-09-2018				EPE-9198		*/
/*  Amrutha R.S						28/12/2018				EPE-11283:EPE-11455		*/ 
/*Amani.P						10.01.2019		EPE-11335*/
--gokul M			12-11-2020			epe-23559
/*Mabel Rita L      17/02/2022          TC-292           */
/*Nithya S			05/04/2022			EPE-43676	  */
/*Aditya S			02/03/2023			TC-1174		  */
/*====================================================*/
create procedure acapamasmspfethdrfetch
	@ctxt_language   		fin_ctxt_language  ,
	@ctxt_ouinstance   		fin_ctxt_ouinstance  ,
	@ctxt_service   		fin_ctxt_service  ,
	@ctxt_user   			fin_ctxt_user  ,
	@capitalizationdate		fin_date ,
	@depcategory   			fin_depcategory  ,
	@fb   				    fin_financebookid  ,
	@guid   			    fin_guid  ,
	@invcyclemlenn			fin_desc40,
	@numbering_type_no   	fin_notypeno  ,
	@timestamp   			fin_timestamp  ,
	@assetclass			    fin_assetclass,
	@tagcost			    fin_amount,
	@proposalnumber			fin_documentnumber,
	@assetclassification 	desc255, --Input/Output
	@assetcategory       	desc255, --Input/Output
	@assetcluster        	desc255, --Input/Output	
	@NatureOfShift			fin_flag,	--epe-23559
	@stNatureOfShift		fin_rowno,		--epe-23559
	@m_errorid  			fin_int output 
as
begin
	-- nocount should be switched on to prevent phantom rows 
	set nocount on
	
	-- @m_errorid should be 0 to indicate success
	select @m_errorid =0
	
	declare	@errmsg     				fin_desc255,
			@m_flag						fin_flag,
			@adepou						fin_ctxt_ouinstance
			,@hdnrt_stcontrol			udd_ctxt_state_name,	--Code added for Defect ID 14H109_ADEPP_00004
			@hdnparamete_state_tmp		fin_number,
/*code modified for EPE-8428 - Harithra*/
			@hdnparamete_tmp			fin_flag ,
			@sysdate					fin_Date,
			@company_code				fin_company,
			@resval_tmp					fin_paramcode,
			@usefulllife_tmp			fin_desc40,
			@hdn_residualvalue			fin_desc255, 
			@hdn_usefullife				fin_desc255, 
			@hdn_workflowsec			fin_desc255
			,@residualvalue      	    fin_depprecent --EPE-11455
			,@shift_applicable		fin_paramcode  	--EPE-23559 
			,@ainfou 		            fin_ctxt_ouinstance     --TC-292
			,@salvageper				fin_amount--EPE-43676
	if @ctxt_language = -915 
		select @ctxt_language = null
	if @ctxt_ouinstance = -915 
		select @ctxt_ouinstance = null
	select @ctxt_service = ltrim(rtrim(@ctxt_service))
	if @ctxt_service = '~#~' 
	select @ctxt_service = null
		select @ctxt_user = ltrim(rtrim(@ctxt_user))
	if @ctxt_user = '~#~' 
		select @ctxt_user = null
	select @depcategory = ltrim(rtrim(@depcategory))
	if @depcategory = '~#~' 
		select @depcategory = null
	select @fb = ltrim(rtrim(@fb))
	if @fb = '~#~' 
		select @fb = null
	select @guid = ltrim(rtrim(@guid))
	if @guid = '~#~' 
		select @guid = null
	select @numbering_type_no = ltrim(rtrim(@numbering_type_no))
	if @numbering_type_no = '~#~' 
		select @numbering_type_no = null
	if @timestamp = -915 
		select @timestamp = null
	if @capitalizationdate = '1900/01/01'
		select @capitalizationdate = null
	select @assetclass = ltrim(rtrim(@assetclass))
	if @assetclass = '~#~' 
		select @assetclass = null
	if @tagcost = -915 
		select @tagcost = null
	select @proposalnumber = ltrim(rtrim(@proposalnumber))
	if @proposalnumber = '~#~' 
		select @proposalnumber = null
	--EPE-11335
	select @assetclassification  = ltrim(rtrim(@assetclassification))
	select @assetcategory        = ltrim(rtrim(@assetcategory))
	select @assetcluster         = ltrim(rtrim(@assetcluster))

	IF @assetclassification = '~#~' 
		Select @assetclassification = null  

	IF @assetcategory = '~#~' 
		Select @assetcategory = null  

	IF @assetcluster = '~#~' 
		Select @assetcluster = null  

	--EPE-23559
	select @NatureOfShift         = ltrim(rtrim(@NatureOfShift))

	IF @NatureOfShift = '~#~' 
		Select @NatureOfShift = null  

	IF @stNatureOfShift = '-915' 
		Select @stNatureOfShift = null  
	--EPE-23559

	select  @sysdate			=	dbo.res_getdate(@ctxt_ouinstance)
	 
	select	@company_code	=	company_code
	from	emod_ou_vw (nolock)
	where	ou_id			=	@ctxt_ouinstance
	and		@sysdate between effective_from and isnull(effective_to,@sysdate)

	declare @workflow_app		fin_metadata_code

	select @workflow_app		= dbo.workflowapp_fet_fn(@ctxt_user,@ctxt_ouinstance,'ACAP','ACAPASSET','CRAUAS')

	select @workflow_app		= isnull(@workflow_app,'N')
	/*-------EPE-9198-------*/
	if (@workflow_app = 'Y')
	   select  @hdn_workflowsec  = 1

	   else 
	      select  @hdn_workflowsec  = 0
    /*-------EPE-9198-------*/

	select	@resval_tmp		    =  parameter_code,
			@residualvalue		= parameter_value	--EPE-11455
	from	cps_processparam_sys (nolock)
	where	company_code	    = @company_code
	AND 	parameter_type	    = 'FASYS' 
	AND		parameter_category  = 'RESVALAPP'
	and     language_id         = @ctxt_language	--EPE-11455

	 if @resval_tmp is null
		begin
			select @resval_tmp = 'N'
	end
	/*-------EPE-9198-------*/
	if(@resval_tmp='N')
			select @hdn_residualvalue =0
	else 
			select @hdn_residualvalue =1
  /*-------EPE-9198-------*/

	
	select	@usefulllife_tmp    =  parameter_code
	from	fin_processparam_sys (nolock)
	where	company_code	    = @company_code
	and		component_id 		= 'ADEP'	
	AND 	parameter_type	    = 'PROPAR' 
	AND		parameter_category  = 'ALLMODUSEFULLIFE'
	
	if @usefulllife_tmp is null
			begin
				select @usefulllife_tmp = 'N'
			end
			/*-------EPE-9198-------*/
		if (@usefulllife_tmp = 'N')
			select @hdn_usefullife  = 0
		else 
			select @hdn_usefullife  = 1
           /*-------EPE-9198-------*/


	select 	@adepou	 	 	 = destinationouinstid  
	from  	fw_admin_view_comp_intxn_model (nolock)
	where  	sourcecomponentname      = 'ACAP'
	and    	sourceouinstid           = @ctxt_ouinstance
	and    	destinationcomponentname = 'ADEP'

	select 	@m_flag		= multi_flag,
		@fb 		= fb_id ,
		@assetclass	= asset_class,		
		@proposalnumber	= proposal_number
	from 	acap_asset_doc_tmp(nolock)
	where	guid		= @guid

	select 	@tagcost	= sum(cap_amount)
	from 	acap_asset_doc_tmp(nolock)
	where	guid		= @guid

		
 if(select count(doc_number) from acap_asset_doc_tmp(nolock)
			where guid 		= @guid 
			and pending_cap_amt	<> cap_amount)> 0
	begin
		if @m_flag = 'P'
		begin
			--raiserror('Perform the compute task in the select document details page',16,1)
			select @m_errorid = 900004493
			return
		end

		if exists (select 'x' from acap_asset_line_tmp(nolock)
		    		where guid = @guid and line_no >1) and (isnull(@m_flag,'N')= 'N')
		begin
			--Document has more than one line item.Pls.visit the select document page
			select @m_errorid = 39304128
        		return
		end
	end

	--ZHE-562	
	--if (isnull(@m_flag,'N')= 'N')			--TC-1174
	if (isnull(@m_flag,'N') in ('N','P') )  --TC-1174
	begin
			if exists
			(
				select 'x'
				from acap_asset_line_tmp(nolock)
				where guid = @guid
				group by doc_number
				having count(line_no) > 1
			)
			begin
					--TC-1174
					if @m_flag = 'P'	 
					begin
						--raiserror('Perform the compute task in the select document details page',16,1)
						select @m_errorid = 900004493
						return
					end
					else
					begin
					--TC-1174
						select @m_errorid = 39304128
        				return
					end --TC-1174
			end	
	end 
	--ZHE-562	


	select 	@numbering_type_no 	= ltrim(rtrim(no_type)) 
	from 	dnm_trans_notype_vw(nolock)
	where   ouinstance 		= @ctxt_ouinstance
	and	trantype_code 		= 'FA_ACAP'
	and     no_type   		<> '~MANUAL~'
	and	default_type		= 'Y'
	
	select 	@depcategory 		= min(depr_category)
	from 	adep_depr_category_vw a(nolock) 
	where 	a.asset_class 		= @assetclass
	and 	a.ou_id			= @adepou
	AND     a.depr_cat_status	= 'A' 
	
	
	
		-- code added for 13H120_General_00032 ;13H120_ACAP_00002 	 starts 
	declare @asset_no		fin_assetnumber,
			@tag_no			fin_assettagno,
			@asset_desc		fin_desc40,
			@tag_desc		fin_desc40,
			@count			fin_int,
			@cost_center	fin_costcenter
	
	if exists (select 'x' 	from 	acap_asset_doc_tmp tmp (nolock),  eam_workorder_cost_detail eam(nolock)
				where	tmp.guid			= @guid
				and tmp.doc_type			= 'EAM_WGDIR'
				and eam.wo_ouinstance		= tmp.ou_id
				and eam.wo_code				= tmp.doc_number
				)
	begin
		select @count =  count (distinct(isnull(asset_number,'')))
		from 	acap_asset_doc_tmp tmp (nolock),  eam_workorder_cost_detail eam(nolock)
		where	tmp.guid			= @guid
		and tmp.doc_type			= 'EAM_WGDIR'
		and eam.wo_ouinstance		= tmp.ou_id
		and eam.wo_code				= tmp.doc_number
		
		if @count >  1
		begin
			--Work orders having more than one asset tag cannot be combined. Modify selection.
			exec fin_german_raiserror_sp 'ACAP',@ctxt_language,504
			return
		end
		else
		begin	
		
				select @asset_no  = wo_fixed_asset_code,
						@tag_no   = wo_asset_tag_code
				from 	acap_asset_doc_tmp tmp (nolock),  eam_workorder_cost_detail eam(nolock)
				where	tmp.guid			= @guid
				and tmp.doc_type			= 'EAM_WGDIR'
				and eam.wo_ouinstance		= tmp.ou_id
				and eam.wo_code				= tmp.doc_number
						 
				select 	@asset_desc	= asset_desc,
						@tag_desc   = tag_desc 
				from acap_asset_tag_dtl (nolock)
				where  asset_number = @asset_no
				and tag_number		= @tag_no
					
				select  @assetclass	= asset_class,
						@cost_center = cost_center
				from acap_asset_hdr (nolock)
				where  asset_number = @asset_no 
	 	end 
	end
	-- code added for 13H120_General_00032 ;13H120_ACAP_00002 	 ends
	/*code modified for EPE-8428 - Harithra*/

		--code for EPE-11455 begins here
	if exists (select 'X'
	           from   ainf_asset_class_mst (nolock)
			   where  asset_class_code	 =  @assetclass		
			   and    ou_id				 =	@ctxt_ouinstance
			   and    asset_Class_status = 'A'
			   and    residual_val        is not null
			   )
	begin	
		select @residualvalue		=  residual_val
		from   ainf_asset_class_mst (nolock)
		where  asset_class_code		=  @assetclass
		and    ou_id				=  @ctxt_ouinstance
		and    asset_Class_status   = 'A'
	end	
	--code for EPE-11455 ends here

	select @hdnparamete_tmp = parameter_code 
	from cps_processparam_sys
	where company_code  = @company_code
	and	language_id   = @ctxt_language
	and	parameter_type = 'FASYS'
	and parameter_category = 'MANENTWOREFDOC'
	
	if @hdnparamete_tmp = 'Y'
		select @hdnparamete_state_tmp = 1
    else
		select @hdnparamete_state_tmp = 0

	if exists (	select	'x' 
			from	acap_asset_doc_tmp (nolock)
			where	guid	= @guid
			)
	select @hdnparamete_state_tmp = 0	

	select @hdnrt_stcontrol = 'ResOffUseLifeOff'	--Code added for Defect ID 14H109_ADEPP_00004

	---EPE-11335
	select  distinct top 1  @AssetClassification = Asset_Classification
	from  adep_entity_depcat_map (nolock)
	where asset_class = @assetclass
	and   ou_id		  =	@ctxt_ouinstance

	select  distinct top 1 @assetcategory	= Asset_Category ,
			@assetcluster   = asset_cluster   
	from  adep_entity_depcat_map (nolock)
	where asset_class = @assetclass
	and   ou_id		  =	@ctxt_ouinstance	
	 
	---EPE-11335
	--TC-292
	select 	@ainfou 			        =  destinationouinstid
	from 	fw_admin_view_comp_intxn_model  (nolock)
    where 	sourceouinstid 			    = @ctxt_ouinstance
	and 	sourcecomponentname 		= 'ACAP'
	and 	destinationcomponentname 	= 'AINF'
	--TC-292
	--EPE-23559  starts
	select @shift_applicable  = shift_applicable
	from   ainf_asset_class_mst(NOLOCK)
	where  ou_id               = isnull(@ainfou,@ctxt_ouinstance) --TC-292
	and    asset_class_code    = @assetclass

	if @shift_applicable = 'Y'
	begin 
		select @stnatureofshift = 1
	end
	else
	begin
		select @stnatureofshift = 0
	end		
	--EPE-23559  ends

	/*code added for the Defect id : EPE-43676 starts here	*/
	if exists (select 'X'
	           from   ainf_asset_class_mst (nolock)
			   where  asset_class_code	 =  @assetclass		
			   and    ou_id				 =	@ctxt_ouinstance
			   and    asset_Class_status = 'A'
			   and    salvage_per        is not null
			   )
	begin	
		select @salvageper			=  salvage_per
		from   ainf_asset_class_mst (nolock)
		where  asset_class_code		=  @assetclass
		and    ou_id				=  @ctxt_ouinstance
		and    asset_Class_status   = 'A'
	end	
	/*code added for the Defect id : EPE-43676 ends here	*/

	select 	@capitalizationdate				'capitalizationdate' ,
		ltrim(rtrim(@depcategory)) 			'depcategory',
		@fb									'fb' ,
		@guid								'guid' ,
		@invcyclemlenn 						'invcyclemlenn' ,
		@numbering_type_no 					'numbering_type_no' ,
		@timestamp							'timestamp',
		@assetclass							'assetclass',
		@tagcost 							'tagcost',
		@proposalnumber						'proposalnumber'
		-- code added for 13H120_General_00032 ;13H120_ACAP_00002 	 starts 
		,@asset_no						    'assetnumber',
		@asset_desc							'assetdescription',
		@tag_no								'tagnumber',
		@tag_desc							'tagdescription',
		@cost_center						'costcenter',
		@residualvalue	                    'RESIDUALVALUE',		--EPE-11455 --Code added for Defect ID 14H109_ADEPP_00004 
		NULL								'USEFULLIFEINMONTHS',	--Code added for Defect ID 14H109_ADEPP_00004
		@hdnrt_stcontrol                    'hdnrt_stcontrol',
		dbo.wf_metadesc_fet_fn('ACAPAMASS',null) 'workflowstatus',--14H109_ACAP_00059
-- code added for 13H120_General_00032 ;13H120_ACAP_00002 	 ends 
/*code modified for EPE-8428 - Harithra*/
		null 'accountcode', 
		null 'accountdescription', 
		null 'lscostcentre', 
		null 'analysiscode', 
		null 'subanalysiscode', 
		@hdnparamete_state_tmp 'hdnparamete_state',
		1	 'Hdn_Image_state',
		'FA_ACAP'              'transaction_type', --EBS-1924
		/*-------EPE-9198-------*/
		@hdn_residualvalue 'hdn_residuallife', 
		@hdn_usefullife 'hdn_userfullife', 
		@hdn_workflowsec 'hdn_workflowsec'
		/*-------EPE-9198-------*/
		--EPE-11335
		,@assetclassification 'assetclassification', 
		@assetcategory 'assetcategory', 
		@assetcluster 'assetcluster'
		--EPE-11335
		--EPE-23559
		,(Select	parameter_text
		from    fin_quick_code_met(nolock)
		where   component_id		 =      'ACAP'     
		and		parameter_type		 =      'CBO' 
		and	    parameter_category	 =		'NAT_SFT'
		and		parameter_code = 'S'
		and	    language_id			 =		 @ctxt_language)			'natureofshift'
		,@stnatureofshift	'stnatureofshift'
		--EPE-23559
		,@salvageper			'salvageper'--EPE-43676
	set nocount off
end








 

