/*$File_version=ms4.3.0.009$*/
/*$file name : acapapaddbspblkasthdrchk.sql*/
/*$version   : 4.0.0.005*/
/*==================================================
   stored procedure : acapapaddbspblkasthdrchk
   method           :acapapaddbmtblkasthdrchk
   author           : functional proto ver 1.0
   created on       : 02 mar 2002 00:51:35:640
   created at       : s4141
   generated by     : suman
   modified by      : Prasad
   modified date    : 24/07/2003-09/08/2003

   modified by		: Sangeetha Sitaraman
   date			: 30/12/2005
   Purpose		: SIN_ACAP revamp(for earlier version of the sps pls refer to VSS) 

   modified by		: Sangeetha Sitaraman
   date			: 25/01/2006
   Purpose		: ACAPDMS412AT_000257
*/
/*Modified by		Date			Remarks				*/
/*Muthu V		4/28/04			For German Support		*/
/*Uma Maheswari		24th Jan 2007		ACAPDMS412AT_000574		*/
/*Uma Maheswari		22nd Dec 2009		ES_ACAP_00103			*/
/*Paneer Selvam 	07/11/2017			ZHE-942					*/  
/*Balaji C			26/04/2019			TLET-402				*/
/*Ashok V			07/01/2020			DA-232					*/
/*Aditya S			20/01/2021			TEIE-597				*/
/*Aditya S			13/10/2021			MHE-247					*/
/*Saranraj C	    28/11/2022			ADECCOUAT-1014		  */
/* Sai Kumar		17/09/2024		    EPE-88624                 */
/******************************************************************************************/
CREATE procedure acapapaddbspblkasthdrchk
		@assetclass   		fin_assetclass  ,
		@assetdescription   	fin_desc40  ,
		@assetnumber   		fin_assetnumber  ,
		@assettaginformation   	fin_subtitle  ,
		@ctxt_language   	fin_ctxt_language  ,
		@ctxt_ouinstance   	fin_ctxt_ouinstance  ,
		@ctxt_service   	fin_ctxt_service  ,
		@ctxt_user   		fin_ctxt_user  ,
		@guid   		fin_guid  ,
		@noofasset   		fin_number  ,
		@nooftag   		fin_number  ,
		@proposalnumber   	fin_documentnumber  ,
		@fprowno   		fin_rowno  ,
		@m_errorid  		fin_int output --to return execution status
as
begin

	/* Code added by Uma for the bug id : ACAPDMS412AT_000574 starts here*/
	--BEGIN of Standard code for getting precision type
	declare @pqty_tmp                  fin_int ,
		@pamt_tmp                  fin_int ,
		@prate_tmp                 fin_int ,
		@perate_tmp                fin_int ,
		@phigh_tmp                 fin_int ,
		@pmed_tmp                  fin_int ,
		@plow_tmp                  fin_int 
		--@invoicedate		fin_date,    --code commented Against EPE-88624 for sca rule
		--@basecurrency_tmp          fin_currencycode   --code commented Against EPE-88624 for sca rule
		
	exec fin_sp_precisiontype_rtr @pqty_tmp output, @pamt_tmp output,
		@prate_tmp output, @perate_tmp output, @phigh_tmp output,
		@pmed_tmp output, @plow_tmp output

	--END of Standard code for getting precision type
	/* Code added by Uma for the bug id : ACAPDMS412AT_000574 end here*/

	declare	@assetcost_tmp 		fin_amount,
		@assetcost1_tmp 	fin_amount,
		@fb_tmp			fin_financebookid,
		@acounterr_tmp		fin_int,
		@capitalizationnumber	fin_documentnumber,
		@today_tmp		fin_date,
		@assetnumberml   	fin_assetnumber  ,
		@tagnumber		fin_tagno,
		@costcenter		fin_costcentercode,
		@linecnt		fin_lineno,
		@assetno		fin_documentnumber,
		@capamt			fin_amount
		
		
		

	-- nocount should be switched on to prevent phantom rows 
	set nocount on
	-- @m_errorid should be 0 to indicate success
	select @m_errorid =0
	
	
	
	select @assetclass = ltrim(rtrim(@assetclass))
	if @assetclass = '~#~' 
		select @assetclass = null

	select @assetdescription = ltrim(rtrim(@assetdescription))
	if @assetdescription = '~#~' 
		select @assetdescription = null

	select @assetnumber = ltrim(rtrim(@assetnumber))
	if @assetnumber = '~#~' 
		select @assetnumber = null

	select @assettaginformation = ltrim(rtrim(@assettaginformation))
	if @assettaginformation = '~#~' 
		select @assettaginformation = null

	if @ctxt_language = -915 
		select @ctxt_language = null

	if @ctxt_ouinstance = -915 
		select @ctxt_ouinstance = null

	select @ctxt_service = ltrim(rtrim(@ctxt_service))
	if @ctxt_service = '~#~' 
		select @ctxt_service = null

	select @ctxt_user = ltrim(rtrim(@ctxt_user))
	if @ctxt_user = '~#~' 
		select @ctxt_user = null

	select @guid = ltrim(rtrim(@guid))
	if @guid = '~#~' 
		select @guid = null

	if @noofasset = -915 
		select @noofasset = null

	if @nooftag = -915 
		select @nooftag = null

	select @proposalnumber = ltrim(rtrim(@proposalnumber))
	if @proposalnumber = '~#~' 
		select @proposalnumber = null

	if @fprowno = -915 
		select @fprowno = null


	select @today_tmp = dbo.RES_Getdate(@ctxt_ouinstance)
  

	if @fprowno = 0 
	begin
		exec fin_sp_raise_error '', '', '', '','acap',6,@m_errorid output
	end 


	/*code added by sangeetha for the issue ACAPDMS412AT_000257 begin here*/
	if not exists(select 'x' from acap_asset_bulk_tmp(nolock)
			where 	guid		= @guid
			and	ou_id 		= @ctxt_ouinstance
			and 	asset_number 	= upper(@assetnumber))
	begin
		--raiserror('Atleast One Asset Number in the Multiline should be the Original Asset Number',16,1)
		select @m_errorid = 900004561
		return
	end
	/*code added by sangeetha for the issue ACAPDMS412AT_000257 end here*/


	/*Code Added By Saranraj for ADECCOUAT-1014 Starts Here*/
	declare @asset_num_tmp  fin_assetnumber;

	if exists (select 'x' from acap_asset_bulk_tmp (nolock)
				where guid = @guid
				and isnull(remarks,'') <> ''
				group by asset_number,ou_id
				having count(distinct remarks) > 1
			  )
	begin
		select @asset_num_tmp = asset_number 
		from acap_asset_bulk_tmp (nolock)
		where guid = @guid 
		and isnull(remarks,'') <> '' 
		group by asset_number,ou_id 
		having count(distinct remarks) > 1

		--raiserror('Remarks for asset <%s> does not match',16,1)
		exec fin_german_raiserror_sp 'ACAP',@ctxt_language,1900027514,@asset_num_tmp
		return
	end

	else
	begin
		update a
		set a.remarks =  b.remarks  
		from acap_asset_hdr a ,
		acap_asset_bulk_tmp b (nolock)
		where guid  = @guid
		and  a.asset_number=b.asset_number
		and  a.ou_id=b.ou_id
		and  isnull(b.remarks,'') <> '' 
	end

	/*Code Added By Saranraj for ADECCOUAT-1014 End Here*/

	--deleting records from temp table
	delete from acap_journal_accounting_tmp
	where guid = @guid

	--to get the asset cost
	select 	@assetcost1_tmp 	= isnull(wip_cost,0)
	from 	acap_wip_tmp(nolock)
	where 	ou_id 			= @ctxt_ouinstance
	and	guid    		= @guid
	and 	doc_number 		= @assetnumber

	select 	@assetcost_tmp 	= isnull(sum(tag_cost),0)
	from 	acap_asset_bulk_tmp(nolock)
	where 	guid 		= @guid
	and 	ou_id 		= @ctxt_ouinstance


	select 	@linecnt 	= count(line_no)
	from 	acap_asset_doc_line_dtl(nolock)
	where  	ou_id 		= @ctxt_ouinstance
	and 	asset_number 	= upper(@assetnumber)	

	/* Code added by Uma for the defect id : ES_ACAP_00103 Starts here*/
	if @ctxt_service = 'ACAPapAddBSrBlkAst'
	begin
		delete 
		from 	acap_accounting_info_dtl
		where 	ou_id 		= @ctxt_ouinstance
		and	asset_number	= @assetnumber
	end
	/* Code added by Uma for the defect id : ES_ACAP_00103 Ends here*/

	--TEIE-597
	create table #acap_doc_roundoff 
	(
		doc nvarchar(18) , 
		cap_amt	numeric(28,8),
		diff_amt	numeric(28,8),
		max_line		int
	)

	insert into #acap_doc_roundoff
	(
		doc,cap_amt
	)
	select doc_number, sum(Cap_amount)
	from acap_tag_doc_dtl(nolock)
	where 	ou_id 		= @ctxt_ouinstance
	and	asset_number	= @assetnumber
	and		tag_number =  1      --code added for EPE-88624
	group by doc_number

	update T
	set  max_line = A.Line
	from #acap_doc_roundoff T, 
	(
		select doc_number,max(line_no) 'Line'
		from acap_asset_doc_line_dtl(nolock)
		where 	ou_id 		= @ctxt_ouinstance
		and	asset_number	= @assetnumber
		group by doc_number
	)A
	where A.doc_number = T.doc
	--TEIE-597

	--MHE-247
	create table #acap_asset_roundoff 
	(
		doc nvarchar(18) , 
		asset nvarchar(18) , 
		tag_cost	numeric(28,8),
		diff_amt	numeric(28,8),
		max_line		int
	)

	insert into #acap_asset_roundoff
	(
		asset,tag_cost
	)
	select 	asset_number , isnull(sum(tag_cost),0)
	from 	acap_asset_bulk_tmp(nolock)
	where	guid	= @guid
	group by asset_number

	update T
	set  doc = doc_number
	from #acap_asset_roundoff T, 
		 acap_tag_doc_dtl A (nolock)
	where 	ou_id 		= @ctxt_ouinstance
	and	A.asset_number	= T.asset

	update T
	set  max_line = A.Line
	from #acap_asset_roundoff T, 
	(
		select doc_number,max(line_no) 'Line'
		from acap_asset_doc_line_dtl(nolock)
		where 	ou_id 		= @ctxt_ouinstance
		and	asset_number	= @assetnumber
		group by doc_number
	)A
	where A.doc_number = T.doc

	create table #acap_line_roundoff 
	(
		doc nvarchar(18) , 
		cap_amt	numeric(28,8),
		diff_amt	numeric(28,8),
		line		int
	)

	insert into #acap_line_roundoff
	(
		doc,cap_amt,line
	)
	select doc_number, sum(Cap_amount),line_no
	from acap_tag_doc_dtl(nolock)
	where 	ou_id 		= @ctxt_ouinstance
	and	asset_number	= @assetnumber
	and		tag_number =  1      --code added for EPE-88624
	group by doc_number,line_no
	--MHE-247


	declare doc_upd cursor
	for
	select 	asset_number , isnull(sum(tag_cost),0)
	from 	acap_asset_bulk_tmp
	where	guid	= @guid
	group by asset_number
	
	open doc_upd
	
	fetch next from doc_upd into @assetno,@capamt
	while @@fetch_status =0
	begin



		update 	acap_asset_doc_dtl with (rowlock)
		set 	cap_amount	= round((isnull(cap_amount,0) * @capamt)/@assetcost_tmp,@pamt_tmp)--code round() added for DA-232
		where 	ou_id 		= @ctxt_ouinstance
		and	asset_number	= @assetno

		update 	acap_asset_doc_line_dtl with (rowlock)
		set 	cap_amount	= round((isnull(cap_amount,0) * @capamt)/@assetcost_tmp,@pamt_tmp)--code round() added for DA-232
		where 	ou_id 		= @ctxt_ouinstance
		and	asset_number	= @assetno

		update  acap_tag_doc_dtl
		set 	cap_amount	= round((isnull(cap_amount,0) * isnull(tag_cost,0)) /(@assetcost_tmp),@pamt_tmp)--code round() added for DA-232
		where 	ou_id 		= @ctxt_ouinstance
		and	asset_number	= @assetno

		--TEIE-597
		/*
		declare acc_ins cursor
		for
		select 	cap_number, asset_number,tag_number,fb_id,cost_center
		from 	acap_asset_tag_dtl (nolock)
		where 	ou_id 		= @ctxt_ouinstance
		and 	asset_number 	= @assetno
		open acc_ins
		
		fetch next from acc_ins into @capitalizationnumber,@assetnumberml,@tagnumber,@fb_tmp,@costcenter
		
		while @@fetch_status=0
		begin
			
				
			exec acapaccountingpost	@ctxt_language  ,@ctxt_ouinstance ,
						@ctxt_service,@ctxt_user ,@assetclass,
						@fb_tmp,@capitalizationnumber,@today_tmp,@today_tmp,
						'FA_ACAP',@assetnumberml,@tagnumber,0,@costcenter,'AST',@acounterr_tmp output
				
			if isnull(@acounterr_tmp,0) <> 0
			begin
				exec fin_sp_raise_error '', '', '', '','ACAP',@acounterr_tmp,@m_errorid output		
				close 		acc_ins
				deallocate	acc_ins
				return
			end	
			fetch next from acc_ins into @capitalizationnumber,@assetnumberml,@tagnumber,@fb_tmp,@costcenter
		end
		close 		acc_ins
		deallocate	acc_ins
		*/
		--TEIE-597

		fetch next from doc_upd into @assetno,@capamt
	end
	close doc_upd
	deallocate doc_upd	

	--MHE-247
	update T
	set  diff_amt = T.tag_cost - A.tag_cost_new
	from #acap_asset_roundoff T, 
	(
		select asset_number,sum(cap_amount) as tag_cost_new
		from acap_tag_doc_dtl(nolock)
		where 	ou_id 		= @ctxt_ouinstance
		and	asset_number	in (select asset_number from acap_asset_bulk_tmp(nolock)	where	guid	= @guid)
		group by asset_number
	)A
	where A.asset_number = T.asset

	if exists 
	(
		select 'x'
		from #acap_asset_roundoff
		where diff_amt <> 0
	)
	begin
		update 	T  
		set 	cap_amount	= cap_amount + diff_amt
		from acap_asset_doc_line_dtl T,
		#acap_asset_roundoff 
		where 	ou_id 		= @ctxt_ouinstance
		and	asset_number	= asset
		and	doc_number = doc
		and line_no = max_line

		update 	T  
		set 	cap_amount	= cap_amount + diff_amt
		from acap_tag_doc_dtl T,
		#acap_asset_roundoff 
		where 	ou_id 		= @ctxt_ouinstance
		and	asset_number	= asset
		and	doc_number = doc
		and line_no = max_line
 
	end		 

	update T
	set  diff_amt = T.cap_amt - A.cap_new
	from #acap_line_roundoff T, 
	(
		select doc_number,sum(cap_amount) as cap_new , line_no
		from acap_tag_doc_dtl(nolock)
		where 	ou_id 		= @ctxt_ouinstance
		and	asset_number	in (select asset_number from acap_asset_bulk_tmp(nolock)	where	guid	= @guid)
		group by doc_number,line_no
	)A
	where A.doc_number = T.doc
	and  A.line_no = T.line
	 
	 
	if exists 
	(
		select 'x'
		from #acap_line_roundoff
		where diff_amt <> 0
	)
	begin
		update 	T  
		set 	cap_amount	= cap_amount + diff_amt
		from acap_asset_doc_line_dtl T,
		#acap_line_roundoff 
		where 	ou_id 		= @ctxt_ouinstance
		and	asset_number	= @assetnumber
		and	doc_number = doc
		and line_no = line

		update 	T  
		set 	cap_amount	= cap_amount + diff_amt
		from acap_tag_doc_dtl T,
		#acap_line_roundoff 
		where 	ou_id 		= @ctxt_ouinstance
		and	asset_number	= @assetnumber
		and	doc_number = doc
		and line_no = line
 
	end	
	--MHE-247

	--TEIE-597
	update T
	set  diff_amt = T.cap_amt - A.cap_new
	from #acap_doc_roundoff T, 
	(
		select doc_number,sum(cap_amount) as cap_new
		from acap_tag_doc_dtl(nolock)
		where 	ou_id 		= @ctxt_ouinstance
		and	asset_number	in (select asset_number from acap_asset_bulk_tmp(nolock)	where	guid	= @guid)
		group by doc_number
	)A
	where A.doc_number = T.doc
	 
	if exists 
	(
		select 'x'
		from #acap_doc_roundoff
		where diff_amt <> 0
	)
	begin
		update 	T  
		set 	cap_amount	= cap_amount + diff_amt
		from acap_asset_doc_line_dtl T,
		#acap_doc_roundoff 
		where 	ou_id 		= @ctxt_ouinstance
		and	asset_number	= @assetnumber
		and	doc_number = doc
		and line_no = max_line

		update 	T  
		set 	cap_amount	= cap_amount + diff_amt
		from acap_tag_doc_dtl T,
		#acap_doc_roundoff 
		where 	ou_id 		= @ctxt_ouinstance
		and	asset_number	= @assetnumber
		and	doc_number = doc
		and line_no = max_line
 
	end	

	declare acc_ins cursor
	for
	select 	cap_number, asset_number,tag_number,fb_id,cost_center
	from 	acap_asset_tag_dtl (nolock)
	where 	ou_id 		= @ctxt_ouinstance
	and 	asset_number 	in (select asset_number from acap_asset_bulk_tmp(nolock)	where	guid	= @guid)

	open acc_ins
		
	fetch next from acc_ins into @capitalizationnumber,@assetnumberml,@tagnumber,@fb_tmp,@costcenter
		
	while @@fetch_status=0
	begin
					
			exec acapaccountingpost	@ctxt_language  ,@ctxt_ouinstance ,
						@ctxt_service,@ctxt_user ,@assetclass,
						@fb_tmp,@capitalizationnumber,@today_tmp,@today_tmp,
						'FA_ACAP',@assetnumberml,@tagnumber,0,@costcenter,'AST',@acounterr_tmp output
				
			if isnull(@acounterr_tmp,0) <> 0
			begin
				exec fin_sp_raise_error '', '', '', '','ACAP',@acounterr_tmp,@m_errorid output		
				close 		acc_ins
				deallocate	acc_ins
				return
			end	
			fetch next from acc_ins into @capitalizationnumber,@assetnumberml,@tagnumber,@fb_tmp,@costcenter
	end
	close 		acc_ins
	deallocate	acc_ins
	--TEIE-597
	

	--TLET-402 starts
	if	@ctxt_service	not in	('acapapaddbsrblkast')
	begin
	--TLET-402 ends
	/*Code added by Uma for the bug id : ACAPDMS412AT_000574 starts here*/
		declare	@salvage_value_tmp	fin_amount
		declare	@asset_count		fin_int
		declare	@tag_count		fin_int
		declare	@salvage_value_new	fin_amount

		select 	@salvage_value_tmp	= sum(isnull(salvage_value,0))
		from	acap_asset_tag_dtl dtl, 
			acap_asset_bulk_tmp tmp (nolock)
		where	guid 			= @guid
		and	dtl.asset_number	= tmp.asset_number 
		and	dtl.tag_number		= tmp.tag_number
		ANd tmp.ou_id			= dtl.ou_id  --ZHE-942

		select 	@asset_count	= count(distinct asset_number),
			@tag_count	= count(distinct tag_number)
		from	acap_asset_bulk_tmp tmp
		where	guid	= @guid

		
		--select 	@salvage_value_tmp = (isnull(@salvage_value_tmp,0)/@asset_count) *@tag_count
		select 	@salvage_value_tmp = (isnull(@salvage_value_tmp,0)/@tag_count) --*@tag_count

		if @salvage_value_tmp > 0
		begin

			update	dtl
			set	salvage_value	= round(@salvage_value_tmp * (dtl.tag_cost/@assetcost_tmp),@pamt_tmp)
			from	acap_asset_tag_dtl dtl, 
				acap_asset_bulk_tmp tmp (nolock)
			where	guid 			= @guid
			and	dtl.asset_number	= tmp.asset_number 
			and	dtl.tag_number		= tmp.tag_number
			ANd tmp.ou_id			= dtl.ou_id  --ZHE-942

			--For rounding off amount
			select	@salvage_value_new = sum(isnull(salvage_value,0))
			from	acap_asset_tag_dtl dtl, 
				acap_asset_bulk_tmp tmp (nolock)
			where	guid 			= @guid
			and	dtl.asset_number	= tmp.asset_number 
			and	dtl.tag_number		= tmp.tag_number
			ANd tmp.ou_id			= dtl.ou_id  --ZHE-942

			if @salvage_value_tmp <> @salvage_value_new
			begin 
				update	dtl
				set	salvage_value	= salvage_value - (@salvage_value_new - @salvage_value_tmp)
				from	acap_asset_tag_dtl dtl, 
					acap_asset_bulk_tmp tmp (nolock)
				where	guid 			= @guid
				and	dtl.asset_number	= tmp.asset_number 
				and	dtl.tag_number		= tmp.tag_number 
				and	tmp.timestamp		= @fprowno
				ANd tmp.ou_id		    = dtl.ou_id  --ZHE-942
			end

		end
		/*Code added by Uma for the bug id : ACAPDMS412AT_000574 ends here*/
	end		--TLET-402

	if @assetcost_tmp <> @assetcost1_tmp
	begin
                --raiserror('Sum of tag cost not equal to asset cost',16,1)
                select @m_errorid = 3455374
		return
	end

	delete from acap_wip_tmp where guid = @guid
		

	select @fprowno 'fprowno'
	
	set nocount off
	
end





