/*$File_version=ms4.3.0.07$*/
/*$file name : acapacapadspfetmldt.sql*/
/*$version   : 4.0.0.10*/
/*==================================================*/
/**
   stored procedure : acapacapadspfetmldt
   method           :acapacapadmtfetmldt
   author           : functional proto ver 1.0
   created on       : 04 sep 2002 09:54:44:467
   created at       : s4141
   generated by     : suman
*/
/*==================================================*/
/*
   Modified By     :  M.Devanathan                      
   Modified Date   :  01-Aug-2005
   Purpose         :  ACAPDMS412AT_000054 
   Version         :  4.0.0.002

   Modified by : Nagarajan G
   Date	       : 09/08/2005
   Purpose     : ACAPBASEFIXES_000482	

   
   Modified by : Swetha
   Date	       : 11/1/2006
   Purpose     : ACAPBGL_000034		
      
   Modified by : Swetha
   Date	       : 12/1/2006
   Purpose     : ACAPBGL_000041	

   Modified by : Swetha
   Date	       : 27/1/2006
   Purpose     : ACAPBGL_000042	

   
   Modified by : Swetha
   Date	       : 30/1/2006
   Purpose     : ACAPBGL_000053	

   Modified by : Swetha
   Date	       : 08/03/2006
   Purpose     : ACAPBGL_000059	
*/
/*==================================================*/
/* 
grant exec on acapacapadspfetmldt to public  
*/	
/********************************************************************************/
/*Modified by        : Swetha                                                   */
/*Modified Date      : 5/5/2006                                                 */
/*Purpose            : CML Changes                                              */
/*
Modification History
Modified by 		Date			Remarks
Uma Maheswari		18th Jan 2006		ACAPDMS412AT_000607
Prabu S			20th Aug 2007		ACAPDMS412AT_000729 
C.Ramesh Kumar		17.09.2012			12h124_acap_00001
Jayanthi A          22/4/2016           ES_REPSFAM_00460 
Mabel Rita.L        05/04/2019          GD-196 
MUTHUPRIYA M		19/6/2020			EPE-20323
Aditya S			14/03/2022			BMPE-1010
saranraj            16/02/2024          TIS-1682
*/
/********************************************************************************/
CREATE procedure acapacapadspfetmldt
	@accountinformation   	fin_subtitle  ,
     	@ctxt_language   	fin_ctxt_language  ,
     	@ctxt_ouinstance   	fin_ctxt_ouinstance  ,
     	@ctxt_service   	fin_ctxt_service  ,
     	@ctxt_user   		fin_ctxt_user  ,
   	@financialpostingdate   fin_date  ,
     	@guid   			fin_guid  ,
     	@hidden_control1   	fin_hiddencontrol  ,	
     	@trannumber   		fin_documentnumber  ,
     	@transactiondate   	fin_date  ,
     	@transactiontype   	fin_transactiontype  ,
		@hdntranno			fin_documentnumber,--12h124_acap_00001
     	@m_errorid  		fin_int output --to return execution status
as
begin
    -- declare @iudmodeflag nvarchar(2) declared not used
     declare @tran_number fin_documentnumber 

	-- nocount should be switched on to prevent phantom rows 
	set nocount on
	-- @m_errorid should be 0 to indicate success
	select @m_errorid =0
	
	select @accountinformation = ltrim(rtrim(@accountinformation))
	if	@accountinformation = '~#~' 
		select @accountinformation = null
	
	if @ctxt_language = -915 
		select @ctxt_language = null
	
	if @ctxt_ouinstance = -915 
		select @ctxt_ouinstance = null
	
	select @ctxt_service = ltrim(rtrim(@ctxt_service))
	if @ctxt_service = '~#~' 
		select @ctxt_service = null
		
	select @ctxt_user = ltrim(rtrim(@ctxt_user))
	if @ctxt_user = '~#~' 
		select @ctxt_user = null
	
	select @financialpostingdate = ltrim(rtrim(@financialpostingdate))
	if @financialpostingdate = '1/1/1900' 
		select @financialpostingdate = null
	
	select @guid = ltrim(rtrim(@guid))
	if @guid = '~#~' 
		select @guid = null
	
	select @hidden_control1 = ltrim(rtrim(@hidden_control1))
	if @hidden_control1 = '~#~' 
		select @hidden_control1 = null
	
	select @trannumber = ltrim(rtrim(@trannumber))
	if @trannumber = '~#~' 
		select @trannumber = null
	
	select @transactiondate = ltrim(rtrim(@transactiondate))
	if @transactiondate = '1/1/1900' 
		select @transactiondate = null
	
	select @transactiontype = ltrim(rtrim(@transactiontype))
	if @transactiontype = '~#~' 
		select @transactiontype = null

	/* code added by swetha for ACAPBGL_000041 on 12/1/2006 */
	select	@tran_number	= doc_number
	from	acap_wip_hdr(NOLOCK)
	where	cap_wo_number	= @hidden_control1
	and	ou_id		= @ctxt_ouinstance
	/* code added by swetha for ACAPBGL_000041 on 12/1/2006 */

--code added for 12h124_acap_00001 starts
			if @hdntranno = '~#~' 
				select @hdntranno = null
		if @hdntranno is not null and @hdntranno <> ''
		begin
			declare @hdntranno_tmp	fin_documentnumber
			select	@hdntranno_tmp = doc_no
			from	acap_cwiptransfer_tgt_dtl
			where	ou_id			=	@ctxt_ouinstance
			and		transfer_no		=	@hdntranno
			and		doc_no is not null
			and		doc_no <> ''

			--BMPE-1010
			if @ctxt_service = 'acapacapadsrui'
			begin
					select @hdntranno_tmp = @trannumber
					 
			end
			--BMPE-1010

			if @hdntranno_tmp IS NOT NULL AND @hdntranno_tmp <> ''
			begin
				select @hidden_control1 = @hdntranno_tmp
			end
			else
			begin
				select	@hdntranno_tmp = revdoc_no	
				from	acap_cwiptransfer_src_dtl(nolock)
				where	ou_id			=	@ctxt_ouinstance
				and		transfer_no		=	@hdntranno
				and		revdoc_no is  null
				and		revdoc_no <> ''

				if @hdntranno_tmp IS NOT NULL AND @hdntranno_tmp <> ''
				begin
					select @hidden_control1 = @hdntranno_tmp
				end
			end
		end
	--code added for 12h124_acap_00001 ends	

	/* code modified by swetha for ACAPBGL_000034 on 11/2006 */
	if exists (	select	'x'
			from	acap_accounting_info_dtl (nolock)
			where	tran_number	= @hidden_control1
			and     ou_id		= @ctxt_ouinstance --GD-196
			)	
			
	/* code modified by swetha for ACAPBGL_000034 on 11/2006 */
	begin 
		select	a1.account_code			'accountcode', 
			a1.currency			'accountcurrency',
			/*Code Modified By Prabu S For the bug id:ACAPDMS412AT_000729 starts here */ 
			--a1.analysis_code		'analysiscode',				
			case
			when	a1.analysis_code='##'	then ''
			else	analysis_code 	
			end				'analysiscode' , 	
			/*Code Modified By Prabu S For the bug id:ACAPDMS412AT_000729 Ends here */
			sum(a1.base_amount) 		'baseamount',
			a1.bc_erate 			'basecurrencyexchangerate',
			/* code Modified by Swetha for ACAPBGL_000053 on 30/1/2006 */
			case
			when	a1.cost_center = '##'	then ''
			else	a1.cost_center
			end	
			/* code Modified by Swetha for ACAPBGL_000053 on 30/1/2006 */
							'costcenter',
			met.parameter_text		'drcr',
			a1.fb_id			'fbml',
			sum(a1.pbase_amount)		'parallelbaseamount',
			a1.pbc_erate			'pbcexchangerate',
			/*Code Modified By Prabu S For the bug id:ACAPDMS412AT_000729 starts here */ 
			--a1.sub_analysis_code		'subanalysiscode',
			case
			when	a1.sub_analysis_code='##'  then ''
			else	a1.sub_analysis_code 	
			end				'SubanalysisCode' , 
			/*Code Modified By Prabu S For the bug id:ACAPDMS412AT_000729 Ends here */ 	
			a1.tran_number			'trannumberml',
			sum(a1.tran_amount)		'transactionamount',
			/*Code Modified by  Nagarajan G for the bug id : ACAPBASEFIXES_000482 Starts here*/
			--a1.tran_type			'transactiontypeml',
			b1.tran_desc			'transactiontypeml',
			--Code Added by Devanathan.M for the bug id : ACAPDMS412AT_000054 starts here
			vw.ml_account_desc		'accountdesc'			
			--Code Added by Devanathan.M for the bug id : ACAPDMS412AT_000054 ends here
		from	acap_accounting_info_dtl a1 (nolock)
			--Code Added by Devanathan.M for the bug id : ACAPDMS412AT_000054 starts here
			,as_opacctfball_ml_vw vw(nolock)
			--Code Added by Devanathan.M for the bug id : ACAPDMS412AT_000054 ends here
			,emod_trantype_vw b1(nolock),
			fin_quick_code_met met(NOLOCK)
			/* code modified by swetha for ACAPBGL_000034 on 11/2006 */
		where	a1.tran_number		= @hidden_control1
		/* code modified by swetha for ACAPBGL_000034 on 11/2006 */
		and	ou_id			= @ctxt_ouinstance
		--Code Added by Devanathan.M for the bug id : ACAPDMS412AT_000054 starts here
		and	a1.company_code		= vw.company_code 
		and	a1.account_code 	= vw.account_code
		and	a1.fb_id		= vw.fb_id
		and	vw.language_id		= @ctxt_language
		and	b1.language_id		= vw.language_id
		--Code Added by Devanathan.M for the bug id : ACAPDMS412AT_000054 ends here
		and	b1.component_id		= 'ACAP'
		and	a1.tran_type		= b1.tran_type
		and	met.component_id	= 'ACAP'
		and	met.parameter_type	= 'CBO'
		and	met.parameter_category	= 'DRCR'
		and	met.language_id		= @ctxt_language
		and	met.parameter_code	= a1.drcr_flag 
		group by a1.account_code , a1.currency ,a1.analysis_code ,a1.bc_erate ,
		a1.cost_center,met.parameter_text ,a1.fb_id ,a1.pbc_erate ,
		a1.sub_analysis_code ,a1.tran_number ,b1.tran_desc,
		/*a1.tran_type*/vw.ml_account_desc --Code Added by Devanathan.M for the bug id : ACAPDMS412AT_000054
		/*Code Modified by  Nagarajan G for the bug id : ACAPBASEFIXES_000482 Ends here*/	
	
	end
	/* code modified by swetha for ACAPBGL_000034 on 11/2006 */
	else if exists (	select	'x' 
				from	acap_journal_accounting_dtl (nolock) 
				where	tran_number	= @hidden_control1
				and		ou_id			= @ctxt_ouinstance --GD-196
			)
	/* code modified by swetha for ACAPBGL_000034 on 11/2006 */
	begin 
		select	a2.account_code			'accountcode', 
			a2.currency			'accountcurrency',
			/*Code Modified By Prabu S For the bug id:ACAPDMS412AT_000729 starts here */ 
			--a2.analysis_code		'analysiscode',				
			case
			when	a2.analysis_code='##' then ''
			else	analysis_code 	
			end				'Analysiscode' , 
			/*Code Modified By Prabu S For the bug id:ACAPDMS412AT_000729 Ends here */ 
			sum(a2.base_amount)		'baseamount',
			a2.bc_erate			'basecurrencyexchangerate',
			/* code Modified by Swetha for ACAPBGL_000053 on 30/1/2006 */
			case	
			when	a2.cost_center = '##' then ''
			else	a2.cost_center
			end	
			/* code Modified by Swetha for ACAPBGL_000053 on 30/1/2006 */ 		
							'costcenter',
			met.parameter_text		'drcr',
			a2.fb_id			'fbml',
			sum(a2.pbase_amount)		'parallelbaseamount',
			a2.pbc_erate			'pbcexchangerate',
			/*Code Modified By Prabu S For the bug id:ACAPDMS412AT_000729 starts here */ 
			--a2.sub_analysis_code		'subanalysiscode',
			case
			when	a2.sub_analysis_code='##'   then ''
			else	a2.sub_analysis_code 	
			end				'SubanalysisCode' , 
			/*Code Modified By Prabu S For the bug id:ACAPDMS412AT_000729 Ends here */ 			
			a2.tran_number			'trannumberml',
			sum(a2.tran_amount)		'transactionamount',
			/*Code Modified by  Nagarajan G for the bug id : ACAPBASEFIXES_000482 Starts here*/
			--a2.tran_type			'transactiontypeml',
			b2.tran_desc			'transactiontypeml',
			--Code Added by Devanathan.M for the bug id : ACAPDMS412AT_000054 starts here
			vw.ml_account_desc		'accountdesc'			
			--Code Added by Devanathan.M for the bug id : ACAPDMS412AT_000054 ends here
		from	acap_journal_accounting_dtl a2(nolock)
			--Code Added by Devanathan.M for the bug id : ACAPDMS412AT_000054 starts here
			,as_opacctfball_ml_vw vw(nolock),
			--Code Added by Devanathan.M for the bug id : ACAPDMS412AT_000054 ends here
			emod_trantype_vw b2(nolock),
			fin_quick_code_met met(NOLOCK)
			/* code modified by swetha for ACAPBGL_000034 on 11/2006 */
		where	a2.tran_number		= @hidden_control1
			/* code modified by swetha for ACAPBGL_000034 on 11/2006 */
		and	ou_id			= @ctxt_ouinstance
			--Code Added by Devanathan.M for the bug id : ACAPDMS412AT_000054 starts here
		and	a2.company_code		= vw.company_code 
		and	a2.account_code		= vw.account_code
		and	a2.fb_id		= vw.fb_id
		--Code Added by Devanathan.M for the bug id : ACAPDMS412AT_000054 ends here
		and	b2.component_id		= 'ACAP'
		and	a2.tran_type		= b2.tran_type
		and	vw.language_id		= @ctxt_language
		and	b2.language_id		= vw.language_id
		and	met.component_id	= 'ACAP'
		and	met.parameter_type	= 'CBO'
		and	met.parameter_category	= 'DRCR'
		and	met.language_id		= @ctxt_language
		and	met.parameter_code	= a2.drcr_flag
		group by a2.account_code , a2.currency ,a2.analysis_code,
		a2.bc_erate ,a2.cost_center,met.parameter_text ,a2.fb_id ,
		a2.pbc_erate ,a2.sub_analysis_code ,a2.tran_number ,
		b2.tran_desc,/*a2.tran_type*/vw.ml_account_desc --Code Added by Devanathan.M for the bug id : ACAPDMS412AT_000054
		/*Code Modified by  Nagarajan G for the bug id : ACAPBASEFIXES_000482 Ends here*/
	end
	/* code added by swetha for ACAPBGL_000041 on 12/1/2006 */
	/* code modified by swetha for ACAPBGL_000034 on 11/2006 */
	/* code modified by swetha for ACAPBGL_000042 on 27/1/2006 */
	else if exists (	select	'x' 
				from	acap_wip_accounting_dtl (nolock) 
				where	tran_number 	= @hidden_control1
				and ou_id			= @ctxt_ouinstance --GD-196
			)
	/* code modified by swetha for ACAPBGL_000042 on 27/1/2006 */
	/* code added by swetha for ACAPBGL_000041 on 12/1/2006 */
	/* code modified by swetha for ACAPBGL_000034 on 11/2006 */
	begin 
		select 	a3.account_code			'accountcode', 
			a3.currency			'accountcurrency',
			/*Code Modified By Prabu S For the bug id:ACAPDMS412AT_000729 starts here */ 
			--a3.analysis_code		'analysiscode',				
			case
			when	a3.analysis_code='##'  then ''
			else	analysis_code 	
			end				'Analysiscode' , 
			/*Code Modified By Prabu S For the bug id:ACAPDMS412AT_000729 Ends here */ 
			sum(a3.base_amount)		'baseamount',
			a3.bc_erate			'basecurrencyexchangerate',
			/* code Modified by Swetha for ACAPBGL_000053 on 30/1/2006 */
			case  
			when	a3.cost_center = '##' then ''
			else	a3.cost_center
			end	
			/* code Modified by Swetha for ACAPBGL_000053 on 30/1/2006 */ 			
							'costcenter',
			met.parameter_text		'drcr',
			a3.fb_id 			'fbml',
			sum(a3.pbase_amount) 		'parallelbaseamount',
			a3.pbc_erate 			'pbcexchangerate',
			/*Code Modified By Prabu S For the bug id:ACAPDMS412AT_000729 starts here */ 
			--a3.sub_analysis_code 		'subanalysiscode',
			case
			when	a3.sub_analysis_code='##' then ''
			else	a3.sub_analysis_code 	
			end				'subanalysiscode' , 
			/*Code Modified By Prabu S For the bug id:ACAPDMS412AT_000729 Ends here */ 
			a3.tran_number			'trannumberml',
			sum(a3.tran_amount) 		'transactionamount',
			/*Code Modified by  Nagarajan G for the bug id : ACAPBASEFIXES_000482 Starts here*/
			--			a3.tran_type 			'transactiontypeml',
			b3.tran_desc 			'transactiontypeml',
			--Code Added by Devanathan.M for the bug id : ACAPDMS412AT_000054 Ends here
			--vw.account_desc			'Account Description'	
			/* code added by swetha for ACAPBGL_000042 on 27/1/2006 */
			vw.ml_account_desc        	'accountdesc'		
			/* code added by swetha for ACAPBGL_000042 on 27/1/2006 */		
			--Code Added by Devanathan.M for the bug id : ACAPDMS412AT_000054 ends here
		from	acap_wip_accounting_dtl a3(nolock)
			--Code Added by Devanathan.M for the bug id : ACAPDMS412AT_000054 starts here
			,as_opacctfball_ml_vw vw(nolock)
			--Code Added by Devanathan.M for the bug id : ACAPDMS412AT_000054 ends here
			,emod_trantype_vw b3(nolock),
			fin_quick_code_met met(NOLOCK)
			/* code modified by swetha for ACAPBGL_000034 on 11/2006 */
			/* code added by swetha for ACAPBGL_000041 on 12/1/2006 */
			/* code added by swetha for ACAPBGL_000042 on 27/1/2006 */
		where   tran_number = @hidden_control1
			/* code added by swetha for ACAPBGL_000042 on 27/1/2006 */
			/* code added by swetha for ACAPBGL_000041 on 12/1/2006 */
			/* code modified by swetha for ACAPBGL_000034 on 11/2006 */
		and	ou_id			= @ctxt_ouinstance
		--Code Added by Devanathan.M for the bug id : ACAPDMS412AT_000054 starts here
		and	a3.company_code		= vw.company_code 
		and	a3.account_code		= vw.account_code
		and	a3.fb_id		= vw.fb_id
		--Code Added by Devanathan.M for the bug id : ACAPDMS412AT_000054 ends here
		and	b3.component_id		= 'ACAP'
		and	a3.tran_type		= b3.tran_type
		and	vw.language_id		= @ctxt_language
		and	b3.language_id		= vw.language_id
		and	met.component_id	= 'ACAP'
		and	met.parameter_type	= 'CBO'
		and	met.parameter_category	= 'DRCR'
		and	met.language_id		= @ctxt_language
		and	met.parameter_code	= a3.drcr_flag
		group by a3.account_code , a3.currency ,a3.analysis_code ,
		a3.bc_erate ,a3.cost_center,met.parameter_text ,a3.fb_id ,
		a3.pbc_erate ,a3.sub_analysis_code ,a3.tran_number ,
		b3.tran_desc/*a3.tran_type*/,vw.ml_account_desc --Code Added by Devanathan.M for the bug id : ACAPDMS412AT_000054 
		/*Code Modified by  Nagarajan G for the bug id : ACAPBASEFIXES_000482 Ends here*/
	end
	/* Code added by Swetha for ACAPBGL_000059 on 08/03/2006 */
	else if exists(	select	'x'
		       	from	adepp_accounting_info_dtl(nolock)
		       	where	tran_number 		= @trannumber
				and		ou_id			= @ctxt_ouinstance --GD-196
		       )
	begin 
		select	a.account_code			'accountcode',
			a.currency			'accountcurrency',
			/*Code Modified By Prabu S For the bug id:ACAPDMS412AT_000729 starts here */ 
			--isnull(a.analysis_code,'')	'analysiscode',
			case
			when	a.analysis_code='##'  then ''
			else	analysis_code 	
			end				'Analysiscode' , 
			/*Code Modified By Prabu S For the bug id:ACAPDMS412AT_000729 Ends here */ 
			a.base_amount			'baseamount',
			a.bc_erate			'basecurrencyexchangerate',
			isnull(replace(a.cost_center,'~#~',''),'')	'costcenter',
			a.drcr_flag			'drcr',
			a.fb_id				'fbml',
			a.pbase_amount			'parallelbaseamount',
			a.pbc_erate			'pbcexchangerate',
			/*Code Modified By Prabu S For the bug id:ACAPDMS412AT_000729 starts here */ 
			--isnull(a.sub_analysis_code,'') 'subanalysiscode',
			case
			when	a.sub_analysis_code='##' then ''
			else	a.sub_analysis_code 	
			end				'subanalysiscode' , 
			/*Code Modified By Prabu S For the bug id:ACAPDMS412AT_000729 Ends here */ 
			a.tran_number			'trannumberml',
			a.tran_amount			'transactionamount',
			b.tran_desc			'transactiontypeml',
			vw.ml_account_desc		'AccountDesc'	
		from	adepp_accounting_info_dtl a(nolock),emod_trantype_vw b(nolock)
			,as_opacctfball_ml_vw vw(nolock) ,
			fin_quick_code_met met(NOLOCK)
		where	a.tran_number		= @trannumber
		and	b.component_id		= 'ADEPP'
		and	b.tran_type		= a.tran_type
		and	b.language_id		= @ctxt_language
		and	a.company_code		= vw.company_code
		and	a.account_code		= vw.account_code
		and	a.fb_id			= vw.fb_id
		and	vw.language_id		= @ctxt_language
		and	b.language_id		= vw.language_id
		and	met.component_id	= 'ACAP'
		and	met.parameter_type	= 'CBO'
		and	met.parameter_category	= 'DRCR'
		and	met.language_id		= @ctxt_language
		and	met.parameter_code	= a.drcr_flag
		and A.ou_id			= @ctxt_ouinstance --GD-196
                
	end
	else if exists(	select	'x'
		       	from	arev_accounting_info_dtl(nolock)
		       	where	tran_number 	= 	@trannumber
				and		ou_id			= @ctxt_ouinstance --GD-196
			)
	begin 
		select	a.account_code		'AccountCode' ,
			currency		'AccountCurrency' ,
			/*Code Modified By Prabu S For the bug id:ACAPDMS412AT_000729 starts here */ 
			--analysis_code		'Analysiscode' ,
			case
			when	analysis_code='##'  then ''
			else	analysis_code 	
			end			'Analysiscode' ,
			/*Code Modified By Prabu S For the bug id:ACAPDMS412AT_000729 Ends here */ 
			base_amount		'BaseAmount' ,
			bc_erate		'Basecurrencyexchangerate' ,
			cost_center		'CostCenter' ,
			drcr_flag		'DrCr' ,
			a.fb_id			'fbml' ,
			pbc_erate		'PBCExchangeRate' ,
			pbase_amount		'ParallelBaseamount' ,
			/*Code Modified By Prabu S For the bug id:ACAPDMS412AT_000729 starts here */ 
			--sub_analysis_code	'subanalysiscode' ,
			case
			when	sub_analysis_code='##' then ''
			else	sub_analysis_code 	
			end			'subanalysiscode' , 
			/*Code Modified By Prabu S For the bug id:ACAPDMS412AT_000729 Ends here */ 
			tran_amount		'Transactionamount' ,
			tran_desc		'TransactionTypeML' ,	
			tran_number		'TranNumberML'  ,
			vw.ml_account_desc	'AccountDesc'	
		from	arev_accounting_info_dtl A(nolock),
			emod_trantype_vw B(nolock)
			,as_opacctfball_ml_vw VW(nolock),
			fin_quick_code_met met(NOLOCK)
		where	tran_number		= @trannumber 
		and	B.component_id		= 'AREV'
		and	A.tran_type		= B.tran_type
		and	A.company_code		= VW.company_code
		and	A.account_code		= VW.account_code
		and	A.fb_id			= VW.fb_id
		and	vw.language_id		= @ctxt_language
		and	b.language_id		= vw.language_id
		and	met.component_id	= 'ACAP'
		and	met.parameter_type	= 'CBO'
		and	met.parameter_category	= 'DRCR'
		and	met.language_id		= @ctxt_language
		and	met.parameter_code	= a.drcr_flag
		and A.ou_id			= @ctxt_ouinstance --GD-196
	end
	/* Code added by Swetha for ACAPBGL_000059 on 08/03/2006 */
	/* Code added by Uma for the bug id: ACAPDMS412AT_000607 starts here*/
	else if exists (	select	'x' 
				from	ainq_accounting_info_dtl (nolock)
				where	ou_id			= @ctxt_ouinstance	
				and	tran_number		= @trannumber 
			)
	begin

		select	/* code commented for ES_REPSFAM_00460 starts */ /* distinct */ /* ends */
			a.account_code		'AccountCode' ,
			currency		'AccountCurrency' ,
			/*Code Modified By Prabu S For the bug id:ACAPDMS412AT_000729 starts here */ 
			--analysis_code 		'Analysiscode' ,
			case
			when	a.analysis_code='##'  then ''
			else	analysis_code 	
			end			'Analysiscode' , 
			/*Code Modified By Prabu S For the bug id:ACAPDMS412AT_000729 Ends here */ 
			base_amount		'BaseAmount' ,
			bc_erate		'Basecurrencyexchangerate' ,
			cost_center		'CostCenter' ,
			drcr_flag		'DrCr' ,
			a.fb_id			'fbml' ,
			pbc_erate		'PBCExchangeRate' ,
			pbase_amount		'ParallelBaseamount' ,
			/*Code Modified By Prabu S For the bug id:ACAPDMS412AT_000729 starts here */ 
			--sub_analysis_code	'SubanalysisCode' ,
			case
			when	sub_analysis_code='##'   then ''
			else	sub_analysis_code 	
			end			'subanalysiscode' , 
			/*Code Modified By Prabu S For the bug id:ACAPDMS412AT_000729 Ends here */ 
			tran_amount		'Transactionamount' ,
			tran_desc		'TransactionTypeML' ,	
			tran_number		'TranNumberML'  ,
			vw.ml_account_desc	'AccountDesc'	
		from	ainq_accounting_info_dtl A(nolock),emod_trantype_vw B(nolock)
			,as_opacctfball_ml_vw VW(nolock),
			fin_quick_code_met met(NOLOCK)
		where	tran_number		= @trannumber 
		and	A.tran_type		= B.tran_type
		and	A.company_code		= VW.company_code
		and	A.account_code		= VW.account_code
		and	A.fb_id			= VW.fb_id
		and	vw.language_id		= @ctxt_language
		and	b.language_id		= vw.language_id
		and	met.component_id	= 'ACAP'
		and	met.parameter_type	= 'CBO'
		and	met.parameter_category	= 'DRCR'
		and	met.language_id		= @ctxt_language
		and	met.parameter_code	= a.drcr_flag
		and	depr_book		= 'CORP'
		and A.ou_id			= @ctxt_ouinstance --GD-196	
		--code added for  TIS-1682 starts
	    union
		select	
			a.account_code		'AccountCode' ,
			currency		'AccountCurrency' ,
			case
			when	a.analysis_code='##'  then ''
			else	analysis_code 	
			end			'Analysiscode' , 
			base_amount		'BaseAmount' ,
			bc_erate		'Basecurrencyexchangerate' ,
			cost_center		'CostCenter' ,
			drcr_flag		'DrCr' ,
			a.fb_id			'fbml' ,
			pbc_erate		'PBCExchangeRate' ,
			pbase_amount		'ParallelBaseamount' ,
			case
			when	sub_analysis_code='##'   then ''
			else	sub_analysis_code 	
			end			'subanalysiscode' , 
			tran_amount			'Transactionamount' ,
			'Reverse Asset Inter Finance Book Transfer'		'TransactionTypeML' ,	
			tran_number		'TranNumberML'  ,
			vw.ml_account_desc	'AccountDesc'	
		from ainq_accounting_info_dtl A(nolock)
			,as_opacctfball_ml_vw VW(nolock),
			 fin_quick_code_met met(NOLOCK)
		where	tran_number		= @trannumber 
		and	A.tran_type		    = 'FA_RAIFBTR' /*Value Hardcore*/
		and	A.company_code		= VW.company_code
		and	A.account_code		= VW.account_code
		and	A.fb_id			    = VW.fb_id
		and	vw.language_id		= @ctxt_language
		and	met.component_id	= 'ACAP'
		and	met.parameter_type	= 'CBO'
		and	met.parameter_category	= 'DRCR'
		and	met.language_id		= @ctxt_language
		and	met.parameter_code	= a.drcr_flag
		and	depr_book		= 'CORP'
		and A.ou_id			= @ctxt_ouinstance 

		--code added for  TIS-1682 ends

	end
	/* Code added by Uma for the bug id: ACAPDMS412AT_000607 ends here*/
	/*Code added for EPE-20323 starts*/
	else if exists (	select	'x'
			from	ahfs_accounting_info_dtl (nolock)
			where	tran_number	= @hidden_control1
			and     tran_ou		= @ctxt_ouinstance
			)	
	begin 
		select
			a.account_code		'AccountCode' ,
			currency		'AccountCurrency' ,
			case
			when	a.analysis_code='##'  then ''
			else	analysis_code 	
			end			'Analysiscode' , 
			base_amount		'BaseAmount' ,
			bc_erate		'Basecurrencyexchangerate' ,
			cost_center		'CostCenter' ,
			drcr_flag		'DrCr' ,
			a.fb_id			'fbml' ,
			pbc_erate		'PBCExchangeRate' ,
			pbase_amount		'ParallelBaseamount' ,
			case
			when	sub_analysis_code='##'   then ''
			else	sub_analysis_code 	
			end			'subanalysiscode' , 
			tran_amount		'Transactionamount' ,
			tran_desc		'TransactionTypeML' ,	
			tran_number		'TranNumberML'  ,
			vw.ml_account_desc	'AccountDesc'	
		from	ahfs_accounting_info_dtl A(nolock),emod_trantype_vw B(nolock)
			,as_opacctfball_ml_vw VW(nolock),
			fin_quick_code_met met(NOLOCK)
		where	tran_number		= @trannumber 
		and	A.tran_type		= B.tran_type
		and	A.company_code		= VW.company_code
		and	A.account_code		= VW.account_code
		and	A.fb_id			= VW.fb_id
		and	vw.language_id		= @ctxt_language
		and	b.language_id		= vw.language_id
		and	met.component_id	= 'ACAP'
		and	met.parameter_type	= 'CBO'
		and	met.parameter_category	= 'DRCR'
		and	met.language_id		= @ctxt_language
		and	met.parameter_code	= a.drcr_flag
		and	depr_book		= 'CORP'
		and A.tran_ou			= @ctxt_ouinstance
	
	/*Code added for EPE-20323 ends*/
     end
	 set nocount off
end








