/*$File_version=ms4.3.0.10$*/  
/*$file name : acapauasmspauashdrsave.sql*/  
/*$version   : 4.0.0.5*/  
/*==================================================  
   stored procedure : acapauasmspauashdrsave  
   method           :acapauasmmtauashdrsave  
   author           : Prasad A  
   created on       : 26 may 2001 13:34:44:780  
   created at       : s4141  
   generated by     : fpuser  
   description      : initialising the row count flag  
   modifiedby     : Prasad  
   modifieddate     : 18/07/2003  
  
   Modified by      : Anuradha.R  
   Modified Date    : 18-May-2004  
   Description      : ACAPDMS41SYTST_000062  
  
   Modified By  : Sangeetha Sitaraman  
   Date   : 10-11-2005  
   Purpose  : For FA revamp(pls refer the prev.version from VSS)  
  
declare @P1 int  
set @P1=NULL  
exec acapauasmspauashdrsave 'Computer', 'Computer', '~#~', 'apt-1', 'Fresh', '01/01/1900', '~#~', '03/12/2002', 
'fpuser', 1, '2', 'acapauasmsrauas', 'fin2user', 'FB1', 'fin2user', @P1 output  
select @P1  
  
grant exec on acapauasmspauashdrsave to public  
====================================================*/  
/*Modified by  Date    Remarks  */  
/*Muthu V  4/28/04    For German Support  */  
/*Rahul Sharma   18/09/2015              ES_ACAP_00865*/  
/*  Harithra   17-08-2018         EPE-8428                             */  
/*  Mabel Rita L  23-07-2019         MKN-1320                             */  
--gokul  M				27/11/2019			epe-17029
/*Ashok V						10/02/2020							EBS-3983  */
 /*Uma Maheshwari M			12/05/2022				EPE-46265			  */
 /* Abinav				01/03/2023			EPE-60038			*/
 /*Abhijith KP			28/07/2023			EPE-62647			*/
 /*Abhijith	KP			31/08/2023			EPE-62647:EPE-68610	*/
/******************************************************************************************/  
Create procedure acapauasmspauashdrsave       
      @assetclass      fin_assetclass  ,  
      @assetdescription    fin_desc40  ,  
      @assetgrpnum     fin_group  ,  
      @assetnumber     fin_assetnumber  ,  
      @assetstatus     fin_status  ,  
      @capitalizationdate    fin_date  ,  
      @capitalizationnumber fin_documentnumber,  
      @costcenter      fin_costcentercode  ,  
      @createddate     fin_date  ,  
      @creationby      fin_ctxt_user  ,  
      @ctxt_language     fin_ctxt_language  ,  
      @ctxt_ouinstance    fin_ctxt_ouinstance  ,  
      @ctxt_service     fin_ctxt_service  ,  
      @ctxt_user      fin_ctxt_user  ,  
      @fb        fin_financebookid  ,  
      @guid     fin_guid,  
      @lastmodificationby    fin_ctxt_user  ,  
      @lastmodifieddate    fin_date  ,  
   @remarks               fin_desc255,--code added by Rahul For the defect id ES_ACAP_00865  
  /*code modified for EPE-8428 - Harithra*/  
   @accountcode           fin_accountcode, --Input   
   @accountdescription    fin_accountdesc, --Input   
   @lscostcentre          fin_costcentercode, --Input   
   @analysiscode          fin_analysiscode, --Input   
   @subanalysiscode       fin_subanalysiscode, --Input   
      @m_errorid     fin_int output --to return execution status  
as  
begin  
       
  
     -- nocount should be switched on to prevent phantom rows   
     set nocount on  
    
 declare @companycode_tmp  fin_companycode,  
  @today_tmp  fin_date,  
  @csetou   fin_ctxt_ouinstance   
  ,@ainfou   fin_ctxt_ouinstance--MKN-1320  
     ,@bu_id         fin_buid--MKN-1320  
  
 -- @m_errorid should be 0 to indicate success  
 select @m_errorid =0       
 /*code modified for EPE-8428 - Harithra*/  
 Set @accountcode           = ltrim(rtrim(@accountcode))  
 Set @accountdescription    = ltrim(rtrim(@accountdescription))  
 Set @lscostcentre          = ltrim(rtrim(@lscostcentre))  
 Set @analysiscode          = ltrim(rtrim(@analysiscode))  
 Set @subanalysiscode       = ltrim(rtrim(@subanalysiscode))  
  
 select @assetclass = ltrim(rtrim(@assetclass))  
 if @assetclass = '~#~'   
  select @assetclass = null  
  
 select @assetdescription = ltrim(rtrim(@assetdescription))  
 if @assetdescription = '~#~'   
select @assetdescription = null  
  
 select @assetgrpnum = ltrim(rtrim(@assetgrpnum))  
 if @assetgrpnum = '~#~'   
  select @assetgrpnum = null  
  
 select @assetnumber = ltrim(rtrim(@assetnumber))  
 if @assetnumber = '~#~'   
  select @assetnumber = null  
  
 select @assetstatus = ltrim(rtrim(@assetstatus))  
 if @assetstatus = '~#~'   
  select @assetstatus = null  
  
 select @capitalizationdate = ltrim(rtrim(@capitalizationdate))  
 if @capitalizationdate = '1900-01-01'   
  select @capitalizationdate = null  
  
 select @costcenter = ltrim(rtrim(@costcenter))  
 if @costcenter = '~#~'   
  select @costcenter = null  
  
 select @createddate = ltrim(rtrim(@createddate))  
 if @createddate = '1900-01-01'  
  select @createddate = null  
  
 select @creationby = ltrim(rtrim(@creationby))  
 if @creationby = '~#~'   
  select @creationby = null  
  
 if @ctxt_language = -915   
  select @ctxt_language = null  
  
 if @ctxt_ouinstance = -915   
  select @ctxt_ouinstance = null  
  
 select @ctxt_service = ltrim(rtrim(@ctxt_service))  
 if @ctxt_service = '~#~'   
  select @ctxt_service = null  
  
 select @ctxt_user = ltrim(rtrim(@ctxt_user))  
 if @ctxt_user = '~#~'   
  select @ctxt_user = null  
  
 select @fb = ltrim(rtrim(@fb))  
 if @fb = '~#~'   
  select @fb = null  
  
 select @guid = ltrim(rtrim(@guid))  
 if @guid = '~#~'   
  select @guid = null  
  
 select @lastmodificationby = ltrim(rtrim(@lastmodificationby))  
 if @lastmodificationby = '~#~'   
  select @lastmodificationby = null  
  
 select @lastmodifieddate = ltrim(rtrim(@lastmodifieddate))  
 if @lastmodifieddate = '1900-01-01'   
  select @lastmodifieddate = null  
  
 /*Code added by Rahul For the defect id ES_ACAP_00865 starts here*/  
 select @remarks               = ltrim(rtrim(@remarks))  
 IF @remarks = '~#~'   
  Select @remarks = null    
  /*Code added by Rahul For the defect id ES_ACAP_00865 ends here*/     
 /*code modified for EPE-8428 - Harithra*/  
 IF @accountcode = '~#~'   
  Select @accountcode = null    
  
 IF @accountdescription = '~#~'   
  Select @accountdescription = null    
  
 IF @lscostcentre = '~#~'   
  Select @lscostcentre = null    
  
 IF @analysiscode = '~#~'   
  Select @analysiscode = null    
  
 IF @subanalysiscode = '~#~'   
  Select @subanalysiscode = null    
  
 select  @assetstatus   = parameter_code   
  from    fin_quick_code_met(nolock)  
 where   upper(component_id)  = 'ACAP'  
 and     upper(parameter_text)  = upper(@assetstatus)  
 and     upper(parameter_category) = 'AS_STA'       
 and     upper(parameter_type)  = 'CBO'  
 and language_id   = @ctxt_language  
  
  
  
 if @assetstatus in ('AC')  
 begin  
  --raiserror('Asset is in Active Status',16,1)  
  --exec fin_german_raiserror_sp 'ACAP',@ctxt_language,83  
  select @m_errorid = 39304129  
  return  
 end  
   
  
 select  @companycode_tmp = company_code   
 ,@bu_id   = bu_id ---MKN-1320  
 from   emod_ou_vw (nolock)  
 where  ou_id   = @ctxt_ouinstance  
  
 -- get date time with only datepart  
 select  @today_tmp  = dbo.RES_Getdate(@ctxt_ouinstance)  
 select  @today_tmp  = convert(datetime,convert(nchar(12),@today_tmp))  
 
/*Code added for EPE-60038 begins */
-- Checking restricted back dated transaction
Exec restrict_bk_dated_tran_sp @ctxt_ouinstance,@ctxt_language,'FA_ACAP',@capitalizationdate,'ACAP',@companycode_tmp,@m_errorid Output

If @m_errorid <> 0
	Return
/*Code added for EPE-60038 ends */ 

 --MKN-1320 starts  
 /*select @csetou    =  destinationouinstid  
 from acap_cim_intxn_model_vw c (nolock)  
 where c.sourceouinstid   = @ctxt_ouinstance  
 and c.sourcecomponentname  = 'acap'  
 and c.destinationcomponentname  = 'cset'  
  
  
  
 if exists(select 'x' from acap_cim_intxn_model_vw c (nolock), emod_ou_vw  b (nolock)  
   where c.sourceouinstid    = @ctxt_ouinstance  
   and c.sourcecomponentname   = 'ACAP'  
   and b.ou_id     = c.destinationouinstid  
   and @today_tmp     between b.effective_from and isnull(b.effective_to,@today_tmp)  
   and c.destinationcomponentname   = 'CSET')  
 begin*/  
 --MKN-1320 ends  
     --MKN-1320 starts  
      
  select  @csetou    =  destinationouinstid  
  from  fw_admin_view_comp_intxn_model  (nolock)  
  where  sourceouinstid    = @ctxt_ouinstance  
  and  sourcecomponentname   = 'ACAP'  
  and  destinationcomponentname  = 'CSET'  
  
  select  @ainfou    =  destinationouinstid  
  from  fw_admin_view_comp_intxn_model  (nolock)  
  where  sourceouinstid    = @ctxt_ouinstance  
  and  sourcecomponentname   = 'ACAP'  
  and  destinationcomponentname  = 'AINF'  

  --EPE-62647
   declare @pps_flag_cc    fin_flag
  
   select @pps_flag_cc = FLAG_YES_NO
   from pps_finance_feature_list with (nolock)
   where FEATURE_ID = 'PPS_CostCenter_FA'
   and company_code = @companycode_tmp

   if @pps_flag_cc is null
   BEGIN
       select @pps_flag_cc = FLAG_YES_NO
       from pps_finance_feature_list with (nolock)
       where FEATURE_ID = 'PPS_CostCenter_FA'
       and company_code IS NULL
   END
  --EPE-62647
   
  if exists (select 'x' from emod_ou_vw  b (nolock)  
    where b.ou_id   = @csetou  
    and @capitalizationdate between b.effective_from and isnull(b.effective_to,@capitalizationdate)  
    )  
  begin  
   if  exists(select 'x' from ainf_asset_class_vw(nolock)  
    where  ou_id   = @ainfou  
    and dest_component  = 'ACAP'  
    and asset_class_code =  @assetclass  
    and depreciable      = 'Y'  
    and asset_class_status = 'A')  
   begin  
		--EPE-62647
		if @pps_flag_cc = 'YES' and @costcenter is null
		  begin
			if  exists(	select  '*' 	      from      mac_acc_ce_cc_mapping mac  with (nolock) ,  
														ard_asset_account_mst ard  with (nolock)     
												where  	ard.account_code 	= mac.account_no  
												and  	ard.fb_id   		= @fb
												and  	ard.asset_class  	= @assetclass  
												and  	ard.asset_usage  	in  ('DEPREC', 'LOSREV','REVDEP','IMPLOSS') 
												and     mac.bu_id			= @bu_id)
					begin
										select @m_errorid = 3455387 --EPE-62647:EPE-68610
										return	
					end


		    end
		--EPE-62647

  ----MKN-1320 ends  

if (@pps_flag_cc = 'YES' and @costcenter is not null) or  @pps_flag_cc = 'NO' --EPE-62647
begin

  if @costcenter is  null  
  begin  
        --raiserror('Cost Center can not be null',16,1)  
                        select @m_errorid = 3455387  
   return  
  end  
  
  
  --existency check for cost center  
     --MKN-1320 starts  
  /*if not exists(select 'x' from mac_cost_center_vw (nolock)  
    where company_code  = @companycode_tmp  
    and ou_id   = @csetou      
    and upper(ma_center_no) = upper(@costcenter)  
    and ma_status   = 'A')  
  
  begin   
                        --raiserror('Cost Center does not exists',16,1)  
                        select @m_errorid = 3455388  
   return  
  end*/    
  --MKN-1320 ends  
  --MKN-1320 starts  
    
  if not exists ( select 'x'   
         from  mac_cost_center_vw (nolock)  
         where  company_code  = @companycode_tmp   
         and  bu_id     = @bu_id   
         and  ma_center_no  = @costcenter  
         and  ma_status = 'A')  
      begin  
        --raiserror('Invalid Cost Center', 16, 1)  
        exec fin_sp_raise_error '','','','','AMIG', 110,@m_errorid out  
        return  
      end  
        
    if not exists( select 'x' from mac_cost_center_vw (nolock)  
        where bu_id    = @bu_id  
        and  upper(ma_center_no) = upper(@costcenter)  
        and  ma_status    = 'A'  
        and  ma_center_leaf  = 'D')  
      begin   
       --raiserror('Invalid Posting Cost Center',16,1)  
       exec fin_german_raiserror_sp 'ADEPP',@ctxt_language,89  
       return  
      end   
       
   
  --MKN-1320 ends  

  /*code added for EBS-3983 starts*/
		if exists(select	'*'
					from	ainf_asset_class_mst(nolock)
					where	asset_class_code	=	@assetclass
					and		depreciable = 'Y')
		begin
	/*code added for EBS-3983 ends*/

  --EPE-8428  
	  if not exists( select  'x'    
		  from   mac_acc_ce_cc_mapping mac (nolock),    
			ard_asset_account_mst ard (nolock)      
		  where   ard.company_code   = mac.company_code   
		  and   ard.account_code  = mac.account_no    
		  and   ard.fb_id     = @fb   
		  and   ard.asset_class   = @assetclass    
		  and   ard.asset_usage   = 'DEPREC'    
		  and   upper(mac.center_no)= upper(@costcenter)  
		  )    
	   begin  
		exec fin_german_raiserror_sp 'ACAP',@ctxt_language,1900027507,@costcenter  
		return  
	   end      
   --EPE-8428  
     end--code added for EBS-3983
   end--EPE-62647
  end  
 end--MKN-1320  
   	
	--EPE-46265 starts 
	if exists(	select	'X'
				from	acap_asset_hdr_tmp(nolock)
				where	guid	=	@guid)
	begin
		return
	end
	--EPE-46265 end

 --assigning the value to the output parameter  
 select 1  'fprowno'  --epe-17029
  
 set nocount off  
end 


