/*$File_version=ms4.3.0.10$*/
/*$file name : acapcrbltgspblktgmldt.sql*/
/*$version   : 4.0.0.008*/
/*==================================================
   stored procedure : acapcrbltgspblktgmldt
   method           :acapcrbltgmtblktgmldt
   author           : functional proto ver 1.0
   created on       : 02 mar 2002 20:45:35:983
   created at       : s4141
   generated by     : Suman

   modified by      : Praveena
   modified  on     : 13th May 2003

   modified by      : Prasad
   modified  on     : 25/07/2003

   modified by      : Biju Varghese
   modified  on     :19/9/2003
   purpose          :ACAPRGGSYSTST_000134-Validatin for Tag Cost/ asset Location

   modified by      : Biju Varghese
   modified date    : 23/09/2003
   purpose	    : ACAPRGGSYSTST_000141

   modified by      : Biju Varghese
   modified date    : 01/10/2003
   purpose	    : ACAPRGGSYSTST_000134

   modified by      : Anuradha.R
   modified date    : 25-May-2004
   purpose	    : ACAPDMS41SYTST_000067

   modified by      : Anuradha.R
   modified date    : 26-May-2004
   purpose	    : ACAPDMS41SYTST_000067

*/
/*
declare @P1 int
set @P1=237
exec acapcrbltgspblktgmldt 'COMPUTER', 'ady', 'TEST', 'BR-CC1', 'finuser', 1, '2', 'acapcrbltgsrblktg', 'finuser', '', '2002-10-08', 'Y', 1.000000000000000e+000, 1, 0, @P1 output
select @P1

*/
/*Modified by		Date				Remarks		*/
/*Muthu V		4/28/04				For German Support		
  Modified BY	    : Sangeetha Sitaraman
   Modified Date    : 07-11-2005
   Purpose	    : SIN_ACAP changes code revamped(for earlier versions pls. refer the VSS)*/
/* Modified BY	    : Sangeetha Sitaraman
   Modified Date    : 10-01-2006
   Purpose	    : ACAPDMS412AT_000281						

   C.Ramesh Kumar				14.06.2016			14h109_acap_00083
   Aditya S						27/03/2018			EP-93	
   Vignesh B					03/11/2020			EPE-23559
   Nithya S						05/04/2022			EPE-43676:EPE-46537
   Harithra						02/08/2023			EPE-66921				
******************************************************************************************/
Create procedure acapcrbltgspblktgmldt
		@assetclass   		fin_assetclass  ,
		@assetlocation   	fin_assetlocation  ,
		@assetnumber   		fin_assetnumber  ,
		@costcenter   		fin_costcentercode  ,
		@creationby   		fin_ctxt_user  ,
		@ctxt_language   	fin_ctxt_language  ,
		@ctxt_ouinstance   	fin_ctxt_ouinstance  ,
		@ctxt_service   	fin_ctxt_service  ,
		@ctxt_user   		fin_ctxt_user  ,
		@inservicedate   	fin_date  ,
		@modeflag   		fin_modeflag  ,
		@tagcost   		fin_amount  	,
		@tagnumber   		fin_assettagno  ,
		@guid   		fin_guid  ,
		@fprowno   		fin_rowno  ,
		@assetclassification 	desc255, --Input 
		@natureofshift			fin_flag,  --EPE-23559
		@salvageper          fin_depprecent, --EPE-43676 
		@salvagevalue        fin_amount, --EPE-43676
		@m_errorid  		fin_int output --to return execution status
as
begin


	declare @companycode_tmp 	fin_companycode,
		@m_errout_tmp		fin_int ,
		@today 			fin_date,
		@capdate_tmp   		fin_date  ,
		@fb 			fin_financebookid,
		@retval_tmp  		fin_int,
		@fcc_status_tmp		fin_status,
		@fcc_fycode1_tmp	fin_desc40,
		@fcc_fpcode1_tmp	fin_desc40,
		@assetcost		fin_amount,
		@cost_center		fin_costcentercode,
		@errmsg			fin_desc255
		,@shift_code	    fin_documentno	--EPE-23559
		,@bargen_tmp     fin_paramcode --EPE-66921
		,@barcodetag1_tmp	 fin_barcode	

	-- nocount should be switched on to prevent phantom rows 
	set nocount on
	-- @m_errorid should be 0 to indicate success
	select @m_errorid 	= 0
	select @m_errout_tmp 	= 0
	select @retval_tmp 	= 0
	


	select @assetclass = ltrim(rtrim(@assetclass))
	if @assetclass = '~#~' 
		select @assetclass = null

	select @assetlocation = ltrim(rtrim(@assetlocation))
	if @assetlocation = '~#~' 
		select @assetlocation = null

	select @assetnumber = ltrim(rtrim(@assetnumber))
	if @assetnumber = '~#~' 
		select @assetnumber = null

	select @costcenter = ltrim(rtrim(@costcenter))
	if @costcenter = '~#~' 
		select @costcenter = null

	select @creationby = ltrim(rtrim(@creationby))
	if @creationby = '~#~' 
		select @creationby = null

	if @ctxt_language = -915 
		select @ctxt_language = null

	if @ctxt_ouinstance = -915 
		select @ctxt_ouinstance = null

	select @ctxt_service = ltrim(rtrim(@ctxt_service))
	if @ctxt_service = '~#~' 
		select @ctxt_service = null

	select @ctxt_user = ltrim(rtrim(@ctxt_user))
	if @ctxt_user = '~#~' 
		select @ctxt_user = null

	select @guid = ltrim(rtrim(@guid))
	if @guid = '~#~' 
		select @guid = null

	select @inservicedate = ltrim(rtrim(@inservicedate))
	if @inservicedate = '01/01/1900' 
		select @inservicedate = null

	select @modeflag = ltrim(rtrim(@modeflag))
	if @modeflag = '~#~' 
		select @modeflag = null

	if @tagcost = -915 
		select @tagcost = null

	if @tagnumber = -915 
		select @tagnumber = null

	if @fprowno = -915 
		select @fprowno = null
Set @assetclassification  = ltrim(rtrim(@assetclassification))
	IF @assetclassification = '~#~' 
		Select @assetclassification = null  

 Set   @natureofshift = ltrim(rtrim(@natureofshift))  
	IF @natureofshift = '~#~' 
		Select @natureofshift = null   --EPE-23559
	
	/* Code added for the defect id : EPE-43676 starts here	*/
	IF @salvageper = -915
		Select @salvageper = null  

	IF @salvagevalue = -915
		Select @salvagevalue = null  
	/* Code added for the defect id : EPE-43676 ends here	*/

	-- get date time with only datepart
	select @today = dbo.RES_Getdate(@ctxt_ouinstance)
	select @today = convert(datetime,convert(nchar(12),@today))

	/*code modified for the issue ACAPDMS412AT_0000281 begin here*/
	if @tagnumber is null
	begin
		--raiserror('Enter Number of Tags',16,1)
		exec fin_german_raiserror_sp 'ACAP',@ctxt_language,92,'' ,'' ,'' , '','','','',@errmsg output
		return
	end
	/*code modified for the issue ACAPDMS412AT_0000281 end here*/



	if @inservicedate is null
	begin
		select 	@inservicedate 	= cap_date 
		from 	acap_asset_hdr (nolock) 
		where 	ou_id 		= @ctxt_ouinstance
		and 	asset_number 	= upper(@assetnumber)
	end
	else 
	begin
		select 	@capdate_tmp 	= cap_date ,
			@fb		= fb_id
		from 	acap_asset_hdr (nolock) 
		where 	ou_id 		= @ctxt_ouinstance
		and 	asset_number 	= upper(@assetnumber)

		if @inservicedate < @capdate_tmp
		begin
			--RAISERROR('Inservice Date Can  Not be Earlier Than Capitalization Date',16,1)
			select @m_errorid = 3455391
			return
		end

	end


	exec @retval_tmp = fcc_sysact_spvaltrndate 	@ctxt_ouinstance, 'ACAP',@ctxt_user,
							@fb,@inservicedate , @fcc_status_tmp output, 
							@fcc_fycode1_tmp output,
							@fcc_fpcode1_tmp output,@ctxt_language

	-- errors to be mapped from IS
	-- 1 - transaction date is in closed period or year of the bfg ou.
	-- 2 - transaction date is in closed period or year of the finance book.
	-- 3 - period or year is not defined in the financial calender for a company corresponding to the given transaction date 
	-- 4 - provide organisation unit
	-- 5 - provide component name
	-- 6 - provide finance book id
	-- 7 - provide transaction date
	
	if ( @retval_tmp <> 0 )	
	begin	
	        --RAISERROR('Transaction date is  not valid for the finanacial period',16,1)
	        select @m_errorid = 3455392
		return		
	end


	if @assetlocation is null
	begin
		--RAISERROR('Enter Asset Location',16,1)
		select @m_errorid = 3455393
		return
	end


	if  not exists (select 'x' from aloc_location_vw (nolock)
			where 	ou_id 		in(select c.destinationouinstid
						from 	acap_cim_intxn_model_vw c (nolock), 
							emod_ou_vw  b (nolock)
						where c.sourceouinstid 		= @ctxt_ouinstance
						and c.sourcecomponentname 	= 'ACAP'
						and b.ou_id			= c.destinationouinstid
						and @today 			between b.effective_from 
										and isnull(b.effective_to,@today)
						and c.destinationcomponentname 	= 'ALOC')
			and 	upper(loc_code) = upper(@assetlocation)
			and 	loc_status 	= 'A')
	begin
		--RAISERROR('Asset Location is not Valid',16,1)
		select @m_errorid = 3455394
		return
	end


	-- location exists or not and CIM interaction between ACAP and ALOC		
	if  not exists (select 'x' from aloc_location_vw (nolock)
			where ou_id 		= @ctxt_ouinstance	
			and upper(loc_code) 	= upper(@assetlocation)
			and loc_status 		= 'A')
	and not exists (select 'x'
			from acap_cim_intxn_model_vw c (nolock), emod_ou_vw  b (nolock)
			where c.sourceouinstid 		= @ctxt_ouinstance
			and c.sourcecomponentname 	= 'ACAP'
			and b.ou_id 			= c.destinationouinstid
			and @today 			between b.effective_from 
							and isnull(b.effective_to,@today)
			and c.destinationcomponentname 	= 'ALOC')

	begin
		exec fin_sp_raise_error '', '', '', '','ACAP',63,@m_errorid output
		return
	end


	select 	@companycode_tmp = company_code 
	from 	emod_ou_vw (nolock)
	where 	ou_id 		= @ctxt_ouinstance


	if @costcenter is not null 
	and not exists ( select 'x'from mac_cost_center_vw (nolock)
			where 	upper(ma_center_no) 	= upper(@costcenter)
			and 	company_code 		= @companycode_tmp
			and 	ma_status 		= 'A')
	begin
		exec fin_sp_raise_error '', '', '', '','ACAP',237,@m_errorid output
		return
	end		


	if @tagcost is null
	begin 
		exec fin_sp_raise_error '', '', '', '','ACAP',42,@m_errorid output
		return
	end

	if @tagcost <= 0
	begin 
		--RAISERROR('Tag Cost Should be greater than zero',16,1)
		select @m_errorid = 3455395
		return
	end

	select 	@assetcost	= asset_cost,
		@cost_center	= cost_center
	from 	acap_asset_hdr (nolock)
	where 	ou_id 		= @ctxt_ouinstance
	and 	asset_number 	= @assetnumber


	if @cost_center <> @costcenter
	begin
		--raiserror('Asset cost center and the Tag cost center should to be the same',16,1)
		exec fin_german_raiserror_sp 'ACAP',@ctxt_language,91,'' ,'' ,'' , '','','','',@errmsg output
		return
	end

	--EPE-23559 starts
   select  @shift_code = parameter_code
	from    fin_quick_code_met(nolock)
	where   component_id		 =      'ACAP'     
	and     parameter_type		 =      'CBO' 
	and	    parameter_category	 =		'NAT_SFT'
	and		parameter_text		 =		@natureofshift	  
	--EPE-23559 ends

	/*code added for EPE-43676 begins here */
	--EPE-46537
	if isnull(@salvagevalue,0) > @tagcost
	begin
		--Salvage Value should not be greater than Tag Cost at rowno
		exec fin_german_raiserror_sp 'FAHUB',@ctxt_language,86,@fprowno 
		return
	end

	if isnull(@salvagevalue,0) < 0 
	begin
		--Salvage value cannot be lesser than Zero at Row no 
		exec fin_german_raiserror_sp 'FAHUB',@ctxt_language,87,@fprowno
		return
	end--EPE-46537

	if isnull(@salvageper,0) < 0 or isnull(@salvageper,0) > = 100
	begin
		--Salvage value % can be between 1 to 100 %. Modify details.
		exec fin_german_raiserror_sp 'ACAP',@ctxt_language,20000
		return
	end

	if @salvagevalue is null and @salvageper is not null
	begin
		select @salvagevalue	=	(@tagcost *@salvageper/100)
	end
	else if @salvagevalue is not null and @salvageper is not null
	begin
		select @salvagevalue	=	@salvagevalue
	end
	/*code added for EPE-43676 ends here */

	if not exists (select 'x' from acap_asset_tag_dtl (nolock)	  
				where ou_id 		= @ctxt_ouinstance
				and asset_number 	= @assetnumber
				and tag_number 		= @tagnumber ) 
	begin
		insert into acap_asset_tag_dtl	
		( asset_number ,tag_number , ou_id ,timestamp ,
		asset_desc , tag_desc , asset_location ,cost_center , inservice_date , tag_cost , 
		tag_status ,proposal_number,depr_category , inv_cycle ,salvage_value ,business_use,
		createdby , createddate ,modifiedby , modifieddate , 
		cap_number,policy_count,fb_id
		,manufacturer,	bar_code,	custodian,	serial_no,	warranty_no,	model,asset_category,asset_cluster--14h109_acap_00083
		,natureofshift	--Added by Vignesh B for EPE-23559
		,salvage_valper--EPE-43676
		)
		select @assetnumber , @tagnumber , @ctxt_ouinstance , 1 , 
		asset_desc , tag_desc ,  @assetlocation , @costcenter , @inservicedate , @tagcost ,
		'FR' ,proposal_number, depr_category , inv_cycle ,@salvagevalue ,business_use,
		@ctxt_user , dbo.RES_Getdate(@ctxt_ouinstance) ,@ctxt_user , dbo.RES_Getdate(@ctxt_ouinstance) ,
		cap_number,policy_count,fb_id
		,manufacturer,	bar_code,	custodian,	serial_no,	warranty_no,	model--14h109_acap_00083
		,asset_category,asset_cluster
		,@shift_code --Added by Vignesh B for EPE-23559
		,@salvageper--EPE-43676
		from acap_asset_tag_dtl (nolock) 
		where ou_id 		= @ctxt_ouinstance
		and asset_number 	= upper(@assetnumber)
		and tag_number 		= 1


		insert into acap_tag_doc_dtl 
		(cap_number ,ou_id ,asset_number , tag_number , doc_number , timestamp ,
		doc_amount , createdby ,  createddate , modifiedby , modifieddate,
		line_no,doc_type ,proposal_number ,cap_amount,fb_id,account_code,tran_ou,tran_type,tag_cost,cost_center) --EP-93	
		select  cap_number ,ou_id  , asset_number , @tagnumber , doc_number , 1 ,
		doc_amount , createdby , createddate ,modifiedby , modifieddate,
		line_no,doc_type ,proposal_number,cap_amount,  fb_id,account_code,tran_ou,tran_type,@tagcost,cost_center --EP-93
		from    acap_tag_doc_dtl (nolock) 
		where 	ou_id 		= @ctxt_ouinstance
		and 	asset_number 	= upper(@assetnumber)
		and 	tag_number 	= 1

		
	end
	else
	begin
		update acap_asset_tag_dtl 
		set 	asset_location 	= @assetlocation ,
			cost_center 	= @costcenter , 
			inservice_date 	= @inservicedate ,
			tag_cost 	= @tagcost
			, natureofshift = @shift_code	--EPE-23559
			,salvage_value	= @salvagevalue,--EPE-43676
			salvage_valper	= @salvageper--EPE-43676
		where 	ou_id 		= @ctxt_ouinstance
		and 	asset_number 	= @assetnumber
		and 	tag_number 	= @tagnumber
		
		update acap_tag_doc_dtl 
		set 	tag_cost 	= @tagcost
		where 	ou_id 		= @ctxt_ouinstance
		and 	asset_number = @assetnumber
		and 	tag_number 	= @tagnumber
		
	end
	

	--Update barcode for the asset - tag starts here 
	--EPE-66921
	if exists(	select 'X' from cps_processparam_vw(nolock)
				where company_code = @companycode_tmp
				and parameter_type = 'FASYS'
				and parameter_code = 'autogenbarcode'
				and language_id	   = @ctxt_language)
	begin

		select @bargen_tmp = parameter_value 
		from cps_processparam_vw(nolock)
		where company_code = @companycode_tmp
		and parameter_type = 'FASYS'
		and parameter_code = 'autogenbarcode'
		and language_id	   = @ctxt_language
	end
	else
	begin
		select @bargen_tmp = 'N'
	end

	select @barcodetag1_tmp  = ''

	if @tagnumber = 1
	begin
		select	@barcodetag1_tmp = bar_code
		from	acap_asset_tag_dtl(nolock)
		where 	ou_id 		= @ctxt_ouinstance
		and 	asset_number = @assetnumber
		and 	tag_number 	= @tagnumber

	end

	if isnull(@bargen_tmp,'N') <> 'N' --and isnull(@barcodetag1_tmp,'') = ''
	begin

			update acap_asset_tag_dtl
			set bar_code = ''
			where 	ou_id 		= @ctxt_ouinstance
			and 	asset_number = @assetnumber
			and 	tag_number 	= @tagnumber

		exec Acap_Barcode_Gen_sp @ctxt_language ,
								 @ctxt_ouinstance,
								 @ctxt_service,
								 @ctxt_user,
								 @assetnumber,
								 @tagnumber,
								 @bargen_tmp
	end

	--EPE-66921
	--update barcode for the asset - tag end here
	 select @fprowno+1 'fprowno'
	
	set nocount off

end

