/*$File_version=ms4.3.0.02$*/
/*$file name : acapaucjmspcomtothref.sql*/
/*$version   : 4.0.0.2*/
/*==================================================
   stored procedure 				:acapaucjmspcomtothref
   method           				:acapaucjmmtcomtothref
   author           				:functional proto ver 1.0
   created on       				:26 may 2001 13:34:46:420
   created at       				:s4036
   generated by     				:kishore a
   purpose					: this method will refresh the hdr controls

   modified by 					: Swetha
   date                                         : 13/12/2005
   purpose                                      : ACAPDMS412AT_000184 

Modification History	
Modified by		Modified Date		Remarks
Uma Maheswari		28th Dec 2006		ACAPDMS412AT_000576 (Bookwise Capitalization)
Abhijith KP			23-08-2023			EPE-62647:EPE-68248

 proc acapaucjmspcomtothref
grant exec on acapaucjmspcomtothref to public
 
*/
Create procedure acapaucjmspcomtothref
	@ctxt_language   			fin_ctxt_language  ,
	@ctxt_ouinstance   			fin_ctxt_ouinstance  ,
	@ctxt_service   			fin_ctxt_service  ,
	@ctxt_user   				fin_ctxt_user  ,
	@credittransactiontotal   		fin_amount  ,
	@cvouchertypeenn   			fin_desc40  ,
	@debittransactiontotal   		fin_amount  ,
	@fbhdr   				fin_financebookid  ,
	@guid   				fin_guid  ,
	@jvnarration   				fin_comments  ,
	/* code modified by swetha for ACAPDMS412AT_000184 on 13/12/2005 */
	@reversalperiod   			fin_financeperiodrange  ,
	/* code modified by swetha for ACAPDMS412AT_000184 on 13/12/2005 */
	@status   				fin_status  ,
	@transactiondate   			datetime  ,
	@voucherno   				fin_documentno  ,
	/*Code added by Uma for the bug id : ACAPDMS412AT_000576 starts here*/
	@DeprBook				fin_deprkey	,
	/*Code added by Uma for the bug id : ACAPDMS412AT_000576 ends here*/
	@m_errorid  				int output --to return execution status
as
begin

    set nocount on

--BEGIN of Standard code for getting precision type
    declare  @pqty_tmp                  fin_int ,
             @pamt_tmp                  fin_int ,
             @prate_tmp                 fin_int ,
             @perate_tmp                fin_int ,
             @phigh_tmp                 fin_int ,
             @pmed_tmp                  fin_int ,
             @plow_tmp                  fin_int

    exec fin_sp_precisiontype_rtr @pqty_tmp output, @pamt_tmp output,
             @prate_tmp output, @perate_tmp output, @phigh_tmp output,
             @pmed_tmp output, @plow_tmp output

--END of Standard code for getting precision type

     -- nocount should be switched on to prevent phantom rows 
     set nocount on
     -- @m_errorid should be 0 to indicate success
     select @m_errorid =0
     if @ctxt_language = -915 
          select @ctxt_language = null
     if @ctxt_ouinstance = -915 
          select @ctxt_ouinstance = null
     select @ctxt_service = ltrim(rtrim(@ctxt_service))
     if @ctxt_service = '~#~' 
          select @ctxt_service = null
     select @ctxt_user = ltrim(rtrim(@ctxt_user))
     if @ctxt_user = '~#~' 
          select @ctxt_user = null
     if @credittransactiontotal = -915 
          select @credittransactiontotal = null
     if @debittransactiontotal = -915 
          select @debittransactiontotal = null
     select @fbhdr = ltrim(rtrim(@fbhdr))
     if @fbhdr = '~#~' 
          select @fbhdr = null
     select @guid = ltrim(rtrim(@guid))
     if @guid = '~#~' 
          select @guid = null
     select @jvnarration = ltrim(rtrim(@jvnarration))
     if @jvnarration = '~#~' 
          select @jvnarration = null
     select @reversalperiod = ltrim(rtrim(@reversalperiod))
     if @reversalperiod = '~#~' 
          select @reversalperiod = null
     select @status = ltrim(rtrim(@status))
     if @status = '~#~' 
          select @status = null
     select @transactiondate = ltrim(rtrim(@transactiondate))
     if @transactiondate = '01-01-1900' 
          select @transactiondate = null
     select @voucherno = upper(ltrim(rtrim(@voucherno)))
     if @voucherno = '~#~' 
          select @voucherno = null

	/*Code added by Uma for the bug id : ACAPDMS412AT_000576 starts here*/
	select @DeprBook = ltrim(rtrim(@DeprBook))
	if @DeprBook = '~#~' 
		select @DeprBook = null
	/*Code added by Uma for the bug id : ACAPDMS412AT_000576 ends here*/

	select @credittransactiontotal = sum (tran_amount)
	from acap_journal_tmp(nolock)
	where guid = @guid
	and voucher_number = @voucherno
	and drcr_flag = 'CR'
	
	select @debittransactiontotal = sum (tran_amount)
	from acap_journal_tmp(nolock)
	where guid = @guid
	and voucher_number = @voucherno
	and drcr_flag = 'DR'	

	select      
		@credittransactiontotal 			'credittransactiontotal',
		@debittransactiontotal 				'debittransactiontotal',     
		@fbhdr 						'fbhdr',
		@guid 						'guid',
		@jvnarration					'jvnarration',
		@reversalperiod 				'reversalperiod',
		@status 					'status',
		convert(nvarchar(10),@transactiondate,120) 	'transactiondate',
		@voucherno 					'voucherno',
		--Code added by Uma for the bug id : ACAPDMS412AT_000576
		@DeprBook					'DeprBook', 	
		@cvouchertypeenn			'cvouchertypeenn'--EPE-62647:EPE-68248

	set nocount off
end





