/*$File_version=ms4.3.0.011$*/
/*$file name : acapaucjmspaujrnhdrchk.sql*/
/*$version   : 4.0.0.14*/
/*===================================================
stored procedure 	:acapaucjmspaujrnhdrchk
method           	:acapaucjmmtaujrnhdrchk
author           	:functional proto ver 1.0
created on       	:28 feb 2002 00:28:42:500
created at       	:s4036
generated by     	:kishore a
purpose			:this method will calcualte the base debit and base credit amount.it will update
			 transaction amount in hdr table.it will throw an error if tey doesnt match wth each
			 other

Modified By		: Swetha
Modified Date    	: 17/01/2006
Purpose	    		: FA CODE REVAMP(For Earlier version  Pls Refer Sourcesafe)

Modified By		: Swetha
Modified Date    	: 15/02/2006
Purpose	    		: ACAPDMS412AT_000346

Modified By		: Swetha
Modified Date    	: 17/02/2006
Purpose	    		: ACAPDMS412AT_000349


Modified By		: Swetha
Modified Date    	: 23/02/2006
Purpose	    		: ACAPDMS412AT_000351


Modified By		: Swetha
Modified Date    	: 09/03/2006
Purpose	    		: ACAPDMS412AT_000375


Modified By		: Swetha
Modified Date    	: 22/03/2006
Purpose	    		: ACAPDMS412AT_000393

grant exec on acapaucjmspaujrnhdrchk to public
*/
/************************************************************************************/
/********************************************************************************/
/*Modified by        : Swetha                                                   */
/*Modified Date      : 5/5/2006                                                 */
/*Purpose            : CML Changes                                              */
/********************************************************************************/
/********************************************************************************/
/*Modified by        : Swetha                                                   */
/*Modified Date      : 7/6/2006                                                 */
/*Purpose            : ACAPDMS412AT_000464                                      */
/********************************************************************************/
/********************************************************************************/
/*Modified by        : Swetha                                                   */
/*Modified Date      : 7/6/2006                                                 */
/*Purpose            : ACAPDMS412AT_000440                                      */
/*
Modification History	
Modified by		Modified Date		Remarks
Uma Maheswari		28th Dec 2006		ACAPDMS412AT_000576
Aparna M.		06/01/2007		ADEPPDMS412AT_000285
Uma Maheswari		12th Jan 2007		ACAPDMS412AT_000599
Uma Maheswari		08th Feb 2007		ACAPDMS412AT_000621
Esther J		18/05/2007		ACAPDMS412AT_000710
Uma Maheswari    	13th June 2007	 	AINQDMS412AT_000030 
Uma Maheswari    	10th Mar 2008		DMS412AT_REPSFAM_00074
T.Suresh	    	25th OCT 2010		Es_adepp_00099
Aditya Sitaraman	04/02/2014			ES_ACAP_00550
C.Ramesh Kumar		22.7.2015			es_jv_00648
Nithya S			26/08/2015			14H109_ACAP_00059
Ashok V				06/03/2018			EP-96
Amrutha R.S			04/10/2018			EPE-7189
Srinivasan M        11-06-2023          TC-1561
Saranraj C          16/06/2023          TIS-1339
Srinivasan M        04/07/2023          RPE-169
Saranraj C          13/09/2023          EBS-6081
*/
/********************************************************************************/
Create  procedure acapaucjmspaujrnhdrchk
	@createddate   				fin_date  ,
	@creationby   				fin_ctxt_user  ,
	@credittransactiontotal   		fin_amount  ,
	@ctxt_language   			fin_ctxt_language  ,
	@ctxt_ouinstance   			fin_ctxt_ouinstance  ,
	@ctxt_service   			fin_ctxt_service  ,
	@ctxt_user   				fin_ctxt_user  ,
	@cvouchertypeenn   			fin_desc40  ,
	@debittransactiontotal   		fin_amount  ,
	@fbhdr   				fin_financebookid  ,
	@guid   				fin_guid  ,
	@jvnarration   				fin_comments  ,
	@lastmodificationby   			fin_ctxt_user ,
	@lastmodifieddate   			fin_date  ,
	@ouinstid				fin_int ,
        /* code modified for acap issue */
	@reversalperiod   			fin_financeperiodrange  ,
      /* code modified for acap issue */
	@status   				fin_status  ,
	@timestamp   				fin_timestamp  ,
	@transactiondate   			fin_date  ,
	@voucherno   				fin_documentno  ,
	@wfdockey				fin_desc120 ,
	@wforgunit				fin_int ,
	/*Code added by Uma for the bug id : ACAPDMS412AT_000576 starts here*/
	@DeprBook				fin_deprkey	,
	/*Code added by Uma for the bug id : ACAPDMS412AT_000576 ends here*/
	@errorno				fin_errorno ,
	@fprowno   				fin_rowno  ,
	@placeholder1				fin_placeholder ,
	@placeholder2				fin_placeholder ,
	@placeholder3				fin_placeholder ,
	@placeholder4				fin_placeholder ,
	@successflag				fin_successflag	,
	@m_errorid  				fin_int output --to return execution status
as
begin
	declare 	
	@drtransactiontotal_tmp   		fin_amount,
	@crtransactiontotal_tmp   		fin_amount,
	--@sum_tran_amount_cur 			fin_amount, 
	--@account_code_cur 			fin_accountcode,	
	--@drcr_flag_cur				fin_desc20 , 
	--@asset_flag_cur				fin_flag,
	--@currency_code_cur			fin_currencycode,
	--@guid_tmp 				fin_guid ,
	@retval_tmp				fin_int ,
	@errorid_tmp				fin_int,
	@companycode				fin_companycode,
	@buid_tmp				fin_buid,
	@fycode_tmp				fin_financeyear,
	@fpcode_tmp				fin_financeperiod,
	@notypeno   				fin_notypeno ,
	@asset_number				fin_assetnumber,
	@tag_number				fin_assettagno,
	--@cost_center				fin_costcentercode,
	--@depr_book				fin_deprkey,
	--@depr_proc_runno			fin_deprkey,
	--@tag_status				fin_status,
	--@depr_charge				fin_amount,
	--@fin_period				fin_calendarcode,
	--@susp_charge				fin_amount,
	--@rev_doc_no				fin_documentnumber,
	@depr_category				fin_deprcategory,
	@asset_class				fin_assetclass,
	@cvouchertypeenn_tmp			fin_documenttype,
	@pamt_tmp                  		fin_int,
	@proposalnumberml			fin_documentno,
	@drcr_flag				fin_flag,
	@assetcost				fin_amount,
	--@rev_depcharge				fin_amount,
    @ref_voucher_no                         fin_documentnumber
    ,@parameter_value       fin_paramcode	--code added for ES_ACAP_00550
						

--BEGIN of Standard code for getting precision type
	declare  @pqty_tmp                  fin_int ,
		@prate_tmp                 fin_int ,
		@perate_tmp                fin_int ,
		@phigh_tmp                 fin_int ,
		@pmed_tmp                  fin_int ,
		@plow_tmp                  fin_int

	exec fin_sp_precisiontype_rtr @pqty_tmp output, @pamt_tmp output,
	@prate_tmp output, @perate_tmp output, @phigh_tmp output,
	@pmed_tmp output, @plow_tmp output

	--acap_journal_tmp

	-- nocount should be switched on to prevent phantom rows 
	set nocount on
	if @ouinstid = -915 
		select @ouinstid = null
		select @createddate = ltrim(rtrim(@createddate))
	if @createddate = '01-01-1900' 
		select @createddate = null
		select @creationby = ltrim(rtrim(@creationby))
	if @creationby = '~#~' 
		select @creationby = null
	if @credittransactiontotal = -915 
		select @credittransactiontotal = null
	if @ctxt_language = -915 
		select @ctxt_language = null
	if @ctxt_ouinstance = -915 
		select @ctxt_ouinstance = null
		select @ctxt_service = ltrim(rtrim(@ctxt_service))
	if @ctxt_service = '~#~' 
		select @ctxt_service = null
		select @ctxt_user = ltrim(rtrim(@ctxt_user))
	if @ctxt_user = '~#~' 
		select @ctxt_user = null
		select @cvouchertypeenn = ltrim(rtrim(@cvouchertypeenn))
	if @cvouchertypeenn = '~#~' 
		select @cvouchertypeenn = null
	if @debittransactiontotal = -915 
		select @debittransactiontotal = null
		select @fbhdr = ltrim(rtrim(@fbhdr))
	if @fbhdr = '~#~' 
		select @fbhdr = null
		select @guid = ltrim(rtrim(@guid))
	if @guid = '~#~' 
		select @guid = null
		select @jvnarration = ltrim(rtrim(@jvnarration))
	if @jvnarration = '~#~' 
		select @jvnarration = null
		select @lastmodificationby = ltrim(rtrim(@lastmodificationby))
	if @lastmodificationby = '~#~' 
		select @lastmodificationby = null
		select @lastmodifieddate = ltrim(rtrim(@lastmodifieddate))
	if @lastmodifieddate = '01-01-1900' 
		select @lastmodifieddate = null
		select @reversalperiod = ltrim(rtrim(@reversalperiod))
	if @reversalperiod = '~#~' 
		select @reversalperiod = null
		select @status = ltrim(rtrim(@status))
	if @status = '~#~' 
		select @status = null
	if @timestamp = -915 
		select @timestamp = null
		select @transactiondate = ltrim(rtrim(@transactiondate))
	if @transactiondate = '01-01-1900' 
		select @transactiondate = null
		select @voucherno = ltrim(rtrim(@voucherno))
	if @voucherno = '~#~' 
		select @voucherno = null
	if @fprowno = -915 
		select @fprowno = null

	/*Code added by Uma for the bug id : ACAPDMS412AT_000576 starts here*/
	select @DeprBook = ltrim(rtrim(@DeprBook))
	if @DeprBook = '~#~' 
		select @DeprBook = null
	/*Code added by Uma for the bug id : ACAPDMS412AT_000576 ends here*/


        -- to get the voucher type for the seleted
	select @cvouchertypeenn_tmp = parameter_code
	from fin_quick_code_met (nolock)
	where component_id = 'ACAP'
	and parameter_type = 'CBO'
	and parameter_category = 'VOU_TYP'
	and parameter_text  = @cvouchertypeenn
	and language_id = @ctxt_language

	/*Code added by EBS-6081 starts*/
	declare @acap_voucher_type		   fin_desc40 

	select @acap_voucher_type = voucher_type
	from   acap_journal_hdr (nolock)
	where  voucher_number     = @voucherno
	and    ou_id              = @ctxt_ouinstance

	if @cvouchertypeenn_tmp <> @acap_voucher_type
	begin
		--raiserror('Voucher type cannot be modified.',16,1)
		exec fin_german_raiserror_sp 'ACAP',@ctxt_language,1900027516
		return
	end
	/*Code added by EBS-6081 ends*/

	--code commented below and added here for es_jv_00648
	select @companycode = company_code  ,
	@buid_tmp    	    = bu_id 
	from   emod_ou_vw(nolock)
	where  ou_id 	    = @ctxt_ouinstance


	if not exists (	select '1'
			from acap_journal_tmp (nolock)
			where ou_id = @ctxt_ouinstance
			and guid = @guid)
	begin
		exec fin_sp_raise_error '', '', '', '', 'ACAP',6 , @m_errorid output
		return					
	end
	exec  acapcjspcomvalidate @ctxt_language,@ctxt_ouinstance,@ctxt_service,
				   @ctxt_user,@guid,@fbhdr,@transactiondate,@cvouchertypeenn,@retval_tmp  output

	 if (@retval_tmp <> 0)
	begin 
		select @errorid_tmp = case @retval_tmp
				when  100 then 196
			        when  101 then 197
				when  102 then 235
				when  103 then 149
				when  104 then 217
				when  105 then 110
				when  106 then 152
				when  107 then 900004524
				when  108 then 143
				when  109 then 160
				when  110 then 47
				when  111 then 162
				when  112 then 900004539
			        when  113 then 186
				when  114 then 245
				when  115 then 246
				when  116 then 152
				when  117 then 247
				when  118 then 900004510
				when  119 then 900004512
				when  120 then 900004523
				when  121 then 240
				when  122 then 111
				when  123 then 900004526
				when  124 then 240
				when  125 then 111
				when  126 then 164
				when  127 then 900004514
				when  128 then 900004515
				when  129 then 48
				when  130 then 49
				when  131 then 900004513
				when  132 then 167
				when  133 then 180
				when  134 then 181
				when  135 then 182
				when  136 then 183
				when  137 then 184
				when  138 then 185
				when  139 then 117
				when  140 then 222
				when  141 then 223
				when  142 then 224
				when  143 then 225
				when  144 then 226
				when  145 then 227
				when  146 then 228
				when  147 then 229			
				when  148 then 900004538
				when  149 then 900004517
				when  150 then 149
				when  151 then 265
				when  152 then 266
				when  153 then 167
				when  154 then 180
				when  155 then 181
				when  156 then 182
				when  157 then 900004525
			/* code modified by Swetha for ACAPDMS412AT_000375 on 09/03/2006 */
				when  158 then 900004646
			/* code modified by Swetha for ACAPDMS412AT_000375 on 09/03/2006 */
		end
		select @m_errorid = @errorid_tmp
		return
	end
				
	-- to check whether atleast one asset account is there or not
	if not exists(	select '1'
				from acap_journal_tmp(nolock)
				where guid = @guid
				and asset_flag = 'Y')
	begin	--1
		exec fin_sp_raise_error '', '', '', '', 'ACAP',238,@m_errorid output
		return		
	end		--1


	select @drtransactiontotal_tmp = sum(tran_amount )
	from acap_journal_tmp (nolock)
	where ou_id = @ctxt_ouinstance
	and guid = @guid
	and drcr_flag = 'DR'
	

	select @crtransactiontotal_tmp = sum(tran_amount )
	from acap_journal_tmp (nolock)
	where ou_id = @ctxt_ouinstance
	and guid = @guid
	and drcr_flag = 'CR'
	
	if(isnull(@crtransactiontotal_tmp,0) <>isnull(@drtransactiontotal_tmp,0))
	begin
		exec fin_sp_raise_error '', '', '', '', 'ACAP',17 ,@m_errorid output
		return	
	end
	
	declare	@timestamp_tmp	fin_int

	select @timestamp_tmp = timestamp
	from acap_journal_hdr (nolock)
	where voucher_number = @voucherno
	and ou_id = @ctxt_ouinstance
		
	if (@timestamp <> @timestamp_tmp)
	begin
		--exec fin_sp_raise_error '', '', '', '', 'ACAP',7 , @m_errorid output
		exec fin_german_raiserror_sp 'HI',@ctxt_language,15
		return	
	end	
        /*Code commented by Swetha for ACAPDMS412AT_000464 on 7/6/2006 */

-- 	--to check whether the balances are avialble for the account codes
-- 
-- 	declare acc_cursor cursor for
-- 	select sum(tran_amount),account_code,drcr_flag,asset_flag,currency_code
-- 	from acap_journal_tmp (nolock)
-- 	where guid = @guid
-- 	group by account_code,drcr_flag,asset_flag,currency_code
-- 	
-- 	open acc_cursor
-- 	fetch next from acc_cursor 
-- 	into @sum_tran_amount_cur , @account_code_cur ,	@drcr_flag_cur , 
-- 	@asset_flag_cur,@currency_code_cur
-- 
-- 	while @@fetch_status = 0
-- 	begin		--2
-- 
--                 execute fbp_sysact_actbal_date @ctxt_ouinstance ,
--                 		@fbhdr ,
--                 		@account_code_cur ,
--                 		@currency_code_cur ,
--                 		@transactiondate ,
--                 		'YTOD' ,
--                 		'' ,
--                 		'' ,
--                                 @guid_tmp output,
--                 		@retval_tmp output,
--                                 @ctxt_language
--  
-- /* 1 - Provide OUInstance 
--  2 - Provide FB 
--  3 - Provide Account Code 
--  4 - Provide Currency 
--  5 - Invalid As on Date 
--  6 - Provide Year to Date 
--  7 - Invalid Year to Date 
--  8 - As on Date greater then the System Date 
--  9 - Provide Analysis Code */
-- 
-- 			if ( @retval_tmp <> 0 )	
-- 				begin	--2.1
-- 					select @errorid_tmp = case (@retval_tmp)
-- 				    	when 1 then 109
-- 				        when 2 then 110
-- 						when 3 then 111
-- 						when 4 then 112
-- 						when 5 then 113
-- 						when 6 then 114
-- 						when 7 then 115
-- 						when 8 then	116
-- 						when 9 then 117
-- 					end
-- 					exec fin_sp_raise_error '', '', '', '', 'ACAP',@errorid_tmp,@m_errorid output
-- 					return		
-- 				end		--2.2	
-- 					
-- 			if (@asset_flag_cur = 'Y')
-- 				begin	--2.3 account code is an asset account code
-- 					if (@drcr_flag_cur = 'CR')
-- 						begin		--2.3.1
-- 							if not exists (	select '1' 
-- 											from fbp_actbal_date_range_vw(nolock)
-- 											where guid = @guid_tmp
-- 											and closing_balance >= @sum_tran_amount_cur
-- 											and cb_drcr = 'DR')
-- 								begin		--2.3.1.1
-- 									exec fin_sp_raise_error '', '', '', '', 'ACAP',239,@m_errorid output
-- 									return		
-- 								end			--2.3.1.1
-- 						end		--2.3.1
-- 				end		--2.3
-- 			else
-- 				begin	--2.4
-- 					if (@drcr_flag_cur = 'CR')
-- 						begin	--2.4.1
-- 							if not exists (	select '1' 
-- 											from fbp_actbal_date_range_vw(nolock)
-- 											where guid = @guid_tmp
-- 											and closing_balance >= @sum_tran_amount_cur
-- 											and cb_drcr = 'DR')
-- 								begin		--2.4.1.1
-- 									exec fin_sp_raise_error '', '', '', '', 'ACAP',239,@m_errorid output
-- 									return		
-- 								end		--2.4.1.1
-- 						end		--2.4.1
-- 					else	-- non asset account with drcr flag DR
-- 						begin	--2.4.2
-- 							if not exists (	select '1' 
-- 											from fbp_actbal_date_range_vw(nolock)
-- 											where guid = @guid_tmp
-- 											and closing_balance >= @sum_tran_amount_cur
-- 											and cb_drcr = 'CR')
-- 								begin		--2.4.2.1
-- 									exec fin_sp_raise_error '', '', '', '', 'ACAP',239,@m_errorid output
-- 									return		
-- 								end			--2.4.2.1
-- 						end			--2.4.2
-- 				end		--2.4
-- 			fetch next from  acc_cursor
--  			into @sum_tran_amount_cur , @account_code_cur ,	@drcr_flag_cur , 
-- 			@asset_flag_cur,@currency_code_cur
-- 		end		--2
-- 	
-- 	close	acc_cursor
-- 	deallocate acc_cursor
        
        /*Code commented by Swetha for ACAPDMS412AT_000464 on 7/6/2006 */
	
	/* code added by Swetha for ACAPDMS412AT_000346 on 15/02/2006 */

        /* code modified by Swetha for ACAPDMS412AT_000440 on 26/6/2006 */

	-- deleting the rows from dtl table
	delete from acap_journal_dtl
	where voucher_number = @voucherno
	and ou_id 	     = @ctxt_ouinstance

	-- inserting the rows from temporary table to dtl table
		
	insert into acap_journal_dtl	(asset_number,tag_number,ou_id,voucher_number,timestamp,
	account_code,drcr_flag,tran_amount,remarks,cost_center,analysis_code,
	subanalysis_code,createdby,createddate,proposal_no
	,Depr_Book ) --Code added by Uma for the bug id : ACAPDMS412AT_000576
	select 	asset_number,tag_number,ou_id,voucher_number,timestamp,
	account_code,drcr_flag,tran_amount,remarks,cost_center,analysis_code,
	subanalysis_code,createdby,createddate , proposal_no
	,@DeprBook --Code added by Uma for the bug id : ACAPDMS412AT_000576
	from acap_journal_tmp (nolock)
	where guid = @guid

        if (@cvouchertypeenn_tmp = 'RE')
        begin 

                select @ref_voucher_no = ref_voucher_no 
                from   acap_journal_hdr(NOLOCK)
                where  voucher_number = @voucherno
	        and    ou_id = @ctxt_ouinstance
	
                delete from acap_journal_dtl
		where voucher_number = @ref_voucher_no
		and   ou_id          = @ctxt_ouinstance

                insert into acap_journal_dtl(asset_number,tag_number,ou_id,voucher_number,timestamp,
		account_code,drcr_flag,tran_amount,remarks,cost_center,analysis_code,
		subanalysis_code,createdby,createddate,proposal_no
		,Depr_Book ) --Code added by Uma for the bug id : ACAPDMS412AT_000576
		select 	asset_number,tag_number,ou_id,@ref_voucher_no,timestamp,
		account_code,case drcr_flag when  'DR' then 'CR'
                                  when 'CR' then 'DR'
                             end ,tran_amount,remarks,cost_center,analysis_code,
		subanalysis_code,createdby,createddate , proposal_no
		,@DeprBook  --Code added by Uma for the bug id : ACAPDMS412AT_000576
		from acap_journal_tmp (nolock)
		where guid = @guid

				--code added for es_jv_00648 starts
				declare @posting_date fin_date
                select 	@posting_date 		= fin_period_stdt
                from 	fcc_sysact_allperiod_vw (nolock)
                where 	close_status 		= 'O'
                and 	company_code   		= @companycode
                and 	financeperiodrange 	like @reversalperiod  + '%'  	--Code modified by EBS-6081
				--code added for es_jv_00648 ensa


            update acap_journal_hdr
        	set tran_amount 			= round(@debittransactiontotal,@pamt_tmp),
        	journal_status 				= 'AC', /*'FR' --es_jv_00648*/ --es_jv_00648 fix reverted by EBS-6081
        	remarks						= @jvnarration,
        	modifiedby					= @ctxt_user,
        	modifieddate				= dbo.RES_Getdate(@ctxt_ouinstance),
        	reversal_period				= @reversalperiod,
      	transaction_date 			= @posting_date,--@transactiondate ,--es_jv_00648
        	fb_id						= @fbhdr ,
        	voucher_type				= 'NO' 
        	where voucher_number 		= @ref_voucher_no
        	and ou_id					= @ctxt_ouinstance
        
				--code commented for es_jv_00648 starts
               /* exec @retval_tmp = acapaccountingpost @ctxt_language , @ctxt_ouinstance , @ctxt_service,
        	@ctxt_user , '',@fbhdr ,@ref_voucher_no  , @transactiondate , @transactiondate ,'FA_ACAPJV',
        	'' ,'' , 0,'', 'CJV' ,@errorid_tmp output   
        	if ( @retval_tmp <> 0 )	
        	begin	
        		exec fin_sp_raise_error '', '', '', '', 'ACAP',@errorid_tmp,@m_errorid output
        		return
        	end	*/
			--code commented for es_jv_00648 ends
        end
        

	-- updating the hdr table with Dr amount and other hdr values
	update acap_journal_hdr
	set 
	tran_amount 				= round(@debittransactiontotal,@pamt_tmp),
	journal_status 				= 'AC',
	remarks					= @jvnarration,
	modifiedby				= @ctxt_user,
	modifieddate				= dbo.RES_Getdate(@ctxt_ouinstance),
	reversal_period				= @reversalperiod,
	transaction_date 			= @transactiondate ,
	fb_id					= @fbhdr ,
	voucher_type				= @cvouchertypeenn_tmp 
	where voucher_number 			= @voucherno
	and ou_id				= @ctxt_ouinstance

	exec @retval_tmp = acapaccountingpost @ctxt_language , @ctxt_ouinstance , @ctxt_service,
			@ctxt_user , '',@fbhdr , @voucherno , @transactiondate , @transactiondate ,'FA_ACAPJV',
						'' ,'' , 0,'', 'CJV' ,@errorid_tmp output   
	if ( @retval_tmp <> 0 )	
	begin	
		exec fin_sp_raise_error '', '', '', '', 'ACAP',@errorid_tmp,@m_errorid output
		return
	end		

    /* code modified by Swetha for ACAPDMS412AT_000440 on 26/6/2006 */

	/*Code added by EBS-6081 starts*/
	update acap_journal_accounting_dtl
	set   tran_date    = @posting_date ,
	      posting_date = @posting_date
	where ou_id        = @ctxt_ouinstance
	and   tran_number  = @ref_voucher_no
	/*Code added by EBS-6081 ends*/

	/* code added by Swetha for ACAPDMS412AT_000346 on 15/02/2006 */
	

	/* inserting into acap_journal_accounting_tmp the values from acap_journal_accounting_dtl with a guid for 
	ainq posting which will inturn does FB posting*/
	insert into acap_journal_accounting_tmp 
	(timestamp , guid ,tran_number ,tran_type ,account_code ,drcr_flag,ou_id,tran_date ,posting_date ,currency ,tran_amount,fb_id ,
	cost_center ,analysis_code, sub_analysis_code,bc_erate ,base_amount ,pbc_erate,
	pbase_amount ,cap_date ,bu_id ,company_code , createdby ,createddate ,modifiedby,modifieddate
	,asset_number ,tag_number ,account_type, depr_book, remarks )--code 'reamrks' added for EP-96
	select timestamp , @guid, tran_number ,tran_type ,account_code ,drcr_flag,ou_id,tran_date ,posting_date ,currency ,tran_amount,fb_id ,
	cost_center ,analysis_code, sub_analysis_code,bc_erate ,base_amount ,pbc_erate,
	pbase_amount ,cap_date ,bu_id ,company_code , createdby ,createddate ,modifiedby,modifieddate ,asset_number,
	tag_number ,account_type , @DeprBook, remarks--code 'reamrks' added for EP-96
	from acap_journal_accounting_dtl (nolock)
	where ou_id = @ctxt_ouinstance
	and tran_number in (@voucherno,@ref_voucher_no)


	/* Code added by Swetha for ACAPDMS412AT_000349 on 17/02/2006 */
	DECLARE prop_cursor  CURSOR FOR
	SELECT proposal_no,  asset_number, drcr_flag
	FROM acap_journal_tmp(nolock) 
	WHERE guid 			= @guid
	AND ISNULL(asset_number,'')    != ''

	OPEN prop_cursor

	FETCH NEXT FROM  prop_cursor 
	INTO  @proposalnumberml, @asset_number, @drcr_flag

	WHILE @@FETCH_STATUS = 0
	BEGIN 

	SELECT 
	       @drcr_flag		= drcr_flag
	FROM acap_journal_tmp(nolock) 
	WHERE guid 			= @guid
	AND ISNULL(asset_number,'')    != ''



	select @asset_class 		= asset_class
	FROM  acap_asset_hdr(nolock) 
	WHERE asset_number 		= @asset_number
	AND 	ou_id			= @ctxt_ouinstance


	SELECT @assetcost 		= CASE  WHEN @drcr_flag = 'DR' THEN tran_amount ELSE tran_amount * -1 END 
	FROM acap_journal_tmp(nolock)
	WHERE guid 			= @guid
	AND   asset_number		= @asset_number


	/* Code added by Uma for the bug id : ACAPDMS412AT_000599 starts here*/
	--Utilized amount updated only for corp book
	if @DeprBook = 'CORP'
	begin
	/* Code added by Uma for the bug id : ACAPDMS412AT_000599 ends here*/
		insert into acap_updproposal_tmp 
		(guid, proposal_number, asset_class, fb_id, tran_amount, tran_date,
		 createdby, createddate, upd_flag ,tran_no) --Code Modified by TIS-1339
		values ( @guid, @proposalnumberml, @asset_class, @fbhdr, @assetcost, @transactiondate,
			    @ctxt_user, dbo.RES_Getdate(@ctxt_ouinstance), 'CRE' , @voucherno )	 --Code Modified by TIS-1339

		/* Code added by Uma for the bug id : DMS412AT_REPSFAM_00074 starts here*/
		--For cwip postings
		insert into acap_asset_info_tmp ( cap_number , asset_number , cap_date , proposal_number   , fb_id ,ou_id,guid )  --Code Modified by TIS-1339
		select distinct     /*cap_number*/@voucherno , asset_number , /*cap_date*/@transactiondate , @proposalnumberml , fb_id ,@ctxt_ouinstance,@guid  --Code Modified by TIS-1339
		from 	ainq_asset_hdr(nolock) 
		where 	asset_number	= @asset_number
		and	depr_book 	= 'CORP'
		/* Code added by Uma for the bug id : DMS412AT_REPSFAM_00074 ends here*/
	end --	Code added by Uma for the bug id : ACAPDMS412AT_000599 

	FETCH NEXT FROM  prop_cursor 
	INTO  @proposalnumberml, @asset_number, @drcr_flag
 	END
	CLOSE prop_cursor
	DEALLOCATE prop_cursor

	/* Code added by Swetha for ACAPDMS412AT_000349 on 17/02/2006 */


---- for depriciation write back	
	--code commented and pasted above for es_jv_00648
	/*select @companycode = company_code  ,
	@buid_tmp    	    = bu_id 
	from   emod_ou_vw(nolock)
	where  ou_id 	    = @ctxt_ouinstance*/

	select 	@fycode_tmp = fin_year_code ,
		@fpcode_tmp = fin_period_code					
	from fcc_sysact_allperiod_vw (nolock)	
	where 	company_code = @companycode
	and 	fb_id 	     = @fbhdr 
	and 	@transactiondate between fin_period_stdt and fin_period_enddt

	
	select  @notypeno = no_type
	from 	dnm_trans_notype_vw(nolock)
	where   ouinstance 	= @ctxt_ouinstance
	and	trantype_code 	= 'FA_ADRPR'	
	and	no_type		<> '~MANUAL~'
	order by no_type


	
	/* Code commented by Uma for the bug id :AINQDMS412AT_000030 starts here*/
	/*declare cur cursor for
	select  asset_number,
	        cost_center,
	        tag_number
	from acap_journal_tmp(nolock)
	where  guid = @guid
	and  asset_number is not null
	and  tag_number is  not  null
	and  ou_id 	      = @ctxt_ouinstance
	and  drcr_flag	      = 'CR'
	
	open cur

	fetch next from cur into @asset_number,@cost_center,@tag_number

	while (@@fetch_status = 0 )
	begin 

		-- Code modified by Swetha for ACAPDMS412AT_000351 on 23/02/2006 
		declare depr_cursor cursor for 
		select depr_book,depr_proc_runno,tag_status,isnull(depr_charge,0),isnull(susp_charge,0),
		fin_period, depr_category,asset_class,isnull(rev_depr_charge,0)
		from   	adepp_process_vw(NOLOCK)
		where  	asset_number 	= @asset_number
		and    	tag_number   	= @tag_number
		and    	ou_id 	    	= @ctxt_ouinstance
		and    	fin_period   	= @fpcode_tmp
		and    	tag_status   	<> 'RV'
		and	depr_book	= @DeprBook
		
		open depr_cursor

		fetch next from depr_cursor into @depr_book,@depr_proc_runno,@tag_status,@depr_charge,@susp_charge,@fin_period,@depr_category,@asset_class,@rev_depcharge

		while @@fetch_status = 0
		begin 

			if (@tag_status = 'CF')
			begin 
				exec acapdepwritebkvalidate @asset_number,@transactiondate,@cost_center,@ctxt_language,@ctxt_ouinstance,
				'ADEPPRVDEPESRREVS',@ctxt_user,@depr_book,@depr_proc_runno,@tag_status,@depr_charge,@fbhdr,'',@fin_period,@fpcode_tmp,@guid,@notypeno,'',
				@transactiondate,@susp_charge,@tag_number,1,@depr_category,@asset_class,@depr_charge,@rev_depcharge,@m_errorid output
					
				if (@m_errorid <> 0)
				begin 
				  select @m_errorid = case @m_errorid
				       when 82 then 2190467
				       when 83 then 2190468
				       when 84 then 2190469
				       when 85 then 2190470
				end
				return
				end
	
				select @rev_doc_no     =rev_doc_no 
				from adepp_reverse_hdr(nolock)
				where depr_proc_runno   = @depr_proc_runno
				and   ou_id 		= @ctxt_ouinstance
	
				update 	acap_journal_tmp
				set    	process_run_number = @rev_doc_no
				where  	guid	 	= @guid
				and    	asset_number 	= @asset_number
				and    	tag_number   	= @tag_number
				and	depr_book	= @deprbook	
	
					
			end
			else if (@tag_status in ('PP','PR'))
			begin 
				update  adepp_process_dtl
				set 	tag_status 	= 'DL'
				where 	ou_id 		= @ctxt_ouinstance
				and     asset_number	= @asset_number
				and    tag_number       = @tag_number
				-- Code added by Swetha for ACAPDMS412AT_000393 on 22/03/2006 
				and    fin_period   	= @fpcode_tmp
				--Code added by Swetha for ACAPDMS412AT_000393 on 22/03/2006 
				--and    depr_book  in ('CORP','TAX')
				and	depr_book	= @deprbook
			end

		fetch next from depr_cursor into @depr_book,@depr_proc_runno,@tag_status,@depr_charge,@susp_charge,@fin_period,@depr_category,@asset_class,@rev_depcharge
		-- Code modified by Swetha for ACAPDMS412AT_000351 on 23/02/2006 
		end
		close depr_cursor
		deallocate depr_cursor
	
	fetch next from cur into @asset_number,@cost_center,@tag_number
	end
	close cur
	deallocate cur*/
	/* Code commented by Uma for the bug id :AINQDMS412AT_000030 ends here*/

	/*Code added by Uma for the bug id : ACAPDMS412AT_000621 starts here*/
	declare	@tran_amount_rmp	fin_amount

	select @tran_amount_rmp = isnull( sum(case when drcr_flag = 'DR' 
					then  isnull(tran_amount,0) 
					else -1 * isnull(tran_amount,0) 
					end),0)
	from 	acap_journal_tmp(nolock)
	where  	guid 		=  @guid
	and  	asset_number 	is not null
	and  	tag_number 	is not  null
	and  	ou_id 	      	=  @ctxt_ouinstance
	
	declare	@doc_status			fin_desc40,	
			@workflow_status	fin_desc40
	
	select	@doc_status			=	journal_status,
			@workflow_status	=	workflow_status
	from	acap_journal_hdr(nolock)
	where	ou_id		= @ctxt_ouinstance
	and		voucher_number	= @voucherno
	
	if (@doc_status = 'AC' and @workflow_status is null) 
	begin
		select	@ctxt_ouinstance = @ctxt_ouinstance
	end		
	else	
	begin
		select	@tran_amount_rmp	=	0	
	end	

	--if @tran_amount_rmp > 0 -- Code commented by T.Suresh for bugid Es_adepp_00099
	if @tran_amount_rmp <> 0 -- Code added by T.Sureshf for bugid Es_adepp_00099
	begin
	/*Code added by Uma for the bug id : ACAPDMS412AT_000621 ends here*/
		--Code added by Aparna M. for the bug ADEPPDMS412AT_000285 starts
		if exists(select	'X'
				from	acap_journal_hdr(nolock)
				where	ou_id		= @ctxt_ouinstance
				and	voucher_number	= @voucherno
				and	journal_status	= 'AC'
				)
		begin
			--Irrespective of the include process date parameter depreciation 
			--has to be calculated till the date one day prior to transfer date
			select	@transactiondate	= dateadd(dd,-1,@transactiondate)
			
			--code added for ES_ACAP_00550 starts
			select	@parameter_value = parameter_value
			from	ips_processparam_vw (nolock)
			where   parameter_code  = 'FAINSTALLDATE'
			and     company_code	= @companycode
		
			select @parameter_value = dbo.fin_dateinuserformat(convert(nvarchar(20),@parameter_value),'YYYY-MM-DD')
			--code added for ES_ACAP_00550 ends
			
			insert	into adepp_is_tmp
			(guid,		asset_number,		tag_number,		process_date,
			fb_id,		asset_class,		depr_book)
			select
			@guid,		A.asset_number,		A.tag_number,		@transactiondate,
			@fbhdr,		B.asset_class,		A.depr_book
			from	acap_journal_dtl A(nolock),/*ainq_asset_hdr*/ ainq_asset_tag_vw B (nolock), --code modified for ES_ACAP_00550
			ainf_asset_class_vw C(nolock)  --ACAPDMS412AT_000710
			where	A.ou_id			= @ctxt_ouinstance
			and	A.voucher_number	= @voucherno
			and	A.asset_number		is not null
			and	A.tag_number		is not null
			and	A.asset_number		= B.asset_number
			and A.tag_number		= B.tag_number   --code added for ES_ACAP_00550
			and	A.depr_book		= B.depr_book
			/* Code added by Esther J on 18/05/2007 for defect ACAPDMS412AT_000710 starts */
			and 	C.ou_id 		 = B.ou_id
			and 	C.asset_class_code       = B.asset_class
			and 	C.dest_component 	 = 'ACAP'  
			and 	C.depreciable	 	 = 'Y'
			and		@transactiondate > = (case when asset_type = 'M' then @parameter_value else inservice_date end) --code added for ES_ACAP_00550

			--TC-1561 code starts here

		declare  
				@depr_rule_number	fin_deprkey ,
				@depr_rule_number_tax fin_deprkey ,
				@source_ou			fin_ctxt_ouinstance	
		
		 declare @pps_flag fin_flag
		 select  @pps_flag = FLAG_YES_NO
		 from	 pps_feature_list(nolock)
		 where	 COMPONENT_NAME = 'ADEPP'
		 and	 FEATURE_ID = 'PPS_ADEPP_0004'
	
		 select @pps_flag = isnull(@pps_flag,'YES')


    if @pps_flag = 'NO'
    begin
 	DECLARE pre_cursor  CURSOR FOR
	SELECT  asset_number,tag_number
	FROM    acap_journal_dtl A(nolock)
	where	A.ou_id			        = @ctxt_ouinstance
			and	A.voucher_number	= @voucherno
			and	A.asset_number		is not null
			and	A.tag_number		is not null

    open pre_cursor

	FETCH NEXT FROM  pre_cursor INTO  @asset_number, @tag_number
	WHILE @@FETCH_STATUS = 0
	BEGIN 
		

		select 	@depr_category	=  depr_category ,
				@asset_class    =  asset_class
		from 	ainq_asset_tag_vw(nolock)  
		WHERE 	asset_number	= @asset_number  
		and		tag_number		= @tag_number
		AND  	ou_id			= @ctxt_ouinstance  
		and		depr_book		= 'CORP'

		select @source_ou	      		=   min(destinationouinstid)
		from   fw_admin_view_comp_intxn_model	(nolock)
		where  upper(sourcecomponentname)    	=   upper('ADEPP')
		and    sourceouinstid         	 	=   @ctxt_ouinstance
		and    upper(destinationcomponentname) 	=   upper('ADEP')
		
		select  @depr_rule_number = depr_rule_number
		from    adep_assign_rules_vw adep (nolock)
		where 	adep.ou_id 			= @source_ou  
		and 	adep.depr_book   	= 'CORP'  
		and 	adep.asset_class  	= @asset_class
		and 	adep.depr_category  = @depr_category
		and 	adep.status   		= 'A'  
		and		@transactiondate between eff_Date and isnull (exp_date,@transactiondate)
		

		if exists
		(	
			select 'x'
			from	adep_depr_rule_hdr_vw adep(nolock)
			where 	adep.ou_id 			  = @source_ou
			and 	adep.depr_rule_number = @depr_rule_number
			and		depr_conv = 'FP'
		)
		begin
				delete from adepp_is_tmp
				where  guid   = @guid
				and    depr_book = 'CORP'
				and asset_number=@asset_number
				and tag_number=@tag_number
		end

	if exists
	(
		select  'X'  
		from  ips_processparam_sys (nolock)  
		where  parameter_type   =  'CPSYS'  
		and  company_code    =  @companycode  
		and  parameter_category = 'TAXBOOKAPPLI'  
		and  parameter_code   = 'Y'  
	)
	begin
			
		select  @depr_rule_number_tax = depr_rule_number
		from    adep_assign_rules_vw adep (nolock)
		where 	adep.ou_id 			= @source_ou  
		and 	adep.depr_book   	= 'TAX'  
		and 	adep.asset_class  	= @asset_class
		and 	adep.depr_category  = @depr_category
		and 	adep.status   		= 'A'  
		and		@transactiondate between eff_Date and isnull (exp_date,@transactiondate)

		
		if exists
		(	
			select 'x'
			from	adep_depr_rule_hdr_vw adep(nolock)
			where 	adep.ou_id 			  = @source_ou
			and 	adep.depr_rule_number = @depr_rule_number_tax
			and		depr_conv = 'FP'
		)
		begin
				delete from adepp_is_tmp
				where  guid   = @guid
				and    depr_book = 'TAX'
				and asset_number=@asset_number
				and tag_number=@tag_number
		end
	end
 FETCH NEXT FROM  pre_cursor 
	INTO  @asset_number, @tag_number
 	END

 CLOSE pre_cursor
	DEALLOCATE pre_cursor

	end
 --TC-1561 code ends here
			if exists (select 'a' from adepp_is_tmp (nolock)
				   Where guid			= @guid)	
			begin
			/* Code added by Esther J on 18/05/2007 for defect ACAPDMS412AT_000710 ends*/
				
				exec	adepp_auto_depreciation_sp
					@ctxt_language,
					@ctxt_ouinstance,
					@ctxt_service,
					@ctxt_user,
					@guid,
					@ctxt_ouinstance,
					@ctxt_service,
					@m_errorid	out
		
				if @m_errorid <> 0
				begin
					select	@m_errorid = @m_errorid
					exec fin_german_Raiserror_sp 'ACAP',@ctxt_language,1900027508 -- code added here RPE-169
					return
				end
			end --ACAPDMS412AT_000710
		end
		--Code added by Aparna M. for the bug ADEPPDMS412AT_000285 ends
	end -- Code added by Uma for the bug id : ACAPDMS412AT_000621

	/*code added for EPE-7189 begins here */
	if exists (select 'X'
			   from fb_tmp (nolock)
			   where remarks		= 'ACAP_WF_MAIL'
			   and   rsih_guid_tmp  =  @guid )
	begin
			return
	end
	/*code added for EPE-7189 ends here */

	select  0			'ErrorNo' ,
		@fprowno 		'fprowno',
		''			'PlaceHolder1',
		''			'PlaceHolder2',
		''			'PlaceHolder3',
		''			'PlaceHolder4',
		0			'SuccessFlag'
	

	set nocount off
end






