/*$File_version=ms4.3.0.02$*/
/*$file name : acapaucjmspaujrnhdrsave.sql*/
/*$version   : 4.0.0.4*/
/*==================================================
   stored procedure 				:acapaucjmspaujrnhdrsave
   method           				:acapaucjmmtaujrnhdrsave	
   author           				:functional proto ver 1.0
   created on       				:28 feb 2002 00:28:42:717
   created at       				:s4036
   generated by     				:kishore a
  purpose					: this method  will the values 
						  in the acap_journal_tmp with the values having same guid and voucher_no.
						  initialises fprowno to zero

     modified by 				: Swetha
  date                  			: 13/12/2005
  purpose               			: ACAPDMS412AT_000184 

  modified by 					: Swetha
  date                  			: 22/12/2005
  purpose               			: ACAPDMS412AT_000190

Modification History	
Modified by		Modified Date		Remarks
Uma Maheswari		28th Dec 2006		ACAPDMS412AT_000576 (Bookwise Capitalization)

 
procedure acapaucjmspaujrnhdrsave
 grant exec on  acapaucjmspaujrnhdrsave to public

*/
/********************************************************************************/
/*Modified by        : Swetha                                                   */
/*Modified Date      : 5/5/2006                                                 */
/*Purpose            : CML Changes                                              */
/* Abinav				01/03/2023				EPE-60038 						*/
/********************************************************************************/
Create procedure acapaucjmspaujrnhdrsave
	@createddate   				fin_date  ,
	@creationby   				fin_ctxt_user  ,
	@credittransactiontotal   		fin_amount  ,
	@ctxt_language   			fin_ctxt_language  ,
	@ctxt_ouinstance   			fin_ctxt_ouinstance  ,
	@ctxt_service   			fin_ctxt_service  ,
	@ctxt_user   				fin_ctxt_user  ,
	@cvouchertypeenn   			fin_desc40  ,
	@debittransactiontotal   		fin_amount  ,
	@fbhdr   				fin_financebookid  ,
	@guid   				fin_guid  ,
	@jvnarration   				fin_comments  ,
	@lastmodificationby   			fin_ctxt_user  ,
	@lastmodifieddate   			fin_date  ,
	@ouinstid				fin_int ,
	/* code modified by swetha for ACAPDMS412AT_000184 on 13/12/2005 */
	@reversalperiod   			fin_financeperiodrange  ,
	/* code modified by swetha for ACAPDMS412AT_000184 on 13/12/2005 */
	@status   				fin_status  ,
	@timestamp   				fin_timestamp  ,
	@transactiondate   			fin_date  ,
	@voucherno   				fin_documentno  ,
	@wfdockey				fin_desc120 ,
	@wforgunit				fin_int ,
	/*Code added by Uma for the bug id : ACAPDMS412AT_000576 starts here*/
	@DeprBook				fin_deprkey	,
	/*Code added by Uma for the bug id : ACAPDMS412AT_000576 ends here*/
	 @m_errorid  				fin_int output 
as
begin
        declare @retval_tmp			fin_int,
        @fcc_status_tmp 			fin_status,
        @fcc_fycode1_tmp 			fin_desc40,
        @fcc_fpcode1_tmp 			fin_desc40 ,
        @errorid_tmp				fin_int ,
        @status_tmp				fin_status
     -- nocount should be switched on to prevent phantom rows 
     set nocount on
     if @ouinstid = -915
          select @ouinstid = null
     select @createddate = ltrim(rtrim(@createddate))
     if @createddate = '01-01-1900' 
          select @createddate = null
     select @creationby = ltrim(rtrim(@creationby))
     if @creationby = '~#~' 
          select @creationby = null
     if @credittransactiontotal = -915 
          select @credittransactiontotal = null
     if @ctxt_language = -915 
          select @ctxt_language = null
     if @ctxt_ouinstance = -915 
          select @ctxt_ouinstance = null
     select @ctxt_service = ltrim(rtrim(@ctxt_service))
     if @ctxt_service = '~#~' 
          select @ctxt_service = null
     select @ctxt_user = ltrim(rtrim(@ctxt_user))
     if @ctxt_user = '~#~' 
          select @ctxt_user = null
     select @cvouchertypeenn = ltrim(rtrim(@cvouchertypeenn))
     if @cvouchertypeenn = '~#~' 
          select @cvouchertypeenn = null
     if @debittransactiontotal = -915 
          select @debittransactiontotal = null
     select @fbhdr = ltrim(rtrim(@fbhdr))
     if @fbhdr = '~#~' 
          select @fbhdr = null
     select @guid = ltrim(rtrim(@guid))
     if @guid = '~#~' 
          select @guid = null
     select @jvnarration = ltrim(rtrim(@jvnarration))
     if @jvnarration = '~#~' 
          select @jvnarration = null
     select @lastmodificationby = ltrim(rtrim(@lastmodificationby))
     if @lastmodificationby = '~#~' 
          select @lastmodificationby = null
     select @lastmodifieddate = ltrim(rtrim(@lastmodifieddate))
     if @lastmodifieddate = '01-01-1900' 
          select @lastmodifieddate = null
     select @reversalperiod = ltrim(rtrim(@reversalperiod))
     if @reversalperiod = '~#~' 
          select @reversalperiod = null
     select @status = ltrim(rtrim(@status))
     if @status = '~#~' 
          select @status = null
     if @timestamp = -915 
          select @timestamp = null
     select @transactiondate = ltrim(rtrim(@transactiondate))
     if @transactiondate = '01-01-1900' 
          select @transactiondate = null
     select @voucherno = ltrim(rtrim(@voucherno))
     if @voucherno = '~#~' 
          select @voucherno = null

	/*Code added by Uma for the bug id : ACAPDMS412AT_000576 starts here*/
	select @DeprBook = ltrim(rtrim(@DeprBook))
	if @DeprBook = '~#~' 
		select @DeprBook = null
	/*Code added by Uma for the bug id : ACAPDMS412AT_000576 ends here*/

	select @status_tmp  = parameter_code
	from fin_quick_code_met (nolock)
	where  component_id = 'ACAP'
	and parameter_type = 'CBO'
	and parameter_category = 'JOU_STA'
	and language_id = @ctxt_language
	and parameter_text = @status
	--to raise error if the record is not in fresh status
	if (@status_tmp <>'FR')
		begin
			exec fin_sp_raise_error '', '', '', '', 'ACAP',52, @m_errorid output
			return	
		end
	-- raise error if fb is null
	if (@fbhdr is null)
		begin
			exec fin_sp_raise_error '','','','','ACAP',84,@m_errorid output
			return					
		end
	-- raise error if transaction date is null
	if (@transactiondate is null)
		begin
			exec fin_sp_raise_error '','','','','ACAP',46,@m_errorid output
			return					
		end 
	-- if transaction date is more than system date
	if (@transactiondate > dbo.RES_Getdate(@ctxt_ouinstance))
		begin
			exec fin_sp_raise_error '','','','','ACAP',80,@m_errorid output
			return					
		end 
	-- to check validaity of the date
	exec @retval_tmp = fcc_sysact_spvaltrndate @ctxt_ouinstance, 'ACAP',@ctxt_user,
					@fbhdr ,@transactiondate , @fcc_status_tmp output, @fcc_fycode1_tmp output,
						@fcc_fpcode1_tmp output,@ctxt_language

	/*Code added for EPE-60038 begins */
	-- Checking restricted back dated transaction
	Declare @cvouchertypeenn_code	fin_documentno

	Select	@cvouchertypeenn_code = parameter_code
	From fin_quick_code_met(nolock)
	Where component_id 		 = 'ACAP'
	And   parameter_type 	 = 'CBO'
	And   parameter_category = 'VOU_TYP'
	And   parameter_text     = @cvouchertypeenn

	If @ctxt_service = 'acapaucjmsraujrn'
	Begin
		If  @cvouchertypeenn_code = 'NO'
			Exec restrict_bk_dated_tran_sp @ctxt_ouinstance,@ctxt_language,'FA_ACAPJV',@transactiondate,'ACAP','',@m_errorid Output

		If  @cvouchertypeenn_code = 'RE'
			Exec restrict_bk_dated_tran_sp @ctxt_ouinstance,@ctxt_language,'FA_RACAPJV',@transactiondate,'ACAP','',@m_errorid Output

		If @m_errorid <> 0
			Return
	End

	/*Code added for EPE-60038 ends */

/*				
errors to be mapped from IS
1 - transaction date is in closed period or year of the bfg ou.
2 - transaction date is in closed period or year of the finance book.
3 - period or year is not defined in the financial calender for a company corresponding to the given transaction date 
4 - provide organisation unit
5 - provide component name
6 - provide finance book id
7 - provide transaction date
*/			
		if ( @retval_tmp <> 0 )	
			begin	
				select @errorid_tmp = case (@retval_tmp)
			    	when 1 then 196
			        when 2 then 197
					when 3 then 235
					when 4 then 149
					when 5 then 217
					when 6 then 110
					when 7 then 46
				end
				exec fin_sp_raise_error '', '', '', '', 'ACAP',@errorid_tmp,@m_errorid output
				return		
			end		

	delete 	from acap_journal_tmp
	where 	guid 	= @guid
	
		
	select 		''		'errorno',
		/* code modified by swetha for ACAPDMS412AT_000190 on 22/12/2005 */
			1 		'fprowno',
		/* code modified by swetha for ACAPDMS412AT_000190 on 22/12/2005 */
			''		'placeholder1',
			''		'placeholder2',				
			''		'placeholder3',
			''		'placeholder4',
			0		'successflag'


	set nocount off
end


