/*$File_version=ms4.3.0.10$*/
/*$file name : acapcrcjspcrjrnmldt.sql*/
/*$version   : 4.0.0.17*/
/*==================================================
stored procedure 	:acapcrcjspcrjrnmldt
method           	:acapcrcjmtcomtotmldt
author           	:functional proto ver 1.0
created on       	:28 feb 2002 00:28:50:450
created at       	:s4036
generated by     	:kishore a
purpose			:this method will insert the rows  from the multi line into dtl_tmp 
			with guid 

Modified By 		: C.D.Arunkumar
Modified Date 		: 11-May-2004
Modified Purpose 	: ACAPDMS41SYTST_000055	

Modified By 		: Saurabh  Mathur
Modified Date 		: 11-May-2004
Modified Purpose 	: ACAPDMS41SYTST_000123	


Modified By 		: Saurabh  Mathur
Modified Date 		: 23-Sept-2004
Modified Purpose 	: ACAPFIN41CT_000012	

Modified By 		: Saurabh  Mathur
Modified Date 		: 28-Sept-2004
Modified Purpose 	: ACAPFIN41CT_000072

Modified By 		: Saurabh  Mathur
Modified Date 		: 28-Sept-2004
Modified Purpose 	: ACAPFIN41CT_000112

Modified By 		: Saurabh  Mathur
Modified Date 		: 18-Nov-2004
Modified Purpose 	: ACAPFIN41CT_000229

Modified By 		: Saurabh  Mathur
Modified Date 		: 26-Nov-2004
Modified Purpose 	: ACAPFIN41CT_000227

Modified By 		: Saurabh  Mathur
Modified Date 		: 25-Dec-2004
Modified Purpose 	: ARDEYCERT_000003

Modified By 	  	: Swetha
Modified Date 	  	: 14/11/2005
Modified Purpose  	: ACAPDMS412AT_000106,ACAPDMS412AT_000107

Modified By 	  	: Swetha
Modified Date 	  	: 30/11/2005
Modified Purpose 	: ACAPDMS412AT_000107

Modified By 	  	: Swetha
Modified Date 	  	: 8/12/2005
Modified Purpose  	: ACAPDMS412AT_000161

Modified By 	  	: Swetha
Modified Date 	 	: 15/12/2005
Modified Purpose  	: ACAPDMS412AT_000106


Modified By	  	: Swetha
Modified Date     	: 30/12/2005
Purpose	    	 	: ACAPDMS412AT_000205

Modified By	    	: Swetha
Modified Date    	: 17/01/2006
Purpose	    		: FA CODE REVAMP(For Earlier version  Pls Refer Sourcesafe)


Modified By	    	: Swetha
Modified Date    	: 07/06/2006
Purpose	    	        : ACAPDMS412AT_000466

Modification History
Modified by		Modified Date		Remarks
Uma Maheswari		28th Dec 2006		ACAPDMS412AT_000576
Uma Maheswari		22nd Jan 2007		ACAPDMS412AT_000589
Selvan.G		18th Dec 2007		ACAPDMS412AT_000770
Uma Maheswari		11th Feb 2008		DMS412AT_ACAP_00007
Uma Maheswari		29th Feb 2008		DMS412AT_ACAP_00011
Uma Maheswari		04th July 2008		ES_EMOD_00001
T.Suresh			13/05/2011			Es_acap_00225
Kuthalam K			08/05/2013			ES_ACAP_00428
Aditya S			03/02/2017			ES_ADISP_00228
Ashok V				02/05/2018			FBF-483(FBF-481/ESS-7)
Saranraj C			19/07/2023			EBS-6047 
grant exec on acapcrcjspcrjrnmldt to public
*/
Create procedure acapcrcjspcrjrnmldt
	@accountcode   			fin_accountcode  ,
	@analysiscodeml   		fin_analysiscode  ,
	@assetnumber   			fin_assetnumber  ,
	@costcenter   			fin_costcentercode  ,
	@ctxt_language   		fin_ctxt_language  ,
	@ctxt_ouinstance   		fin_ctxt_ouinstance  ,
	@ctxt_service   		fin_ctxt_service  ,
	@ctxt_user   			fin_ctxt_user  ,
	@cvouchertypeenn   		fin_desc40  ,
	@drcrenn   			fin_desc40  ,
	@fb				fin_financebookid ,
	@guid   			fin_guid  ,
	@jvnarrationml   		fin_comments  ,
	@modeflag   			fin_modeflag  ,
	@proposalnumber			fin_documentno ,
	@subanalysiscodeml   		fin_subanalysiscode  ,
	@tagnumber   			fin_assettagno  ,
	@tranamount   			fin_amount  ,
	@transactiondate		fin_date ,
	@voucher_number   		fin_documentno  ,
	@wfdockey			fin_desc120 ,
	@wforgunit			fin_int ,
	/*Code added by Uma for the bug id : ACAPDMS412AT_000576 starts here*/
	@DeprBook			fin_deprkey	,
	/*Code added by Uma for the bug id : ACAPDMS412AT_000576 ends here*/
	@errorno			fin_errorno ,
	@fprowno   			fin_rowno  ,
	@placeholder1			fin_placeholder ,
	@placeholder2			fin_placeholder ,
	@placeholder3			fin_placeholder ,
	@placeholder4			fin_placeholder ,
	@successflag			fin_successflag ,
	@m_errorid  			fin_int output --to return execution status
as
begin

    set nocount on

--BEGIN of Standard code for getting precision type
	declare  @pqty_tmp       fin_int ,
	@pamt_tmp         fin_int ,
	@prate_tmp                 fin_int ,
	@perate_tmp                fin_int ,
	@phigh_tmp                 fin_int ,
	@pmed_tmp                  fin_int ,
	@plow_tmp            fin_int,
	@errmsg                    fin_desc255

	exec fin_sp_precisiontype_rtr @pqty_tmp output, @pamt_tmp output,
	@prate_tmp output, @perate_tmp output, @phigh_tmp output,
	@pmed_tmp output, @plow_tmp output

--END of Standard code for getting precision type

     -- nocount should be switched on to prevent phantom rows 
     set nocount on

	declare @assetclasscode_tmp		fin_desc40,
	@fb_tmp					fin_desc40,
	@companycode_tmp			fin_desc40,
	@retval_tmp				fin_int,
	@flag_out				fin_flag,
	@errorid_tmp				fin_int,
	@errormsg				fin_placeholder,
	@basecurrency_tmp			fin_currency,
	@currency                   		fin_currency, 
	@accountcode_tmp			fin_accountcode ,
	@guid_tmp				fin_guid ,
	@asset_account_flag			fin_flag ,
	@fcc_status_tmp 			fin_status,
	@fcc_fycode1_tmp 			fin_desc40,
	@fcc_fpcode1_tmp 			fin_desc40 ,
	@inservice_date_tmp			fin_date,
	@fcc_start_date				fin_date,
	@acap_date_tmp 				fin_date,
	@costcentermap				fin_flag,
	@buid_tmp				fin_buid,
	@companycode				fin_companycode,
	@asgusg 				fin_documentno,
	@asset_class				fin_assetclass	,
	@cap_date				fin_date,
	@cost_center				fin_costcentercode
	/* Code Added By Selvan.G For the Bug Id : ACAPDMS412AT_000770 Starts here */
	declare	@destinationouinstid   		fin_ctxt_ouinstance
	/* Code Added By Selvan.G For the Bug Id : ACAPDMS412AT_000770 Ends here */
	
			
     	select @accountcode = upper(ltrim(rtrim(@accountcode)))
     	if @accountcode = '~#~' 
          select @accountcode = null
    	  select @analysiscodeml = ltrim(rtrim(@analysiscodeml))
     if @analysiscodeml = '~#~' 
          select @analysiscodeml = null
     	  select @assetnumber = upper(ltrim(rtrim(@assetnumber)))
     if @assetnumber = '~#~' 
          select @assetnumber = null
     	  select @costcenter = upper(ltrim(rtrim(@costcenter)))
     if @costcenter = '~#~' 
          select @costcenter = null
     if @ctxt_language = -915 
          select @ctxt_language = null
     if @ctxt_ouinstance = -915 
          select @ctxt_ouinstance = null
     	  select @ctxt_service = ltrim(rtrim(@ctxt_service))
     if @ctxt_service = '~#~' 
          select @ctxt_service = null
     	  select @ctxt_user = ltrim(rtrim(@ctxt_user))
     if @ctxt_user = '~#~' 
          select @ctxt_user = null
     	  select @cvouchertypeenn = ltrim(rtrim(@cvouchertypeenn))
     if @cvouchertypeenn = '~#~' 
          select @cvouchertypeenn = null
     	  select @drcrenn = ltrim(rtrim(@drcrenn))
     if @drcrenn = '~#~' 
          select @drcrenn = null
     	  select @guid = ltrim(rtrim(@guid))
     if @guid = '~#~' 
          select @guid = null
     	  select @jvnarrationml = ltrim(rtrim(@jvnarrationml))
     if @jvnarrationml = '~#~' 
          select @jvnarrationml = null
     	  select @modeflag = ltrim(rtrim(@modeflag))
     if @modeflag = '~#~' 
          select @modeflag = null
    	  select @subanalysiscodeml = ltrim(rtrim(@subanalysiscodeml))
     if @subanalysiscodeml = '~#~' 
          select @subanalysiscodeml = null
     if @tagnumber = -915 
          select @tagnumber = null
     if @tranamount = -915 
          select @tranamount = null
    	  select @voucher_number = upper(ltrim(rtrim(@voucher_number)))
     if @voucher_number = '~#~' 
          select @voucher_number = null
     	  select @proposalnumber = upper(ltrim(rtrim(@proposalnumber)))
     if @proposalnumber = '~#~' 
          select @proposalnumber = null
     if @fprowno = -915 
          select @fprowno = null

	/*Code added by Uma for the bug id : ACAPDMS412AT_000576 starts here*/
	select @DeprBook = ltrim(rtrim(@DeprBook))
	if @DeprBook = '~#~' 
		select @DeprBook = null
	/*Code added by Uma for the bug id : ACAPDMS412AT_000576 ends here*/
	
	--ES_ADISP_00228
	declare @company_code fin_company_code 	,
			@ctrlacc	  fin_controlaccounttype ,
			@opcoid		  fin_coaid				 
	
	select @company_code  =	company_code 
	from   emod_ou_vw(nolock)
	where  ou_id	=	@ctxt_ouinstance 
	
	select @opcoid = opcoa_id
	from  as_opcoaid_map(nolock)
	where company_code = @company_code 
	and	  map_status   = 'A'	
	
	if exists
	(
		select 'x'
		from    as_opaccount_dtl ast(nolock)
		where   ast.opcoa_id		=	@opcoid
		and		ast.account_code	=	@accountcode
		and     ast.ctrl_acctype	is not null
		and		ast.ctrl_acctype  not in ('ASSETACCOUNT','CAPWIPACC')	
	)	
	begin	
			select @ctrlacc	=	ast.ctrl_acctype
			from    as_opaccount_dtl ast(nolock)
			where   ast.opcoa_id		=	@opcoid
			and		ast.account_code	=	@accountcode
			and     ast.ctrl_acctype	is not null
			and		ast.ctrl_acctype  not in ('ASSETACCOUNT','CAPWIPACC')
			
			exec fin_german_raiserror_sp 'ACAP',@ctxt_language,4004, @accountcode , @ctrlacc
			return	
	end
	--ES_ADISP_00228
	
	/*Code added for the Ticket No : ES_ACAP_00428 by Kuthalam Starts */
	if 	ISNULL(@assetnumber,'')<>''
	begin
		     	if exists 
				(
					select	'x'
					from	ainq_asset_Tag_balance(nolock)
					where	ou_id = @ctxt_ouinstance
					and		asset_number = @assetnumber
					and		tag_number = @tagnumber
					and		fb_id = @fb
					and		tran_type	= 'FA_ACAP' 
					and		srno in  (select min(srno) 
								from	ainq_asset_Tag_balance(nolock)
								where	ou_id = @ctxt_ouinstance
								and		asset_number = @assetnumber
								and		tag_number = @tagnumber
								and		fb_id = @fb
								and		tran_type	= 'FA_ACAP' )
					and		tran_date > @transactiondate
				)
			begin
				--Raiserror('Voucher date should not less than the Asset Capitalization date for given Asset %s, Tag number %d in line no %d.',16,1,@assetnumber,@tagnumber,@fprowno)
				exec fin_german_raiserror_sp 'ACAP',@ctxt_language,138,@assetnumber,@tagnumber,@fprowno
				return
			end	
	end
		
	/*Code added for the Ticket No : ES_ACAP_00428 by Kuthalam Ends */

	/* Code added by Uma for the bug id: ACAPDMS412AT_000589 starts here*/
	if @tagnumber is not null and @assetnumber is not null
	begin
		if not exists (	select 	'x'
				from 	ainq_asset_tag_vw (nolock)
				where	asset_number 	= @assetnumber
				and	tag_number   	= @tagnumber
				and	fb_id		= @fb
				and	depr_book	= @DeprBook )
		begin
			--raiserror('Fiance book selected is not the FB of the ASSET/TAG',16,1)
			exec fin_german_raiserror_sp 'ACAP',@ctxt_language,113
			return
		end
	end
	/* Code added by Uma for the bug id: ACAPDMS412AT_000589 ends here*/

   	  select @asset_account_flag = 'Y'

        /* code modified by Swetha for ACAPDMS412AT_000466 on 7/6/2006 */
	select  @drcrenn =  parameter_code 
	from 	fin_quick_code_met(nolock)
	where 	component_id          = 'ACAP'
	and   	parameter_type        = 'CBO'
	and   	parameter_category    = 'DRCR'
	and   	language_id           = @ctxt_language
        and   	parameter_text        = @drcrenn
        /* code modified by Swetha for ACAPDMS412AT_000466 on 7/6/2006 */

	/* Code Added By Selvan.G For the Bug Id : ACAPDMS412AT_000770 Starts here */
	if @proposalnumber is not null
	begin
		select	@destinationouinstid 	 = destinationouinstid  
		from	fw_admin_view_comp_intxn_model (nolock)
		where	sourcecomponentname      =  'ACAP'
		and	sourceouinstid           =  @ctxt_ouinstance
		and	destinationcomponentname = 'APLAN'

		if not exists (	select	'x' 
				from	aplan_acq_proposal_vw(nolock)
				where	proposal_number = @proposalnumber
				and	fb_id		= @fb 
				and	dest_ouid	= @destinationouinstid 
					)
		begin
		    --Proposal Number not mapped to the Finance Book
		    exec fin_german_raiserror_sp 'ACAP',@ctxt_language,109
		    return
		end
	end
	/* Code Added By Selvan.G For the Bug Id : ACAPDMS412AT_000770 Ends here */

	/* Code added by Uma for the bug id : DMS412AT_ACAP_00007 starts here*/
	select 	@companycode_tmp = company_code
	from	emod_ou_vw (nolock) -- emod_ou_mst(nolock)  -- Code modifed by Uma for the bug id: ES_EMOD_00001
	where	ou_id		= @ctxt_ouinstance
	-- and	map_status	= 'M' -- Code commented by Uma for the bug id: ES_EMOD_00001

	if exists (	select 	'x' 
			from 	ainq_asset_hdr (nolock)
			where 	asset_number 	= @assetnumber	
			-- and	depr_book	= @DeprBook --Code commented by Uma for the bug id : DMS412AT_ACAP_00011
			and	asset_type	= 'M' )
	begin
		if exists (	select  'x'
				from 	ips_processparam_sys (nolock)
				where 	parameter_type 		=  'CPSYS'
				and 	company_code  		=  @companycode_tmp
				and 	parameter_category 	= 'TAXBOOKAPPLI'
				and 	parameter_code 		= 'Y'	
			    )
		begin	
			if exists ( 	select 'x'
					from	ainq_accounting_info_dtl CORP(nolock)
					where	depr_book	= 'CORP'
					and	asset_number 	= @assetnumber
					and	tran_type	= 'FA_IABE'	)
			and  exists	(
				 	select 'x'
					from	ainq_accounting_info_dtl CORP(nolock)
					where	depr_book	= 'TAX'
					and	asset_number 	= @assetnumber
					and	tran_type	= 'FA_IABE'	)
			begin
				select @ctxt_user = @ctxt_user
			end
			else
			begin
				--raiserror('Initial balance not completed for Migrated asset',16,1)
				exec fin_german_raiserror_sp 'AMIG',@ctxt_language,7
				return
			end

		end
	end
	/* Code added by Uma for the bug id : DMS412AT_ACAP_00007 ends here*/
	/* Code added by T.Suresh for bugid es_acap_00225 starts here */
	if isnull(@assetnumber,'')<>''
		begin
		if Exists  
		(
		select 	'X'
		from 	adepp_process_dtl (nolock)
		where 	ou_id		= @ctxt_ouinstance
		and	asset_number	= @assetnumber
		and	tag_number	= @tagnumber
		and	depr_book	= @DeprBook
		and	isnull(fb_id,'')= isnull(@fb,'')
		and	tag_status 	in('CF','PR','PP')
		--and	isnull(fp_upto_date,fp_end_date)	>=	@transactiondate
		and	isnull(fp_end_date,fp_upto_date)	>=	@transactiondate--FBF-483(ESS-7)
		) 
		begin
			exec fin_german_raiserror_sp 'ACAP',1,1004,@assetnumber
			return			
		end
     end
	/* Code added by T.Suresh for bugid es_acap_00225 ends here */

	--EBS-6047 Starts
	if exists
	(
		select 'x'
		from	acap_journal_tmp(nolock) 
		where   guid		 = @guid
		and		asset_number = @assetnumber
		and		tag_number	 = @tagnumber
		and		drcr_flag   <> @drcrenn
	)
	begin
	--raiserror('Same Asset Number-Tag Number combination cannot be debited and credited for capital journal',16,1)
	exec fin_german_raiserror_sp 'ACAP',1,1900027515
	return
	end
	--EBS-6047 Ends

	-- inserting into tmp table from multiline values
	insert into acap_journal_tmp( guid,asset_number,tag_number,ou_id,voucher_number,timestamp,
	account_code,drcr_flag,tran_amount,remarks,cost_center,analysis_code,
	subanalysis_code,createdby,createddate,asset_flag,currency_code ,proposal_no
	,depr_book)--Code added by Uma for the bug id: ACAPDMS412AT_000576
	values(@guid, @assetnumber, @tagnumber,@ctxt_ouinstance ,1,1,
	@accountcode,@drcrenn,@tranamount,@jvnarrationml,@costcenter ,@analysiscodeml,
	@subanalysiscodeml,@ctxt_user,dbo.RES_Getdate(@ctxt_ouinstance),@asset_account_flag,@currency,@proposalnumber
	,@DeprBook) --Code added by Uma for the bug id: ACAPDMS412AT_000576
	
	select  0			'ErrorNo' ,
		@fprowno +1		'fprowno',
		''			'PlaceHolder1',
		''			'PlaceHolder2',
		''			'PlaceHolder3',
		''			'PlaceHolder4',
		0			'SuccessFlag'
	set nocount off
end





