/*$File_version=ms4.3.0.32$*/
/*$file name : acapauasmspauasmldt.sql*/
/*$version   : 4.0.0.012*/
/*==================================================
   stored procedure : acapauasmspauasmldt
   method           :acapauasmmtauasmldt
   author           : Prasad A
   created on       : 26 may 2001 13:34:44:983
   created at       : s4141
   generated by     : fpuser
   description	     : updating the status, updating the amounts and fb postings

   Modified By		: Muthu V
   Modified Date	: 17-APR-2004
   Purpose		: SP Modification for German Language Support

   Modified By		: Vairamani.C
   Modified Date	: July 29 2004
   Purpose		: ACAPDMS41SYTST_000118 - Merging from Tc 5186

   Modified By		: Nagarajan G
   Modified Date	: 09/11/2004
   Purpose		: SNPFIN41CT_000081 - Merging from Tc ACAPPH2SYSTEST_000009

    Modified By		: Sangeetha Sitaraman
   Date			: 10-11-2005
   Purpose		: For FA revamp(pls:refer the VSS for the Previous version)

    Modified By		: Sangeetha Sitaraman
   Date			: 27-12-2005
   Purpose		: ACAPDMS412AT_000179

  Modified By		: Sangeetha Sitaraman
   Date			: 09-01-2006
   Purpose		: ACAPDMS412AT_000277

   
   Modified By		: Swetha
   Date			: 13/03/2006
   Purpose		: ACAPDMS412AT_000385


proc acapauasmspauasmldt
grant exec on acapauasmspauasmldt to public
====================================================*/
/********************************************************************************/
/*Modified by        : Swetha                                                   */
/*Modified Date      : 5/5/2006                                                 */
/*Purpose            : CML Changes                                              */
/********************************************************************************/
/******************************************************************************************/
/*Modified by        : Swetha                                                             */
/*Modified Date      : 21/08/2006                                                         */
/*Purpose            : ACAPDMS412AT_000512                                                */
/*****************************************************************************************/
/* Swetha               05/01/2007                SDINDMS412AT_000538             */
/* Uma Maheswrai        22nd Jun 2007             ACAPDMS412AT_000716             */
/* Esther J				07th Sep 2007				APLANDMS412AT_000193		  */
/* Esther J				17/10/2007				ADISPDMS412AT_000246	
 Aditya S		18/07/2014		  ES_ACAP_00621				  	  
   Esther				17/1/2014				13H120_General_00032 ;13H120_ACAP_00002 
   Damodharan. R		12/12/2014				14H109_ADEPP_00004
   Aditya Sitaraman		15/07/2015				ES_ACAP_00811
   Rahul Sharma         18/09/2015              ES_ACAP_00865  
   Anusha.p            28/03/2018         epe-5924 
   Ashok V				17/7/2018			EBS-1694 
   Harithra				17-08-2018         EPE-8428 
   Indira G				21/09/2018		   EBS-1882     
   Ashok V				04/02/2019		   EBS-2581  
   Banurekha B          13/3/2019          IHH-437    
   Amrutha R.S			22/04/2019		   EPE-13183                  
   Gokulamanikandan M		24/06/2019		epe-14592
   Ashok V				23/09/2019		   PTP-206	
   --C.Ramesh Kumar		24.10.2019			epe-16037
   /*Priyadarshini R       21-10-19                EBS-3156              */
   --gokul M			27.11.2019   epe-17029
   --Abimathi.M					02-12-2019		EPE-16162
   /*gokul M				03/11/2020				EPE-23559  */
   Abimathi.M				29-01-2021		EPE-29932
   Revathi M				05/02/2021          EPE-30257
   Amani.P					09-03-2021			EPE-26603:EPE-31143:EPE-31349
   Aditya S					09/07/2021			RWSE-157
   Ashok V					11/01/2022			BS-750
   Aditya S					06/04/2022			FBF-1113
   Nithya S					04/04/2022			EPE-43676
   Uma Maheshwari M			12/05/2022			EPE-46265
   Harithra					08/08/2023			EPE-66921
   Kavitha R				23/06/2024			EPE-83025
*/
------------------------------------------------------------------------------------------------------------------------
Create procedure acapauasmspauasmldt
	     @assetclass   			fin_assetclass  ,
	     @assetdescription   	fin_desc40  ,
	     @assetgrpnum   		fin_group  ,
	     @assetlocation   		fin_assetlocation  ,
	     @assetnumber   		fin_assetnumber  ,
		 @assetstatus   		fin_status  ,
	     --@barcode   			fin_documentnumber  ,
		 @barcode   			fin_barcode,   --EPE-66921
		 @businessuse   		fin_depprecent  ,
	     @capitalizationdate   	fin_date,
	     @capitalizationnumber	fin_documentnumber,
	     @costcenter   			fin_costcentercode  ,
	     @createddate   		fin_date,
	     @creationby   			fin_ctxt_user  ,
	     @ctxt_language   		fin_ctxt_language  ,
	     @ctxt_ouinstance   	fin_ctxt_ouinstance  ,
	     @ctxt_service   		fin_ctxt_service  ,
	     @ctxt_user   			fin_ctxt_user  ,
	     @custodian   			fin_employeename  ,
	     @depcategory   		fin_depcategory  ,
	     @fb   					fin_financebookid  ,
	     @guid					fin_guid,
	     @inservicedate   		fin_Date,
	     @inventorycycle   		fin_inventorycycle  ,
	     @lastmodificationby   	fin_ctxt_user  ,
	     @lastmodifieddate		fin_date,
	     @manufacturer   		fin_name  ,
	     @modeflag   			fin_modeflag  ,
	     @model   				fin_desc40  ,
	     @salvagevalue   		fin_amount  ,
	     @serialnumber   		fin_serialno  ,
	     @tagcost   			fin_amount  ,
	     @tagdescription   		fin_desc40  ,
	     @tagnumber   			fin_assettagno  ,    
	     @timestamp1			fin_timestamp,
	     @warrentynumber   		fin_documentnumber  ,
	     @fprowno   			fin_rowno  ,
		 @remarks				fin_desc255, --code added by Rahul For the defect id ES_ACAP_00865
		  /*code added for PTP-206 starts*/
		@assetcategory        	fin_desc255, --Input 
		@assetcluster         	fin_desc255, --Input 
		 /*code added for PTP-206 ends*/
		 @measurunit				udd_uomcode,--epe-16037
	     @totalcapact			fin_quantity,--epe-16037
		 @natureofshift        	fin_flag, --Input	--epe-23559
		 @salvageper           	fin_depprecent,--EPE-43676
	    @m_errorid  			fin_int output--int output --to return execution status
as
begin
     

     -- nocount should be switched on to prevent phantom rows 
     set nocount on

	declare @rowno_tmp 		fin_rowno,
		@status_tmp		fin_status,
		@timestamp_tmp		fin_timestamp ,
		@today_tmp		fin_date ,
		@trandate_tmp		fin_date ,
		@errorcode		fin_errorcode ,		
		@errorcode_tmp		fin_errorcode ,
		@pubouinstid_tmp	fin_ctxt_ouinstance,
		@proposalnum		fin_documentnumber,
		@propno			fin_documentnumber,
		@capamt			fin_amount,
		@capflag		fin_flag,
		@fbid			fin_financebookid,
        @doc_type        fin_documenttype,
        @doc_number        fin_documentnumber,
        @doc_date_tmp        fin_date,		--code added for ES_ACAP_00621
        @line_no             fin_lineno   
		--EPE-23559 starts
		declare @adepou			fin_ctxt_ouinstance,
					@depr_method	fin_deprmethodenu,
					@shift_code	    fin_documentno,
					@exchangerate		fin_rate,
					@tran_currency		fin_currency

	declare @bargen_tmp     fin_paramcode, --EPE-66921
			@Manbargen_tmp	fin_paramcode,
			@asset_barcode	fin_barcode,
			@company_code	fin_companycode,
			@error_msg		fin_desc255
			
		--BEGIN of Standard code for getting precision type
	declare @pqty_tmp                  fin_int ,
		@pamt_tmp                  fin_int ,
		@prate_tmp                 fin_int ,
		@perate_tmp                fin_int ,
		@phigh_tmp                 fin_int ,
		@pmed_tmp                  fin_int ,
		@plow_tmp                fin_int
	
	exec fin_sp_precisiontype_rtr @pqty_tmp output, @pamt_tmp output,
	     @prate_tmp output, @perate_tmp output, @phigh_tmp output,
	     @pmed_tmp output, @plow_tmp output
	
	 select  @natureofshift         = ltrim(rtrim(@natureofshift))  
	 IF @natureofshift = '~#~'  
			Select @natureofshift = null  
	 --EPE-23559 	
		
	-- @m_errorid should be 0 to indicate success
	select @m_errorid =0     

	select @assetclass = ltrim(rtrim(@assetclass))
	if @assetclass = '~#~' 
		select @assetclass = null

	select @assetdescription = ltrim(rtrim(@assetdescription))
	if @assetdescription = '~#~' 
		select @assetdescription = null

	select @assetgrpnum = ltrim(rtrim(@assetgrpnum))
	if @assetgrpnum = '~#~' 
		select @assetgrpnum = null

	select @assetlocation = ltrim(rtrim(@assetlocation))
	if @assetlocation = '~#~' 
		select @assetlocation = null

	select @assetnumber = ltrim(rtrim(@assetnumber))
	if @assetnumber = '~#~' 
		select @assetnumber = null

	select @assetstatus = ltrim(rtrim(@assetstatus))
	if @assetstatus = '~#~' 
		select @assetstatus = null

	select @barcode = ltrim(rtrim(@barcode))
	if @barcode = '~#~' 
		select @barcode = null

	if @businessuse = -915 
		select @businessuse = null

	select @capitalizationdate = ltrim(rtrim(@capitalizationdate))
	if @capitalizationdate = '1900-01-01' 
		select @capitalizationdate = null

	select @capitalizationnumber = ltrim(rtrim(@capitalizationnumber))
	if @capitalizationnumber = '~#~' 
		select @capitalizationnumber = null

	select @costcenter = ltrim(rtrim(@costcenter))
	if @costcenter = '~#~' 
		select @costcenter = null

	select @createddate = ltrim(rtrim(@createddate))
	if @createddate = '1900-01-01'
		select @createddate = null

	select @creationby = ltrim(rtrim(@creationby))
	if @creationby = '~#~' 
		select @creationby = null

	if @ctxt_language = -915 
		select @ctxt_language = null

	if @ctxt_ouinstance = -915 
		select @ctxt_ouinstance = null

	select @ctxt_service = ltrim(rtrim(@ctxt_service))
	if @ctxt_service = '~#~' 
		select @ctxt_service = null

	select @ctxt_user = ltrim(rtrim(@ctxt_user))
	if @ctxt_user = '~#~' 
		select @ctxt_user = null

	select @custodian = ltrim(rtrim(@custodian))
	if @custodian = '~#~' 
		select @custodian = null

	select @depcategory = ltrim(rtrim(@depcategory))
	if @depcategory = '~#~' 
		select @depcategory = null

	select @fb = ltrim(rtrim(@fb))
	if @fb = '~#~' 
		select @fb = null

	select @guid = ltrim(rtrim(@guid))
	if @guid = '~#~' 
		select @guid = null

	select @inservicedate = ltrim(rtrim(@inservicedate))
	if @inservicedate = '1900-01-01' 
		select @inservicedate = null

	select @inventorycycle = ltrim(rtrim(@inventorycycle))
	if @inventorycycle = '~#~' 
		select @inventorycycle = null

	select @lastmodificationby = ltrim(rtrim(@lastmodificationby))
	if @lastmodificationby = '~#~' 
		select @lastmodificationby = null   

	select @lastmodifieddate = ltrim(rtrim(@lastmodifieddate))
	if @lastmodifieddate = '1900-01-01' 
		select @lastmodifieddate = null  

	select @manufacturer = ltrim(rtrim(@manufacturer))
	if @manufacturer = '~#~' 
		select @manufacturer = null

	select @modeflag = ltrim(rtrim(@modeflag))
	if @modeflag = '~#~' 
		select @modeflag = null

	select @model = ltrim(rtrim(@model))
	if @model = '~#~' 
		select @model = null

	if @salvagevalue = -915 
		select @salvagevalue = null

	if @serialnumber = '-915 ' or @serialnumber ='~#~'
		select @serialnumber = null

	if @tagcost = -915 
		select @tagcost = null

	select @tagdescription = ltrim(rtrim(@tagdescription))
	if @tagdescription = '~#~' 
		select @tagdescription = null

	if @tagnumber = -915 
		select @tagnumber = null     

	if @timestamp1 = -915 
		select @timestamp1 = null

	select @warrentynumber = ltrim(rtrim(@warrentynumber))
	if @warrentynumber = '~#~' 
		select @warrentynumber = null

	if @fprowno = -915 
		select @fprowno = null
		
	/*Code added by Rahul For the defect id ES_ACAP_00865 starts here*/
	select @remarks               = ltrim(rtrim(@remarks))
		IF @remarks = '~#~' 
		Select @remarks = null  
   /*Code added by Rahul For the defect id ES_ACAP_00865 ends here*/

   --epe-16037
	if @measurunit = '~#~' 
		select @measurunit = null
	
	if @totalcapact = -915
		select @totalcapact = null
	--epe-16037

	--EPE-43676
	IF @salvageper = -915
		Select @salvageper = null 
	--EPE-43676

	/*select  @status_tmp 		= parameter_code
	from 	fin_quick_code_met(nolock)
	where 	component_id 		= 'ACAP'
	and	parameter_type		= 'CBO'
	and	parameter_category 	= 'TAG_STA'	
	and 	parameter_text 		= 'Active'
	and	language_id		= @ctxt_language*/


        select  @status_tmp             = 'AC'



	--if modeflag value is U update the table
	/*code commented by sangeetha for the issue ACAPDMS412AT_000277 begin here*/
	--if @modeflag='Z'
	--begin	
	/*code commented by sangeetha for the issue ACAPDMS412AT_000277 end here*/
		select @rowno_tmp = @fprowno + 1


		--getting timestamp from table
		declare	@usefullifeinmonths	fin_lineno		--epe-17029
			
		select 	@timestamp_tmp 	= timestamp
				,@usefullifeinmonths = usefullifeinmonths	--EPE-17029
		from 	acap_asset_tag_dtl(nolock)
		where 	ou_id 			= @ctxt_ouinstance	
		and 	asset_number 	= @assetnumber
		and		cap_number		= @capitalizationnumber
		and 	tag_number 		= @tagnumber
		
		
		--checking concurrency
		if @timestamp_tmp <> @timestamp1
		begin
			exec fin_sp_raise_error '', '', '', '', 'ACAP',7,@m_errorid output
			return
		end
	   
	   -- epe-5924
	   if exists  ( Select 'X'
	                from  acap_asset_hdr(nolock)
					where  cap_number      = @capitalizationnumber 
					and    asset_number    = @assetnumber
					and    ou_id           = @ctxt_ouinstance
					and    asset_status    = 'RET'
					)
		begin
		  -- Capitalization No. %d is not in Fresh status
			exec fin_german_raiserror_sp 'ACAP',@ctxt_language,200,@capitalizationnumber
			return
		end
		-- epe-5924
		
		--updating the asset status
		update  acap_asset_hdr with (rowlock)
		set 	asset_status 	= @status_tmp,
			modifiedby	= @ctxt_user,
			modifieddate	= dbo.RES_Getdate(@ctxt_ouinstance),
			cost_center	= @costcenter
		where 	ou_id 		= @ctxt_ouinstance
		and 	asset_number 	= @assetnumber
		
		update  acap_asset_hdr with (rowlock)
		set 	cap_status 	= @status_tmp
		where 	ou_id 		= @ctxt_ouinstance
		and 	asset_number 	= @assetnumber
		/*Code Commented by Swetha for ACAPDMS412AT_000385 on 13/03/2006 */
		--and	cap_number	= @capitalizationnumber	
		/*Code Commented by Swetha for ACAPDMS412AT_000385 on 13/03/2006 */

		--EPE-23559 starts
		select  @adepou      = destinationouinstid      
		from   fw_admin_view_comp_intxn_model (nolock)    
		where   sourcecomponentname      =  'ACAP'    
		and     sourceouinstid           =  @ctxt_ouinstance    
		and     destinationcomponentname = 'ADEP' 
	
		select @depr_method = depr_method  
		from adep_assign_rules_mst a (nolock)    
		join adep_depr_rule_hdr b (nolock)    
		on  a.ou_id			 = b.ou_id    
		and  a.depr_rule_number = b.depr_rule_number     
		and  a.asset_class		 = b.asset_class    
		and  a.ou_id			 = @adepou    
		and  a.depr_book		 = 'CORP'    
		and  a.depr_category    = @depcategory    
		and  a.asset_class		 = @assetclass    
		and  a.status			 = 'A'    
		and  @capitalizationdate between a.eff_date and isnull(a.exp_date,@capitalizationdate)    
   
		select  @shift_code = parameter_code
		from    fin_quick_code_met(nolock)
		where   component_id		 =      'ACAP'     
		and     parameter_type		 =      'CBO' 
		and	    parameter_category	 =		'NAT_SFT'
		and		parameter_text		 =		@natureofshift

		if  @depr_method =  'SY' and  @shift_code <> 'S'
		begin
			/*Depreciation Category Chosen mapped with Depreciation Method Sum of Years Digits Method. 
			Nature of Shift cannot be chosen as Double/Triple. Modify either depreciation category or Nature 
of Shift at row no %d*/
			exec fin_german_raiserror_sp 'ACAP',@ctxt_language,1900027511,@fprowno
			RETURN		
		end	  
		--EPE-23559 ends

		--Update barcode for the asset - tag starts here 
		--EPE-66921
		if @ctxt_Service = 'FAHcapSrAssetA' 
		begin
			select @company_code = company_code
			from emod_ou_vw(nolock)
			where ou_id	= @ctxt_ouinstance

			select @asset_barcode = bar_code
			from acap_Asset_Tag_dtl(nolock)
			where   ou_id				=	@ctxt_ouinstance
			and upper(asset_number)		=	upper(@assetnumber)
			and  tag_number				=   @tagnumber

			if exists(	select 'X' from cps_processparam_vw(nolock)
						where company_code = @company_code
						and parameter_type = 'FASYS'
						and parameter_code = 'autogenbarcode'
						and language_id	   = @ctxt_language)
			begin
				select @Manbargen_tmp = parameter_value 
				from cps_processparam_vw(nolock)
				where company_code = @company_code
				and parameter_type = 'FASYS'
				and parameter_code = 'AllowManGenBarcode'
				and language_id	   = @ctxt_language

				select @bargen_tmp = parameter_value 
				from cps_processparam_vw(nolock)
				where company_code = @company_code
				and parameter_type = 'FASYS'
				and parameter_code = 'autogenbarcode'
				and language_id	   = @ctxt_language
			end
			else
			begin
				select @bargen_tmp = 'N'
			end

			/*if isnull(@asset_barcode,'') <> isnull(@barcode,'') and @Manbargen_tmp = 'N'
			begin
				select @barcode = @asset_barcode
			end*/


			--if @Manbargen_tmp = 'Y' and isnull(@asset_barcode,'') <> isnull(@barcode,'') and  isnull(@barcode,'') <> ''
			if @Manbargen_tmp = 'Y' and isnull(@barcode,'') <> ''
			begin
				select @bargen_tmp = 'N'
				if isnull(@asset_barcode,'') <> isnull(@barcode,'')
				begin
				if exists(select 'X' from acap_Asset_Tag_dtl(nolock)
						  where ou_id		=	@ctxt_ouinstance
						  and   bar_code	=	@barcode)
				begin
					--raiserror('Barcode number already exists for another Asset.',16,1)
					select @m_errorid = 302
					exec fin_german_raiserror_sp 'ACAP',@ctxt_language,302
					return
				end	
				end
			end	

			--Update barcode for the asset - tag starts here (will be called only when barcode is null)
			--EPE-66921

			if isnull(@bargen_tmp,'N') <> 'N' --and isnull(@barcode,'') = ''
			begin
			begin try
				exec Acap_Barcode_Gen_sp @ctxt_language ,
										 @ctxt_ouinstance,
										 @ctxt_service,
										 @ctxt_user,
										 @assetnumber,
										 @tagnumber,
										 @bargen_tmp
			end try

			begin catch
				select @error_msg = error_message()
			end catch

			if isnull(@error_msg,'#') <> '#'
				select @m_errorid  = 1
			else 
				select @m_errorid  = 0

			if @m_errorid = 1
			begin
				raiserror (@error_msg,16,1)
				return
			end 
			end

			--EPE-66921
			--update barcode for the asset - tag ends here	(will be called only when barcode is null)
		end

		--EPE-66921
		--Update barcode for the asset - tag ends here 		

		--updating the tag status
		update 	acap_asset_tag_dtl with (rowlock)
		set 	timestamp 	= @timestamp_tmp + 1,
			tag_status	= @status_tmp,
			cost_center	= @costcenter,
			modifiedby	= @ctxt_user,
			modifieddate    = dbo.RES_Getdate(@ctxt_ouinstance)
			,natureofshift = @shift_code		--epe-23559
		where 	ou_id 		= @ctxt_ouinstance
		and 	asset_number 	= @assetnumber		
		and 	tag_number 	= @tagnumber	
		/*code modified for EPE-8428 - Harithra*/
		
		--epe-17029
 declare @errorid fin_int,  
    @success_flag  fin_modeflag  

 exec acap_cmn_usage_val_sp  @guid,    'FA_ACAP',    'ACAP',  
         @ctxt_ouinstance,  @ctxt_service,  @assetclass,  
         @depcategory,  @usefullifeinmonths, @capitalizationdate,  
         @totalcapact,  @measurunit,   'Y',  
         @businessuse,  
         @errorid out,  @fprowno,      @success_flag OUT  
 if @errorid > 0  
 return  
  
 --epe-17029

		if(@ctxt_user = 'debuguser') --EBS-3156
		begin
		  select @tagcost   	    '@tagcost' ,  	
			   @tagdescription	'@tagdescription',
			   @tagnumber   	'@tagnumber' 

		   select @guid,@ctxt_ouinstance,a.cap_number,a.asset_number,a.timestamp,
		a.cap_date,a.cap_status,a.fb_id,a.num_type,a.asset_class,
		a.asset_group,a.cost_center,a.asset_desc,@tagcost,
		b.asset_location/*a.asset_location*/,a.seq_no,a.as_on_date,a.asset_type,a.asset_status,  -- Code Changed by Esther J for defect id ADISPDMS412AT_000246
		a.transaction_date,a.account_code,b.tag_number,b.tag_desc,
		b.inservice_date,@tagcost,b.proposal_number,b.tag_status,
		b.depr_category,b.inv_cycle,b.salvage_value,b.manufacturer,
		b.bar_code,b.serial_no,b.warranty_no,b.model,b.custodian,
		b.business_use,b.book_value,b.revalued_cost,b.inv_date,
		b.inv_due_date,b.inv_status,b.softrev_run_no,b.insurable_value,
		b.policy_count,b.dest_fbid,b.transfer_date,b.legacy_asset_no,
		b.migration_status,@ctxt_user,dbo.RES_Getdate(@ctxt_ouinstance),null,null
		,b.residualvalue,	b.usefullifeinmonths,	--Code added by Damodharan. R for Defect ID 14H109_ADEPP_00004
		b.LAccount_code,b.LAccount_desc,b.Lcost_center,b.LAnalysis_code,b.LSubAnalysis_code
		,a.asset_classification, b.asset_category,b.asset_cluster ,asset_capacity_uom,asset_capacity--epe-16037 --EPE-11335--epe-14592
		,b.salvage_valper--EPE-43676
		from 	acap_asset_hdr a(nolock), 
			acap_asset_tag_dtl b(nolock)
		where 	a.ou_id 		= @ctxt_ouinstance
		and 	a.asset_number	= @assetnumber			
		and	a.asset_class	= @assetclass				
		and	a.cap_number	= @capitalizationnumber
		and	b.ou_id		= a.ou_id
		and	b.asset_number	= a.asset_number	
		and	b.tag_number	= @tagnumber
		and	b.cap_number	= a.cap_number	
		
		select @ctxt_ouinstance '@ctxt_ouinstance',@assetnumber '@assetnumber',@assetclass'@assetclass',@capitalizationnumber'@capitalizationnumber',
		@tagnumber'@tagnumber'
		
		end
		
		
		--inserting the asset,tag information into temp table  
		insert into acap_asset_info_tmp(guid,ou_id,cap_number,asset_number,timestamp,
		cap_date,cap_status,fb_id,num_type,asset_class,asset_group,cost_center,
		asset_desc,asset_cost,asset_location,seq_no,as_on_date,asset_type,
		asset_status,transaction_date,account_code,tag_number,tag_desc,
		inservice_date,tag_cost,proposal_number,tag_status,depr_category,inv_cycle,
		salvage_value,manufacturer,bar_code,serial_no,warranty_no,model,custodian,
		business_use,book_value,revalued_cost,inv_date,inv_due_date,inv_status,
		softrev_run_no,insurable_value,policy_count,dest_fbid,transfer_date,
		legacy_asset_no,migration_status,createdby,createddate,modifiedby,
		--modifieddate)	--Code commented by Damodharan. R for Defect ID 14H109_ADEPP_00004
		modifieddate,	residualvalue,	usefullifeinmonths,	LAccount_code,LAccount_desc,Lcost_center,LAnalysis_code,LSubAnalysis_code	--Code added by Damodharan. R for Defect ID 14H109_ADEPP_00004
		,asset_classification,asset_category,asset_cluster  --epe-14592	
		,asset_capacity_uom,asset_capacity,natureofshift,salvage_valper)--epe-29932--epe-16037 --EPE-11335--EPE-43676
		select @guid,@ctxt_ouinstance,a.cap_number,a.asset_number,a.timestamp,
		a.cap_date,a.cap_status,a.fb_id,a.num_type,a.asset_class,
		a.asset_group,a.cost_center,a.asset_desc,@tagcost,
		b.asset_location/*a.asset_location*/,a.seq_no,a.as_on_date,a.asset_type,a.asset_status,  -- Code Changed by Esther J for defect id ADISPDMS412AT_000246
		a.transaction_date,a.account_code,b.tag_number,b.tag_desc,
		b.inservice_date,@tagcost,b.proposal_number,b.tag_status,
		b.depr_category,b.inv_cycle,b.salvage_value,b.manufacturer,
		b.bar_code,b.serial_no,b.warranty_no,b.model,b.custodian,
		b.business_use,b.book_value,b.revalued_cost,b.inv_date,
		b.inv_due_date,b.inv_status,b.softrev_run_no,b.insurable_value,
		b.policy_count,b.dest_fbid,b.transfer_date,b.legacy_asset_no,
		b.migration_status,@ctxt_user,dbo.RES_Getdate(@ctxt_ouinstance),null,null
		,b.residualvalue,	b.usefullifeinmonths,	--Code added by Damodharan. R for Defect ID 14H109_ADEPP_00004
		b.LAccount_code,b.LAccount_desc,b.Lcost_center,b.LAnalysis_code,b.LSubAnalysis_code
		,a.asset_classification, b.asset_category,b.asset_cluster ,asset_capacity_uom,asset_capacity--epe-16037 --EPE-11335--epe-14592
		,natureofshift,b.salvage_valper --epe-29932--EPE-43676
		from 	acap_asset_hdr a(nolock), 
			acap_asset_tag_dtl b(nolock)
		where 	a.ou_id 	= @ctxt_ouinstance
		and 	a.asset_number	= @assetnumber			
		and	a.asset_class	= @assetclass				
		and	a.cap_number	= @capitalizationnumber
		and	b.ou_id		= a.ou_id
		and	b.asset_number	= a.asset_number	
		and	b.tag_number	= @tagnumber
		and	b.cap_number	= a.cap_number					
			

		select  @proposalnum	= proposal_number
		from 	acap_asset_tag_dtl(nolock)
		where 	ou_id 		= @ctxt_ouinstance
		and 	asset_number 	= @assetnumber		
		and 	tag_number 	= @tagnumber
		and	cap_number	= @capitalizationnumber

		/* Code added by Uma for the bug id : ACAPDMS412AT_000716 starts here*/

		--temp table insert for ainq_tag_doc_dtl in AINQ
		
		insert into acap_doc_dtl_tmp
		(
		guid, ou_id,fb_id,cap_number,asset_number,tag_number,
		doc_number,line_no,doc_amount,doc_type, cap_amount ,
		proposal_number
		)	
		select
		@guid, ou_id ,  fb_id ,  cap_number ,  asset_number ,  tag_number
		, doc_number  , line_no , doc_amount , doc_type, cap_amount
		, proposal_number
		from	acap_tag_doc_dtl (nolock)
		where	ou_id		= @ctxt_ouinstance
		and	asset_number 	= @assetnumber
		and	tag_number 	= @tagnumber

		--code added for EPE-16162 starts
		if isnull(@proposalnum,'') <> ''
		begin
		declare @success_flag_in  fin_modeflag,
				@errorid_in		fin_int
	 
		EXEC aplan_cmn_addl_entity_val_sp
						 @guid,
						 'FA_ACAP',
						 'ACAP',
						 @ctxt_ouinstance,
						 @ctxt_service,
						 @proposalnum,
						 @costcenter,
						 null,
						 0,
						 0,
						 'Y',
						 @errorid_in      out,
						 @success_flag_in out

			if @errorid_in  > 0
			begin
				return
			end 
		end
	--code added for EPE-16162 ends 


		if exists (	select 	'x' 
				from 	acap_tag_doc_dtl dtl(nolock),
					si_doc_hdr si(nolock)
				where	asset_number 	= @assetnumber
				and	tag_number 	= @tagnumber
				and	doc_number	= SI.tran_no
				and	doc_type	= SI.tran_type
				and	ou_id		= SI.tran_ou
				and	dtl.ou_id	=	@ctxt_ouinstance -- code added for the defect id IHH-437
				and	doc_status	in ('RV','RVD','REV','R'))
		begin
			-- raiserror('Reference Document is not in Valid Status for Capitalization',16,1)
			exec fin_german_raiserror_sp 'ACAP',@ctxt_language,119
			return
		end
		/* Code added by Uma for the bug id : ACAPDMS412AT_000716 ends here*/
			
	
        	 /* code modified by Swetha for ACAPDMS412AT_000512 on 21/08/2006 */
			 --EPE-31349
			declare @doc_amount		 fin_amount
			declare @prop_cap_amount fin_amount
			declare @pending_cap_amt fin_amount
			declare @basecurr		 fin_currencycode --FBF-1113
			declare	@companycode_tmp	fin_companycode --FBF-1113
			--EPE-31349

		if exists(select 'x' from acap_asset_doc_dtl (nolock)
			where 	ou_id 		= @ctxt_ouinstance		
			and 	asset_number 	= @assetnumber)
		begin	
	 		declare acapins_cursor cursor
			for	
			select 	b.cap_amount,b.proposal_number,b.fb_id,a.cap_flag,a.doc_type,a.doc_number,b.line_no,a.doc_date,a.exchange_rate,a.currency ,a.doc_amount--code modified for ES_ACAP_00621--EPE-26603
			from 	acap_asset_doc_dtl a(nolock), 
					acap_tag_doc_dtl  b(nolock)
			where 	a.ou_id		= @ctxt_ouinstance
			and		a.asset_number	= @assetnumber
			and		b.tag_number	= @tagnumber
			and		a.ou_id		= b.ou_id
			and 	a.asset_number	= b.asset_number
			and		a.doc_number	= b.doc_number
			and		a.doc_type	= b.doc_type 
			and		a.cap_number	= @capitalizationnumber
			and		a.cap_number	= b.cap_number
			and		a.proposal_number = b.proposal_number--Multiproposal--EPE-83025

			open acapins_cursor
			fetch next from acapins_cursor into @capamt,@propno,@fbid,@capflag,@doc_type,@doc_number,@line_no,@doc_date_tmp ,@exchangerate,@tran_currency,@doc_amount--code modified for ES_ACAP_00621:EPE-26603

			while @@fetch_status = 0
			begin
			----EPE-31349

			
				select @pending_cap_amt = sum(pending_cap_amount+ capitalized_amount)
				from  si_line_dtl(nolock)
				where tran_type  = @doc_type
				and   tran_ou	 = @ctxt_ouinstance
				and   tran_no	 = @doc_number
				

				if @pending_cap_amt is null 
				begin
					select @pending_cap_amt =@doc_amount /*@capamt*/ --RWSE-157
				end

				--FBF-1113
				select	@companycode_tmp	= company_code 
				from	emod_ou_vw (nolock)
				where	ou_id			= @ctxt_ouinstance

				select @basecurr = currency_code
				from   emod_basecurr_vw(nolock)
				where  company_code	=	@companycode_tmp
				and	   flag		=	'B'

				if exists
				(
					select 'x'
					from	aplan_Acq_proposal_hdr(nolock)
					where	proposal_number = @propno	
					and		fb_id			= @fbid
					and		currency_code	=	@basecurr
				)
				begin
						select @exchangerate = 1
				end
				--FBF-1113

				/*code added for BS-750 starts*/
				if @exchangerate <> 1
				begin
				/*code added for BS-750 ends*/
					select @prop_cap_amount = (@doc_amount/@pending_cap_amt)*@capamt
				/*code added for BS-750 starts*/
				end
				else
				begin
					select @prop_cap_amount = @capamt
				end
				/*code added for BS-750 ends*/

				if @ctxt_user='proposeddebug'
				begin
				select'before'
					select @doc_amount '@doc_amount',@prop_cap_amount,@capamt,@pending_cap_amt '@pending_cap_amt',
					@capamt,@exchangerate,@doc_type,@ctxt_ouinstance,@doc_number
				
				end

				----EPE-31349
                 if(@doc_type = 'CO')
                 begin 
							 select @capflag = cap_flag
                            from   acap_wip_line_dtl(NOLOCK)
                            where  cap_wo_number = @doc_number
                            and    ou_id         = @ctxt_ouinstance
                            
                             --ES_ACAP_00811
							if exists
							(
								 select 'x'
								 from   acap_wip_line_dtl(NOLOCK)
								 where  cap_wo_number = @doc_number
								 and    ou_id         = @ctxt_ouinstance  
								 and	line_no       = @line_no
								 and	doc_type      = 'IBE'
							)	  
							begin 
                            
								select @capflag = 'CI' --'NC'	--EPE-13183

							end
							--ES_ACAP_00811
							
                 end
                 /* Code modified by Swetha for SDINDMS412AT_000538 on 05/01/2007 */
/* Code changed by Esther J on 7-9-2007 for defect id APLANDMS412AT_000193 starts */
 --          if (@doc_type ='PM_PV')
                  --if @doc_type in ('PM_PV','PM_SCA','PM_SCI')
				  if @doc_type in ('PM_PV','PM_SCI') --'PM_SCA'--EPE-30257
/* Code changed by Esther J on 7-9-2007 for defect id APLANDMS412AT_000193 ends*/
                 /* Code modified by Swetha for SDINDMS412AT_000538 on 05/01/2007 */
                 begin 
                            select @capflag = 'NC'
                 end
                
                --code added for the dts id 13H120_General_00032 ;13H120_ACAP_00002 starts  
				select @propno =  proposal_number  
				from 	acap_asset_info_tmp(nolock)
				where 	guid 		= @guid
				and  	asset_number 	= @assetnumber
				and	tag_number	= @tagnumber
				and	cap_number	= @capitalizationnumber
				--code added for the dts id 13H120_General_00032 ;13H120_ACAP_00002 ends
				
	

				 if @capflag = 'CI'
				 begin
					insert into acap_updproposal_tmp 
					(guid, proposal_number, asset_class, fb_id, tran_amount, tran_date,
				 	createdby, createddate, upd_flag,tran_currency ,tran_erate) --EPE-26603
					select @guid, @propno, asset_class, @fbid, 
   				   round( ( @prop_cap_amount/@exchangerate),@pamt_tmp)/*EPE-31143*/,/*cap_date*/@doc_date_tmp, @ctxt_user,dbo.RES_Getdate(@ctxt_ouinstance), 'CRE',@tran_currency,@exchangerate--code modified for ES_ACAP_00621 --EPE-26603
					from 	acap_asset_info_tmp(nolock)
					where 	guid 		    = @guid
				       and  	asset_number 	= @assetnumber
					and	tag_number	= @tagnumber
					and	cap_number	= @capitalizationnumber

					
				end
				else
				begin

					insert into acap_updproposal_tmp 
					(guid, proposal_number, asset_class, fb_id, tran_amount, tran_date,					
				 	createdby, createddate, upd_flag, tran_currency,tran_erate)  --EPE-26603
					select @guid, @propno, asset_class, @fbid, 
				        				       round( ( @prop_cap_amount/@exchangerate),@pamt_tmp)/*EPE-31143*/,/*cap_date*/@doc_date_tmp, @ctxt_user,dbo.RES_Getdate(@ctxt_ouinstance)--,'NC'--code modified for ES_ACAP_00621
												--,case when @doc_type = 'BK_JV' then 'C' else 'NC' end--code modified for EBS-1694
												/*code commented & added for EBS-2581 starts*/
												--,case when @doc_type in('BK_JV','PUR_GR') and @capflag 'NC' then 'C' else 'NC' end --EBS-1882
												,case when @doc_type ='BK_JV'  and isnull(@capflag,'') <>'NC' then 'C'
												when @doc_type ='PUR_GR' then 'C' 
												else 'NC' end 
												/*code commented & added for EBS-2581 ends*/	
												,@tran_currency		 --EPE-26603
												,	@exchangerate	 --EPE-26603							
					from 	acap_asset_info_tmp(nolock)
					where 	guid 		= @guid
				    and  	asset_number 	= @assetnumber
					and	tag_number	= @tagnumber
					and	cap_number	= @capitalizationnumber
					
				end
								fetch next from acapins_cursor into @capamt,@propno,@fbid,@capflag,@doc_type,@doc_number,@line_no,@doc_date_tmp,@exchangerate,@tran_currency ,@doc_amount--code modified for ES_ACAP_00621 --EPE-26603
			end
			close acapins_cursor
			deallocate acapins_cursor
            /* code modified by Swetha for ACAPDMS412AT_000512 on 21/08/2006 */

		end
		else
		begin
			insert into acap_updproposal_tmp 
	 		(guid, proposal_number, asset_class, fb_id, tran_amount, tran_date,
	 	 	createdby, createddate, upd_flag )
	 		select @guid, proposal_number, asset_class, fb_id, 
	                tag_cost,cap_date, @ctxt_user,dbo.RES_Getdate(@ctxt_ouinstance), 'NC'
	 		from 	acap_asset_info_tmp(nolock)
	 		where 	guid 		= @guid
	                and  	asset_number 	= @assetnumber
			and	tag_number	= @tagnumber
			and	cap_number	= @capitalizationnumber
		end
		
			
	/*code commented by sangeetha for the issue ACAPDMS412AT_000277 begin here*/
	--end
	/*code commented by sangeetha for the issue ACAPDMS412AT_000277 end here*/

	--EPE-46265 starts 
	if exists(	select	'X'
				from	acap_asset_hdr_tmp(nolock)
				where	guid	=	@guid)
	begin
		return
	end
	--EPE-46265 end

	----EBS-3156 start
	if(@ctxt_service like  'fahcap%')
	begin 
	    select  @m_errorid = 0
		return
	end
	----EBS-3156 ends
	else
	begin
	--assigning the value to the output parameter
	select @rowno_tmp   'fprowno'
	end
	set nocount off
end





